### ISSUE TITLE
All transposons "unknown"

### ISSUE THREAD

**Issue by aderzelle** [oushujun/EDTA#10]
Hello,
in the file.fa.EDTA.TElib.fa, virtually all transposons are labelled as "unknown":
16712 are unknown
48 are Gypsy 
Presuming my study organism is not having completely strange transposons, is it the kind of expected statistics? 

Thank you

**Comment by oushujun** [comment]
Hello,

No, this is not normal. You may experience faults when running TIR-Learner. We are fixing this soon. Please hold on for a couple of days. 

Best,
Shujun

**Comment by oushujun** [comment]
I just pushed some new updates to EDTA, mainly to fix the TIR-Learner issue. Please reinstall EDTA and rerun it in the same work folder. Existing results will be reused so there is essentially no waste of time. Thank you for your patience and support!

**Comment by oushujun** [comment]
I consider this issue resolved. Please reopen it if not. Thanks!
