### ISSUE TITLE
The discrepancy between the classification of TEsorter and results of EDTA

### ISSUE THREAD

**Issue by YTLogos** [oushujun/EDTA#101]
Hi shujun,
After the TE annotation with EDTA(v1.8.5), I used TEsorter to further classify the $EDTA.TElib.fa and found a lot of discrepancies between the classification of TEsorter and results of EDTA (especially LINE and Helitron). So which classification I should select to do the downstream analysis?

Many thanks,
Tao

**Comment by oushujun** [comment]
Hi Tao,

You may use TEsorter to reclassify sequences in the EDTA library. However, Helitrons may capture sequences and if other TEs were captured, the TEsorter classification may not be Helitron anymore. It is also possible that Helitron was a false positive. 

Best,
Shujun
