### ISSUE TITLE
Error during run of EDTA.pl

### ISSUE THREAD

**Issue by brettChapman** [oushujun/EDTA#102]
Hi

Thank you for such a great tool!

I'm currently trying out EDTA, by running EDTA.pl after running EDTA_raw.pl with tir, ltr and helitron. I'm running through Singularity.

I receive the following error in the cleanup_nested.pl script, about an uninitialised value. I'm not sure if this would impact the running of EDTA and the cleanup step:

srun -n 1 singularity exec --bind /data/EDTA_analysis_testing:/data/EDTA_analysis_testing /data/edta_builds/edta_latest.sif EDTA.pl --threads 16 --overwrite 0 --genome /data/EDTA_analysis_testing/felCat5.fna --sensitive 1 --anno 1 --evaluate 1

########################################################
########################################################

Fri Aug 14 23:32:16 UTC 2020	Dependency checking:
				All passed!

Fri Aug 14 23:33:46 UTC 2020	Obtain raw TE libraries using various structure-based programs: 
Fri Aug 14 23:33:46 UTC 2020	EDTA_raw: Check dependencies, prepare working directories.

Fri Aug 14 23:35:56 UTC 2020	Start to find LTR candidates.

Fri Aug 14 23:35:56 UTC 2020	Existing result file felCat5.fna.mod.LTR.raw.fa found! Will keep this file without rerunning this module.
	Please specify --overwrite 1 if you want to rerun this module.

Fri Aug 14 23:35:58 UTC 2020	Finish finding LTR candidates.

Fri Aug 14 23:35:58 UTC 2020	Start to find TIR candidates.

Fri Aug 14 23:35:58 UTC 2020	Existing result file felCat5.fna.mod.TIR.raw.fa found! Will keep this file without rerunning this module.
	Please specify -overwrite 1 if you want to rerun this module.

Fri Aug 14 23:35:59 UTC 2020	Finish finding TIR candidates.

Fri Aug 14 23:35:59 UTC 2020	Start to find Helitron candidates.

Fri Aug 14 23:35:59 UTC 2020	Existing result file felCat5.fna.mod.Helitron.raw.fa found! Will keep this file without rerunning this module.
	Please specify -overwrite 1 if you want to rerun this module.

Fri Aug 14 23:36:00 UTC 2020	Finish finding Helitron candidates.

Fri Aug 14 23:36:00 UTC 2020	Execution of EDTA_raw.pl is finished!

Fri Aug 14 23:36:03 UTC 2020	Obtain raw TE libraries finished.
				All intact TEs found by EDTA: 
					felCat5.fna.mod.EDTA.intact.fa
					felCat5.fna.mod.EDTA.intact.gff

Fri Aug 14 23:36:03 UTC 2020	Perform EDTA advcance filtering for raw TE candidates and generate the stage 1 library: 

Use of uninitialized value $subject in exists at /opt/conda/share/EDTA/util/cleanup_nested.pl line 141.
Use of uninitialized value in subroutine entry at /opt/conda/share/EDTA/util/cleanup_nested.pl line 141.
Sat Aug 15 03:11:17 UTC 2020	EDTA advcance filtering finished.

Sat Aug 15 03:11:17 UTC 2020	Perform EDTA final steps to generate a non-redundant comprehensive TE library:

				Use RepeatModeler to identify any remaining TEs that are missed by structure-based methods.

**Comment by oushujun** [comment]
Hello Brett,

Thanks for using EDTA. Yes that error is negligible. Just some random
memory leaks while constructing the library and usually won't affect the
outcome.

Best,
Shujun
