### ISSUE TITLE
Warning: LOC list Pcal.genome.fa.mod.ltrTE.veryfalse is empty.

### ISSUE THREAD

**Issue by schraderL** [oushujun/EDTA#103]
Hi, 

thanks a lot for this great software! I am having some issues with the annotation of a genome after a fresh install of EDTA using conda. 

When running EDTA with 
`
EDTA.pl --threads 20 --genome $short.genome.fa --sensitive 1 --cds $base/$short/EDTA/Pbar.cds.fa
`
I get the following warning:
> Warning: LOC list Pcal.genome.fa.mod.ltrTE.veryfalse is empty.

I did not find any documentation of what that is supposed to tell me. Can you share some insights?

Best
lukas

**Comment by oushujun** [comment]
Hello Lukas,

This is a warning generated by LTR_retriever. it is likely your input
sequence is too small and it didn't defect obviously false LTR elements.
This won't affect your run of the EDTA. To further test the pipeline, you
may use the Arabidopsis or Drosophila genome.

Best,
Shujun

**Comment by schraderL** [comment]
Good to know! Thanks!
