### ISSUE TITLE
%masked TE

### ISSUE THREAD

**Issue by wyim-pgl** [oushujun/EDTA#104]
Dear Shujun,
I recently finished EDTA run on B. oleacea genome and the results from mod.EDTA.TEanno.sum indicates below.
https://pastebin.com/9fG8bvRk
That 21% of repeat seems to include intact and fragmented repeats with gapped region. Do you have any method for ungapped calculation ?
Regards,
Won

**Comment by oushujun** [comment]
Hi Won,

You may use the RepeatMasker .out file or the EDTA .gff3 file to get coordinates of TEs, and minus the gap regions for your summary. 21% total repeats seem low in B. oleacea although I don't have a clear idea about this genome.

Best,
Shujun
