### ISSUE TITLE
How to use make_panTElib.pl ?

### ISSUE THREAD

**Issue by yuanhelianyi** [oushujun/EDTA#106]
@oushujun 

Hi, I get something wrong when I use make_panTElib.pl to get panTElib. My used 
`perl /data2/EDTA/util/make_panTElib.pl -liblist ./Tu/Tu_v2.fasta.mod.EDTA.TElib.fa \
> ./Aet/Aet_v4.fasta.mod.EDTA.TElib.fa`, the info as blows. What can I do to resolve this problem? Thanks!

2020年 08月 31日 星期一 03:24:03 EDT
Start to combine individual TE libraries from ./Tu/Tu_v2.fasta.mod.EDTA.TElib.fa.
Parameters to cluster sequences:
	Minimum identity: 80
	Minimum coverage: 0.95
	Minimum length: 80
The library file >TE_00000000#Unknown in ./Tu/Tu_v2.fasta.mod.EDTA.TElib.fa is not found!

Jing

**Comment by oushujun** [comment]
Hi Jing,

Please check out the usage by running: perl make_panTElib.pl
The option -liblist requires a file that contains a list of TE libraries
with path. One each line.

Shujun

**Comment by yuanhelianyi** [comment]
@oushujun 

Thanks! I'm sorry I don't know how to write the command despite I actually know need a list for TE libraries. Can you give me a example?

Jing

**Comment by yuanhelianyi** [comment]
@oushujun 

Thanks! I got it. It should build a new file.

Jing
