### ISSUE TITLE
How to cluster the candidate?

### ISSUE THREAD

**Issue by yuanhelianyi** [oushujun/EDTA#107]
@oushujun 

Hi!  There are some questions when I used the convenient tool to annotate T.urartu genome, please help me.
1. I get $genome.EDTA.TEanno.sum as follows. I doubt why the classification has double "DTA, DTC, DTH, DTM, DTT, Helotron"?
<img width="358" alt="屏幕快照 2020-09-03 上午10 51 55" src="https://user-images.githubusercontent.com/28393277/92066047-8b597700-edd3-11ea-9586-8564fd93c7a6.png">

2. There are 23753 sequences in the $genome.EDTA.TElib.fa. Otherwise, I get only 1471 sequences when I solely used RepeatModeler to get non-redundant liarabry. Is this caused by the reason that high covering (90%) when clustering?

3. I found annotation using EDTA-library is more piecemeal than RepeatModerler-library. Why there is big difference and how to choose?
<img width="801" alt="屏幕快照 2020-09-03 上午10 44 58" src="https://user-images.githubusercontent.com/28393277/92066111-b93ebb80-edd3-11ea-8f9f-5c06b3d1a57d.png">
<img width="803" alt="屏幕快照 2020-09-03 上午10 44 08" src="https://user-images.githubusercontent.com/28393277/92066141-c8256e00-edd3-11ea-8ecc-baef3d1f252c.png">

4. The annotation of EDTA have some overlap, how to solve it?
<img width="794" alt="屏幕快照 2020-09-03 上午10 58 36" src="https://user-images.githubusercontent.com/28393277/92066644-fce5f500-edd4-11ea-8701-a55cafc901bd.png">

5. I saw LRT-retriever used 80-90-100 rule to reduce redundancy using cd-hit, what about the rule for TIR and Helitron in EDTA?

Jing

**Comment by oushujun** [comment]
Hi Jing,

Thank you for your detailed descriptions. For 1, 3, and 4, they are known issues solved in the latest version v1.9.0, please update your EDTA and run the patch script. Please check out the [release note](https://github.com/oushujun/EDTA/releases/tag/v1.9.0) for details.

2. EDTA and RepeatModeler use different strategies to construct libraries. EDTA chooses representing sequences for library construction while RepeatModeler tries to construct consensus sequences.

5. EDTA uses a slightly different rule to cluster TIR and Helitron. It requires a minimum length of 80bp to reconcile the shorter nature of these elements. Also, the coverage cutoff changed to 95%.

Best,
Shujun
