### ISSUE TITLE
ERROR: RepeatMasker results not found in REFERENCE-fa.mod.out!

### ISSUE THREAD

**Issue by huiWyuan** [oushujun/EDTA#108]
Hi,
I have running EDTA on a 2 Gb genome with parameter "-anno 1". It encountered the problem ""ERROR: RepeatMasker results not found in REFERENCE-fa.mod.out!" " when perform post-EDTA analysis for whole-genome annotation. Any help or suggestion will be appreciated.
Thanks,
huiyuan

**Comment by oushujun** [comment]
Hi Huiyuan,

You may use `--anno 1` (two dashes) to activate the annotation mode. Please double-check if there is any library file generated (TElib.fa) and in the `*anno/` folder, you should see the `REFERENCE-fa.mod.out` file if it runs correctly. You may rerun the annotation step with `--step anno --anno 1`.

Best,
Shujun
