### ISSUE TITLE
EDTA stuck in TIR-Learner phase ?

### ISSUE THREAD

**Issue by mscharmann** [oushujun/EDTA#109]
Dear Shujun,
first of all, let me thank you for your heroic effort of making an all-in-one pipeline for repeat annotation! EDTA installed seamlessly through conda, unlike any of the individual components I tried before EDTA..
I am processing a 500Mb plant genome, through slurm with a memory limit of 20 GB:

EDTA.pl --threads 12 --genome genome.fasta

It churned through the LTR phase but now is stuck in the TIR phase, in particular it called several python3 instances ( TIR-Learner2.5/Module3_New/getDataset.py ) that ran for about 60 min CPU time and built up 2.5 GB RAM each, but now they are inactive since at least 12 hours, i.e. no further outputs were written and CPU usage is zero. The last outputs it produced were of the kind "TIR-Learner-+-contig*-+-GRFmite.fa-+-p-+-toPre.fa-+-predi.fa".

I'll cancel the slurm process and re-start with a higher memory limit, but in case that was not the problem, I thought you might have an idea how to avoid the apparent "freeze" next time.

EDIT: Indeed 20GB mem was not enough, and one or more of EDTA's sub-processes got an OOM kill from slurm. However, this did not kill the main process, leading to freeze of the pipeline. 

With best regards, Mathias

**Comment by oushujun** [comment]
Hi Mathias,

Thank you for trying out EDTA. It seems that memory is usually the issue it gets stuck. You may also update EDTA to v1.9.0 which resolves some dead loop situation in the TIR process. Let me know if you have more questions.

Best,
Shujun
