### ISSUE TITLE
Whole-genome TE annotation summary empty

### ISSUE THREAD

**Issue by dong571** [oushujun/EDTA#110]
hellow,thank you for your soft.
       I find in the anno stage the Whole-genome TE annotation summary file （.sum），always emtpy .however I can not resolve the problems.
      wish your help,thanks

**Comment by oushujun** [comment]
Hello,

Please reinstall and update the package and rerun your analysis again. It may be a good idea to test on a small genome such as Arabidopsis or Drosophila. Please let me know if you encounter any errors.

Best,
Shujun

**Comment by dong571** [comment]
success，thank you again
