### ISSUE TITLE
question of patch_1.8.3_to_1.9.0.pl

### ISSUE THREAD

**Issue by yuanhelianyi** [oushujun/EDTA#111]
@oushujun 
Hi! I tried to convert the output to v1.9.0 using 'perl /data2/zhaoJing/bin/EDTA_V1.9.0/util/patch_1.8.3_to_1.9.0.pl Tu_v2.fasta'. There are two error as below. How to solve it? Thanks for your patient help.

Can't open perl script "/data5/zhaoJing//las/git_bin/LTR_retriever/bin/make_gff3.pl": 没有那个文件或目录
ls: 无法访问Tu_v2.fasta.mod*masked.cleanup.rmlist: 没有那个文件或目录

Jing

**Comment by oushujun** [comment]
Uhh, I didn't put the dependent script in the folder. Fixed. Please pull the new update and try again.

**Comment by yuanhelianyi** [comment]
@oushujun 

Thanks! I have pulled the new update. Now, it only indicated 'ls: 无法访问Tu_v2.fasta.mod*masked.cleanup.rmlist: 没有那个文件或目录'.

Jing

**Comment by oushujun** [comment]
Do you have the original intermediate files in the working folder?

**Comment by yuanhelianyi** [comment]
@oushujun 

Thanks! There is no file named "$genome*masked.cleanup.rmlist" when I checked in the $genome.EDTA.final. But a similar named file "$genome.RepeatModeler.raw.fa.masked.cleanup" exits. And I find there is file named '$genome.EDTA.intact.fa.masked.cleanup.rmlist' in the EDTA.pl script only when remove cds-related sequences in the EDTA library. However, I didn't offer cds file when I do the EDTA pipeline. How to solve it ?
 

Jing

**Comment by oushujun** [comment]
Hi Jing,

I see. I have made a changed to the script yesterday to fix this. You may try again.

Shujun

**Comment by yuanhelianyi** [comment]
@oushujun 
Hi shujun,

I do this convert using the latest version. It ran completely. It also indicated some warning lines. one is "Warning: TIR/MuDR_Mutator not found in the TE_SO database, will use the general term 'repeat_region     SO:0000657' to replace it." The other is "Use of uninitialized value $type in concatenation (.) or string at /data2/zhaoJing/bin/EDTA_v1.9.0/util/gff2bed.pl line 82, <GFF> line 4." There were thousands of lines per every warning. However, there is no record in the $genome.EDTA.TEanno.sum. I want you can check it.

Jing

**Comment by oushujun** [comment]
Hi Jing,

Thanks for your feedback. The first issue is easy to fix, if you see similar warnings for different TEs, please let me know and I can add them to the alias file. For the second error, can you send me samples of your gff3 files? 1000 lines of $genome.EDTA.intact.gff3, $genome.EDTA.RM.gff3, and $genome.EDTA.TEanno.gff3 should be sufficient. You may attach them on this thread or send them to shujun.ou1.@gmail.com. Thanks!

Shujun

**Comment by oushujun** [comment]
Hi Jing,

Please update to v1.9.3 and try the patch script again. THanks!

Shujun
