### ISSUE TITLE
TIR search fails

### ISSUE THREAD

**Issue by zhen0506** [oushujun/EDTA#112]
Hi Shujun,
TIR search failed when I ran EDTA for the first time.
This error message was retrieved from log.
Traceback (most recent call last):
  File "/apps/edta/1.9.0/share/EDTA/bin/TIR-Learner2.5/Module3_New/getDataset.py", line 12, in <module>
    from tensorflow.python.keras.utils import to_categorical
ImportError: cannot import name 'to_categorical' from 'tensorflow.python.keras.utils' (/apps/edta/1.9.0/lib/python3.8/site-packages/tensorflow/python/keras/utils/__init__.py)
cat: *-+-DTA.fa: No such file or directory
cat: *-+-DTC.fa: No such file or directory
cat: *-+-DTH.fa: No such file or directory
cat: *-+-DTM.fa: No such file or directory
cat: *-+-DTT.fa: No such file or directory
cat: *-+-NonTIR.fa: No such file or directory
cat: *-+-*-+-*.gff3: No such file or directory
rm: cannot remove â€˜*-+-*-+-*.gff3â€™: No such file or directory

I am using slurm to run on a cluster.
Best,
Zhen

**Comment by oushujun** [comment]
Hi Zhen,

Please test your installation with a small genome such as Arabidopsis, or allocate more resources to the run. If the test run fails, you may need to double-check the installation of EDTA.

Best,
Shujun

**Comment by zhen0506** [comment]
Hi Shujun,
Thanks for your reply. I ran small Arabidopsis genome, the same error still occurred.
I consulted with the HPC help desk of my institution. They suggest the the edta conda recipe is not working for HPC. They are trying to install it with other approach.
Best,
Zhen

**Comment by zhen0506** [comment]
What installation method do you recommend us to use?

**Comment by oushujun** [comment]
Hi Zhen,

I am sorry it's not successful for the conda approach. You may install the latest conda on your account, create a new env, and install it step by step. You may combine these approaches one way or the other. For example, you may use the HPC conda and try to install step by step, or install your own conda with the one-liner installation, and etc. It's tricky for some python dependencies and the only way is to keep trying until python yields on you.

If conda does not work, you may use the docker/singularity version, which is more platform independent.

Best,
Shujun
