### ISSUE TITLE
The correspondence b/w TElib.fa and TEanno.gff3 files

### ISSUE THREAD

**Issue by DrHogart** [oushujun/EDTA#113]
Hi,
I'm curious about the correspondence b/w two output files - TElib.fa and TEanno.gff3 have different sequence names. TElib.fa contains names such as TE_000001 while TEanno.gff3 contains names like Chr1:385616..392272. I understand that the sequences in TEanno.gff3 file came from the additional filtering and classification steps, while TElib.fa came primary from EDTA_raw.pl + RepeatModeller step. My expectation is that TElib.fa should contain all consensus sequences mentioned in the TEanno.fa file, but it is not the case. Is there any native way to extract all consensuses listed in the TEanno.gff3?

**Comment by oushujun** [comment]
Hi, the TEanno.gff3 is generated by combining the RepeatMasker annotation and structural annotation. For the RM annotation, the TElib.fa is used as the library, which also inherited the sequence IDs. Names like "Chr1:385616..392272" should be derived from the structural annotation. Currently, I keep their coordinates as IDs. You may run the EDTA.pl again with parameters `--anno 1 --step anno --curatedlib TElib.fa` to rename these structurally defined TEs with the TElib.fa ID. I will see if I can improve it on my end.

Shujun

**Comment by DrHogart** [comment]
Hi,
thanks for the suggestion.
I've re-run the EDTA with  `--anno 1 --step anno --curatedlib TElib.fa --overwrite 1` and get the novel TEanno.gff3. But now its size more than twice bigger than before and it contains all repeats from the first run and second re-run (with TElib.fa as the curatedlib). So, it is not renaming, but just the addition.
I'm curious, is it possible to add the extra field at column 9 in the TEanno.gff3 referring to the parental TE_* from TElib.novel.fa?
Thanks.

**Comment by oushujun** [comment]
It shouldn't contain the previous results with the overwrite option. I will
further look into it. You may remove the EDTA final and anno folders (be
sure to backup) and rerun from step final.

**Comment by oushujun** [comment]
@DrHogart I have incorporated your comments (rename intact TEs) as well as the bug (twice bigger) you identified to the new version. Please try it out. Thanks!

Shujun

**Comment by DrHogart** [comment]
Cool! I will try the upgraded EDTA this week. thanks!
