### ISSUE TITLE
Bypass TIR Learner step?

### ISSUE THREAD

**Issue by lcoombe** [oushujun/EDTA#115]
Hi Shujun,

You were helping me out over at the LTR retriever repo, and suggested I run the EDTA pipeline for a couple of ~6Gb genome assemblies. (https://github.com/oushujun/LTR_retriever/issues/81)

I've launched the EDTA pipeline (v1.9.0) over 3 weeks ago using the "Divide and Conquer" approach. The helitron and LTR jobs finished a while ago, but the TIR job is still running. Is there anyway that I could bypass the TIR prediction altogether, and finish the pipeline with just the Helitron/LTR data?

For more information, one of the assemblies has 658,701 scaffolds, and the other has 1,344,647 scaffolds. Both have been running for over 3 weeks.

Thank you in advance!
Lauren

**Comment by oushujun** [comment]
Hi Lauren,

Thank you for trying out EDTA! At the moment these three are critical components of the entire pipeline, especially during the filtering step, each of them helps to filter out false positives of the other two.

TIR_Learner may be stuck if the computation resource is not exclusive for the job. It seems like Python is not very good at working in multitasking mode. You may check the work folder and see if there are any new files being generated, otherwise, you need to kill and rerun this step with `--overwrite 0` and a dedicated node.

Best,
Shujun

**Comment by lcoombe** [comment]
Hi Shujun,

Thank you for your prompt repose! 

I do see that files are still being created in each run, although the two seem to be in different stages:
```
TIR-Learner-+-s00005782-+-GRFmite.fa-+-p-+-toPre.fa-+-predi.fa
```
```
TIR-Learner-+-s00779621-+-GRFmite.fa
```

So I suppose if the files are still being generated I should just let it keep running? Based on those file names, do you have any sense of how far along the runs are in the TIR learner process?

Thank you!
Lauren

**Comment by oushujun** [comment]
Hi Lauren,

It seems that the program is still running normally. s00005782 and s00779621 are the sequences it was working on. The program works on sequences in the order of how they present in the input, so you can use this to guess how far away is the finishing line. 

Best,
Shujun

**Comment by oushujun** [comment]
@lcoombe Any luck?

**Comment by lcoombe** [comment]
Hi Shujun,

Yes, I've had partial luck! The TIR step finished running after 33 days for one of the assemblies, but I decided to kill the other job, since it had been going for nearing 2 months, and didn't appear close to finishing. 
It's good to know though that for the TIR step anyway, it seems like the slowdown is due to the number of sequences vs. the genome size -- I also ran an EDTA job for a spruce genome (~20Gbp genome size), but it was quite a lot more contiguous than my 6Gbp genomes, and the TIR step finished in ~17 days!

Thanks for your help,
Lauren

**Comment by oushujun** [comment]
Hi Lauren,

It's true that the TIR module is the slow part. I recently fixed a bug (v1.
9. 3) for occasional dead loops, which are quite frequently seen in
good/large genomes. Those have been run for 2 months may be a similar case,
and the new code can speed up these dead loops for over 1000 times. You may
want to pull the new update and try again.

Best,
Shujun

**Comment by lcoombe** [comment]
Hi Shujun,

Oh great - thank you for the heads up with the new version! I'll give that a try.
Are you planning on making an official release for that version? Just wondering if it will be updated on conda.

Thank you for your help!
Lauren

**Comment by oushujun** [comment]
I am planning to add more updates to it before a new release based on
feedbacks from other issues. It could be done this week. You don't need to
reinstall with conda, just pull the github version and specify the path.

Shujun

**Comment by oushujun** [comment]
@lcoombe v1.9.4 [released](https://github.com/oushujun/EDTA/releases/tag/v1.9.4)!

**Comment by lcoombe** [comment]
Excellent - thanks Shujun! I'm excited to try it out!
