### ISSUE TITLE
suggestion: add rpt_type and rpt_family to gff3

### ISSUE THREAD

**Issue by JWDebler** [oushujun/EDTA#117]
Would it be possible to add the 'rpt_type' and 'rpt_family' tags to the gff3 file, so the annotation can be added to a submitted genome to genbank?
https://www.ncbi.nlm.nih.gov/WebSub/html/annot_examples.html#repeat

**Comment by oushujun** [comment]
Hello @JWDebler,

Based on the definition provided by your link, 'rpt_type' is equivalent to the third column 'sequence_ontoloty' and 'rpt_family' is equivalent to the Family info in the last column. You may convert them to your desired format.

Best,
Shujun

**Comment by JWDebler** [comment]
What I meant was to make the GFF3 output compliant with Genbank's vocabulary. Currently, if I run the gff3 file through genbank's table2asn converter, which converts an input gff file to sqn format that can be uploaded I get several errors:

`Recognized annotation format: GFF3
Falling back on built-in data for popular organisms.
                Error:
Problem:        Bad data line: Invalid feature type "hAT_TIR_transposon"
Line:           1


                Error:
Problem:        Bad data line: Invalid feature type "Mutator_TIR_transposon"
Line:           2


                Error:
Problem:        Bad data line: Invalid feature type "target_site_duplication"
Line:           4


                Error:
Problem:        Bad data line: Invalid feature type "LTR_retrotransposon"
Line:           6


                Error:
Problem:        Bad data line: Invalid feature type "target_site_duplication"
Line:           8


                Error:
Problem:        Bad data line: Invalid feature type "Mutator_TIR_transposon"
Line:           9
 `

Genbank doesn't accept these names in the 'feature' field. They would have to be 'repeat_region' or 'mobile_element' as described [here](http://www.insdc.org/controlled-vocabulary-rpttype-qualifier) and [here](http://www.insdc.org/documents/feature-table) and would then have to be further described with the 'rpt_type, rpt_family etc. tags in column 9 of the gff.
I know that I can manually parse the output file to make it genbank compliant, but I was hoping that that could be integrated directly into the software, so the output file is immediately useable for genbank upload purposes.

**Comment by oushujun** [comment]
Hello @JWDebler,

I am afraid the feature field descriptions 'repeat_region' or 'mobile_element' are not informative enough for the TE classifications. I coded the third column based on the Sequence Ontology standard as you can find more information here: http://www.sequenceontology.org/browser/obob.cgi. Such information is parsable by other programs and you can find more discussions in this thread: https://github.com/oushujun/EDTA/issues/83

Best,
Shujun
