### ISSUE TITLE
Use cleanup_TE.pl alone on TElibrary and CDS files

### ISSUE THREAD

**Issue by zhen0506** [oushujun/EDTA#118]
Hi Shujun,
I tried to use cleanup_TE.pl providing a custom TE library and a CDS file to clean up the TE library.
It stopped after showing these messages.
2020-10-01 08:22:51,265 -INFO- Pipeline done.
2020-10-01 08:22:51,266 -INFO- cleaning the temporary directory ./tmp
awk: fatal: cannot open file `TElib.fa.out' for reading (No such file or directory)
awk: fatal: cannot open file `TElib.fa.out' for reading (No such file or directory)
Thanks,
Zhen

**Comment by zhen0506** [comment]
$ ls
F15_TElib.fa               F15_TElib.fa.prot_clean                  f.ananassa_GDR_reftransV1.fasta.code.TE.list        f.ananassa_GDR_reftransV1.fasta.code.rexdb.cls.tsv   f.ananassa_GDR_reftransV1.fasta.code.rmTE
F15_TElib.fa.clean         consensi.fa.classified                   f.ananassa_GDR_reftransV1.fasta.code.list           f.ananassa_GDR_reftransV1.fasta.code.rexdb.dom.faa   f.ananassa_GDR_reftransV1.fasta.code.rmTE2
F15_TElib.fa.exclude       f.ananassa_GDR_reftransV1.fasta          f.ananassa_GDR_reftransV1.fasta.code.noTE           f.ananassa_GDR_reftransV1.fasta.code.rexdb.dom.gff3
F15_TElib.fa.exclude.list  f.ananassa_GDR_reftransV1.fasta.code     f.ananassa_GDR_reftransV1.fasta.code.rexdb.cls.lib  f.ananassa_GDR_reftransV1.fasta.code.rexdb.dom.tsv
F15_TElib.fa.prot.out      f.ananassa_GDR_reftransV1.fasta.code.TE  f.ananassa_GDR_reftransV1.fasta.code.rexdb.cls.pep  f.ananassa_GDR_reftransV1.fasta.code.rexdb.domtbl

**Comment by zhen0506** [comment]
Hi Shujun,
Do I need to provide path of Repeatmasker to the cleanup_TE.pl?
Thanks,
Zhen

**Comment by zhen0506** [comment]
Also cleanup_proteins.pl exits before completion, too.
With the following message.
$ perl ~/miniconda3/pkgs/edta-1.9.0-0/share/EDTA/util/cleanup_proteins.pl -seq 15_TElib.fa
Use of uninitialized value $stp in subtraction (-) at /home/fan/miniconda3/pkgs/edta-1.9.0-0/share/EDTA/util/call_seq_by_list.pl line 186.
Use of uninitialized value $stp in division (/) at /home/fan/miniconda3/pkgs/edta-1.9.0-0/share/EDTA/util/call_seq_by_list.pl line 186.
Illegal division by zero at /home/fan/miniconda3/pkgs/edta-1.9.0-0/share/EDTA/util/call_seq_by_list.pl line 186.

**Comment by oushujun** [comment]
Hello @zhen0506,

Sorry for the delayed response. The error for your `cleanup_TE.pl` execution should be due to the incorrect installation of `TEsorter`. Please test it first then this script.

The errors for `cleanup_proteins.pl` may be due to the lack of blast results using your provided sequence (meaning there is no protein contaminations). You may check the execution folder for `*.dnate.out`, `*.line.out`, and `*.prot.out` and see if any of them is empty.

Best,
Shujun

**Comment by zhen0506** [comment]
Hi Shujun,
Thank you for your reply. The cleanup_proteins.pl generated the following file.
![image](https://user-images.githubusercontent.com/61021345/95594827-70ed6b80-0a19-11eb-8ed8-4a5fd463387f.png)
Besides *.exclude, others are not empty.

Best,

**Comment by oushujun** [comment]
@zhen0506 Can you provide the file `15_TElib.fa` to test on my end?

**Comment by zhen0506** [comment]
Hi Shujun
I rerun the whole process on my local machine. It completes. 
Thanks,
Zhen
