### ISSUE TITLE
Suggestion：A potential bug: in the EDTA.pl script

### ISSUE THREAD

**Issue by Tianxuzhang-bio** [oushujun/EDTA#119]
Hi !   I noticed a potential bug at line 221 to 222 in EDTA.pl 

# GenomeTools
221:chomp ($genometools=`which gt 2>/dev/null`) if $genometools eq '';
222:$genometools=~s/gt\n?// unless -d $genometools;

if my genometools‘s path has the key words “gt” , the program will get a wrong path of genometools , is better to do Dependency checking in another way(such as basename library?).

Tianxu

**Comment by oushujun** [comment]
Fixed. Thanks! -Shujun
