### ISSUE TITLE
TEanno.sum file empty

### ISSUE THREAD

**Issue by rimjhimroy** [oushujun/EDTA#123]
Hi @oushujun,

I am running EDTA as follows:
`EDTA.pl --step all --curatedlib ../Brassicaceae_repbase_all_march2019.fa --sensitive 1 --evaluate 1 --anno 1 --threads 10 --genome athchr1.fasta`

I am testing the pipeline with Arabidopsis chromosome 1.
I am getting this error at the end of the EDTA pipeline,

```
Tue Oct  6 22:04:39 CEST 2020   Evaluate the level of inconsistency for whole-genome TE annotation (slow step):

Use of uninitialized value in pattern match (m//) at /data/users/rchoudhury/programs/EDTA1.9/EDTA/util/call_seq_by_list.pl line 88.
Use of uninitialized value $chr_pre in hash element at /data/users/rchoudhury/programs/EDTA1.9/EDTA/util/call_seq_by_list.pl line 90.
Use of uninitialized value $pos in pattern match (m//) at /data/users/rchoudhury/programs/EDTA1.9/EDTA/util/call_seq_by_list.pl line 100.
Use of uninitialized value $pos in concatenation (.) or string at /data/users/rchoudhury/programs/EDTA1.9/EDTA/util/call_seq_by_list.pl line 103.
ERROR: Can not recognize this MSU position in the list!
ERROR: TE annotation stats results not found in athchr1.fasta.mod.EDTA.TE.fa.stat!
```

I have attached the full error report here
[EDTA.txt](https://github.com/oushujun/EDTA/files/5369816/EDTA.txt)

Many thanks for your help.

Rimjhim

**Comment by oushujun** [comment]
Hi Rimjhim,

It's likely that the curated library you provided `Brassicaceae_repbase_all_march2019.fa` does not have classification info in it. 

v1.9.3 should have fixed this error: `Use of uninitialized value $type in concatenation (.) or string at /data/users/rchoudhury/programs/EDTA1.9/EDTA/util/gff2bed.pl line 82, <GFF> line 6331.`

Please update and try again.

Best,
Shujun

**Comment by rimjhimroy** [comment]
Hi Shujun,

Thanks for your swift response. Indeed, updating to v1.9.3 + a library with classification information in RepeatMasker format solved the issue. 

Many Thanks,
Rimjhim

**Comment by oushujun** [comment]
Hi @sanyalab, you may install v1.9.0 using conda, then git clone v1.9.3 and run EDTA from the cloned path using the conda env. - Shujun

**Comment by Min84-dl** [comment]
Hi, @oushujun 

I ran EDTA with v2.1.3, and I met the same issue that 'TEanno.sum file is empty'.

My commond: EDTA.pl --genome genome.fa --cds cds.fa --species others --step all --sensitive 1 --anno 1 --overwrite 0

Error: Use of uninitialized value $type in concatenation (.) or string at /home/wangmin/software/EDTA/util/gff2bed.pl line 110, <GFF> line 5320.
Use of uninitialized value $type in concatenation (.) or string at /home/wangmin/software/EDTA/util/gff2bed.pl line 110, <GFF> line 7173.
...

Can you help me?

Thanks
Min
