### ISSUE TITLE
Error while identifying TIR candidates

### ISSUE THREAD

**Issue by moreiradaniel** [oushujun/EDTA#126]
Dear Shujun,

Thank you for have developed this pipeline! 

I have installed EDTA using conda, and I am processing a 2.5Gb primate genome through slurm, using 50 threads and 128Gb of memory.

I've got the following error message while TIR candidates were been identified:

################
Tue Oct 20 18:55:52 -03 2020    Start to find TIR candidates.

Tue Oct 20 18:55:53 -03 2020    Identify TIR candidates from scratch.

Species: others

        ERROR: no LOC list!

        Usage: perl call_seq_by_list.pl MSU_format_list -C genome.fasta -out file.fa [options]
                itself  Output sequence specified in the list (default).
                up_[int]        Output sequences [int] bp upstream of the region.
                down_[int]      Output sequences [int] bp downstream of the region.
                -C [fasta]      A fasta file you want to extract sequence from.
                -out    Output file name. Default: MSU_format_list.fa
                -header [0|1]   Output sequence with (1, default) or without (0) sequence header.
                -rmvoid [0|1]   Remove empty sequence (1, default) or retain empty sequence (0) in output.
                -ex             Exclude sequence specified by the list. Default: Output sequence specified by the list.
                -cov    [0-1]   Work with -ex. If excluding too much of the target (default 1), discard the entire sequence.
                -purge  [0|1]   Work with -ex. Switch on=1/off=0(default) to clean up aligned region and joint unaligned sequences.
        Example:
                Call sequence of upper 2000 bp region in the list and output to result.fa
                        perl call_seq_by_list.pl array_list -C rice.fasta up_2000 -out result.fa
################

However, after printing the same message a few more times, the script returned the message that this step was finished:
"Wed Oct 21 06:19:12 -03 2020    Finish finding TIR candidates."

Is this error message something I should be concerned about?

Thanks for your help.

Best,
Daniel

**Comment by oushujun** [comment]
Hi Daniel,

Sorry for the delayed response. I just made a new release [v1.9.4](https://github.com/oushujun/EDTA/releases/tag/v1.9.4). The update of conda installation approach may be lagging for a couple of hours but you can simply pull it from github. Now you can test the installation with files and code in the `./EDTA/test` folder. Please let me know if your run still has errors.

Best,
Shujun

**Comment by moreiradaniel** [comment]
Hi Shujun,

Thank you for your reply. I just ran the new release on your test data and got some errors as following (log file attached):

2020-10-29 16:57:33,441 -WARNING- exit code 1 for CMD 'hmmscan --notextw -E 0.01 --domE 0.01 --noali --domtblout ./tmp/chunk_aaseq.13.fasta.domtbl /data04/projects04/HectorSeuanez/brachyteles/bin/Daniel/EDTA/lib/python3.6/site-packages/TEsorter/database/REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm ./tmp/chunk_aaseq.13.fasta'
2020-10-29 16:57:33,441 -WARNING-
        STDOUT:
b''
        STDERR:
b'\nError: Sequence file ./tmp/chunk_aaseq.13.fasta is empty or misformatted\n\n'

I'm also running the new version of EDTA on my own data and is all going well so far.

Best,
Daniel
[EDTA.test.txt](https://github.com/oushujun/EDTA/files/5461052/EDTA.test.txt)

**Comment by oushujun** [comment]
Hi Daniel,

Thanks for testing it out. The error is due to an existing bug https://github.com/zhangrengang/TEsorter/issues/18 which has been fixed in the new version of TEsorter. When TEsorter recipe is updated on conda (pending), this should go away. However, this does not affect your run when the input sequence is large enough (i.e., seq # > thread #). Please let me know if you encounter other issues.

Best,
Shujun
