### ISSUE TITLE
libstdc++.so.6: version `GLIBCXX_3.4.20' not found

### ISSUE THREAD

**Issue by oushujun** [oushujun/EDTA#13]
hi Shujun, 

Unfortunately I'm still having trouble with this. Following on from my previous comment, I am now using my own installed version of RepeatMasker and everthing seems to work until it gets to TIR learner, where I am now getting the below error.

```

Fri Aug 16 19:10:44 CEST 2019	Dependency checking:
		All passed!
Fri Aug 16 19:10:56 CEST 2019	Obtain raw TE libraries using various structure-based programs:
/stn4/djeffrie/EDTA/bin/TIR-Learner1.19/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /stn4/djeffrie/EDTA/bin/TIR-Learner1.19/../GenericRepeatFinder/bin//grf-main)
/stn4/djeffrie/EDTA/bin/TIR-Learner1.19/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /stn4/djeffrie/EDTA/bin/TIR-Learner1.19/../GenericRepeatFinder/bin//grf-main)

```

Apparently I don't have the correct GLIBCXX version? 

Any ideas? 

Best

Dan

_Originally posted by @DanJeffries in https://github.com/oushujun/EDTA/issues/11#issuecomment-522095771_

**Comment by oushujun** [comment]
Hi Dan,

This is an issue with GRF. Please enter the GRF folder and recompile the program.

`cd /stn4/djeffrie/EDTA/bin/TIR-Learner1.19/../GenericRepeatFinder/`
Follow `[1] Installation of GRF` in `readme.txt`:
>[1] Installation of GRF  
Download and unzip our source code and executable programs - "grf.XXX.tar.gz".# tar zxf grf.XXX.tar.gz
The source code is under "grf.XXX/src/".
If you want to compile the source code yourself, 
(1) go to "grf.XXX/src/", and run "make" (easy way)
or (2) use g++ to compile with flag: "-std=c++11 -fopenmp". e.g.,
   cd grf.XXX/src/grf-main
   g++ main.cpp DetectMITE.h DetectMITE.cpp DetectIR.h DetectIR.cpp functions.h functions.cpp -std=c++11 -fopenmp -O3 -o grf-main

To test the freshly installed GRF, simply run:
`/stn4/djeffrie/EDTA/bin/TIR-Learner1.19/../GenericRepeatFinder/bin/grf-main`

If you don't see the same error but instead seeing program instructions, then GRF is good now.

After that, rerun EDTA and it should be able to pick up where it ceased without rerunning the modules that are finished. You don't need to specify extra parameters because I try to make it as easy as possible.

Best,
Shujun

**Comment by oushujun** [comment]
I just pushed some new updates to EDTA, mainly to fix the TIR-Learner issue. Please reinstall EDTA and rerun it in the same work folder. Existing results will be reused so there is essentially no waste of time. Thank you for your patience and support!

**Comment by Neato-Nick** [comment]
Hi, I'm getting this same bug with GRF, except my messages are for both GLIBCXX_3.4.20 and GLIBCXX_3.4.21. I'm using a new EDTA environment that I installed at the same time I pulled the EDTA repo after your commits on 8/16/19. It sounds like the GRF binaries you include with EDTA aren't playing nicely with the OS I'm running it in and I should re-compile GRF?

**Comment by oushujun** [comment]
Hi @Neato-Nick, yes, that GRF was only compiled to RedHat Enterprise. So please recompile it on your own OS following the instructions of the GRF readme or some hints above.

Best,
Shujun

**Comment by Neato-Nick** [comment]
Followed the instructions (both the "easy" way and the other way) and I couldn't get it to compile. Looks like GRF requires g++ and gcc 4.9+, my OS is running g++ and gcc 4.8.5. I was hoping to do all this on my university's HPC, but I don't have super user privileges to upgrade my compiler. I'll try running locally, where my system is up-to-date

```
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36)
```

**Comment by oushujun** [comment]
bummer... maybe you can try conda g++? Not sure if this exists or works.
HPCs may have multiple g++ available, so you may want to search or ask your
HPC admin, or request an update.

**Comment by QiushiLi** [comment]
My solution:

in the EDTA env

conda install -c serge-sans-paille gcc_49
ln -s /path/to/anaconda3/envs/EDTA/bin/gcc-4.9 /path/to/anaconda3/envs/EDTA/bin/gcc
ln -s /path/to/anaconda3/envs/EDTA/bin/gcc++-4.9 /path/to/anaconda3/envs/EDTA/bin/gcc++

conda install libgcc
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/anaconda3/lib

**Comment by sunnycqcn** [comment]
> My solution:
> 
> in the EDTA env
> 
> conda install -c serge-sans-paille gcc_49
> ln -s /path/to/anaconda3/envs/EDTA/bin/gcc-4.9 /path/to/anaconda3/envs/EDTA/bin/gcc
> ln -s /path/to/anaconda3/envs/EDTA/bin/gcc++-4.9 /path/to/anaconda3/envs/EDTA/bin/gcc++
> 
> conda install libgcc
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/anaconda3/lib

Your method can be successfully installed EDTA env and compiled GRF. However, I run the pipeline, it  still need "/home/AAFC-AAC/fuf/EDTA/bin/TIR-Learner2.4/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/AAFC-AAC/fuf/EDTA/bin/TIR-Learner2.4/../GenericRepeatFinder/bin//grf-main)".
Thanks,
Fuyou

**Comment by sunnycqcn** [comment]
> My solution:
> 
> in the EDTA env
> 
> conda install -c serge-sans-paille gcc_49
> ln -s /path/to/anaconda3/envs/EDTA/bin/gcc-4.9 /path/to/anaconda3/envs/EDTA/bin/gcc
> ln -s /path/to/anaconda3/envs/EDTA/bin/gcc++-4.9 /path/to/anaconda3/envs/EDTA/bin/gcc++
> 
> conda install libgcc
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/anaconda3/lib

LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/anaconda3/lib change to:
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/anaconda3/envs/EDTA/lib
Then it works to me.
Thanks,
Fuyou

**Comment by oushujun** [comment]
Since there is more than one solution for this issue, I mark this as resolved. Feel free to reopen it if you identify new issues on this topic.
