### ISSUE TITLE
"--evaluate" can not work

### ISSUE THREAD

**Issue by 1Wencai** [oushujun/EDTA#130]
Hi
Thanks for developing the EDTA.
I am using EDTA ,following is the code :
`/home/zhangwencai/EDTA/EDTA.pl -genome /data/zhangwencai/reference/pombe.ASM294v2.29.dna.toplevel.fa -species others -step all -sensitive 1 -t 14 -anno 1 -evaluate 1 -curatedlib /data/zhangwencai/reference/curatelib2.fa`

but "--evaluate" can not work, and the file 'pombe.ASM294v2.29.dna.toplevel.fa.mod.EDTA.TE.fa.stat'  is  empty ，following is Part of the run log :
`Sun Oct 18 17:50:28 HKT 2020	Evaluate the level of inconsistency for whole-genome TE annotation (slow step):
ERROR: TE annotation stats results not found in pombe.ASM294v2.29.dna.toplevel.fa.mod.EDTA.TE.fa.stat!
`
My EDTA version is v1.9.3

Is this a bug? Could you tell me how I use the parameter of "--evaluate"?

best
wencai

**Comment by oushujun** [comment]
Hi Wencai,

Please use double dashes (`--`) for parameter settings in EDTA. Do you see annotation results as expected? You need to have annotations before `--evaluate 1`. Please double-check if the pipeline is running properly.

Best,
Shujun

**Comment by 1Wencai** [comment]
Hi Shunjun,
It also does not work after i double "-" .

following is the code :
`/home/zhangwencai/EDTA/EDTA.pl --genome /data/zhangwencai/reference/pombe.ASM294v2.29.dna.toplevel.fa --species others --step all --sensitive 1 -t 14 --anno 1 --evaluate 1 --curatedlib /data/zhangwencai/reference/curatelib2.fa`

 the file 'pombe.ASM294v2.29.dna.toplevel.fa.mod.EDTA.TE.fa.stat'  also is empty ，following is Part of the run log :
`Evaluate the level of inconsistency for whole-genome TE annotation (slow step):

ERROR: TE annotation stats results not found in pombe.ASM294v2.29.dna.toplevel.fa.mod.EDTA.TE.fa.stat!`

looking forward to receive your answer.

Best
Wencai

**Comment by oushujun** [comment]
Hi Wencai,

The single dash parameter setting has been removed for quite a while. What version of EDTA are you using? Please update to the latest version.

Best,
Shujun

**Comment by 1Wencai** [comment]
Hi Shujun,

My version is v1.9.3, I will try v1.9.4. And tell you what happened later.
Thanks.

Best,
Wencai

**Comment by 1Wencai** [comment]
Hi Shujun,

My version is v1.9.4 now,but "--evaluate" also does not work after i double "-" .

following is the code :
/home/zhangwencai/EDTA194/EDTA/EDTA.pl --genome /data/zhangwencai/reference/pombe.ASM294v2.29.dna.toplevel.fa --species others --step all --sensitive 1 -t 14 --anno 1 --evaluate 1 --curatedlib /data/zhangwencai/reference/curatelib2.fa

the file 'pombe.ASM294v2.29.dna.toplevel.fa.mod.EDTA.TE.fa.stat' also is empty ，following is Part of the run log :
`Evaluate the level of inconsistency for whole-genome TE annotation (slow step):

ERROR: TE annotation stats results not found in pombe.ASM294v2.29.dna.toplevel.fa.mod.EDTA.TE.fa.stat!`

looking forward to receiving your answer.

Best
Wencai

**Comment by oushujun** [comment]
Hi Wencai,

Sorry for the delayed response. You may run the test case (./EDTA/test/) to make sure your version of EDTA is running properly.

Best,
Shujun

**Comment by oushujun** [comment]
Hi Wencai,

Sorry for the delayed response. You may run the test case (./EDTA/test/) to make sure your version of EDTA is running properly.

Best,
Shujun
