### ISSUE TITLE
Clarification regarding the filters used

### ISSUE THREAD

**Issue by mariaventimiglia** [oushujun/EDTA#131]
Hi, I am using EDTA on TE types individually (EDTA_raw.pl) starting from TIR elements.
I am getting this outputs:
- TIR-Learner_FinalAnn.fa & TIR-Learner_FinalAnn_filter.fa in the TIR-Learner-Result directory;
- genome.fasta.mod.TIR.intact.fa & genome.fasta.mod.TIR.raw.fa in the upper directory

I would like to know which filters in particular generate the different types of output. I guess TIR-Learner_FinalAnn.fa is the TIR-Learner output, but what about the _filter.fa file? Are the other two outputs, respectively, the result of the "simple filter" and of the "higher level filter" as mentioned in the paragrafh "Construction of the Extensive de-novo TE annotator pipeline" of your published article?

Thanks,
Maria

**Comment by oushujun** [comment]
Hi Maria,

Both TIR-Learner_FinalAnn.fa & TIR-Learner_FinalAnn_filter.fa in the TIR-Learner-Result directory are generated by TIR-Learner. 

genome.fasta.mod.TIR.intact.fa & genome.fasta.mod.TIR.raw.fa in the upper directory are generated by simple filters of EDTA.

These are the codes for TIR-Learner simple filters by EDTA:
https://github.com/oushujun/EDTA/blob/7f9f72fe13ea29908982c3cc7829f12dc5ed2515/EDTA_raw.pl#L386-L416

The higher-level filter is done by the EDTA_process.pl [script](https://github.com/oushujun/EDTA/blob/master/EDTA_processI.pl). 

Hope this helps!
Shujun

**Comment by mariaventimiglia** [comment]
Thanks for the very clear explanation. It was helpful!

Maria
