### ISSUE TITLE
Pan genome comparison

### ISSUE THREAD

**Issue by Chriswinefield** [oushujun/EDTA#132]
Dear Sunjun,

Like many others, my thanks to you for developing and maintaining this pipeline - it is a fantastic toolset.

I have a quick request for your advice on how best to set EDTA up to allow direct comparison of the TE landscapes between cultivars/landraces of the same species. 

I am working on comparisons among 2 Tobacco populations where I am keen to compare the development of the TE landscapes in their respective genomes.

I have run each genome separately and am wondering how best to reorganize the family names to ensure matching data ( so family TE00001 in genome 1 is the same family as in genome 2 - which at the moment we obviously don't know without further manipulation of the output of genome 2).

I have contemplated using the TE lib from one genome in the EDTA run of the second but given this is machine generated I gather this isnt an appropriate way forward.

I then thought combining the genomes in a single input might be a way forward - splitting the output(s) afterward.

I have concatenated the 2 genomes and have set up a run - however this is taking a very long time to complete.....we are not too far off 1 month at the moment. The pipeline is in the annotation phase at the moment. The genome is 18 chromosomes derived from a allotetraploid of around 3.5 GB

If you have any suggestions I would be most grateful

Kind Regards

Chris

**Comment by oushujun** [comment]
Hi Chris,

Thanks for using EDTA! It is you and other users making this program better and better.
For your question, you may run EDTA on both genomes separately and combine them with the make_panTElib.pl [script](https://github.com/oushujun/EDTA/blob/master/util/make_panTElib.pl). Then feed EDTA with this combined library with the `--curatedlib` parameter (even though it is not curated...) and rerun EDTA on both genomes again. You may rerun it on the existing results from the first round. After that, you will get a pan-genome annotation for both genomes with unified TE names.

Best,
Shujun

**Comment by Chriswinefield** [comment]
Hi Shujun,

Many thanks for that - I will queue this up shortly
Best
Chris
