### ISSUE TITLE
mv: cannot stat 'xxxx.fasta.mod.EDTA.intact.fa.rename': No such file or directory

### ISSUE THREAD

**Issue by licheng0921** [oushujun/EDTA#140]
Hi Shujun,
Thank you for your EDTA! 
I am trying to annotate TE using EDTA (v1.9.4). I have tested several genomes with genome size from 0.5g to 1.5g. It always gave same error, as follows.

mv: cannot stat 'xxxx.fasta.mod.EDTA.intact.fa.rename': No such file or directory
Homology-based annotation of TEs using xxxxx.fasta.mod.EDTA.TElib.fa from scratch.
Use of uninitialized value $element_start in subtraction (-) at /path/to/biosoft/EDTA/util/make_masked.pl line 119, <Mask> line 653711.
Use of uninitialized value $element_end in subtraction (-) at /path/to/biosoft/EDTA/util/make_masked.pl line 119, <Mask> line 653711.
Use of uninitialized value $element_start in subtraction (-) at /path/to/biosoft/EDTA/util/make_masked.pl line 120, <Mask> line 653711.
Use of uninitialized value in substr at /path/to/biosoft/EDTA/util/make_masked.pl line 120, <Mask> line 653711.
......
......
Use of uninitialized value $type in concatenation (.) or string at /vol1/agis/wangli_group/licheng/biosoft/EDTA/util/gff2bed.pl line 84, <GFF> line 1971848.
Use of uninitialized value $type in concatenation (.) or string at /vol1/agis/wangli_group/licheng/biosoft/EDTA/util/gff2bed.pl line 84, <GFF> line 1977469.
Use of uninitialized value $type in concatenation (.) or string at /vol1/agis/wangli_group/licheng/biosoft/EDTA/util/gff2bed.pl line 84, <GFF> line 1978999.
.....
.....

How can I deal with this error ?

By the way, when I set `--sensitive =0` to run the script, it will run smoothly. I do not know whether the error is about repeatmodeler.

best,

licheng

**Comment by oushujun** [comment]
Hi licheng,

Did you use the conda version or the docker version? Please double check your sequence names, make sure they are simple and short. Have you run with the test sample? Or can you provide a small sequence file to reproduce your error? Thanks!

Shujun
