### ISSUE TITLE
Repbase repeats via --curatedlib parameter

### ISSUE THREAD

**Issue by sanyalab** [oushujun/EDTA#141]
Hi Shujun,

I am still a little fuzzy on how the --curatedLib feature gets used. Although you have given a very good explanation in Issue#128 "How to find TIR in novel species by EDTA #128"

If we give libraries from Repbase or some other source for a particular species or its close relative to EDTA, how do these repeats appear in the final TElib.fa? When you say that these repeats are incorporated "as is" in the final TElib, do you mean

1) the final TElib will contain them these repeats given by --curatedlib parameter without any modification OR
2) In the final TElib, homologs of the repeats specified by the --curatedlib parameter will be present.
Lastly, If I want repeatmasker to use the Repbase database to predict homology based repeats, do I specify that with the --curatedlib parameter?

Thanks
Abhijit

**Comment by oushujun** [comment]
HI Abhijit,

"As is" means exactly the same information (down to the level of bits and characters) is appended to the final TElib. EDTA will treat information from `--curatedlib` like gold and use it to remove anything similar to them from the _de novo_ library, and concatenate (i.e., `cat novol_TE.fa >> curated_TE.fa`) novel seqs from the _de novo_ library to the curated library. So if sequence names in the curatedlib are malformatted, i.e., do not follow the RepeatMasker library naming format, then they won't be correctly categorized in the final report.

Hope this helps!

Best,
Shujun
