### ISSUE TITLE
Filtering of Helitron and TIR fails

### ISSUE THREAD

**Issue by cgrootcrego** [oushujun/EDTA#143]
Dear Shujun,

I have been rerunning EDTA on two genomes with the most recent version 1.9.4 (previously run with 1.8.5), and have been running into a lot of problems that did not come up previously, for some reason. One of them is that in some runs, TIR or Helitron end up with empty filtered files. In my last run, TIR ran without issues but Helitron failed this way:

Tue Dec 29 14:51:36 CET 2020	Dependency checking:
				All passed!
	A CDS file ../../pineapple.20150427.cds.wo_transposons.fasta is provided via --cds. Please make sure this is the DNA sequence of coding regions only.
Tue Dec 29 14:51:54 CET 2020	Obtain raw TE libraries using various structure-based programs: 
Tue Dec 29 14:51:54 CET 2020	EDTA_raw: Check dependencies, prepare working directories.
Tue Dec 29 14:52:03 CET 2020	Start to find LTR candidates.
Tue Dec 29 14:52:03 CET 2020	Identify LTR retrotransposon candidates from scratch.
Tue Dec 29 18:36:27 CET 2020	Finish finding LTR candidates.
Tue Dec 29 18:36:27 CET 2020	Start to find TIR candidates.
Tue Dec 29 18:36:27 CET 2020	Identify TIR candidates from scratch.
Species: others
Tue Dec 29 21:05:27 CET 2020	Finish finding TIR candidates.
Tue Dec 29 21:05:27 CET 2020	Start to find Helitron candidates.
Tue Dec 29 21:05:27 CET 2020	Identify Helitron candidates from scratch.
	perl make_bed_with_intact.pl EDTA.intact.fa > EDTA.intact.bed 
Wed Dec 30 04:38:48 CET 2020	Warning: The Helitron result file has 0 bp!
Wed Dec 30 04:38:48 CET 2020	Execution of EDTA_raw.pl is finished!
ERROR: Raw Helitron results not found in Tillandsia_leiboldiana_26_scaffolds.fasta.mod.EDTA.raw/Tillandsia_leiboldiana_26_scaffolds.fasta.mod.Helitron.raw.fa
	If you believe the program is working properly, this may be caused by the lack of intact Helitrons in your genome. Consider to use the --force 1 parameter to overwrite this check

The file HelitronScanner.filtered.ext.fa.cov0.9iden90.tabout is not empty, but anything created after that is. Here's a section of the tabout file:
true	1	1	NA	Scaffold_247	4278200	4276539	Scaffold_247:4278200..4276539	CATATTCTTTTACTT*TTTTACATAACATGC	CGTTTCTAAAATGTACATATTCTTTTACTT	TCCTGACTAATAAAAAAAAAATTAAAATTT	GTCCGCCGCGAAGCGCGGGTCTTTAACTAG	TTTTACATAACATGCCGCATGCAAGATAAC
false	119	467	0	Scaffold_247	36914733	36920267	Scaffold_247:36914733..36920267	TTCATACTTTAACTA*TGTAGTCGGGTTGAT	GATTCATTTCCCGCATTCATACTTTAACTA	TCTATCTATCTATCTATCTATCTGTTTTTG	TTTTTCGGTTTAGCTCGGGTGTTGTGCTAG	TGTAGTCGGGTTGATTTGGAGGTTGGGTCG
false	68	1	NA	Scaffold_247	3971059	3971347	Scaffold_247:3971059..3971347	AGTTTTGCTACTTAA*TAATATTTAATTTTA	TATCTAATTTAAATTAGTTTTGCTACTTAA	TCATTTACTATTATATATATAATTATAATT	TACCGCAGCGAAGCGCGGGTGTTTAACTAG	TAATATTTAATTTTAAACATTTGAACAGAG
false	3	189	NA	Scaffold_247	21973860	21957465	Scaffold_247:21973860..21957465	GCATAAATAATATTA*TTGTTAGGAGCTCAG	GATATATAGAGCAGTGCATAAATAATATTA	TCTATAATATTTTTTTATGAAAATATATAA	GTCACGTGAGAGCGCGGGGTATTTGTCTAG	TTGTTAGGAGCTCAGGTATATTTCACACTA
true	1	1	NA	Scaffold_247	25057767	25055301	Scaffold_247:25057767..25055301	AAATTCCACAAAATT*TACAATTTAAAATTT	TGAATACATATTGTCAAATTCCACAAAATT	TCTTCTGATTTAAAATTAAAAAAAATAAGA	ATCCGCAGCGAAGCGCGGGTACTTTACTAG	TACAATTTAAAATTTGTGTTTAAATCAAGA
false	3825	434	0	Scaffold_247	9417320	9432629	Scaffold_247:9417320..9432629	ATTATAAACCGTTTT*TGAGGGAGGGTGCGT	AAACAAAGATAAGACATTATAAACCGTTTT	TCATATTATATACGTCAAACACAAGTCATC	TTATTTCAGCGGCGCGGGCCAGAAGACTGG	TGAGGGAGGGTGCGTGGCCTATTAGCATCG
false	965	1333	0	Scaffold_247	43882102	43884756	Scaffold_247:43882102..43884756	GTTCGGATCATCACA*TCACTGTATTTAATT	ACAGTTCCTGCGGGAGTTCGGATCATCACA	TCCTCCCCCACTAAAAAGAGTTTCGTCCTC	TGCGCGGCAAAGGGTACTTGTTCTTGCTGG	TCACTGTATTTAATTCCCTATAGTCCACAC

The same issue has come up with TIR as well. Interestingly, I have run the same analysis (same version) previously on the same cluster without this error coming up (but it failed further on - an issue I may ask about later), so it is really unclear to me why this error arises. I tested EDTA with the test folder and it ran fine.

If you could help me out, that would be great!
Thank you,
Clara

**Comment by oushujun** [comment]
Hi Clara,

One common issue is the sequence name - if the test sequence works fine but
not on your genome, you may want to further simplify the sequence names and
try again. For example, remove spaces and symbols that are not underscores
(_). Let me know if you still have issues.

Best,
Shujun

**Comment by oushujun** [comment]
Hi Clara, Did you figure it out eventually? - Shujun

**Comment by cgrootcrego** [comment]
Hi Shujun,

Sorry for not getting back to you. The issue was not the sequence names; these were already very simplified ("Scaffold_1", "Scaffold_2" etc). But it seems I was having memory issues - after clearing my directory EDTA ran to completion. 

Thanks,
Clara
