### ISSUE TITLE
Some errors about ltr_finder

### ISSUE THREAD

**Issue by sunnycqcn** [oushujun/EDTA#145]
Hello Shujun,
I run EDTA old version well. However, I used the latest version. I find the error as following:
`timeout: the monitored command dumped core
sh: line 1: 92935 Segmentation fault      timeout 10 /home/AAFC-AAC/fuf/miniconda3/envs/RTE/bin/ltr_finder -w 2 -C -D 15000 -d 1000 -L 7000 -l 100 -p 20 -M 0.85 scf35_sub8_sub2 > scf35_sub8_sub2.finder.scn
`
`sh: -c: line 0: unexpected EOF while looking for matching `"'
sh: -c: line 1: syntax error: unexpected end of file
`
But I still get LTR prediction.
I did not know what happened.
Thanks,
Fuyou

**Comment by oushujun** [comment]
Hi Fuyou,

Do you have this error all the time or occasionally? Did you test on the
toy genome and also have this issue? I am not sure what causes this. But if
you still get results, this error could be occasional and you were getting
results from other correct child jobs.

Best,
Shujun

**Comment by sunnycqcn** [comment]
Hi Shujun,
It is only this time. Other times is good. And the results look good, but it is not done.
If I have any strange results, I will let you know.
Thanks,
Fuyou

**Comment by sunnycqcn** [comment]
Hello Shujun,
By the way, did you compare the results with  REPET pipeline. Because I find the results is different. EDTA can identify much more TE than REPET. This table is my one plant genome prediction result with EDTA :
`==================================================
file name: STA.fa                   
sequences:         13846
total length:  471563096 bp  (446933036 bp excl N/X-runs)
GC level:         37.39 %
bases masked:  300755134 bp ( 63.78 %)
==================================================
               number of      length   percentage
               elements*    occupied  of sequence
--------------------------------------------------
Retroelements       199428    161954132 bp   34.34 %
   SINEs:                0            0 bp    0.00 %
   Penelope              0            0 bp    0.00 %
   LINEs:             1040       514459 bp    0.11 %
    CRE/SLACS            0            0 bp    0.00 %
     L2/CR1/Rex          0            0 bp    0.00 %
     R1/LOA/Jockey       0            0 bp    0.00 %
     R2/R4/NeSL          0            0 bp    0.00 %
     RTE/Bov-B           0            0 bp    0.00 %
     L1/CIN4             0            0 bp    0.00 %
   LTR elements:    198388    161439673 bp   34.24 %
     BEL/Pao             0            0 bp    0.00 %
     Ty1/Copia       43382     35285115 bp    7.48 %
     Gypsy/DIRS1     64036     78624217 bp   16.67 %
       Retroviral        0            0 bp    0.00 %

DNA transposons     408141    119324536 bp   25.30 %
   hobo-Activator        0            0 bp    0.00 %
   Tc1-IS630-Pogo        0            0 bp    0.00 %
   En-Spm                0            0 bp    0.00 %
   MuDR-IS905            0            0 bp    0.00 %
   PiggyBac              0            0 bp    0.00 %
   Tourist/Harbinger   152        55402 bp    0.01 %
   Other (Mirage,        0            0 bp    0.00 %
    P-element, Transib)

Rolling-circles          0            0 bp    0.00 %

Unclassified:        62584     14315292 bp    3.04 %

Total interspersed repeats:   295593960 bp   62.68 %


Small RNA:               0            0 bp    0.00 %

Satellites:              0            0 bp    0.00 %
Simple repeats:     103445      4263665 bp    0.90 %
Low complexity:      17779       842107 bp    0.18 %
==================================================

* most repeats fragmented by insertions or deletions
  have been counted as one element
                                                      

RepeatMasker version 4.1.1 , sensitive mode
                                      
run with rmblastn version 2.10.0+
The query was compared to classified sequences in "STA.fa.mod.EDTA.TElib.fa"

`
However, if I used REPET pipeline, the results is as following with the same plant genome.
`
![image](https://user-images.githubusercontent.com/24547624/104629433-1fc7c600-565f-11eb-87bf-3c6fbae09919.png)
`
The REPET have more classes than EDTA. 
Thanks,
Fuyou

**Comment by oushujun** [comment]
Hi Fuyou,

Yes, we have test REPET and compared it with an earlier version of EDTA. Please find more details in our paper. Overall, REPET has much higher misclassification rates than EDTA and could not identify Helitrons.

I could not read from your results, can you paste a clearer version?

Thanks,
Shujun
