### ISSUE TITLE
how to use sinebase 

### ISSUE THREAD

**Issue by lisajq** [oushujun/EDTA#148]
Dear shujun,
    I have read your article about EDTA, you mentioned sinebase could be a supplement  to find SINE. may I ask you how you use sinebase in your article? 

cuzz lisa

**Comment by oushujun** [comment]
Use the `--curatedlib` parameter. Make sure the input sequence is high quality.

**Comment by lisajq** [comment]
Hi Shujun,

Thank you for your quick reply, I will try to run it.


cuzz lisa
