### ISSUE TITLE
Illegal division by zero at /EDTA/util/flanking_filter.pl line 213

### ISSUE THREAD

**Issue by lisajq** [oushujun/EDTA#150]
Hi shujun,

Thank you very much for developing such a good software.
I encountered an error when I ran the EDTA_raw.pl.
could you help me with this?

09:04:46 CST    EDTA_raw: Check dependencies, prepare working directories.
09:04:53 CST    Start to find LTR candidates.
09:04:53 CST    Identify LTR retrotransposon candidates from scratch.
09:10:27 CST    Finish finding LTR candidates.
09:10:27 CST    Start to find TIR candidates.
09:10:27 CST    Identify TIR candidates from scratch.

Species: others
Thread 3 terminated abnormally: Illegal division by zero at /home/anaconda2/pkgs/edta-1.9.5-0/share/EDTA/util/flanking_filter.pl line 213.

 14:34:44 CST    Finish finding TIR candidates.
14:34:44 CST    Start to find Helitron candidates.
14:34:44 CST    Identify Helitron candidates from scratch.
17:17:50 CST    Finish finding Helitron candidates.
17:17:50 CST    Execution of EDTA_raw.pl is finished!

cuzz lisa

**Comment by oushujun** [comment]
Hello Lisa,

Thanks for reporting. I just fix this bug in addf414.

As for your analysis, because it occurred in only one candidate, so most likely it won't have a noticeable effect on your results. You may proceed ahead. 

Best,
Shujun

**Comment by lisajq** [comment]
Hi Shujun,

Thank you very much! you're responsible and very nice!


Best,
cuzz lisa
