### ISSUE TITLE
EDTA_raw miss one transposon in a ~20kb genome

### ISSUE THREAD

**Issue by hrwang** [oushujun/EDTA#152]
Hi, I am trying to annotate all the transposons within a 20kb rice DNA sequence, so I detect with the `perl EDTA_raw.pl` program. I can see there are two transpons, probably both are LTR transposons, but the program ended up only detect the first transpson, but not the second. I will show the first 5 columns of the result from the *LTR.intact.gff3 below:

```
rr	EDTA	repeat_region	3636	9786
rr	EDTA	target_site_duplication	3636	3640
rr	EDTA	long_terminal_repeat	3641	4081
rr	EDTA	Gypsy_LTR_retrotransposon	3641	9781
rr	EDTA	long_terminal_repeat	9341	9781
rr	EDTA	target_site_duplication	9782	9786
```

**Comment by hrwang** [comment]
the second TE closely follows the first one, they may overlap.

**Comment by oushujun** [comment]
`EDTA_raw` detects structurally intact TEs. If the second TE is not intact, it will not be detected by this part of the method. Alternatively, it will be annotated by homologous sequences from other intact TEs, but that requires the whole genome. So if you run EDTA on the entire genome, the second TE will get a chance to be annotated. If you only have a few candidates, you may manually annotate them with a bunch of NCBI blast or HMM searches.

**Comment by hrwang** [comment]
> `EDTA_raw` detects structurally intact TEs. If the second TE is not intact, it will not be detected by this part of the method. Alternatively, it will be annotated by homologous sequences from other intact TEs, but that requires the whole genome. So if you run EDTA on the entire genome, the second TE will get a chance to be annotated. If you only have a few candidates, you may manually annotate them with a bunch of NCBI blast or HMM searches.

Thanks!
