### ISSUE TITLE
Error thrown, no gt dependency

### ISSUE THREAD

**Issue by juliayork** [oushujun/EDTA#155]
Hello, I am trying to run EDTA but it fails on dependency checking and throws this error:

Error: gt is not found in the genometools path ./!

I don't see a "genometools" path or gt anywhere. What is this dependency? I installed it using conda the way that was suggested in the README

Thanks.

**Comment by oushujun** [comment]
Hi, please reinstall EDTA. If the error persists, let me know what
command you are using. - Shujun

**Comment by Wanjie-Feng** [comment]
hi, I have the same problem, but what the difference is that I have installed EDTA before successfully.
However, when I use it again, it occurs   "Dependency checking:
Error: gt is not found in the genometools path ./!"
The commands I used are :  ` git clone https://github.com/oushujun/EDTA.git          conda env create -f EDTA.yml  `

**Comment by oushujun** [comment]
Hi, Thanks for the report. The conda env comes with a version of EDTA, can
you try it out? It's accessible from ENV, So no path is needed.

Best,
Shujun
