### ISSUE TITLE
RepeatMasker results not found in *mod.out

### ISSUE THREAD

**Issue by aaronphillips7493** [oushujun/EDTA#156]
Hey,

Can someone please help me understand the error "RepeatMasker results not found in ragtag.scaffolds.fasta.mod.out", in the attached image? It looks like it might have stemmed from the error above it: "mv: cannot stat 'ragtag.scaffolds.fasta.mod.EDTA.intact.fa.rename': No such file or directory"
<img width="1358" alt="Screen Shot 2021-02-07 at 3 11 12 pm" src="https://user-images.githubusercontent.com/52693945/107136894-365bf700-6957-11eb-8709-df0f13397372.png">

I'm not sure what has gone wrong, or what steps can be taken to resolve it. Any help would be greatly appreciated. 

The code I ran was:
`perl EDTA.pl --genome $GENOME \
        --curatedlib ragtag.scaffolds.fasta.mod.EDTA.TElib.fa \
        --cds Oryza_sativa_vg_japonica.coding.fasta\
        --overwrite 1 \
        --sensitive 1 \
        --anno 1 \
        --evaluate 1 \
        --threads ${SLURM_CPUS_PER_TASK}`

Thanks,
Aaron :)

**Comment by oushujun** [comment]
Hi Aaron,

If you want to continue a previous EDTA run, then you may just run it without `--overwrite 1`. In your case, the `final` step is not finished, so you may specify `--step final` to start from this step. It looks like you are annotating a rice genome, you may want to supply the curated rice TE library to boost your annotation. The library is from here: https://github.com/oushujun/EDTA/blob/master/database/rice6.9.5.liban

If necessary, you may also want to update your EDTA to the current version 1.9.6, which is much better than 1.8.x and older.

Best,
Shujun

**Comment by aaronphillips7493** [comment]
Hey Shujun,

Thank you for your advice. I think the problem was that I was using a repeat library from a previous run of EDTA as the input for a new run of EDTA (**I guess I should ask whether it is ok to use the EDTA output 'genome.mod.EDTA.TElib.fa' file as the new curated library for subsequent EDTA runs?** I used the supplied rice TE library 'rice6.9.5.liban' on my first try). I did not change the name of the file after copying it into a new directory for the new EDTA run, so I think EDTA was not happy that there was a file already there that it was trying to create. I am not sure, though I re-ran EDTA after changing the name of this file and it worked. I am now waiting for the evaluation step to finish. 

I will update EDTA soon. 

Thank you again for you advice,
Aaron :)

**Comment by oushujun** [comment]
Hi Aaron,

Sorry for the long delay. To answer your question, it's not a good idea to treat an EDTA library as curated because it is not. If you have a particular purpose, ie, supply a pangenome library to reannotate each genome, that's OK but keep in mind it's not curated.

How did the evaluation go?

Best,
Shujun

**Comment by oushujun** [comment]
close due to lack of activity.
