### ISSUE TITLE
Identify homologous transposons across species

### ISSUE THREAD

**Issue by stefaniehoho** [oushujun/EDTA#157]
Dear Shujun,

Thank you so much for developing this excellent tool. I've successfully run an early version of EDTA pipeline(v1.8.2) for a teleost genome. I want to find close related/homologous TEs from this fish genome and zebrafish genome for further analysis. I'm wondering if I can somewhat track the origins of the EDTA annotated TEs. Any suggestion and advice are welcomed. 

Thanks,
Yixuan

**Comment by oushujun** [comment]
Hi Yixuan,

You may want to use the TE library of your teleost genome to annotate the
zebrafish genome for closely related TEs. You may also want to update your
annotation to the latest EDTA version for a much better presentation of the
result.

Best,
Shujun
