### ISSUE TITLE
extracting 5' LTR and 3' LTR from intact EDTA.TElib.fa output

### ISSUE THREAD

**Issue by sadikmu** [oushujun/EDTA#158]
Hi Shujun, 

Thanks for providing EDTA. I am looking into TE insetion time analysis and wanted to get the 5' LTR and 3'LTR from the final intact *EDTA.TElib.fa output. Is there internal script in EDTA to deal with this ? Could you please advise me on how to go about it? Any suggestion is highly appriciated. 

Thanks,

Sadik

**Comment by oushujun** [comment]
Hi Sadik, please check out the *raw/LTR/*mod.pass.list file. -Shujun

**Comment by sadikmu** [comment]
Hi @oushujun 

Thank you. The table *raw/LTR/*mod.pass.list is in the following format and nice to see the insertion time estimate included. But because  3' end of 5' LTR and 5' end 3' LTR are missing in the table, I am unable to capture full bourders of both LTRs. 


`LTR_loc    Category      Motif       TSD         X5_TSD         X3_TSD          Internal Identity Strand SuperFamily TE_type Insertion_Time`

**Comment by oushujun** [comment]
Hi Sadik, you can use the internal region's coordinate to get the left and
right LTR coordinates. -Shujun

**Comment by sadikmu** [comment]
Hi @oushujun 
Yes, but it leaves you with PBS and PPT included in R and L LTRs, respectively, and it seems to need filtering the PBS and PPT out afterward to get the LTRs. Or are they included as part of the internal sequence so that can be used to get the LTR ends?

**Comment by oushujun** [comment]
The later. It is structured like LTR-INT-LTR. So besides the left and right
LTR regions, the rest of the element is considered the INTernal region
including PBS and PPT, if any. - Shujun

**Comment by sadikmu** [comment]
Hi @oushujun, 

This addresses my issue and the ticket can be closed. Highly appreciate your responsiveness and thanks a lot.
