### ISSUE TITLE
Very long runtime of gt suffixerator

### ISSUE THREAD

**Issue by hkchi** [oushujun/EDTA#160]
Hi Shujun, 

I am running EDTA on a 5.+Gb plant genome (unscaffolded contigs excluded). I ran EDTA_raw.pl for LTR, TIR, and Helitron on 48-core nodes separately. While TIR and Helitron jobs finished quickly (~3 days), LTR identification has been running for >14 days. I checked the jobs and it turned out that process `gt suffixerator` is running single-core for >300h. 
A search through the issues seems to suggest that TIR should be the one that takes the most resources and time. The genome is expected to have a large proportion of LTR-RTs, but I am wondering if the process `gt suffixerator` is supposed to run for so long? 

Thanks, 
Kaichi

**Comment by baozg** [comment]
Hi, Kaichi

What's your version of EDTA? Since the version of 1.9.4, `LTR_HARVEST_parallel` has included in the EDTA pipeline, which adapted from the `LTR_FINDER_parallel`. It split the genome into small chunks and run parallel, every single task are single-core.

**Comment by oushujun** [comment]
Hi Kaichi,

As Zhigui mentioned, you may want to update EDTA to the current version, then rerun `EDTA_raw.pl --type ltr`. The existing results for TIR and Helitron should be fine.

Best,
Shujun

**Comment by hkchi** [comment]
Hi Zhigui and Shujun, 

I reinstalled my EDTA from the v1.9.6 release and deployed a new conda env using EDTA.yml. The LTR job now ran smoothly and finished in 2 days. I am now running the rest of the pipeline with the new LTR output along with results of TIR and Helitron from my previous run. 

Thank you, 
Kaichi

**Comment by GallVp** [comment]
Hi @oushujun 

This is old and you have already solved it but I just experienced it. `gt suffixerator` goes on forever at 0.1% CPU when the input assembly fasta has lots of small contigs (~35, that's actually not that many). I switched to the parallel version and it worked. Great work and thank you!
