### ISSUE TITLE
Sequence length of TE_IDs inconsistent between TEanno.sum file and TElib.fa file

### ISSUE THREAD

**Issue by Ti-Wen** [oushujun/EDTA#161]
Dear Shujun,
Thank you so much for developing this pipeline. EDTA pipeline is beneficial for annotating TEs from newly sequenced organisms.

The pipeline worked fine and successfully output five desired results. However, when I looked into the .sum and TElib.fa files, I observed a problem. The issue is that the sequence length of TE_IDs is inconsistent between .sum and TElib.fa files. For example, for a TE_ID with only one count, the bpmasked in the file is 650 bp, while the sequence length in the TElib.fa file shows only 243bp. Is this because of some parameters settings? I am looking forward to your response. Thank you so much!

Best wishes,
Ti-Wen

**Comment by oushujun** [comment]
Hi Ti-Wen,

Thank you for using EDTA. The annotation process utilizes repeatmasker
which may include gaps in the annotation. Please check the alignment to be
sure.

Best,
Shujun

**Comment by Ti-Wen** [comment]
Dear Shujun,
Thank you for your quick response! I will head on to check the alignment! Thank you so much!

Best wishes,
Ti-Wen

**Comment by oushujun** [comment]
This issue may be also related to #184.

**Comment by Ti-Wen** [comment]
Oh, I see! Thank you very much! I will have a look at #184!

**Comment by Ti-Wen** [comment]
Dear Shujun,
I have tried the updated version of EDTA. Thank you so much for the notification of this new release. Recently, I have started to check the results, and I found that the "seqid" title in .TEanno.gff3 file does not represent the scaffold IDs. But I don't know the meaning of it and the relation between "seqid" , "start", and "end" in .TEanno.gff3 file. Hope that you can help me with this. Thank you.

Best,
Ti-Wen

**Comment by oushujun** [comment]
Hi Ti-Wen,

This is likely due to the sequence ID conversion carried by EDTA because the original IDs are too long or contain special characters. You may see something likein #203.

**Comment by Ti-Wen** [comment]
Dear Shujun,

Thank you for the quick response. I eventually found that this issue was merely caused by my own operation mistake when analyzing the results. And I have fixed it. Sorry for the disturbance.

Best,
Ti-Wen
