### ISSUE TITLE
output for MAKER 

### ISSUE THREAD

**Issue by wyim-pgl** [oushujun/EDTA#162]
Hi Shujun,
I am trying to replace RepeatMasker step in Maker with EDTA. Do you have any instructions for it? I saw the output fasta file from EDTA but no idea to use it on MAKER. Do I need to use your masked fasta or GFF file?

Thanks.

Won

**Comment by oushujun** [comment]
Hi Won,

I am not particularly familiar with RepeatMasker, you may try the lightly
masked file. You may also use the test file to quickly test it on Maker.
Please let me know how you work it out. Thanks!

Best,
Shujun

**Comment by baozg** [comment]
I have tried used the `EDTA.anno.gff` （before version 1.8.0）in maker first round, but cannot figure out the exactly worked format in the maker(MAKER repeat gff only have match and match-part). So here is the way I use EDTA library.
```shell
# maker_opts.ctl
model_org=simple # let maker find simple repeat and softmask genome
rmlib=mygenome.fa.mod.EDTA.TElib.fa # EDTA library
```

I think gff format should be more properly than the lightlt masked fasta, but you need reformat the EDTA.gff the MAKER format. Maybe GMOD of MAKER will have the answer.

**Comment by wyim-pgl** [comment]
@baozg 
Hi Zhigui! Thanks for your suggestion. In that case, we need to rerun RepeatMasker within MAKER. 
I will find a way to use GFF directly.
@oushujun 
Thanks, I will update here whenever I found a way to handle it.
