### ISSUE TITLE
How to  get the TE annotation of MSU7.0?

### ISSUE THREAD

**Issue by zhangaicen** [oushujun/EDTA#163]
Dear Shujun, 
   Sorry to disturb you, recently I tried to do some analyses about rice TEs, but from the  RGAP program I cannot find the TE annotation file, as I saw in your release, you mentioned the TE version v6.9.5, so could you please tell me how to get the released TE   annotation file of MSU 7.0? or the anotation file from your work? 

   Thanks. Zhang.

**Comment by oushujun** [comment]
Hi Zhang,

These are different version numbers. The TE library is in the EDTA package
in /database. You may get the MSU7 TE annotation from the MSU rice website:
rice.plantbiology.msu.edu

Hope this helps,
Shujun

**Comment by zhangaicen** [comment]
OK ,   thanks a lot
