### ISSUE TITLE
No SINE and LINE in the results

### ISSUE THREAD

**Issue by biozhangzhou** [oushujun/EDTA#164]
Hello Dr.Ou:
 I'm confusing with the EDTA result which have no LINE and SINE. What's that mean ? Or what should i do to next ?
This is a bird genome.  
<img width="886" alt="Screen Shot 2021-02-23 at 10 13 05 AM" src="https://user-images.githubusercontent.com/42492970/108793942-b91fbb80-75bf-11eb-8a87-b9322f43de5c.png">

**Comment by oushujun** [comment]
Hi, you may want to update EDTA and rerun the pipeline with --sensitive 1.
If you have curated sine line sequences, you may supply them to EDTA with
--curatedlib.

Best,
Shujun

**Comment by biozhangzhou** [comment]
Thank you for you reply. I'm using the (EDTA) v1.8.5 which already have the --sensetive option. I still not clear with you reply. -sensetive means "Use RepeatModeler to identify remaining TEs", Is it  essential to get sine and line ??

**Comment by oushujun** [comment]
Hi, EDTA v1. 9+ is much better. For SINE LINE elements they are identified
by RM2.

Shujun

**Comment by biozhangzhou** [comment]
One more question. Can I only use EDTA for Birds Repeats annotation ? 
Thanks a lot.

**Comment by oushujun** [comment]
You may, but it also depends on what questions you have interested to
answer with the genome.

Best,
Shujun

**Comment by biozhangzhou** [comment]
e, hello, I'm here again.

I think I find why EDTA cann't get SINE and LINE resutls, it will default use the viridiplantae database (see below), but I'm working on Bird genome. However,  I cann't find the option to rejust this behavior. So I need your help again.

"
2021-02-28 19:29:37,906 -WARNING- Grid computing is not available because DRMAA not configured properly: Could not find drmaa library.  Please 
2021-02-28 19:29:37,915 -INFO- VARS: {'sequence': 'SX04_FINAL_PLUS_Unplaced_Gapcloser_Polished.fa.mod.RM.consensi.fa', 'hmm_database': 'rexdb',
2021-02-28 19:29:37,915 -INFO- checking dependencies:
2021-02-28 19:29:37,941 -INFO- hmmer    3.3.2   OK
2021-02-28 19:29:38,011 -INFO- blastn   2.10.0+ OK
2021-02-28 19:29:38,012 -INFO- check database rexdb
2021-02-28 19:29:38,012 -INFO- db path: /home/zhangzhou209/1.bin/miniconda3/envs/EDTA/lib/python3.6/site-packages/TEsorter/database
2021-02-28 19:29:38,012 -INFO- db file: REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm
2021-02-28 19:29:38,013 -INFO- REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm    OK
2021-02-28 19:29:38,013 -INFO- Start classifying pipeline
"

**Comment by oushujun** [comment]
Hi,

EDTA could not identify SINE LINE elements based on structural features.
Like I said before, it relies on the homology based RepeatModeler2 for this
purpose. So If you don't get SINE LINE elements when using the --sensitive
1 parameter, you need to id them with other tools separately.

Best,
Shujun

**Comment by biozhangzhou** [comment]
After different try I realized that. And I think EDTA cann't merge results from RepeatMasker well either(see below,a log file with --rmout offered)
"
Warning: rRNA not found in the TE_SO database, will use the general term 'repeat_region SO:0000657' to replace it.
Warning: rRNA not found in the TE_SO database, will use the general term 'repeat_region SO:0000657' to replace it.
Warning: rRNA not found in the TE_SO database, will use the general term 'repeat_region SO:0000657' to replace it.
"
Also, The statistic in the final *sum file are  incredible.

**Comment by oushujun** [comment]
As suggested by the message, the term "rRNA" is not included in the TE_SO database (`EDTA/util/TE_Sequence_Ontology.txt`).

I just check the SO database, rRNA is available as a SO term: http://www.sequenceontology.org/browser/current_release/term/SO:0000252

If you want it annotated correctly, you may add this line: `rRNA    SO:0000252      rRNA` into the TE_SO file above and rerun the anno step.

**Comment by biozhangzhou** [comment]
Ok, Thanks! 
But I'm trying mannually merge them now.

**Comment by oushujun** [comment]
If you supply `--rmout file` in `--step anno --anno 1` of EDTA, the remaining execution is very quick (< 1h).

**Comment by biozhangzhou** [comment]
Hello, I'm here again.

I have read the EDTA.pl script and some other relate scripts except for those TElib learning and constructing part.
It does helps to change TE_Sequence_Ontology.txt when I use the --rmout option; but I still have no enough confidence on the accracy of the summary statitics based on my personal TE classification. So I choose the other way which combine the EDTA high quality TElib and repeatmasker lib and then use repeatmasker to do the whole-genome annotation. The results seems alright. But I also mentioned that EDTA.pl have some more processis on annotation especially for the Differently homology-based and strutrual-based annotation. It's essential ? And why don't you just use the TElib and don't care about intact.bed and RM.bed.

**Comment by oushujun** [comment]
Hi, it's alright even with a simple RepeatMasker annotation but that's not
the mere purpose of EDTA. The structural information and filtering steps
aim for higher quality and more indepth information for TE annotation,
which can provide more opportunities for data integration. You may read the
EDTA paper for more information.

Best,
Shujun
