### ISSUE TITLE
Is there any pipelines for genotyping TEs using population illumina reads?

### ISSUE THREAD

**Issue by caixu0518** [oushujun/EDTA#172]
Hi Shujun,

I'm very satistified with the results of EDTA. It is an excellent tool.  I have annotated TEs in my reference genome using EDTA, and next, I want to genotype these annotated TEs in my large population using short reads. I have tried some pipelines, which are based on split-read and pair-end reads stratigies.  However,these pipelines are not performing well. This confuses me. Do you know of some efficient pipelines for genotyping TEs using population short reads?

Many thanks.

Best,
Xu

**Comment by caixu0518** [comment]
Thank you so much for your help, I will try the software right now.

Best，
Xu

**Comment by shuren7** [comment]
> Thank you so much for your help, I will try the software right now.
> 
> Best， Xu

Hello @caixu0518 , could you please tell me how this software performs and is it reliable?
