### ISSUE TITLE
DNA transposons in Saccharomyces cerevisiae

### ISSUE THREAD

**Issue by Dichopsis** [oushujun/EDTA#173]
Hi @oushujun ,
I tried the EDTA pipeline on the yeast genome (Saccharomyces cerevisiae). I get TIRs and Helitrons that represent about 1% of the genome.

First, when I run RepeatMasker on the library built from EDTA, these transposable elements are all listed as DNA transposons and are not classified into subfamilies.

Secondly, in the literature it is stated that the yeast genome contains 0% DNA transposons, whereas I get 1% (number of DNA transposons: 301), but when I run RepeatModeler alone, I get 0% DNA transposons.

I was wondering how to explain these results.

Many thanks

**Comment by oushujun** [comment]
Hello, if you run EDTA with --anno 1 --step anno, you will get a summary
file with proper superfamily info.

The low amount of TIR annotations could be false positives or previously
unreported TIRs - you need to further verify them to be sure. A good start
will be using TEsorter to identify conserved coding domains.

Best,
Shujun
