### ISSUE TITLE
How to detect only LTR by EDTA

### ISSUE THREAD

**Issue by 1Wencai** [oushujun/EDTA#176]
Hi shujun，
 I only want to detect LTR in my project by EDTA. I found that structural TIR indentied by EDTA will influence homology LTR when them have overlapped coordinate,  homology LTR will disappear.
So how i detect only LTR by EDTA, I do not care about TIR or helitron.

beat wishes!
wencai

**Comment by oushujun** [comment]
You should use LTR_retriever. -Shujun

**Comment by 1Wencai** [comment]
Thank you very much for solving my problem right away，i will try LTR_retriever later.

best wishes！
wencai
