### ISSUE TITLE
Specifying RepeatMasker query species

### ISSUE THREAD

**Issue by Neato-Nick** [oushujun/EDTA#18]
Hi,

I'm annotating a genome pretty distant from homo sapiens. Checking the RM_ output folder, it looks like the call to RepeatMasker just queries this as the default species ("`The query species was assumed to be homo`" in the RM_*/*.fasta.tbl output in the *.fasta.EDTA.final/ folder). Is there any way to change this in my call to EDTA so I can most effectively use a homology-based TE calling method? Alternatively, I could just run RepeatMasker myself at the end using *.fasta.EDTA.TElib.fa as a custom library

**Comment by oushujun** [comment]
Hi @Neato-Nick,

I have not implemented whole-genome annotation in EDTA yet, which is simply a line using RepeatMasker:
`RepeatMasker -pa 36 -no_is -norna -nolow -div 40 -lib your_genome.fasta.EDTA.TElib.fa -cutoff 225 your_genome.fasta`

In this way RepeatMasker will use the EDTA-generated library to make a homology-based annotation. Please ignore the imprecise wordings in *.tbl, which does not affect the annotation outcome. For a better summary table, please visit [the issue 8](https://github.com/oushujun/EDTA/issues/8) for some helpful info.

Best,
Shujun

**Comment by Neato-Nick** [comment]
Great, thank you!

**Comment by Neato-Nick** [comment]
I think I closed this a bit too early, I do have a question that isn't discussed in https://github.com/oushujun/EDTA/issues/8. If we plan on including homology-based TEs from RepBase or Dfam as well as the structure-based TEs from EDTA, do you suggest including the RepBase/Dfam libraries in the -curatedlib option of the EDTA run? Or should we run EDTA and then concatenate with RepBase/Dfam results?
