### ISSUE TITLE
terminates with a cds file provided

### ISSUE THREAD

**Issue by sarjopp** [oushujun/EDTA#180]
Everything seems fine but then my EDTA run ends. In the log, I see "file not found" errors where it looks like the expected output from earlier stages is not present. I'm having a hard time figuring out where the initial problem is. Can you help?
[LTRcompareEDTAusda.log](https://github.com/oushujun/EDTA/files/6282880/LTRcompareEDTAusda.log)

**Comment by sarjopp** [comment]
I'm trying using a re-named version of my CDS input, which had very long names. It looks like EDTA at least has gotten past where it terminated before. I will update when something happens!

**Comment by oushujun** [comment]
Glad you figured it out. Can you inform me what version of EDTA you are
using? I had cds sequence names converted in the later versions and image
long/weird names should not be an issue, otherwise there is a bug in the
conversation code and if this is the case I need your cds file to further
debug.

Best,

Shujun

**Comment by sarjopp** [comment]
I'm using v1.9.6. Manually changing the cds seqIDs did allow my EDTA run to complete. I'm attaching my un-renamed cds file.
[GCF_014083535.2_V.mandarinia_Nanaimo_p1.0_cds_from_genomic.fna.gz](https://github.com/oushujun/EDTA/files/6287015/GCF_014083535.2_V.mandarinia_Nanaimo_p1.0_cds_from_genomic.fna.gz)

**Comment by oushujun** [comment]
Hi, thanks for sharing the cds file. I checked the name conversion code and it worked fine. Did you accidentally provide a gzipped file to the program? I don't think it can handle zipped files. - Shujun

**Comment by sarjopp** [comment]
Hi Shujun, yes, my cds file was gzipped! I didn't realize it needed to be
an uncompressed file. It sounds like that was the issue--thank you for
investigating!

I do have another question: if I want to modify the option settings for any
of the tools the edta.pl script calls, what is the best way to do so? I
edited the script directly but wondered if there was a more elegant way to
feed in options.

Thanks!
Sara

**Comment by oushujun** [comment]
@sarjopp If you want to use utility scripts from the EDTA package, most of them have parameter setting options. You may want to check them out with `-help|-h|--help`, or simply open up the script and see how it works. If you want to modify options for the `EDTA.pl` script, you can do so similarly. Most of the options from utility scripts can be set through the `EDTA.pl` script. For those who don't, you may modify the `EDTA.pl` script directly.
