### ISSUE TITLE
Illegal division by zero - cleanup.pl

### ISSUE THREAD

**Issue by goeckeritz** [oushujun/EDTA#182]
Hi Shujun, it's me again....

Recently we made some scaffolding changes to our genome, so I'm trying to rerun EDTA produce the very nice, custom repeat library. But for some reason... the thing won't run on the rearranged genome. I thought maybe a reinstall would fix the problem, but it's doing something a little odd. It should be working since I got the test run to work (aside from it not being able to find the DRMAA library). I included a txt file with the stdout of the test run if you want to look. Nothing special is in the stderr - just that dependencies passed and eventually messages saying the programs finished and to check the .sum files. 

I did the conda installation with the yml file. I also updated conda with 'conda update conda' prior to installing it. I had to add pydot to the installation to parse dotplots, but that should be the only thing I added to this install. I'm also 'module purge'ing every time I reroute to a new shell -- I've learned my lesson! 

So -- my own data! What changed from before? Nothing really, just some rearrangements. But something I found odd for this attempt at getting EDTA to run is the message I get in the error file at the very beginning. Here's the gist of the stderr log file:

>########################################################

>##### Extensive de-novo TE Annotator (EDTA) v1.9.7  ####
>##### Shujun Ou (shujun.ou.1@gmail.com)             ####
>########################################################

>Fri Apr  9 10:36:55 EDT 2021    Dependency checking:
                                All passed!

>Fri Apr  9 10:37:22 EDT 2021    **The longest sequence ID in the genome contains 22 ch
>aracters, which is longer than the limit (15)**
                                >Trying to reformat seq IDs...
                                >Attempt 1...
>Fri Apr  9 10:37:31 EDT 2021    Seq ID conversion **successful**!
>Fri Apr  9 10:37:31 EDT 2021    Obtain raw TE libraries using various structure-base
>d programs:
>Fri Apr  9 10:37:31 EDT 2021    EDTA_raw: Check dependencies, prepare working directories.

>Fri Apr  9 10:37:41 EDT 2021    Start to find LTR candidates.

>Fri Apr  9 10:37:41 EDT 2021    Identify LTR retrotransposon candidates from scratch.

>substr outside of string at /mnt/home/goeckeri/miniconda3/envs/EDTA/share/LTR_retriever/bin/call_seq_by_list.pl line 128.
>Use of uninitialized value $seq in string eq at >/mnt/home/goeckeri/miniconda3/envs/EDTA/share/LTR_retriever/bin/call_seq_by_list.pl line 129.
>.
>.
>. (repeats this substr warning many times..)
>.
>.
>Illegal division by zero at /mnt/home/goeckeri/miniconda3/envs/EDTA/share/LTR_retriever/bin/cleanup.pl line 79, <File> >chunk 23385.
>awk: fatal: cannot open file `Pcerasus_fixed8.fasta.mod.pass.list' for reading (No such file or directory)
>Warning: LOC list - is empty.

>        perl rename_LTR_skim.pl target_sequence.fa LTR_retriever.defalse

>Error: Error while loading sequence
 >       perl filter_gff3.pl file.gff3 file.list > new.gff3

>cp: cannot stat 'Pcerasus_fixed8.fasta.mod.LTRlib.fa': No such file or directory
>cp: cannot stat 'Pcerasus_fixed8.fasta.mod.LTRlib.fa': No such file or directory
>Error: LTR results not found!

>ERROR: Raw LTR results not found in Pcerasus_fixed8.fasta.mod.EDTA.raw/Pcerasus_fixed8.fasta.mod.LTR.raw.fa
        >If you believe the program is working properly, this may be caused by the lack of intact LTRs in your genome. Consider >to use the --force 1 parameter to overwrite this check
        
I bolded the warning at the beginning about the seq ids because it struck me as odd. Don't remember that being a problem before, and I used essentially the same naming system. My seq ids should only be up to 14 characters. Their general format is like so:

>Pcerasus_chr1B
>Pcerasus_alt8
>unanchored####

There should be absolutely no seq ids even close to 22 characters. Unless, somehow, some weird invisible line endings crept their way into the files. EDTA says it is able to convert the seq ids, but it still struck me as extremely odd. Ultimately it looks like the program dies because of that illegal division in the cleanup.pl script... but could the mysterious info involving the seq ids be a clue?

Any advice is MUCH appreciated... hope you are doing well!

Kindly, 
Charity 

[EDTA_reinstall_test_case_stout.txt](https://github.com/oushujun/EDTA/files/6290919/EDTA_reinstall_test_case_stout.txt)

**Comment by oushujun** [comment]
Hi Charity,

Howdy! Thank you for providing all the details for what you have done and what you are thinking. In my opinion the sequence name is an issue. You may want to double check the names and see if there are any accidental '>' placed incorrectly. If you don't have a super long list of scaffolds, you may simple do:
`grep '>' genome.fa | less`

or more specifically to find the long name:

`perl -nle 'next unless />/; my $len = length $_; print $_ if $len > 14' genome.fa | less`

Please let me know how it goes.

Best,
Shujun

**Comment by goeckeritz** [comment]
SHUJUN YOU BEAUTIFUL GENIUS!!

That perl print code saved my life. The way that I renamed scaffolds required me to cat the scaffolded and unscaffolded stuff afterward, and for some reason where the files joined, cat didn't make a new line, it apppended unanchored1 onto the end of the previous scaffold - so it looked like this:
CCGATAACGG>unanchored1 

Easy fix! I'm rerunning EDTA now and it doesn't throw the seq length error. I think it will be okay now! But I'll keep you posted. :)

Kindly, 
Charity

**Comment by oushujun** [comment]
Haha, I guessed this was the case. I am just getting better at guessing all possible scenarios going wrong ;) - Shujun
