### ISSUE TITLE
failed buildSummary.pl

### ISSUE THREAD

**Issue by qisun2** [oushujun/EDTA#185]
The last step buildSummary.pl failed with error message:
missing type for TE_00000515 ... <>

In the file "mygenome.fasta.mod.EDTA.TEanno.out", the last column is missing for this element: TE_00000515:
10000 0.001 0.001 0.001 Scaffold_35 20140507 20141388 NA + TE_00000515

This is the only TE element with missing type 

Qi

**Comment by oushujun** [comment]
`buildSummary.pl` is expecting 10 columns and the last column (`type`) is missing in your example. You may want to check why it's missing. - Shujun

**Comment by qisun2** [comment]
I traced back to the TE element that caused the problem in the gff3 file. All other TE elements have Classifications like "Classifications=DNA/DTA", "DNA/DTC", "MITE/DTA" .  This problematic TE has "Classification=Penelope", only one field.

**Comment by qisun2** [comment]
In this file util/TE_Sequence_Ontology.txt,  you have "Penelope_retrotransposon", while other LTR categories have three fields like "L1_LINE_retrotransposon". Could this cause the problem?

**Comment by qisun2** [comment]
I think I found the problem. It is in the script gff2bed.pl,  you did not handle $class "Penelope". The $type is undefined for "Penelope".

**Comment by oushujun** [comment]
Good catch! I modified the gff2bed.pl file based on your finding. Please replace the script in your program and try again. 
[gff2bed.pl.zip](https://github.com/oushujun/EDTA/files/6347858/gff2bed.pl.zip)
