### ISSUE TITLE
About TIR annotation

### ISSUE THREAD

**Issue by MrbrilliantLL** [oushujun/EDTA#186]
Hi Shujun,

I have annotated the B73 maize genome with EDTA v1.8.5 and get the following results:
<img width="583" alt="截屏2021-04-19 下午11 55 15" src="https://user-images.githubusercontent.com/56568825/115266369-bc23cc00-a16a-11eb-9475-d08b7d0453b1.png">

However, there is a big gap between this result and the result shown in the TIR-learner article (TIR-Learner, a New Ensemble Method for TIR Transposable Element Annotation, Provides Evidence for Abundant New Transposable Elements in the Maize Genome). I want to know where the problem caused these differences.
<img width="960" alt="截屏2021-04-19 下午11 42 52" src="https://user-images.githubusercontent.com/56568825/115265335-b4aff300-a169-11eb-8d1c-a44dbdb90759.png">

Thank you for your help!

Lei

**Comment by oushujun** [comment]
Hi Lei,

The original paper is TIR-Learner beta v1 or v0, which is a prototype to
prove the machine learning approach. The program has been involved to v2.5
during the development of EDTA. We trained another and hopefully better
model for different species in this version. please use the current version
if possible.

Best,
Shujun

**Comment by MrbrilliantLL** [comment]
Dear Shujun,
Thank you for your quick response!
Now, I have two questions about the final output files.

 I am working on a genome where some TIR elements are active. I know that “ *.fa.mod.EDTA.TEanno.gff ” contains the annotation of the fragments of the intact transposons. However, the newly inserted transposons should be intact in the genome.  How can I find the intact TIR elements that recur? 

From the " *.fa.mod.EDTA.intact.gff ", I have observed that most DNA/MITE TEs have 10bps TIR. Is the length of these TIRs determined? Or only the 10bp TIR is shown in the file. If so, how can I annotate the complete TIR for these DNA/MITE TEs. 

Best wishes,
Lei

**Comment by oushujun** [comment]
Hi Lei,

`*.fa.mod.EDTA.TEanno.gff3` contains both intact and fragmented TEs. Look for the tag `method=structural|homology` in the last column of the file. "structural" means intact. Other tags contain TIR, TSD, and identity info which are the complete features founded by TIR-Learner but not necessarily 100% accurate.

Best,
Shujun
