### ISSUE TITLE
Use of uninitialized value within @ARGV

### ISSUE THREAD

**Issue by sitaramrajaraman** [oushujun/EDTA#19]
Dear Shujun
I managed to generate the raw files for LTR, TIR, MITE (Copy of TIR) and Helitrons. I am getting the following error while running EDTA_processF.pl.

/usr/local_sbs/source_files/EDTA/EDTA_processF.pl -genome HaploidAssemblyPilonPolishedCleaned.fasta -ltr HaploidAssemblyPilonPolishedCleaned.fasta.EDTA.raw/HaploidAssemblyPilonPolishedCleaned.fasta.LTR.raw.fa -tir HaploidAssemblyPilonPolishedCleaned.fasta.EDTA.raw/HaploidAssemblyPilonPolishedCleaned.fasta.TIR.raw.fa -helitron HaploidAssemblyPilonPolishedCleaned.fasta.EDTA.raw/HaploidAssemblyPilonPolishedCleaned.fasta.Helitron.raw.fa -mite HaploidAssemblyPilonPolishedCleaned.fasta.EDTA.raw/HaploidAssemblyPilonPolishedCleaned.fasta.MITE.raw.fa

Use of uninitialized value within @ARGV in pattern match (m//) at /usr/local/local_sbs/source_files/EDTA/util/cleanup_nested.pl line 41.
Use of uninitialized value $blastplus in string eq at /usr/local/local_sbs/source_files/EDTA/util/cleanup_nested.pl line 49.

Could you help me with this?

The picture shows the final files that were generated. 

<img width="999" alt="Screenshot 2019-09-18 at 5 09 03 PM" src="https://user-images.githubusercontent.com/10266964/65134549-0ac12f80-da37-11e9-897e-487d52d8923b.png">

**Comment by sitaramrajaraman** [comment]
Ok strangely it is continuing to run so far... Some blastn runs are happening. I will keep you posted upon success or failure.

**Comment by oushujun** [comment]
Hello @sitaramrajaraman 

Thanks for reporting this bug. I have fixed it and will show up in the next update. Overall this does not affect your run but just a small glitch of finding a path to the blastn program. It should be fine if the program finds it in the shell $ENV.

An easier way to do this is run the `EDTA.pl` script without using the `-overwrite 1` parameter. It will automatically pick up the raw results and continue to finish the entire run. I should update the readme too.

Best,
Shujun

**Comment by sitaramrajaraman** [comment]
Thanks for that Shujun. At the moment the run is complete without any further errors. I will go ahead with the final segment and see how it goes with mine. I will be doing more repeat library generation for other species. I will try continuing from the raw files using EDTA.pl as you suggest.

**Comment by oushujun** [comment]
@sitaramrajaraman Thanks again for using EDTA! The issue seems to be resolved. I will close this issue for the moment. Please reopen it if you think it's necessary, or open other new issues.

Best,
Shujun
