### ISSUE TITLE
Has .sum changed? No "simple repeats" listed.

### ISSUE THREAD

**Issue by sarjopp** [oushujun/EDTA#190]
My .sum output looks different than I expected. A snippet is pasted below. I was expecting a second table that summarized Low_complexity, Satellite, Simple_repeat, etc. My initial command: 
perl /nas4/CG2/soppenheim/miniconda3/envs/EDTA/bin/EDTA.pl --genome /nas5/soppenheim/Rosenfeld/Vmandarinia/Vespidae/Vmandarinia_Japan_OriginalAssem/renamed_newONT2021_VmanJapanAssembly.fasta --species others --step all --cds /nas5/soppenheim/Rosenfeld/Vmandarinia/Vespidae/Vmandarinia_Japan_OriginalAssem/newONT0nly2021/Repeats/USDAVman_CDS_shortIDs.fna --species others --step all --sensitive 1 --anno 1 --evaluate 1 --threads 60

Repeat Classes
==============
Total Sequences: 268
Total Length: 247731252 bp
Class                  Count        bpMasked    %masked
=====                  =====        ========     =======
LTR                    --           --           --
    Gypsy              484          580261       0.23%
    unknown            40           44395        0.02%
TIR                    --           --           --
    CACTA              594          146430       0.06%
    Mutator            53432        24145744     9.75%
    PIF_Harbinger      5            7626         0.00%
    Tc1_Mariner        387          251034       0.10%
    hAT                2            5022         0.00%
nonLTR                 --           --           --
    LINE_element       197          68643        0.03%
nonTIR                 --           --           --
    helitron           272          234748       0.09%
repeat_region          59190        11526442     4.65%
                      ---------------------------------
    total interspersed 114603       37010345     14.94%

---------------------------------------------------------
Total                  114603       37010345     14.94%

Repeat Stats
============
Total Sequences: 268
Total Length: 247731252 bp
      ID               Count      bpMasked      %masked
================       =====      ========       =======
      TE_00000000      12339        1629499      0.66%
      TE_00000001      910          93538        0.04%

Thank you!
Sara

**Comment by sarjopp** [comment]
By the way, I'm using v1.9.6, installed with conda.

**Comment by oushujun** [comment]
It appears that the simple repeat satellite etc were labeled as unknown
repeats and counted in the repeat_region category. If you have particular
repeats wanted to be included in the result, you should provide them via
--curatedlib.

Shujun

**Comment by sarjopp** [comment]
OK, thanks Shujun!
