### ISSUE TITLE
Benchmarking EDTA results with a curated TE library

### ISSUE THREAD

**Issue by elissaralam** [oushujun/EDTA#191]
Hello,

I generated an EDTA TE library for my genome and wanted to compare its performance to a curated library, so i masked the genome with the curated library and with the EDTA library using RepeatMasker and then tested the annotation performance using "lib-test.pl". However, i am not sure how to interpret the report that EDTA outputs. I would really appreciate your help in understanding how the metrics help me in deciding which TE library is better to use for downstream analyses.

Here is the content of the report:
Genome:                 fvc1158.asm.hap.p_ctg.fa.rand431332
Standard annotation:    fvc1158.asm.hap.std.p_ctg.fa.out.rand431332
Testing annotation:     fvc1158.asm.hap.test.p_ctg.fa.out.rand431332

sens=TP/(TP+FN)
spec=TN/(FP+TN)
accu=(TP+TN)/(TP+TN+FP+FN)
prec=TP/(TP+FP)
FDR=1-prec=FP/(TP+FP)
F1=2TP/(2TP+FP+FN)

TP: 338847057
FN: 100903451
TN: 451653393
FP: 11938674
Sensitivity: 0.77054386711476
Specificity: 0.974247458380257
Accuracy: 0.875083796421308
Precision: 0.965965907547135
FDR: 0.0340340924528655
F1 measure: 0.857258757495113

#Metrics        sens    spec    accu    prec    FDR     F1      TP      TN      FP      FN
fvc1158.asm.hap.test.p_ctg.fa.out.rand431332.total.lib.report   0.77054386711476        0.974247458380257       0.875083796421308       0.965965907547135       0.0340340924528655      0.857258757495113       338847057       451653393
       11938674        100903451

Thank you so much for your help,
Elissar

**Comment by oushujun** [comment]
Hi Elissar,

You probably need Wikipedia to understand the report. Try to search each
term for better understanding of what it means in your case. You may also
find our benchmark paper helpful in interpreting these quality metrics.

EDTA also can take the curated library as input and generate an augmented
library. Please let me know if you have any other questions.

Best,
Shujun

**Comment by oushujun** [comment]
For your results, very nice specificity (97.4%) and accuracy (96.6%), very low FDR (3%), but the sensitivity (77%) is a bit low. You may provide this library to EDTA and boost its sensitivity. It will be a very nice combination.

Shujun
