### ISSUE TITLE
How to get all LTR elements instead of non-redundant ones

### ISSUE THREAD

**Issue by uceleste** [oushujun/EDTA#195]
Dear Developers,

Thanks for this really useful program!

I have a question about the library of LTR elements generated by EDTA. It is not entirely clear to me what it means that the identified LTR elements are "non-redundant". I'm asking this because I need to get every single LTR element in my genome (as far as possible of course), even if there are identical copies. It seems to me that the final library is composed of exemplars, therefore a representative set but not the total number of LTR elements.
If this is the case, is there a way to obtain all the LTR elements? I saw a ".LTRlib.redundant.fa" file in the output folder. Is this file what I'm looking for?

Thanks for any clarification.
Kind Regards,

Gabriele

**Comment by oushujun** [comment]
Hi, you need to use the --anno 1 function to annotate whole genome TEs. To
use the current results without spending extra time for rerunning the
entire process, you can use "--step anno" to start from the annotation
step. You will get a TEanno.gff3 file for your use.

Shujun

**Comment by uceleste** [comment]
Thanks for the quick and accurate reply! I can close this post.
Kind Regards,

Gabriele
