### ISSUE TITLE
Is HelitronScanner configured to run with multiple threads?

### ISSUE THREAD

**Issue by andreaswallberg** [oushujun/EDTA#197]
Dear @oushujun & Co,

Thanks for a great tool. I am looking to run it on a large genome and have tested it on a small chunk.

Most crucial steps seem to run fine but I can not see that HelitronScanner is actually set to run with multiple threads in my console or in run_helitron_scanner.sh . As far as I understand, this should be set with the "­‐tl $CPU" parameter and variable for HelitronScanner.jar run_helitron_scanner.sh.

Is it possible for a user to edit the Singularity image once downloaded or could you consider updating run_helitron_scanner.sh for multi-threaded execution?

Cheers!

**Comment by oushujun** [comment]
Dear Andreas,

I didn't know it could be parallelized that way. Let me try. Thanks for the
heads up!

As for the singularity version, it's compiled locally then shared to the
hub. You can use the docker file to recompile and get the latest version.

Best,
Shujun

**Comment by andreaswallberg** [comment]
Hi again!

I tried parallelizing HelitronScanner myself using `-lt` and I did not see it actually use or benefit from that at all. Perhaps the parallelized algorithm only applies to a small part of the total CPU-time of HelitronScanner?

Instead, I restructured the jobs launched inside `run_helitron_scanner.sh`, so that that several launch in parallel. The change to `run_helitron_scanner.sh` is only about structure and allowing it to run several HelitronScanner.jar jobs at the same time.

In pseudo-code:

**Current solution:**

```
run direct orientation scanHead
run direct orientation scanTail
run direct orientation pairends
run direct orientation draw

run reverse complement scanHead
run reverse complement scanTail
run reverse complement pairends
run reverse complement draw

run format output
```

**Suggested solution:**

```
# Start for jobs in parallel

run direct orientation scanHead &
run direct orientation scanTail &
run reverse complement scanHead &
run reverse complement scanTail &

wait

# Start two jobs in parallel

(
    run direct orientation pairends
    run direct orientation draw
) &

(
    run reverse complement pairends
    run reverse complement draw
) &

wait

run format output
```

This works great for small genome sequences / chunks runs run as separate EDTA instances. In my test it cut nearly 20% of the overall EDTA clock time. It might cause issues for huge genomes if several concurrent `HelitronScanner.jar` jobs use too much memory. For the latter kind of data, `HelitronScanner.jar` might need to be run sequentially rather than in parallel, or the `buffer_size` might need to be limited to 1M as per the manual for HelitronScanner.jar.

**Comment by oushujun** [comment]
@andreaswallberg 
I tried the `-tl $CPU` parameter, java didn't recognize it. 
>java -Xmx300g -tl 36 -jar ../bin/HelitronScanner/HelitronScanner.jar scanHead -lcv_filepath ../bin/HelitronScanner/TrainingSet/head.lcvs -g genome.fa -buffer_size 0 -output genome.fa.HelitronScanner.head
Unrecognized option: -tl
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

If I add this parameter at the end of the command, `HelitronScanner` kind of ignored it because there is no speedup.

Can you specify how you use this parameter? Or maybe my version of `HelitronScanner` is outdated?

Shujun

**Comment by andreaswallberg** [comment]
`-­‐tl $CPU` ( or the long option `-­‐threads_LCV $CPU`) is for HelitronScanner.jar, not for java, so it should be:

`java -Xmx300g -jar ../bin/HelitronScanner/HelitronScanner.jar scanHead -tl 36 -lcv_filepath ../bin/HelitronScanner/TrainingSet/head.lcvs -g genome.fa -buffer_size 0 -output genome.fa.HelitronScanner.head`

**Comment by andreaswallberg** [comment]
I did not see any speedup either in my test, but the jobs in parallel as I suggested above will speed up the HelitronScanner step regardless, if the user has enough memory to run them side by side.

**Comment by oushujun** [comment]
As suggested in your previous comment, running concurrent jobs of HelitronScanner for large genomes may cause issues due to memory consumptions. I will leave it as it is and other users may manually modify their code to speed up. Thanks for your suggestions!

**Comment by andreaswallberg** [comment]
Good point!

Also, if someone is reading this and is keen on adjusting the workflows for their one analyses according to these lines, it is very easy to do working with docker/singularity file.

Check out the `singularity build` command to extract and rebuild the image using singularity. Some examples are here:
https://stackoverflow.com/questions/52785108/singularity-extract-edit-and-rebuild-image
