### ISSUE TITLE
Manually curated transposable elements in Arabidopsis thaliana?

### ISSUE THREAD

**Issue by MehmetGoktay** [oushujun/EDTA#198]
Hi,

Thank you  very much for such a nice tool!

I would like to annotate and mask de-novo assembled Arabidopsis thaliana genome. I wanted to also use manually curated A. thaliana TEs to run EDTA but I could not find it.  I found these TEs but there is no information about whether they are manually curated (https://www.arabidopsis.org/download/index-auto.jsp?dir=%2Fdownload_files%2FGenes%2FTAIR10_genome_release%2FTAIR10_transposable_elements)

I guess, there might be some people are also working on A. thalina. 

If anyone already knows where can I find manually curated A. thaliana TEs, would be highly appreciated!

Best,
Mehmet

**Comment by oushujun** [comment]
Hi Mehmet,

I am not an Arabidopsis person. My understanding is that the TE library used in TAIR10 is manually curated. A simple way to figure out: 

1. download it and format the sequence names.
2. use this library to RepeatMask your genome, then
3. use `EDTA/util/evaluation.pl` to evaluate the annotation (in)consistency. 

Manually curated libraries are highly consistent, and the annotation inconsistency is generally lower than 1%. Please refer to the EDTA paper for more details.

Best,
Shujun

**Comment by MehmetGoktay** [comment]
Thank you  very much Shujun!

**Comment by oushujun** [comment]
@MehmetGoktay if you figure out the curated TE library for Arabidopsis, it would be great if you can post it here, so that other people can benefit from your efforts. Thanks in advance!

**Comment by MehmetGoktay** [comment]
Hi Shujun,

I have contacted to TAIR10 Help desk and clearly (to my understanding) they are manually curated.

 Here is the info. 

ftp://ftp.arabidopsis.org/home/tair/Genes/TAIR8_genome_release/Readme-transposons

**Comment by oushujun** [comment]
@MehmetGoktay Great! Thanks for sharing the info. I will close this tab since it's resolved. Please open new tags if you have other issues or questions. Good luck! - Shujun
