### ISSUE TITLE
Change the parameters of the LTR retrotransposon related programs 

### ISSUE THREAD

**Issue by uceleste** [oushujun/EDTA#200]
Dear Shujun,

Is it possible to change the parameters of the LTR retrotransposon related programs? I would like to test your pipeline with different parameters. For example, I would like to use ltr-harvest without the "-motif TGCA" parameter, and other slightly different parameters.

Kind Regards,

Gabriele

**Comment by oushujun** [comment]
Hi Gabriele,

You may want to test parameters with LTR_retriever which allows for
customerization of many parameters including the motif requirement. EDTA is
directly using the results of LTR_retriever. For benchmarks, you may use
the lib-test.pl script in the EDTA package, which is applicable for both
packages and results from other packages.

Best,
Shujun

**Comment by uceleste** [comment]
Thank you Shujun! I can close this post.
Kind Regards,

Gabriele
