### ISSUE TITLE
evaluate option crashing computer

### ISSUE THREAD

**Issue by Brent-Saylor-Canopy** [oushujun/EDTA#201]
Hi,

I have run your pipeline on both the test data you provide and the a genome assembly of my own. The majority of the pipeline looks to be working fine but for the test data I'm not getting any the stat output files from the --evaluate 1 option, and on my own larger genome.

The test run works find and I'm able to find all of the files, however the run on my genome seems to be crashing my computer at the --evaluate 1 stage. I haven't been able to track down the exact source of the crash, but I've tried twice and both times when I come back in the morning my computer has been rebooted and looks to have crashed. I'm running on an up to date ubuntu box. 

I'd appreciate you help getting this last step running as I really like the rest of the pipeline.

**Comment by oushujun** [comment]
Hi, please provide error messages otherwise I can't troubleshoot. And
please confirm you are using the latest version (v1. 9. 9). Thanks!

Shujun

**Comment by Brent-Saylor-Canopy** [comment]
I've checked as much as I could, but because the computer is crashing I'm not getting any error message I can find.

This is the last line of the log file I delivered  to a text file using tee 

`Fri 25 Jun 2021 04:14:45 PM EDT	Evaluate the level of inconsistency for whole-genome TE annotation (slow step):
`
The rest of the document is blank

**Comment by oushujun** [comment]
For the test data did your computer also crushed? Any error messages? You
may diagnose with test data before using it on your genome.

Shujun

**Comment by Brent-Saylor-Canopy** [comment]
I think the problem was a system update that was causing crashes, and a long runtime was the only reason it kept happening while running the script. Thanks for the help.
