### ISSUE TITLE
The integrity of results in regards to a failed evaluation step

### ISSUE THREAD

**Issue by KaparaNewbie** [oushujun/EDTA#204]
Hey there, and thanks for all work you put into EDTA.

(some background)

At first, I installed `EDTA` directly from an existing conda environment, and used it to annotate the Turquoise killifish Genome for some joint project I'm part of. Only when it was time to submit my results I noticed I had a bug with `RepeatModeler` (same as [23](https://github.com/oushujun/EDTA/issues/23)).
Therefore, I installed `EDTA` by cloning the git repository and creating a fresh conda environment out of the `YAML` file. This time the annotation was successful, but the `TEanno.sum` file was empty and the last evaluation step was crushed (same as [171](https://github.com/oushujun/EDTA/issues/171) and [178](https://github.com/oushujun/EDTA/issues/178)). 

In both times the command used was something like:
```bash
conda activate EDTA

cd OutDir

nohup ~/anaconda3/envs/EDTA/bin/perl \
~/anaconda3/envs/EDTA/bin/EDTA.pl \
--genome Nothobranchius_furzeri_genome.fasta \
--cds CDS.fasta \
--curatedlib Repeats-DB-families.fa \
--sensitive 1 \
--anno 1 \
--evaluate 1 \
--threads 25 \
> EDTA.out &
```

(BTW, the same happened with a Genome of another organism, except then I didn't provide a `--curatedlib Repeats-DB-families.fa` that was generated with `RepeatMasker`'s `queryRepeatDatabase.pl`)

So, I would like to know if I may use the output of the last results, specifically the `TEanno.gff3` file.
If the answer is yes, I'd like to know what is the best way to summarize the results in the same way as they would appear in the `TEanno.sum` file. I found [174](https://github.com/oushujun/EDTA/issues/174) but it mostly dealt with costume summaries.

Thanks a lot!

**Comment by oushujun** [comment]
Hi @KaparaNewbie,

You need to test the installation with the test files first. Did you see any error messages?

Shujun

**Comment by KaparaNewbie** [comment]
Hey, sorry I forgot to mention it! 
Of course, I tested the installation. There were no error messages.

**Comment by oushujun** [comment]
Thanks for this extra info. Did you see any error messages for your genome? 

You said the other genome also had such an error, but did this happen to all of your genomes? 

If you believe this error randomly happens without providing the `Repeats-DB-families.fa` file, I would need your data to troubleshoot on my end. If possible, you may make a subset of your data that would still reproduce this error and send it to me via shujun.ou.1@gmail.com. Thanks!

**Comment by KaparaNewbie** [comment]
Hey @oushujun, just sent you an example. Thanks ahead!

**Comment by oushujun** [comment]
@KaparaNewbie I got your email, thanks! There will be some delay from my side due to summer craziness. - Shujun

**Comment by oushujun** [comment]
Hello @KaparaNewbie 

Sorry it took me a while to find a chance. I tested the data you sent me, they worked fine without any issues. I was using v1.9.9 and this command `nohup perl ~/las/git_bin/EDTA/EDTA.pl --genome D.acutus.genome.fa --cds D.acutus.CDS.fa --sensitive 1 --anno 1 --threads 36 --evaluate 1 &`

Did you get a chance to try on the latest update?

Best,
Shujun

[D.acutus.genome.fa.mod.EDTA.zip](https://github.com/oushujun/EDTA/files/6949360/D.acutus.genome.fa.mod.EDTA.zip)

**Comment by oushujun** [comment]
@KaparaNewbie any updates? - Shujun

**Comment by KaparaNewbie** [comment]
Oh, so sorry, I missed your previous message!
Thanks you so much for investing your time in this.

I cloned the repo on the 6.7.2021, so I think it was after the latest update. Am I right?

**Comment by oushujun** [comment]
@KaparaNewbie How did it go?

**Comment by KaparaNewbie** [comment]
Hello @oushujun and sorry for the delayed response.
I repeated my steps today (i.e. git clone the repo, create a conda env, run EDTA on the subset of data I created), but still got those errors at the end:
```
Tue Nov 23 09:51:07 IST 2021	TE annotation using the EDTA library has finished! Check out:
				Whole-genome TE annotation (total TE: ): D.acutus.genome.fa.mod.EDTA.TEanno.gff3
				Whole-genome TE annotation summary: D.acutus.genome.fa.mod.EDTA.TEanno.sum
				Low-threshold TE masking for MAKER gene annotation (masked: 5.32%): D.acutus.genome.fa.mod.MAKER.masked

Tue Nov 23 09:51:07 IST 2021	Evaluate the level of inconsistency for whole-genome TE annotation (slow step):

Use of uninitialized value in pattern match (m//) at ~/anaconda3/envs/EDTA-23.11.21/share/EDTA/util/call_seq_by_list.pl line 88.
Use of uninitialized value $chr_pre in hash element at ~/anaconda3/envs/EDTA-23.11.21/share/EDTA/util/call_seq_by_list.pl line 90.
Use of uninitialized value $pos in pattern match (m//) at ~/anaconda3/envs/EDTA-23.11.21/share/EDTA/util/call_seq_by_list.pl line 100.
Use of uninitialized value $pos in concatenation (.) or string at ~/anaconda3/envs/EDTA-23.11.21/share/EDTA/util/call_seq_by_list.pl line 103.
ERROR: Can not recognize this MSU position in the list!
ERROR: TE annotation stats results not found in D.acutus.genome.fa.mod.EDTA.TE.fa.stat!
```

**Comment by oushujun** [comment]
@KaparaNewbie Can you reproduce the issue with a small dataset? I'd like to access that dataset and test it on my end. Thanks!

Shujun

**Comment by oushujun** [comment]
From the error message you provided, it seems like you are using the EDTA version provided by conda. ie., `~/anaconda3/envs/EDTA-23.11.21/share/EDTA/`. You may use the cloned version (v1.9.9), ie., `perl ~/your-path-to-the-cloned-EDTA/EDTA/EDTA.pl <parameters>`.

**Comment by KaparaNewbie** [comment]
Oh! My bad. You were right.
This time I ran as follows:
```
~/EDTA/EDTA-23.11.2021/EDTA.pl \
~/anaconda3/envs/EDTA-23.11.21/bin/EDTA.pl \
--genome genome.fa \
--cds CDS.fa \
--sensitive 1 \
--anno 1 \
--evaluate 1 \
--threads 30
```
and no errors occurred.
Thank you so much!
