### ISSUE TITLE
Different TE names in *.TElib.fa and *.TEanno.gff3

### ISSUE THREAD

**Issue by MrbrilliantLL** [oushujun/EDTA#205]
Hi Shujun,

I am now using EDTA v1.9.9. I annotated each of the three maize genomes according to your description in #132, and combine them with the make_panTElib.pl script at one time. Then I use the following command to rerun the EDTA to obtain the pan-genome annotation relation to the three genomes.

`perl EDTA.pl --genome ./B73.fasta --species Maize --overwrite 0 --curatedlib ../panTE/TElib.panTE.fa --anno 1 -t 32`

The *.TElib.fa obtained in the three genomes are consistent in TE name. However, some TE names are inconsistent in *.TElib.fa and *.TEanno.gff3. There are some instances:

![image](https://user-images.githubusercontent.com/56568825/125195628-107daa00-e289-11eb-928d-8d4708df4b7c.png)

The "TE_00000002" is "#DNA/Helitron" in *.TElib.fa, and  not found in *.intact.gff3, "Mutator_TIR_transposon" in *.TEanno.gff3. The log file of the program run does not report an error, so I don't know what is causing this result.

Lei

**Comment by oushujun** [comment]
Hi Lei,

It's normal. If the renaming precess cannot find any intact TEs passing the
criteria, the TE library sequence won't be used to rename anything. This is
because the library construction process tries to remove nest insertions
and the resulting sequence may not be an actual sequence anymore.

Shujun

**Comment by MrbrilliantLL** [comment]
Thank you for your quick response! 

For this case, how can I distinguish TE names in *.gff3 matching the TE lib or not?

**Comment by oushujun** [comment]
The ones with no qualified matches are named using their coordinates.

Shujun

**Comment by MrbrilliantLL** [comment]
In *.intact.gff3, TEs with no qualified matches are named using their coordinates.  However, like first my instance shows, the *.TElib and *.TEanno.gff3 from one genome have different annotations for TE_00000002.

**Comment by oushujun** [comment]
Are these from the same annotation? If you rerun the final step (`--step final --overwrite 1`), the resulting TE library will be different.

**Comment by MrbrilliantLL** [comment]
I annotated each of the three maize genomes, and combine them with the make_panTElib.pl script at one time. Then feed EDTA with this combined library with the --curatedlib parameter and rerun EDTA on three genomes again (with --overwrite 0). This is the command:

`perl EDTA.pl --genome ./B73.fasta --species Maize --overwrite 0 --curatedlib ../panTE/TElib.panTE.fa --anno 1 -t 32`

You say that I will get a pan-genome annotation for all genomes with unified TE names in #132. But now, some TE names in *.TElib and *.TEanno.gff3 is different.

**Comment by MrbrilliantLL** [comment]
I annotated each of the three maize genomes, and combine them with the make_panTElib.pl script at one time. Then feed EDTA with this combined library with the --curatedlib parameter and rerun EDTA on three genomes again (with --overwrite 0). This is the command:

perl EDTA.pl --genome ./B73.fasta --species Maize --overwrite 0 --curatedlib ../panTE/TElib.panTE.fa --anno 1 -t 32

You say that I will get a pan-genome annotation for all genomes with unified TE names in #132. But now, some TE names from one genome in *.TElib and *.TEanno.gff3 is different.

You mean I should try to rerun the final step (--step final --overwrite 1) with the combined library?

**Comment by oushujun** [comment]
Yes, please try to rerun the final step (--step final --overwrite 1) with
the combined library. The final step will rename IDs.

Shujun

**Comment by MrbrilliantLL** [comment]
Ok, thank you a lot for you help! I will close this issue.
