### ISSUE TITLE
extract RT domain

### ISSUE THREAD

**Issue by hexin010101** [oushujun/EDTA#207]
Hi, @oushujun 
I want to extract the GYPSY RT domain of intact LTR-RT from the result of EDTA,What method should i use?

**Comment by oushujun** [comment]
Hi @hexin010101, please try out TEsorter: https://github.com/zhangrengang/TEsorter

-Shujun

**Comment by hexin010101** [comment]
Thanks for your reply! It's very usefull . Best regards.
