### ISSUE TITLE
Keeping all full-length transposons?

### ISSUE THREAD

**Issue by aderzelle** [oushujun/EDTA#21]
Hello, 
I might have a suggestion:
I was wondering if it wouldn't be useful for the final user to be able to get a file with the coordinates of the transposon, for example if one is interested to look at their position in the genome.

Thanks for EDTA, it's a cool pipeline.

**Comment by oushujun** [comment]
Hi @aderzelle,

Thanks for your suggestion. I am working with a functionality to retain all intact transposons identified by EDTA, which could be useful for people who want to study the biology of transposons. I think this is essentially what you are proposing. Currently, EDTA produces a non-redundant library for the whole-genome annotation purpose.

Best,
Shujun

**Comment by oushujun** [comment]
Hi @aderzelle ,

Sorry for the delay response. I have updated EDTA, it now also outputs intact TEs. Please try it out and let me know if there is any issues.

Best,
Shujun

**Comment by oushujun** [comment]
The current version provides outputs for full-length LTR, TIR, and Helitrons in both fasta and gff formats. (*.intact.fa and *.intact.fa.gff). Feel free to reopen this issue if you identify new problems or have any suggestions.

**Comment by aderzelle** [comment]
Hello,
it works however LTR are in gff3 formats while the others are in gff2 format, which might create confusion in downstream analysis (though it's not a big deal of course but as a little improvement they could be in the same gff version).

**Comment by oushujun** [comment]
Dear @aderzelle,

Thank you for your suggestions. I have incorporated the intact TE annotation to the whole-genome TE annotation. Also, gff format of the final annotation is more consistent with each other. Now the *EDTA.TEanno.gff file contains both structural-based and homology-based annotations. Please check out the [new release](https://github.com/oushujun/EDTA/releases) or the latest repository for more details.

Happy New Year!

Best,
Shujun
