### ISSUE TITLE
TEanno.sum file is empty.

### ISSUE THREAD

**Issue by d00bin** [oushujun/EDTA#210]
I used EDTA on various teleost genomes and for all of them it was excellent (thank you!), except one.
For some reason in the end the summary file is empty no matter what I do. 

It printed out warnings like this:
Warning: TIR/PiggyBac not found in the TE_SO database, will use the general term 'repeat_region SO:0000657' to replace it.

Which I guess are ok. These types of warnings are present in other species runs as well. 

But then there are errors unique to this genome run:
Use of uninitialized value $type in concatenation (.) or string at /path/to_folder/REPEATS/EDTA/util/gff2bed.pl line 85, <GFF> line 1564.

Could someone help me, please?

**Comment by oushujun** [comment]
Hi, it's likely this genome is lacking at least one of the target TE types (LTR, TIR, Helitron). To find out, list the raw directory and see if there are any very small-sized files and that indicate missing TE types. If this is the case, you may try to add the `--force 1` parameter to overcome this.

Shujun

**Comment by d00bin** [comment]
Thanks for such a fast response! 

I looked into the mod.EDTA.raw folder and it doesn't look like it if full of small-sized files, however I remember noticing empty files on the final RM step. So I decided to re-run everything with the --force 1 parameter.

It didn't help with the summary file (still empty) and "_Use of uninitialized value $type in concatenation (.)_" errors are still there as well. 
I decided to have a look at the mod.tbl in the .mod.EDTA.anno folder, and here is what it looks like:


==================================================
               number of      length   percentage
               elements*    occupied  of sequence
--------------------------------------------------
Retroelements        92597     18520613 bp    3.08 %
   SINEs:                0            0 bp    0.00 %
   Penelope              0            0 bp    0.00 %
   LINEs:             4123      1630535 bp    0.27 %
    CRE/SLACS            0            0 bp    0.00 %
     L2/CR1/Rex          0            0 bp    0.00 %
     R1/LOA/Jockey       0            0 bp    0.00 %
     R2/R4/NeSL          0            0 bp    0.00 %
     RTE/Bov-B           0            0 bp    0.00 %
     L1/CIN4             0            0 bp    0.00 %
   LTR elements:     88474     16890078 bp    2.81 %
     BEL/Pao             0            0 bp    0.00 %
     Ty1/Copia           0            0 bp    0.00 %
     Gypsy/DIRS1      8750      6348607 bp    1.06 %
       Retroviral        0            0 bp    0.00 %

DNA transposons     423501     65570391 bp   10.91 %
   hobo-Activator        0            0 bp    0.00 %
   Tc1-IS630-Pogo        0            0 bp    0.00 %
   En-Spm                0            0 bp    0.00 %
   MuDR-IS905            0            0 bp    0.00 %
   PiggyBac            139        41803 bp    0.01 %
   Tourist/Harbinger     0            0 bp    0.00 %
   Other (Mirage,        0            0 bp    0.00 %
    P-element, Transib)

Rolling-circles          0            0 bp    0.00 %

Unclassified:       310592     56125293 bp    9.34 %

Total interspersed repeats:   140216297 bp   23.33 %




It seems that you were right regarding the missing transposon types, but the numbers look very strange. 
For example it says that there are 423501 of DNA transposons which comprises 10.91 % of the genome, but where this number is coming from? Looks like only PiggyBac is present, but in a few numbers.
Maybe I don't understand something... Could this weird behaviour be related to high number of duplicated genes in this species, which are somehow recognised as repeats?

**Comment by oushujun** [comment]
You need to check `*intact.gff3` files in the raw directory, and if all four of them contain at least one entry (not just the header), that means you don't need to use `--force 1`. You may have tried this, but removing all EDTA files and rerun EDTA is a good idea.

Shujun

**Comment by d00bin** [comment]
>You need to check *intact.gff3 files in the raw directory, and if all four of them contain at least one entry,  that means you don't need to use --force 1

They do! Does that mean that all types of repeats are present? 
How can I get the summary file then if everything is OK?

**Comment by oushujun** [comment]
You may need to rerun EDTA fresh.

**Comment by d00bin** [comment]
Hello, Shujun! 

The thing is, I used EDTA for other genomes similar in size, with the same settings and all runs finished fine. 
But I identified the problem, I think it was RepeatModeler that caused the issues.
As a test, I decided to use RepeatModeler alone and see how it compares to EDTA. It crashed for the same genome EDTA was crashing. This gave me an idea to try EDTA without -sensitive option, and it finished correctly! 

So perhaps it would be possible to implement some sort of check for errors during RM runs. If RM crashes, perhaps EDTA could give user an option to restart it.

**Comment by DevonJBoland** [comment]
Hello!

I was running into a similar problem OP was running into. I have three genomes from different strains of a microalga (all the same species). I was running EDTA on each one, with --sensitive, --overwrite, and --anno all set to 1. One of the genomes had no issue generating all the summary files. However the other two genomes, kept resulting in all files generated except for the .sum file.

I will try the workaround OP presented about removing the --sensitive flag, and see if it works!

Good luck,
-Devon

**Comment by d00bin** [comment]
Hello, Devon! 

Please let me know if it worked! I'm curious:)

**Comment by DevonJBoland** [comment]
Hello!

I can confirm that the workaround OP presented, also worked for me. I should also clarify, I am using a singularity container of v1.9.4 of EDTA.

Side note, thank you for developing the software. I have been looking for a program that annotates TEs, and came across the program in a recent pan-genome analysis of maize that used EDTA.

Best,
-Devon

**Comment by oushujun** [comment]
Hi Devon,

Thank you for reporting back. EDTA was originally developed to annotate
maize pan-genomes.

You may use the conda version for latest updates. The singularity version
is a couple updates behind.

Best,
Shujun
