### ISSUE TITLE
How use LTRdigest to note intact LTR

### ISSUE THREAD

**Issue by 1Wencai** [oushujun/EDTA#211]
Hi shujun
   How i use LTRdigest to note EDTA's output( intact LTR).

Best
Wencai

**Comment by oushujun** [comment]
You may need to write your own conversion script to prepare for LTRdigest inputs. Check their readme for more info. - Shujun

**Comment by 1Wencai** [comment]
Thanks for your return.

Best
Wencai

**Comment by oushujun** [comment]
Feel free to share your solution here so that others can benefit from your efforts. Thanks! - Shujun

**Comment by 1Wencai** [comment]
I basically looked up "LTRdigest User’s Manual" to solve my problem. (http://genometools.org/documents/ltrdigest.pdf) In addition,I converted the format of LTRretriever output to the format of LTRharvest output.

**Comment by oushujun** [comment]
That's great! Would you mind sharing your commands and parameters for your conversion and LTRdigest analysis? Thanks! - Shujun

**Comment by 1Wencai** [comment]
Sorry for taking so long to reply, I haven't used it recently, but the  "LTRdigest User’s Manual" manual explains it in detail and I follow it step-by-step. -Wencai
