### ISSUE TITLE
Genome Masked file has lesser number of masked bases than reported in summary

### ISSUE THREAD

**Issue by sanyalab** [oushujun/EDTA#212]
Hi Shujun

While using EDTA with the "--anno 1", I noticed that there is a wide discrepancy in the number of masked bases in the final genome file "MAKER.masked" and what is reported in summary "TEanno.sum". Attached is an example summary output. I am using version 1.9.4 and the species is "other"

![Capture](https://user-images.githubusercontent.com/20696713/128997870-878bb907-4c9a-4c49-a6f3-5c805206bd64.PNG)

In the image the total masking is 1466501272 bp = 78.89% for my grass genome. When I use "MAKER.masked" with emboss tool compseq, I get the output as 657530182 bp or 35.31%. The 78% is more reasonable and expected versus 35.31%. Have you seen this in your tests with other grass species? Is there a fix as I have the intermediate files with me.

Thanks
Abhijit

**Comment by oushujun** [comment]
Hi Abhijit,

the MAKER.masked file is for gene annotation not for TE annotation. Please check other discussions.

Best,
Shujun

**Comment by sanyalab** [comment]
Hi Shujun,

I use the MAKER.masked file for gene annotation. That file has only 35% N's in this case. I wanted to know if you have come across this in some other examples as well.

Thanks
Abhijit

**Comment by oushujun** [comment]
Hi Abhijit,

That's normal. The MAKER.masked file has short repeats removed to preserve the genic region as intact for better gene annotation. If I recall all repeats under 1kb are removed to generate this file. It is expected to have some TE genes in your gene annotation result, so you should identify and remove them afterward. It is recommended to use TEsorter to identify these TE genes.

best,
Shujun

**Comment by sanyalab** [comment]
Ok. Thanks Shujun
