### ISSUE TITLE
Invalid process during LTR identification

### ISSUE THREAD

**Issue by wjwei-handsome** [oushujun/EDTA#216]
Dear Shujun

Thank you for developing this effective and useful tool, but I encountered a small problem in using it. When I was running a genome with a size of about 3.3G, in the step of identifying the LTR, I found that a process that took up only a small part of the memory but not the CPU was generated. This stopped my identification. My command is Such: `EDTA.pl --genome ref.fa --species Maize --step all --threads 16 1>EDTA_02.log 2>&1`, the resulting invalid process is shown in the following figure:
![image](https://user-images.githubusercontent.com/56633839/130384712-060ff813-aec1-48c3-b8ca-005b08ee13fc.png)
The CPU occupancy rate of this process is 0, and the memory occupancy rate is 0.2%. 
So I need your help!Thanks for the advice!

**Comment by oushujun** [comment]
Looks similar to #208

**Comment by oushujun** [comment]
The screenshot you provided is LTR_retriever processes, not TIR. Did you receive any error messages?

**Comment by wjwei-handsome** [comment]
> The screenshot you provided is LTR_retriever processes, not TIR. Did you receive any error messages?

Sorry,My fault! In fact it is LTR. And I did not receive any error messages.

**Comment by oushujun** [comment]
I don't see any error neither. Did you finish your run?

**Comment by oushujun** [comment]
@wjwei-handsome do you have any updates?  - Shujun
