### ISSUE TITLE
Dependency Error

### ISSUE THREAD

**Issue by shivanisehrawat4** [oushujun/EDTA#217]
Hii I am getting the following error :

Dependency checking:
Error: The RMblast engine is not installed in RepeatMasker!

Can you please check it at your end?

**Comment by oushujun** [comment]
Hi You can search the issues for solutions: https://github.com/oushujun/EDTA/issues?q=The+RMblast+engine+is+not+installed+in+RepeatMasker
Basically reinstall the entire EDTA repo will quickly solve the problem.

Best,
Shujun
