### ISSUE TITLE
The duplicate TE in lib.fa file

### ISSUE THREAD

**Issue by wushyer** [oushujun/EDTA#221]
Hi Shujun,

   I found some duplicate TE name in the result file.

(base) wusy@anita-PowerEdge-R740:~/TAK$ grep 'TE_00000248' genome.fa.mod.EDTA.TElib.fa
>TE_00000248_#LTR/unknown
>TE_00000248_#LTR/unknown
>TE_00000248#Unknown

The first two are in different seize. Is this a bug in EDTA? Thanks.

Best
Shuangyang

**Comment by oushujun** [comment]
Can you check which version you were using? Any error messages?  -Shujun

**Comment by wushyer** [comment]
Hi Shujun,
 
    No error, I just checking out the fasta to find this. The version is 1.9.4. The command line is

nohup EDTA.pl --genome genome.fa --species others --sensitive 1 --threads 10 --anno 1 --force 1 &

   I also checked the log file for the error info, it seems the only error reported with no helitron, which use force 1 to proceed anyway.

   Thanks for the help.

Shuangyang

**Comment by wushyer** [comment]
I tried the signularity today and pull the 1.9.5 from docker.
singularity pull EDTA.sif docker://oushujun/edta:1.9.5
nohup singularity exec EDTA.sif EDTA.pl --genome ../genome.fa --species others --sensitive 1 --threads 10 --anno 1 --force 1 &
But the version still be 1.9.4 in nohup.out. Please see below, I would tell you the result once it finished by signularity. Thx

INFO:    Converting SIF file to temporary sandbox...

########################################################
##### Extensive de-novo TE Annotator (EDTA) v1.9.4  ####
##### Shujun Ou (shujun.ou.1@gmail.com)             ####
########################################################



Mon Sep 13 12:16:42 CEST 2021	Dependency checking:
				All passed!

**Comment by oushujun** [comment]
Hi Shuangyang,

This is a known bug fixed in v1.9.9. Please use the conda version.

Best,
Shujun

**Comment by wushyer** [comment]
Yes! That's all fixed. Thanks!

Best
Shuangyang
