### ISSUE TITLE
how to add the latest Repbase and Dfam library to EDTA?

### ISSUE THREAD

**Issue by biozzq** [oushujun/EDTA#222]
Dear @oushujun 

Thank you for developing this tool. I have tried to run it recently and have some doubts. For most animal genomes, obtaining a  curated library is difficult, thus I think I can change to use the homology-based library generated by RepeatMasker (I also referred to this issue (https://github.com/oushujun/EDTA/issues/193)). I know that RepeatModeler (build a de novo repeat library) and RepeatMasker can be used together with the Repbase and Dfam to generate a combined library (including homology-based and de novo based library). I do not know whether EDTA has used the Repbase and Dfam libraries or not? If not, I think I will have two ways to get it done, (1) put the Repbase and Dfam libraries under specific directory where EDTA can find it automatically; (2) run RepeatModeler and RepeatMasker alone and pass the high quality entries in the RM.out to parameter `-rmout`. 

Since I just started to use EDTA in animal genomes, hope you can let me know if I'm misunderstanding. Thank you.

Best wishes,
Zheng zhuqing

**Comment by oushujun** [comment]
Hi Zhuqing,

Repbase and Dfam may not be very helpful for EDTA. You may check out other
issues on this topic.

Shujun

**Comment by biozzq** [comment]
Dear @oushujun 

Thank you. Yes, I have checked the related issues, e.g., https://github.com/oushujun/EDTA/issues/164 https://github.com/oushujun/EDTA/issues/199. The EDTA will not benefit from these external libraries, and these libraries may also cause the program to fail. The best way is to organize a high-quality TE database and pass it to parameter `--curatedlib`, but this work maybe difficult for those non-model species. Based on the EDTA paper, maybe we can extract the TEs of the study species in Repbase and treat them as a curated library (you have done the evaluation in rice). If the TEs of the study species is not available in the Repbase, it is better to run following command with default setting
`perl EDTA.pl --genome genome.fa --cds genome.cds.fa --overwrite 1 --sensitive 1 --anno 1 --evaluate 1`. Is this right?

Best wishes,
Zheng zhuqing

**Comment by oushujun** [comment]
Rice is a special case because historically it has tons of manual curations
for TE sequences. Thus, the rice library in Repbase is of high quality. I
am not sure if many other species have such a background. For animals,
maybe human, fruit fly, and mouse? You may try to use Repbase sequences as
"curated" if you believe the quality is good enough. You should aware that
the resulting annotation will have the same level of quality as the
"curated" library.

Shujun
