### ISSUE TITLE
EDTA stalling at LTR stage versions 1.9.4 and 1.9.9

### ISSUE THREAD

**Issue by Chriswinefield** [oushujun/EDTA#225]
Hi Shujun,

I have been having some great success with the pipeline and it is proving invaluable to the projects I am working on.
However I have suddenly started having issues with EDTA stalling the the LTR discovery stage. This is impacting both my work and that of a colleague. In my case genomes that are better assembled with relatively few contigs/scaffold appear to work ok. But with more fragmented assemblies (30K+ contigs/scaffolds) time to run extends out quite dramatically as expected. We are using EDTA on a large cray based cluster and in my own case I have generated a conda environment in my account to spin up EDTA. This has been working well up until a few weeks ago. 

There are no errors in the .err or .out. Tracking the folders it appears that quick quickly there is no further writing to the LTR directory and in particular the .mod.harvest folder. For the latest run the assembly consists of ~23K contigs/scaffolds, with fasta entry names no longer than 12 characters and is ~a 3Gbase triploid plant genome. The file number in the .mod.harvest is the correct size (i.e. dounble the fasta entries)

We are a bit perplexed as sporadically a reboot of the pipeline allows progression past the point where things were hung up and then progression to a successful completion of a run. For some of the assemblies this just doesn't work and I suspect there is a permission-read-write issue that EDTA is encountering with our system that is causing the problem but without any error output it is proving difficult to resolve the issue. 

I have seen other issues posted with similar problems but none exactly like what we are observing. Usually the LTRs work fine and there are issues with the TIR (memory based largely).

Any suggestions would be really fantastic

Kind Regards
Chris

**Comment by oushujun** [comment]
Hi Chris,

Thank you for describing the issue clearly. It seems like the program may
encounter write restrictions. As you described, It works for continuous
genomes but not for some highly fragmented ones, and rebooting sometimes
could resolve. You may need to check if there is enough space in the disk,
or if there is any file number restrictions for your system.

A bypass Maybe is to split the genome file into multiple pieces and run
EDTA in a pan-genome mode. Or run LTRarvest and LTR_FINDER independently
for the entire genome, then put the results in the EDTA_raw/LTR folder, and
the program will pickup what has done.

Best,
Shujun

**Comment by oushujun** [comment]
Hi Chris,

Yes, all files generated by EDTA should be visible. The LTR module should generate relatively fewer files comparing to the TIR module. For a 3Gb genome with 30k contigs, the average contig length is 100k, which means the LTR module will process each contig separately. For LTRharvest, each process will generate 12 files but only 2 files will be kept at the end of the child process, and the final output of this program is two files. For LTR_FINDER, each child process will generate 2 intermediate files and also final output 2 files. The two steps run sequentially, so you may have ~60-100k files in max. For the TIR module, each contig will have 4 files plus other intermediate files, you will have a range of 120k - 130k files.

The output of LTRharvest_parallel and LTR_FINDER_parallel is a .scn file of 11-12 columns, and the 11th column is the order of contig that appears in the input file. If you want to split the genome and combine in this step, then you need to rename the 11th column back into the original order. It's a bit tricky.

For bypassing system file number limitations, @philippbayer may have some experience.

Best,
Shujun

**Comment by philippbayer** [comment]
Hi! We have a 1 million file-limit on our /scratch/, I've had good success in running EDTA within a Singularity overlay filesystem. That way the cluster only sees a single file, and there's another file-system inside that file 
I put a tutorial here: https://gist.github.com/philippbayer/aacf8f32825f917e0b81785906f36754  
I haven't really encountered any slowdowns or issues, the only problem is that only one process can use a Singularity overlay FS at a time.

**Comment by Chriswinefield** [comment]
Hi Shujun and Philip,
Many thanks for you helpful comments. I have installed the pipeline in a conda environment in the backed-up 'project' partition of my account. I run the pipeline in the scratch partition where there is plenty of capacity. However it appears that there is a large number of 'tmp' files being written into the project node that would exceed my quota in this partition. I have had the quota increased in this partition and am re-trying the pipeline now. 
I had the pipeline installed in this way so as to avoid the automatic file deletion that occurs in scratch (and so having to regularly reinstall the pipeline). The system administrator helping me had also developed a module (that avoids having to install a instance in user accounts) and this also fails as I suspect there is read-write activity to locations that the pipeline wont have permission to access.
I will post my progress and a summary of our solution for folks if they find themselves in a similar situation.

Kind Regards
Chris
