### ISSUE TITLE
Use of uninitialized value $lLTR_start ($rLTR_end, $chr)

### ISSUE THREAD

**Issue by kingforest93** [oushujun/EDTA#228]
Hi shujun,

Thanks for your excellent work in developing `EDTA` as an Extensive _de-novo_ TE Annotator for the research community. I am using `EDTA` to annotate interspersed repeat in a _de-novo_ assembled plant genome, and in particular, to build a non-redundant TE library for the following analysis.

I used conda to install the dependencies of EDTA and then cloned the source code of EDTA v1.9.9, and the `test` run OK and the produced results were exactly as expected. Further, I used part of the assembled contigs (total length ranging from 1-Mb to 500-Mb) to estimate the run time of EDTA. The command and options of runing EDTA were as follows:
`/usr/bin/time -v EDTA.pl --genome JJ_100Mb.fa --sensitive 1 --overwrite 1 --force 1 --threads 20`

EDTA pipeline run well with the input contigs from 1-Mb to 100-Mb and finished without ERROR. There were two WARNING in the following that should not affect the results.
> -WARNING- Grid computing is not available because DRMAA not configured properly: Could not find drmaa
library.  Please specify its full path using the environment variable DRMAA_LIBRARY_PATH
> BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.

When the contigs 500-Mb were used as input for EDTA, the following WARNING and ERROR appeared. Despite this, the pipeline continued and finished (except for the unfinished remaining TE discovery by RepeatModeler), but I was not sure whether these ERROR affect the final results.
> Use of uninitialized value $lLTR_start in numeric lt (<) at path_to_anaconda3/envs/EDTA/share/LTR_retriever/bin/make_gff3.pl line 55, <List> line 2.
> Use of uninitialized value $rLTR_end in numeric lt (<) at path_to_anaconda3/envs/EDTA/share/LTR_retriever/bin/make_gff3.pl line 55, <List> line 2.
> Use of uninitialized value $chr in concatenation (.) or string at path_to_anaconda3/envs/EDTA/share/LTR_retriever/bin/make_gff3.pl line 63, <List> line 2.
> Use of uninitialized value $chr_ori in exists at path_to_anaconda3/envs/EDTA/share/LTR_retriever/bin/make_gff3.pl line 72, <List> line 2.
> ...
> Use of uninitialized value $chr_pre in hash element at path_to_anaconda3/envs/EDTA/share/EDTA/util/call_seq_by_list.pl line 90.
> ERROR: Can not recognize this MSU position in the list!
> Use of uninitialized value $lLTR_start in numeric lt (<) at  path_to_anaconda3/envs/EDTA/share/EDTA/util/rename_LTR_skim.pl line 49, <Seq> chunk 1.
> Use of uninitialized value $rLTR_end in numeric lt (<) at path_to_anaconda3/envs/EDTA/share/EDTA/util/rename_LTR_skim.pl line 49, <Seq> chunk 1.
> Illegal division by zero at path_to_anaconda3/envs/EDTA/share/EDTA/util/cleanup_tandem.pl line 100, <File> chunk 1.
> ...
> Use of uninitialized value $info in pattern match (m//) at path_to_anaconda3/envs/EDTA/share/EDTA/util/filter_gff3.pl line 38, <GFF> line 6.
> ...
> Use of uninitialized value $seq_new in substr at path_to_anaconda3/envs/EDTA/share/EDTA/util/cleanup_nested.pl line 190.
> Thread 30 terminated abnormally: substr outside of string at path_to_anaconda3/envs/EDTA/share/EDTA/util/cleanup_nested.pl line 190.

I also tried EDTA v1.9.6 (installed by my colleague and worked well for several genomes ~ 1-Gb), but the above WARNING and ERROR still occured. Did these affect the final results?

wang sen

EDTA runing commands and log are attached:
[edta.500Mb.zip](https://github.com/oushujun/EDTA/files/7309299/edta.500Mb.zip)

**Comment by oushujun** [comment]
@kingforest93 How did it go?

**Comment by oushujun** [comment]
@BRNiu It has been a while... I hope this issue is solved. Please reopen the issue if not. Thank you! - Shujun
