### ISSUE TITLE
Naming issues in gff3 and TE sequences missing from the TE library

### ISSUE THREAD

**Issue by david-roquis** [oushujun/EDTA#229]
Dear Shujun,

I have been testing EDTA extensively on plant genomes lately, and I may have listed some issues that I have not been able to explain and solve on my own. Would it be possible to have your input on them?

1. **Major issue:** In the **my_genome.fa.mod.EDTA.TEanno.gff3**, some TEs are neither given a TE_00000000 number nor a name from my reference TE library, but are referred by their position in the 'name' field of the gff. For example, as such:

_chr1	EDTA	Mutator_TIR_transposon	21741	24965	.	.	.	ID=TE_struc_302;Name=chr1:21741..24965;Classification=DNA/DTM;Sequence_ontology=SO:0002280;
Identity=0.9;Method=structural;TSD=AAAAAAAA_AAAAAAAT_87.5;TIR=GAGAAGAGAA_TTCTCTTCGC

chr1	EDTA	repeat_region	106517	118085	.	+	.	ID=repeat_region_1;Name=chr1:106522..118080;Classification=LTR/Gypsy;Sequence_ontology=SO:0000657;ltr_identity=0.9997;Method=structural;motif=TGCA;tsd=ATGGT

chr1	EDTA	long_terminal_repeat	114996	118080	.	+	.	ID=rLTR_1;Parent=repeat_region_1;Name=chr1:106522..118080;Classification=LTR/Gypsy;Sequence_ontology=SO:0000286;ltr_identity=0.9997;Method=structural;motif=TGCA;tsd=ATGGT

chr1	EDTA	Gypsy_LTR_retrotransposon	106522	118080	.	+	.	ID=LTRRT_1;Parent=repeat_region_1;Name=chr1:106522..118080;Classification=LTR/Gypsy;Sequence_ontology=SO:0002265;ltr_identity=0.9997;Method=structural;motif=TGCA;tsd=ATGGT
_

This is problematic for me, as I can't tell from which family/consensus sequence do these TEs come from; i.e. does this Mutator_TIR_Transposon at a given position on chr1 has the same/similar sequence to another one located elsewhere in the genome. Something I have noticed is that all these TEs without a proper name are detected through the "structural" method. However, not all "structural" annotation are problematic. Some are properly named with a TE_00000000 number. In this case, this naming issues affects 31021 records out of 377321 in the gff file (so around 10%). 

2. **Major issue:** It seems that these TEs without names are not included in the TE library file **my_genome.fa.mod.EDTA.TElib.fa**. For example, the Mutator_TIR_Transposon sequence shown above can be found in the **my_genome.fa.mod.TIR.raw.fa**, **my_genome.fa.mod.TIR.intact.fa** file or **my_genome.mod.EDTA.intact.fa**, but is absent from the final library. The same issue occurs for the Gypsy_LTR_retrotransposon also listed above.

3. **Minor issue:** I have the recurring error message on several lines when running EDTA at the "Homology-based annotation of TEs using my_genome.fa.mod.EDTA.TElib.fa from scratch." step. Should I be concerned?

_Use of uninitialized value $type in concatenation (.) or string at ~/Tools/EDTA/util/gff2bed.pl line 85, <GFF> line 371._

4. **Minor issue:** When using a manually curated TE library, how should I name the TEs so the SO annotation is taken into account? At the moment, I use the SO terms but EDTA seems to have a problem to process them. For example, if a sequence is named >P5425_LTR_RLC#Copia_LTR_retrotransposon ; I get the following error message, yet my annotation is properly added to the third column of the gff file

_Copia_LTR_retrotransposon/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation._

5. **Minor issue:** I also always have this error message during the TE library generation. Is it problematic?

_Perform EDTA advance filtering for raw TE candidates and generate the stage 1 library: 

Use of uninitialized value $subject in exists at /home/evdad.admin.ch/a80852139/Tools/EDTA/util/cleanup_nested.pl line 158.
Use of uninitialized value in subroutine entry at /home/evdad.admin.ch/a80852139/Tools/EDTA/util/cleanup_nested.pl line 158._

##Run details
I have tried to run the pipeline as a whole, or following the 'divide and conquer' method (doing Helitrons, LTR, and TIR separately, and then resuming the pipeline with overwrite 0), but the result is the same. I used the following command line:

perl ~/Tools/EDTA/EDTA.pl --genome ~/Downloads/my_genome.fa --species Rice --curatedlib ~/Downloads/my_curated_lib.fa --overwrite 0 --cds ~/Downloads/IRGSP_CDS.fa' --sensitive 1 --anno 1 --evaluate 0 --threads 32 --step all 

These issues have been reproduced over several genomes. Thanks a lot for your advice and your help!

EDIT: I am using EDTA version 1.9.9

**Comment by oushujun** [comment]
Hello @david-roquis,

Thanks for describing your questions clearly and in detail. My answers are below.

To Q1 and Q2, these TEs were annotated by the structural method, but don't have enough copies to count as a family. Most likely they are singletons. Since they are not repetitive, they are likely very rare TEs or false positives, and thus they were not included in the TE library because the library is used to identify copies of the TE via homology. I keep them in the final annotation in case people are interested. You may try to extract their sequence and use blast or RepeatMasker to find similar sequences in the genome, but again, they are most likely singletons.

To Q3, this is a known bug. You may try the temporary fix proposed in #219 or remove the `--sensitive 1` parameter. The fix will be shown in the next update. Sorry about the inconvenience. 

To Q4, you need to use the RepeatMasker naming convention. Please find discussions in #220, #222.

To Q5, warnings like these are fine. 

Best,
Shujun
