### ISSUE TITLE
RepeatModeler in conda

### ISSUE THREAD

**Issue by baozg** [oushujun/EDTA#23]
Hi, all

`EDTA` pipeline rely on the `RepeatModeler` in the conda, but it have a known issue, the conda version seems cannot produce the `consensi.fa`.
https://github.com/rmhubley/RepeatModeler/issues/38

If you want to find TE in your genome by RepeatModeler, please install the software by yourself, assign the `-repeatmodeler`  and  `-repeatmasker` to the install path, and then use the `consensi.fa.classified` as your RepeatModerler raw fa.

**Comment by davidecarlson** [comment]
Hi all,
I'm hoping to get a bit more clarification on the above workaround for RepeatModeler.  I've run EDTA, and provided the paths to my non-conda installations of Repeatmodeler and Repeatmasker.

RepeatModeler runs, apparently successfully, and I have a consensi.fa.classified file.  It is located at 

`/path/to/my-working-dir/my-genome.fasta.EDTA.final/RM_72384.ThuDec120316282019/consensi.fa.classified`

However, in my EDTA log file, I still receive the following error message:

> cat: RM_*/round-*/consensi.fa.classified: No such file or directory
>                                 RepeatModeler is finished, but no consensi.fa.classified files found.

It seems that EDTA is not looking for the file in the correct place.

What do I need to do to make user of the RepeatModeler output?  Should I copy consensi.fa.classified to the EDTA.raw folder, name it Repeatmodeler.raw.fa, and then rerun the EDTA.pl script to finalize the raw repeats?

I'd be grateful for any suggestions!
Thanks,
Dave

**Comment by baozg** [comment]
Hi davidecarlson,

 I write a perl script `rename_RM_TE.pl` to rename RepeatModeler result and successfully get the final result with the newest EDTA. It is on pull request. 

Please wait Shujun check for the script.

**Comment by davidecarlson** [comment]
Thanks, @baozg .  I will wait for an update from Shujun.
Best,
Dave

**Comment by jensbast** [comment]
Same problem:
RepeatModeler is finished, but no consensi.fa.classified files found.

I did not tweak anything though, cloned the git 2 days ago.

**Comment by oushujun** [comment]
@davidecarlson @jensbast 
I have merged the update from @baozg and it should be working. Please install the git version RepeatModeler (not the conda version), update EDTA, and try again. Sorry for the inconvenience.

Best,
Shujun

**Comment by jensbast** [comment]
Thanks a lot!
how can I update EDTA via conda with the git RepeatModeler?
Sorry, I am not familiar with conda.
Best,
Jens

**Comment by oushujun** [comment]
Hi @jensbast ,

There are two steps involved:
1. update EDTA by entering the EDTA folder and run:
`git pull`
2. install git version [RepeatModeler](https://github.com/Dfam-consortium/RepeatModeler). Please follow their instructions.

Then you can run EDTA.pl with the parameter `-repeatmodeler [path]` to indicate the fresh installed RepeatModeler.

Hope this helps!
Shujun

**Comment by davidecarlson** [comment]
Hi @baozg & @oushujun 

After updating EDTA and re-running, the RepeatModeler output is properly found and utilized.  Note, however, that I had to change the shebang on `rename_RM_TE.pl` from 

`#!/usr/bin/perl -wuse strict;`

to 

`#!/usr/bin/perl -w`

in order to get the script to work properly.  That could just be a peculiarity on my end, though.

Thanks for your help!
Dave

**Comment by oushujun** [comment]
@davidecarlson 

Thanks for your report. It looks like there is a run over in the first line. I will correct this in the next update. 

Best,
Shujun
