### ISSUE TITLE
How to get the 3 'LTR and 5' LTR sequences for each retrotransposon found with EDTA.pl?

### ISSUE THREAD

**Issue by omar-almolla209** [oushujun/EDTA#234]
I have already used EDTA.pl in the past and managed to get the file "intact.fa" (eg Slycopersicum_691_SL4.0.fa.mod.LTR.intact.fa) but I am also interested in identifying the specific sequences of the LTRs in 3 ' and 5 'LTRs. Do any of you know how to do it?

**This is how I used EDTA.pl:**
`perl EDTA.pl --genome /home/omar-almulla/Desktop/Prunus_TE_project/INPUT/genomes/20-WGS-PCE.2.0_shortIDs.fasta --species others --curatedlib /home/omar-almulla/Desktop/Prunus_TE_project/INPUT/genomes/Viridiplantae_rep.fa --anno 1 --threads 8
`
**This is the output that I got about the TE LTRs**
-  20-WGS-PCE.2.0_shortIDs.fasta.mod.LTR.raw.fa 
- and others file **but nothing about LTR 3' and 5' sequences.**

**Comment by oushujun** [comment]
Hi, intact LTR information is located at EDTA.raw/LTR/*more.pass.list

Shujun
