### ISSUE TITLE
Error regarding libdrmaa.so.1 during run

### ISSUE THREAD

**Issue by soungalo** [oushujun/EDTA#236]
I installed EDTA using conda, according to the instructions here (tried several options).
I ran EDTA like this:
`EDTA.pl --genome genome.fasta --cds CDS.fasta --anno 1 --threads 30 --force 1`
And got the error:
`OSError: libdrmaa.so.1: cannot open shared object file: No such file or directory`
The full STDOUT and STDERR are attached.
It looks like all the expected files were created, but I'm not sure if the run completed successfully.
I also see other error messages like:
`Thread 12 terminated abnormally: Illegal division by zero`

[EDTA.err.txt](https://github.com/oushujun/EDTA/files/7518785/EDTA.err.txt)
[EDTA.out.txt](https://github.com/oushujun/EDTA/files/7518786/EDTA.out.txt)

**Comment by oushujun** [comment]
Looks like an installation issue. Have you tested with the small file?

Shujun
