### ISSUE TITLE
LOC list HelitronScanner.raw.ext.list is empty, Error while loading sequence

### ISSUE THREAD

**Issue by dongzhang0725** [oushujun/EDTA#237]
Dear shujun,

Thank you for developing this useful software. I encountered a problem when I analysize my genome. My code is: 

```docker run --rm -v $PWD:$PWD -w $PWD oushujun/edta:1.9.5 EDTA.pl --genome hifiasm.purge_nextpolish2_rmcontam.rename.fas --anno 1 --evaluate 1 -t 80 --sensitive 1 > EDTA.log 2>&1```

The error log is:
```Warning: LOC list hifiasm.purge_nextpolish2_rmcontam.rename.fas.mod.HelitronScanner.raw.ext.list is empty.
Warning: LOC list hifiasm.purge_nextpolish2_rmcontam.rename.fas.mod.HelitronScanner.raw.ext.list is empty.

Error: Error while loading sequence
	perl make_bed_with_intact.pl EDTA.intact.fa > EDTA.intact.bed

Sat Nov 13 09:04:23 UTC 2021	Warning: The Helitron result file has 0 bp!

Sat Nov 13 09:04:23 UTC 2021	Execution of EDTA_raw.pl is finished!

ERROR: Raw Helitron results not found in hifiasm.purge_nextpolish2_rmcontam.rename.fas.mod.EDTA.raw/hifiasm.purge_nextpolish2_rmcontam.rename.fas.mod.Helitron.raw.fa
	If you believe the program is working properly, this may be caused by the lack of intact Helitrons in your genome. Consider to use the --force 1 parameter to overwrite this check
```

I also attached the complete log file: [EDTA.log](https://github.com/oushujun/EDTA/files/7532162/EDTA.log)

Am I wrong in any of the procedures?

Thank you for your kindly help,

Dong

**Comment by oushujun** [comment]
Hi Dong,

It could be that your genome does not have Helitrons. You may check this out by listing the files and size in the `EDTA_raw/Helitron/` directory. If `.pairends` files are not empty but the `.filtered.tabout` file is empty, then there is no candidates passing the filtering criteria. IF this is the case, you may use `--force 1` to overcome this issue.

Best,
Shujun

**Comment by dongzhang0725** [comment]
Dear shujun,

Thank you for your reply, I checked the files you specified, it seems both files are empty (except that `.tabout` file has a header), in this case, can I use `--force 1`, or there may be other problems?

Best,
Dong

**Comment by oushujun** [comment]
Yes you may use --force 1 if you think lacking helitrons makes sense in
your genome.

Best,
Shujun

**Comment by dongzhang0725** [comment]
I get it, I will check if lacking helitrons is valid in my genome, thank you for your help.

Best,
Dong

**Comment by oushujun** [comment]
I assume you have tested with the test files and nothing wrong with your clone. - Shujun

**Comment by dongzhang0725** [comment]
Yeah, the test file and my another genome data can run EDTA successfully.
