### ISSUE TITLE
Double ID annotation?

### ISSUE THREAD

**Issue by aderzelle** [oushujun/EDTA#24]
Hello,
not sure if it's EDTA or RepeatMasker, but I ran on the EDTA output
```
RepeatMasker -pa 4 -no_is -norna -nolow -div 40 -lib genome.sixLongest.fa.EDTA.TElib.fa -cutoff 225 -gff genome.FLYE.sixLongest.fa
buildSummary.pl genome.FLYE.sixLongest.fa.out > summary.tbl
```
and some sequences in the output repeat tables have a "doubled" ID like
`TE_00001277_INT-int` while the sequence ID is 
`>TE_00001277_INT#LTR/Gypsy`

Any idea of where the "int" after the "INT" comes from? I concede it seems absolutely benign but I want to be sure it doesn't clue to a bigger problem. 

Thank you

**Comment by oushujun** [comment]
The lower case int is from RepeatMasker. It's slightly annoying but not a
big issue. You may need to remove the extra int if you want an accurare
count of this element.

Best,
Shujun
