### ISSUE TITLE
test EDTA consistency of different runs

### ISSUE THREAD

**Issue by ting-hsuan-chen** [oushujun/EDTA#240]
Hi @oushujun ,

I am working on a plant species that has no standard/curated TE annotation before.
But I would like to test how consistent the EDTA results are in independent runs with the same parameter settings and the same reference genome. So I used the script "lib-test.pl" to compare run1.fa.mod.EDTA.RM.out and run2.fa.mod.EDTA.RM.out.

For LTR, TIR, and Helitron, I got pretty good sensitivity, accuracy, precision, F1, and very low FDR. However, the specificity is quite low.
For LINE and non-LTR, none of these benchmarking values looks good.
So my questions are:
**1. Any suggestion on improving the specificity for LTR, TIR, and Helitron?**
**2. Why the annotation for LINE and non-LTR is so inconsistent in my case and how to improve it?**

**_The script to run EDTA:_**
`EDTA.pl --genome $genomeName --species others --step all --sensitive 1 --anno 1 --evaluate 1 --threads $thread`

**_The script to test consistency:_**
`lib-test.pl -genome $genomeName -std $run1 -tst $run2 -cat $TE`

**_The benchmarking output for LTR:_**
>Genome:                 ref.fa.rand120151
>Standard annotation:    run1.fa.mod.EDTA.RM.out.rand120151
>Testing annotation:     run2.fa.mod.EDTA.RM.out.rand120151
>
>sens=TP/(TP+FN)
>spec=TN/(FP+TN)
>accu=(TP+TN)/(TP+TN+FP+FN)
>prec=TP/(TP+FP)
>FDR=1-prec=FP/(TP+FP)
>F1=2TP/(2TP+FP+FN)
>
>TP: 139278561
>
>FN: 3332936
>
>TN: 109154
>
>FP: 2795682
>
>Sensitivity: 0.976629261524406
>Specificity: 0.0375766480448466
>Accuracy: 0.957883641831464
>Precision: 0.980322386796036
>FDR: 0.0196776132039641
>F1 measure: 0.978472339359183

**_The benchmarking output for LINE:_**
>Genome:                 ref.fa.rand19612
>Standard annotation:    run1.fa.mod.EDTA.RM.out.rand19612
>Testing annotation:     run2.fa.mod.EDTA.RM.out.rand19612
>
>sens=TP/(TP+FN)
>spec=TN/(FP+TN)
>accu=(TP+TN)/(TP+TN+FP+FN)
>prec=TP/(TP+FP)
>FDR=1-prec=FP/(TP+FP)
>F1=2TP/(2TP+FP+FN)
>
>TP: 646324
>
>FN: 371053
>
>TN: 133126
>
>FP: 852104
>
>Sensitivity: 0.635284658489429
>Specificity: 0.135121748221228
>Accuracy: 0.389217654786985
>Precision: 0.431334705437966
>FDR: 0.568665294562034
>F1 measure: 0.51381088756879

Kind regards,
Ting-Hsuan

**Comment by oushujun** [comment]
Sorry just see this thread. Something is wrong with the TN calculation. It should not be this small.

You may not estimate consistency like this anyways. You can use the --evaluation 1 to estimate the annotation consistency within one run.

For SINEs/LINEs' annotation, EDTA has low power. You may search other issues or read the original paper for more details. 

Best,
Shujun

**Comment by ting-hsuan-chen** [comment]
Hi Shujun,

Thanks for your reply. Now I know that I should look at these files: 

> - Annotation inconsistency for simple TEs: $genome.mod.EDTA.TE.fa.stat.redun.sum 
> - Annotation inconsistency for nested TEs: $genome.mod.EDTA.TE.fa.stat.nested.sum 
> - Oveall annotation inconsistency: $genome.mod.EDTA.TE.fa.stat.all.sum

Cheers,
Ting-Hsuan
