### ISSUE TITLE
EDTA annotation step

### ISSUE THREAD

**Issue by elissaralam** [oushujun/EDTA#247]
Hello,

I ran EDTA on a **contig assembly** and obtained a repeat library. I would like to annotate the **scaffolded version** of the same assembly with that repeat library. Based on your code commentary, I can ask EDTA to only annotate a provided genome by specifying **--step anno**. But I am unsure how to provide the custom library with which I want EDTA to annotate the provided genome. I would appreciate your guidance.  Just to clarify, my aim is not to mask the genome. I want to annotate the scaffolded genome with repeats because i would like to perform repeat density analysis in a downstream step. 

Thanks,
Elissar

**Comment by elissaralam** [comment]
I apologize for my question, you can close this issue!

**Comment by oushujun** [comment]
Hi Elissar,

Sorry I missed your issue somehow. If you want to perform a full annotation on your scaffolded genome you will need to rerun EDTA. If you want to perform a homology annotation with the library generated from contigs, you can use Repeatmasker with -lib as the EDTA generated library (lib.fa).

Best,
Shujun
