### ISSUE TITLE
Higher threads, less intact LTR

### ISSUE THREAD

**Issue by baozg** [oushujun/EDTA#248]
Hi, @oushujun 

Accidently, I try to use different thread number to annotate a plant genome (73% repeat based on the EDTA result). I find the intact  LTR number have huge difference. (64 threads: 54k; 32 threads: 47k). Then I use the B73 v5 chr10 to test, it did have same tendcey.  Is there any random step in the `LTR_retriever` ?

|   File                  | -t 64 | -t 32 |
|:-------------------:|-------|-------|
| finder.combine.scn  | 4411  | 4411  |
| harvest.combine.scn | 4328  | 4328  |
| mod.rawLTR.scn      | 8739  | 8739  |
| retriever.all.scn   | 7282  | 7282  |
| pass.list           | 3690  | 3934  |

**Comment by oushujun** [comment]
Hi Zhigui,

Sorry I just saw this message. I have not seen that before. For your plant genome, higher threads result in more LTRs, but the trend is in reverse for your test in B73 chr10. Something is wrong here. I need to double check.

Shujun

**Comment by baozg** [comment]
Sorry for misleading. The intact LTR number will changed in the running of the EDTA. I find when all program finish, its intact LTR number doesn't change much. So I should close the issue.
