### ISSUE TITLE
Dependency error even when creating conda env with EDTA.yml 

### ISSUE THREAD

**Issue by smorzechowski** [oushujun/EDTA#250]
I see many people have had the same error message I received: 

Error: The RMblast engine is not installed in RepeatMasker! 

This is despite installing in the recommended way that freezes all the dependency versions -- 
conda env create -f EDTA.yml  

Why would this dependency error still be occurring?

**Comment by smorzechowski** [comment]
For those who may be interested, it may be due to the fact that I have a version of perl locally installed. I was getting the following error when I tried to access the version of RepeatMasker installed in the conda environment: 

```
(EDTA) [smorzechowski@holy7c16606 ~]$ RepeatMasker --help
/n/home09/smorzechowski/.conda/envs/EDTA/bin/perl: symbol lookup error: /n/home09/smorzechowski/perl5/lib/perl5/x86_64-linux-thread-multi/auto/List/Util/Util.so: undefined symbol: Perl_xs_apiversion_bootcheck
```
But, I found this blog, which had the same issue --
https://www.jianshu.com/p/a90a8a47cc8f

Including the following in my sbatch script appears to have fixed the issue --

```
export PERL5LIB=/
```

**Comment by oushujun** [comment]
Thank you for finding out the issue! I think this will help many others. - Shujun

**Comment by Zhenlisme** [comment]
I got this warning information: "WARNING- Grid computing is not available because DRMAA not configured properly: Could not find drmaa library.  Please specify its full path using the environment variable DRMAA_LIBRARY_PATH". Will this influence the result?

**Comment by HejunLu** [comment]
> I see many people have had the same error message I received:
> 
> Error: The RMblast engine is not installed in RepeatMasker!
> 
> This is despite installing in the recommended way that freezes all the dependency versions -- conda env create -f EDTA.yml
> 
> Why would this dependency error still be occurring?

I meet the same problem with you, when I run several genomes in a bash cycle, the first genome finish with out erro,while from the second the erro comes:
Thu Jun 16 06:27:47 CST 2022    Dependency checking:
Error: The RMblast engine is not installed in RepeatMasker!

**Comment by oushujun** [comment]
Hello @HejunLu,

Did you have the same error on other genomes or if you rerun EDTA on this genome, did you receive the same error?

On a side note, you may want to update EDTA to 2.0. 

Best,
Shujun

**Comment by minutoides** [comment]
I'm having some problems with EDTA, when I run it with test data it gives me an error with Hmmer, that it's installed with mamba install edta, and also I tried to install separately. I remove the environment (EDTA) and tried to install everything again but the error persist.

Thanks in advance.

########################################################
##### Extensive de-novo TE Annotator (EDTA) v2.0.1  ####
##### Shujun Ou (shujun.ou.1@gmail.com)             ####
########################################################



Tue Sep 20 00:57:58 PDT 2022    Dependency checking:
                                All passed!

        A custom library ../database/rice6.9.5.liban is provided via --curatedlib. Please make sure this is a manually curated library but not machine generated.

        A CDS file genome.cds.fa is provided via --cds. Please make sure this is the DNA sequence of coding regions only.

        A BED file is provided via --exclude. Regions specified by this file will be excluded from TE annotation and masking.

Tue Sep 20 00:58:01 PDT 2022    Obtain raw TE libraries using various structure-based programs:
Tue Sep 20 00:58:01 PDT 2022    EDTA_raw: Check dependencies, prepare working directories.

Tue Sep 20 00:58:03 PDT 2022    Start to find LTR candidates.

Tue Sep 20 00:58:03 PDT 2022    Identify LTR retrotransposon candidates from scratch.

Error: hmmsearch is not found in the HMMER path !
awk: fatal: cannot open file `genome.fa.mod.pass.list' for reading (No such file or directory)
Warning: LOC list - is empty.

        perl rename_LTR_skim.pl target_sequence.fa LTR_retriever.defalse


Error: Error while loading sequence
        perl filter_gff3.pl file.gff3 file.list > new.gff3

Tue Sep 20 00:58:13 PDT 2022    Warning: The LTR result file has 0 bp!

Tue Sep 20 00:58:13 PDT 2022    Start to find TIR candidates.

Tue Sep 20 00:58:13 PDT 2022    Identify TIR candidates from scratch.

Species: others

**Comment by oushujun** [comment]
You may want to check which hmmer is in ENV by using ´which hmmsearch´.
Sometimes you need to clear your ENV for example with module purge.

Shujun

**Comment by JiyangChang** [comment]
As this issue is listed on the wiki page, so I think it's worth sharing my problem and solution.

I installed EDTA via `conda env create -f EDTA.yml` and tried to submit my job to compute nodes. However, I always have this `Error: The RMblast engine is not installed in RepeatMasker!`.

As Shujun and others already mentioned in other threads, this is caused by `RepeatMasker error: mdb_env_open: Cannot allocate memory`, which sometimes occurred when the software tries to build the index for the input fasta file.

I add the following line in my script and now it solves this issue for me:
```
export BLASTDB_LMDB_MAP_SIZE=100000000
```

Hope this could help.

**Comment by oushujun** [comment]
@JiyangChang Thank you for your suggestion! I have updated the [wiki](https://github.com/oushujun/EDTA/wiki/Installations,-builds,-and-tests-Q&A) to include your solution. Thanks!

Shujun
