### ISSUE TITLE
The step of ProcessRepeats cost long time

### ISSUE THREAD

**Issue by zhangzhiyangcs** [oushujun/EDTA#253]
Hi,
    When I run the EDTA pipeline by singularity. I stagnate at the step of ProcessRepeats for several days. The command is "perl /opt/conda/share/RepeatMasker/ProcessRepeats -lib genome_chr.fasta.mod.EDTA.TElib.fa -orifile genome_chr.fasta.mod -maskSource genome_chr.fasta.mod genome_chr.fasta.mod.cat.gz". My genome size is about 900Mb, but the genome_chr.fasta.mod.cat.gz file is about 3.7Gb.  While genome_chr.fasta.mod.EDTA.TElib.fa and genome_chr.fasta.mod files are 7.0 Mb and 940 Mb repectively. Is there any wrong?  Do you have any advice to accelerate it.
Thanks

**Comment by oushujun** [comment]
Hi, it should not take this long but it happens. Please just wait. There is
nothing I can do about it. You may want to start a new RepearMasker test
With these files to figure it out.

Best,
Shujun

**Comment by zhangzhiyangcs** [comment]
Thanks your advise, I have start a new test for these files. Once I have the results, I'll tell you.

**Comment by zhangzhiyangcs** [comment]
Happy Spring Festival, I get my results after 5 days. The total interspersed repeat elements is about 70% and the CACTA repeat elements is about 24%.
Thanks a lot
