### ISSUE TITLE
Differences in masking %. RepeatMasker vs EDTA using repeat library produced by EDTA.

### ISSUE THREAD

**Issue by d00bin** [oushujun/EDTA#254]
Hello, Shujun! 

I successfully ran EDTA on a genome with a _sensitive_ setting. 
In the log file EDTA printed:

```
TE annotation using the EDTA library has finished! Check out:
Whole-genome TE annotation (total TE: 16.73%): some_species.fasta.mod.EDTA.TEanno.gff3

Low-threshold TE masking for MAKER gene annotation (masked: 1.00%): some_species.fasta.mod.MAKER.masked
```

I thought that 1% is a bit too low, so I decided to re-run RepeatMasker with the library produced by EDTA.
I used _-xsmall -nolow_ options to later use the soft-masked genome sequence in BRAKER2.

For some reason though RepeatMasker masked 24.43 % this time. 

What is the reason for that? Should I be worried about the output?

**Comment by d00bin** [comment]
>Did you run through the unfinished RepeatModeler run? How Did you maje it?

Actually, I just re-ran the final step with --step final option and it worked this time. 

>For masking differences, you may search other issues for similar
discussions.

I can't really find related topics in the issues. I saw some where people wonder about the differences between RepeatMasker with RM libraries and EDTA de-novo.

But I first created the repeat library with EDTA, and then used it to mask the genome. 
For some reason I get different results (16.73% from EDTA sum vs 24.43 %  from RepeatMasker out), even though I assumed that EDTA used RepeatMasker to mask the genome in the end. Am I correct about this assumption? 

I just would like to have a general statistics about repeat content and I don't know which number to trust 16.73% or  24.43 %.

**Comment by oushujun** [comment]
Hello @d00bin,

Sorry for the delay. First of all, `Low-threshold TE masking for MAKER gene annotation (masked: 1.00%): some_species.fasta.mod.MAKER.masked` this information says the file `some_species.fasta.mod.MAKER.masked` is for MAKER gene annotation, not representing the actual TE content. Is it confusing?

If everything ran without error, the EDTA sum file represents what the program believes the TE content of the genome.

>16.73% from EDTA sum vs 24.43 % from RepeatMasker out

This does represent some significant differences. Can you paste here the Repeatmasker command you were using?

Shujun

**Comment by oushujun** [comment]
@d00bin do these issues resolved?

**Comment by d00bin** [comment]
@oushujun Dear Shujun, 
I'm terribly sorry for such a delayed response!

Nope the issue is still there.


The command I used for RepeatMasker is:

```
RepeatMasker \
-a -gff -pa 32 -u \
-dir final_RepeatMasker_out \
-xsmall \
-nolow \
-lib /path/to/EDTA/library.fasta.mod.EDTA.TElib.fa \
genome_chromosomelevel.fasta
```



>Low-threshold TE masking for MAKER gene annotation (masked: 1.00%): some_species.fasta.mod.MAKER.masked this information says the file some_species.fasta.mod.MAKER.masked is for MAKER gene annotation, not representing the actual TE content. Is it confusing?

And this I understand, yes.

**Comment by oushujun** [comment]
Is this a non-plant?

**Comment by d00bin** [comment]
>Is this a non-plant?

Yes. It's a teleost fish. 
There is a genome of a sister species, from the same genus, published and the repeat content is ~23%. 
Also, previously I used [this](https://github.com/uio-cels/Repeats) workflow to produce a repeat library for my genome, and it ended up around ~23%. 
But EDTA is a much more elegant solution than what I used before.

**Comment by oushujun** [comment]
That make sense to me. If EDTA produced no error, then it's running as
expected.

**Comment by d00bin** [comment]
>That make sense to me. If EDTA produced no error, then it's running as
expected.

So this difference between 16.73% from EDTA sum vs 24.43 % from RepeatMasker out is due to my repeat masker settings? 
And if yes, then what should I consider as "true" TE content of the genome?

**Comment by oushujun** [comment]
You may want to manually collect some SINE LINE sequences and give it to
EDTA. These Could be missed.

Shujun
