### ISSUE TITLE
the threads for RepeatModeler updated version should be divided by 4

### ISSUE THREAD

**Issue by tinyhys** [oushujun/EDTA#256]
Hi dear developers,
I noticed the unusual CPU occupancy rate when using --sensitive 1. 
The updated version of RepeatModeler uses 4 threads per parallel job. So maybe there should be a small modification on the number of $threads.

![image](https://user-images.githubusercontent.com/37066354/155507305-16cb0b73-bd64-42a9-b28f-739770799a9a.png)

![image](https://user-images.githubusercontent.com/37066354/155507367-8fd6d24c-0162-4bc4-83d1-2ac5d16232ba.png)

**Comment by oushujun** [comment]
Hi @tinyhys,

Yes, I noticed that previously. You may need to compile RepeatModeler or RMblast with custom settings to avoid potential overutilization of CPUs, or simply change the `-pa` setting in your version of EDTA. So far I have not received any overutilization reports. Please let me know if your job scheduler reports any issues.

Shujun

**Comment by tinyhys** [comment]
Thanks for your reply, the issue is that in some steps of RepeatModeler, the cpu occupation may reach 200% or even higher which should be about 70% if usuall when running the command on a 56 threads slot with -t 56. I am not confident to edit the script so I run the command twice as this way and it looks fine but more time consuming.

```
edta --genome geno.fa -t 56
edta --genome geno.fa -t 14 --sensitive 1
```

**Comment by oushujun** [comment]
My above command stands. Again if your job scheduler reports any issues, please let me know. Or ask your HPC admin to recompile RMblast for you. - Shujun

**Comment by tinyhys** [comment]
Hi dear teacher,

Thanks for your reply! 

The RepeatMasker version 4.1.2-p1 and RepeatModeler version 2.0.2 used by me are both employing 4 cores per rmblast job, as description in the help information.  So I think it is just a new feature of them and not a strange issue. Maybe the threads used in RepeatModeler in the script may be changed to an integer which can be conducted by dividing the original threads by 4 to feed these software of specific version. 

Best,
Tinyhys.

**Comment by oushujun** [comment]
Thanks again for the catch. I have fixed this issue.
