### ISSUE TITLE
Running EDTA on the whole genome and split fasta files from the same genome gave different results

### ISSUE THREAD

**Issue by joeplanta** [oushujun/EDTA#258]
Hi Shujun,

We ran EDTA on the whole genome and then split this genome into several fasta files and ran EDTA on these individual split files. We got significantly more TE counts from the split files (after adding all the TE counts from these individual split files) than the analysis with the whole genome. As our issue might be similar to issue #246, where EDTA randomly subsamples the input sequence(s) to generate the library for analysis, are we over-inflating the TE counts by running EDTA on split fasta files from the whole genome sequence? Which results should we therefore use - that from the whole genome analysis or from the split files generated from this whole genome sequence?

Thank you.

-Jose

**Comment by oushujun** [comment]
Hi Jose,

It's not recommended to split the genome If EDTA can be executed within
reasonable time. You will have inflated false discovery by doing so. The
more you split, The higher The FDR. If you have to split, you should follow
the pan-genome protocol to reduce FDR.

Shujun

**Comment by joeplanta** [comment]
Thanks, Shujun!

-Jose
