### ISSUE TITLE
Illegal division by zero in flanking_filter.pl during EDTA.pl

### ISSUE THREAD

**Issue by sjteresi** [oushujun/EDTA#259]
Hello Shujun,

I am running EDTA 2.0.0 and performed the small test with no issues.  I did some digging and this issue seems to be related to Issue #150.

The only difference I can determine here is that **all** of my threads are terminating abnormally. Do you have any suggestions, or is this something I should not worry about?

Here is the log file (for reference I am using 24 threads):
[log.txt](https://github.com/oushujun/EDTA/files/8208336/log.txt)
Note, the program doesn't crash at all, it continues to run, I just provided a shortened version of the log file.

Thanks in advance for your time and consideration!
-- Scott Teresi

**Comment by oushujun** [comment]
Hi Scott,

This is strange behavior. Usually if you pass the test you should be fine with your genome. From your log, the LTR part is done without errors suggesting the code is OK. You may want to remove the TIR folder in the EDTA.raw folder and retry. Or you can try the arabidopsis genome and see if it still behaves like that.

Best,
Shujun

**Comment by oushujun** [comment]
Do you have a lot of `Illegal division by zero` errors or just the ones you shared in the log file? Also, do you have the TIR output with a non-empty list of candidates?

**Comment by sjteresi** [comment]
What is the suffix of the TIR output file? Is it "'GenomeName'.fasta.mod.TIR"? If so, it seems to have plenty of entries. In regards to the other files in the TIR directory of the EDTA raw directory, there doesn't seem to be anything anomalous going on there either. No files that seem out of the ordinary.

I will try the Arabidopsis genome shortly. Currently trying a small diploid strawberry genome as a sanity check. I forgot to add, this problem I am having is with multiple blueberry genomes, each running independently of course.

In regards to the `illegal division by zero errors`, so far it seems to be limited to the phase: `Identify TIR candidates from scratch`. I have not seen it in other pipeline stages but I must admit I have not fully run the pipeline to completion yet because I was so caught up trying to debug. So far LTR and Helitron stages have been fine.

**Comment by oushujun** [comment]
You don't have to try on Arabidopsis, just something not this genome and see if EDTA runs normally. The small strawberry genomes sounds good.

If you are getting normal outputs, that suggest it's a glitch similar to #150. Do you see just a few dozens of such errors or a few thousands? Do you see this error concurently happend on your multiple blueberry genomes?

**Comment by sjteresi** [comment]
I see an illegal division by zero error for each thread I use on each genome. There are no other errors (no. errors == no. threads). The only exception to this is that on **one** blueberry genome (called "Draper") only **one** thread fails, as opposed to all (~20+).

**Comment by oushujun** [comment]
Hi Scott,

This behavior does look like a bug in the code. Can you locate this file `EDTA/util/flanking_filter.pl` and modify it as follows?

Yours should be located here: 
`/mnt/ufs18/rs-004/edgerpat_lab/EDTA/util/flanking_filter.pl`

Edit the file, scroll down to line 209, and replace the last block of code with the following:

```
# determine if the given sequence is simple repeat
sub count_base(){
        my $seq = lc $_[0];
        my $repeat = "false";
        $seq =~ s/[nx]+//gi;
        if (length $seq > 0){
                my @base = ('a', 't', 'c', 'g');
                my @count = map { $_ = () = ($seq =~ /$_/gi) } @base; #base count
                @count = (sort { $b<=>$a } @count); #reverse sort
                my $dominant_base = ($count[0] + $count[1])/length $seq;
                $repeat = "true" if $dominant_base >= 0.85;
                } else {
                $repeat = "true";
                }
        return $repeat;
        }
``` 

Please try the updated code on your genome and let me know if this works. Thank you.

Shujun

**Comment by sjteresi** [comment]
Hi Shujun,
The above solution works! Thank you so much! Would you like for me to create a pull request and reference this issue?

**Comment by oushujun** [comment]
Hi Scott, that's good news! No worries about the code update. I have had it on my record. The new changes will be reflected in the next update. Thanks for helping to debug!

Shujun
