### ISSUE TITLE
Use of unitialized value $chr_pre in has element call_seq_by_list.pl line 87

### ISSUE THREAD

**Issue by sjteresi** [oushujun/EDTA#261]
Hello Shujun,

I was running EDTA v2.0.0 on a small cranberry genome and got the following error:
`Use of uninitialized value $chr_pre in hash element at /mnt/home/teresisc/anaconda3/envs/EDTA/share/LTR_retriever/bin/call_seq_by_list.pl line 87.`

The pipeline does **not** fail and continues to run. I looked for similar issues in your repo and only ever found this error occurring in the context of something else (usually it seemed like this error was a by-product of some bigger error). The small genome check works just fine and so does the dependency check. I also would like to note that this has not occurred for the other 3 cranberry genomes I am running, and has not occurred for 8 other blueberry genomes that are running. 

Is this something I should be concerned about, or should I just let it ride? I can provide you with my input files if desired.

Thank you very much for your time and consideration!

Sincerely,
Scott Teresi

**Comment by oushujun** [comment]
Hi Scott,

You may Check the pass.list file in the raw/LTR folder. If the line count
is similar to those of other cranberry genomes, that should be fine. I will
further look into the code and see if there's any big issues.

Shujun
