### ISSUE TITLE
EDTA run so fast

### ISSUE THREAD

**Issue by Xinxin0314** [oushujun/EDTA#262]
Hi @oushujun ,
    I run two soybean genomes (about 900-1000Mb) by edta. Using genome A run about 2 days only, and another（genome B） run 9 days about. And i run genome B in another server using only two days too. The  resulting file size varies slightly. And there are no erro.
    First i think maybe i used the different EDTA.pl, because one is ~/miniconda3/envs/edta/bin/EDTA.pl, and one is ~/te/EDTA/EDTA.pl. Subsequently, i run genome A use another EDTA.pl. But it took only 2 days about too . 
    Everyone run this pipline seems take many days, but i only use so few days. Now i am confused...
    ps: The types of resulting fies are same.

    Thank you for taking the time. I am looking forward to your reply~

Best wishes,
Xinxin

**Comment by Xinxin0314** [comment]
Hi Shujun,
    Thanks for your reply~
    I have another question. When i run pipeline,  I forgot to add the  parameter “--anno 1”. If I want get the result file "genome.mod.EDTA.TEanno.sum", do I have to re-run it?

Best,
Xinxin

**Comment by oushujun** [comment]
> Hi Shujun, Thanks for your reply~ I have another question. When i run pipeline, I forgot to add the parameter “--anno 1”. If I want get the result file "genome.mod.EDTA.TEanno.sum", do I have to re-run it?
> 
> Best, Xinxin

No, just run the command again with `--anno 1` added to it. Please read the manual and Q&A.

Shujun
