### ISSUE TITLE
TE classification in repeat_region

### ISSUE THREAD

**Issue by yueqitaoo** [oushujun/EDTA#264]
Dear Shujun,

Thanks for excellent tool!

I have following questions when I try to classify my TE dataset and notice part of repeat_region also classify as TE:
1. What's different between unknown and unassigned?
2. If repeat_region shows TE classification (e.g. Classification=RC/Helitron or Classification=DNA/EnSpm), can I count them as Helitron / EnSpm?
3. how can I classify "target_site_duplication"?
4. For example "Name=AT1TE49885_ATREP18;Classification=DNA" in repeat_region, is this also TE? Do I need to count in?

Many thanks!

Best,
Yueqi

**Comment by oushujun** [comment]
Hi Yueqi,

Please read more info in the [Q&A](https://github.com/oushujun/EDTA/wiki/Making-sense-of-EDTA-usage-and-outputs---Q&A).

Shujun
