### ISSUE TITLE
ERROR: awk: fatal: cannot open file `genome.fna.mod.pass.list' for reading (No such file or directory)

### ISSUE THREAD

**Issue by MoradMMokhtar** [oushujun/EDTA#265]
I run EDTA_raw.pl for identifying LTR using numbers of plant genomes. some of these genomes get good results using EDTA_raw.pl. However, others can not get it. with the error as following: I have tried lots of times.

Sun Apr 17 23:45:51 +00 2022	EDTA_raw: Check dependencies, prepare working directories.
Sun Apr 17 23:45:52 +00 2022	Start to find LTR candidates.
Sun Apr 17 23:45:52 +00 2022	Identify LTR retrotransposon candidates from scratch.

Warning: [blastx] Number of threads was reduced to 8 to match the number of available CPUs
Warning: [blastx] Number of threads was reduced to 8 to match the number of available CPUs
Warning: [blastx] Number of threads was reduced to 8 to match the number of available CPUs
awk: fatal: cannot open file `genome.fna.mod.pass.list' for reading (No such file or directory)
Warning: LOC list - is empty.
	perl rename_LTR_skim.pl target_sequence.fa LTR_retriever.defalse
Error: Error while loading sequence
	perl filter_gff3.pl file.gff3 file.list > new.gff3
Sun Apr 17 23:57:07 +00 2022	Warning: The LTR result file has 0 bp!
Sun Apr 17 23:57:07 +00 2022	Execution of EDTA_raw.pl is finished!

Thanks,

**Comment by oushujun** [comment]
These genomes may not have intact LTR elements assembled. You may Check the
defalse file.

Shujun

**Comment by MoradMMokhtar** [comment]
Dear Shujun,
Thanks for your response, below is an example of defalse data
JAE010000001:694441..699694	false	motif:TGCA	TSD:AGTCA	694436..694440	699695..699699	IN:694607..699532	0.9765	?	unknown	NA	919480
	Adjust: NO	lLTR: NA	rLTR: NA
	Alignment regions: 1945, 2118, 5085, 5254
	LTR coordinates: 694441, 694606, 699533, 699694
	TSD-LTR overlap: 0
	Boundary missing: 0
Thanks
Morad

**Comment by MoradMMokhtar** [comment]
Also, I tried EDTA.pl with --force 1 with the same error as the following:
Mon Apr 18 01:38:44 +00 2022	Dependency checking:
				All passed!
Mon Apr 18 01:38:46 +00 2022	Obtain raw TE libraries using various structure-based programs: 
Mon Apr 18 01:38:46 +00 2022	EDTA_raw: Check dependencies, prepare working directories.
Mon Apr 18 01:38:47 +00 2022	Start to find LTR candidates.
Mon Apr 18 01:38:47 +00 2022	Identify LTR retrotransposon candidates from scratch.
Warning: [blastx] Number of threads was reduced to 8 to match the number of available CPUs
Warning: [blastx] Number of threads was reduced to 8 to match the number of available CPUs
Warning: [blastx] Number of threads was reduced to 8 to match the number of available CPUs
awk: fatal: cannot open file `genome2.fna.mod.pass.list' for reading (No such file or directory)
Warning: LOC list - is empty.
	perl rename_LTR_skim.pl target_sequence.fa LTR_retriever.defalse
Error: Error while loading sequence
	perl filter_gff3.pl file.gff3 file.list > new.gff3
Mon Apr 18 01:50:11 +00 2022	Warning: The LTR result file has 0 bp!
Mon Apr 18 01:50:11 +00 2022	Start to find TIR candidates.
Mon Apr 8 01:50:11 +00 2022	Identify TIR candidates from scratch.
Regards

**Comment by oushujun** [comment]
If you grep the second column of the defalse file, do you see all "false" and no "pass"? ie., `awk '{print $2}' defalse.file | sort | uniq -c`

**Comment by MoradMMokhtar** [comment]
Dear Shujun,
Thanks for your response and efforts, yes I get your point 
Regards
Morad Mokhtar
