### ISSUE TITLE
Error: gt is not found in the genometools path ./!

### ISSUE THREAD

**Issue by AMartinsJr** [oushujun/EDTA#266]
Dear all,
I'm trying to run EDTA to construct a library from a mammal genome and when I tryied to run it as a test as suggested in the EDTA guide, I received this error:
Error: gt is not found in the genometools path ./!

My command line to run it was: perl EDTA.pl --genome test/genome.fa --cds test/genome.cds.fa --curatedlib database/rice6.9.5.liban --exclude test/genome.exclude.bed --overwrite 1 --sensitive 1 --anno 1 --evaluate 1 --threads 10

Somebody knows how can I fix it?

Best regards,

Antonio Martins-Junior

**Comment by oushujun** [comment]
Hi Antonio,

Please reinstall and test with the small data in EDTA/test/.

Shujun

**Comment by oushujun** [comment]
#153 #155
