### ISSUE TITLE
empty consensi.fa file

### ISSUE THREAD

**Issue by JonEilers** [oushujun/EDTA#269]
Hi,
I installed EDTA using conda and ran it on a sea cucumber genome assembly. When it finished the repeatmodeler step it returned the below output
```bash
Use RepeatModeler to identify any remaining TEs that are missed by structure-based methods.

cat: 'RM_*/consensi.fa': No such file or directory
				RepeatModeler is finished, but no consensi.fa files found.
```

a little further poking around turned up this in the repeatmodeler logs
```bash
Can't locate File/Which.pm in @INC (you may need to install the File::Which module) (@INC contains: /home/jon/anaconda3/envs/edta/lib/perl5/5.32/site_perl /home/jon/anaconda3/envs/edta/lib/perl5/site_perl /home/jon/anaconda3/envs/edta/lib/perl5/5.32/vendor_perl /home/jon/anaconda3/envs/edta/lib/perl5/vendor_perl /home/jon/anaconda3/envs/edta/lib/perl5/5.32/core_perl /home/jon/anaconda3/envs/edta/lib/perl5/core_perl .) at /home/jon/anaconda3/envs/edta/bin/filter-stage-1.prl line 14.
BEGIN failed--compilation aborted at /home/jon/anaconda3/envs/edta/bin/filter-stage-1.prl line 14.
```

Thoughts/suggestions? Is there a specific perl module I should try installing into the conda environment? A list of everything installed in the conda edta environment can be found [here](https://github.com/JonEilers/error_logs/blob/main/edta_env_list)

**Comment by oushujun** [comment]
Hello,

I am not sure. Can you run an independent RepeatModeler using the EDTA env on your unmasked genome?

Shujun

**Comment by oushujun** [comment]
@JonEilers Did you find out why? - Shujun

**Comment by niconm89** [comment]
Hi @oushujun , I hava the same issue with the genome of the moth Galleria mellonella, which is already available at https://www.ncbi.nlm.nih.gov/data-hub/genome/GCF_003640425.2/.

I have tried several things, from reinstalling EDTA to shorten the contigs/scaffolds names. Do you have any recommendations on this?

Nicolás

**Comment by oushujun** [comment]
Hi Nicolá, 

I am not sure the cause of this error. What EDTA version are you using?
