### ISSUE TITLE
Is it necessary for --anno 1 for pangenome in the initial annotation? 

### ISSUE THREAD

**Issue by jia-wu-feng** [oushujun/EDTA#270]
https://github.com/HuffordLab/NAM-genomes/tree/master/te-annotation

Generate de novo TE library for each genome and perform initial annotation.

Is it necessary for --anno 1 for this step?

**Comment by jia-wu-feng** [comment]
Hi shujun,

When closed --anno, I also got the library in *.mod.EDTA.final
I don't have --curatedlib, so I just use this software results. 

for *.EDTA.TElib.fa, is it different? 


Thanks.

**Comment by oushujun** [comment]
Hi Jia-Wu,

Not sure I follow your question. You do not need to provide --curadedlib, but when you provide curated TE sequences, it will improve the annotation and also harness previous work.

Shujun

**Comment by jia-wu-feng** [comment]
Hi, shujun,

I am sorry for my expression.

My command:
EDTA.pl --genome FB19_011_3_pseudomolecules_v6_hap1.fasta.1.contig.fa -t 28 --cds HBULBOSUM.r1.pgsb.Dec2021.high.cds.fa --anno 1

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/24247803/169488610-60d9ebb9-8106-4ac7-96e2-e9f2db5ec146.png">
The results of EDTA

When I don't use --curatedlib, EDTA doesn't generate the file  $genome.mod.EDTA.TElib.novel.fa. 

In the pangenome pipeline, I use  FB19_011_3_pseudomolecules_v6_hap1.fasta.1.contig.fa.mod.EDTA.TElib.fa file to do next step.  Is it right?

When I use --anno 0, I think it also generate the file FB19_011_3_pseudomolecules_v6_hap1.fasta.1.contig.fa.mod.EDTA.TElib.fa.

Do you think FB19_011_3_pseudomolecules_v6_hap1.fasta.1.contig.fa.mod.EDTA.TElib.fa is same.

I think if I use --anno 0, I can save time in the first step. Is it right?

Thanks.

**Comment by oushujun** [comment]
hello,

Sorry for missing this thread. `-anno 1` is required because the initial annotation is needed for filtering of individual libraries.

Thanks,
Shujun
