### ISSUE TITLE
calculate the LTR insertion time by EDTA

### ISSUE THREAD

**Issue by tinyfallen** [oushujun/EDTA#271]
Hi dear developer,
The LTR_retriever accepts the -u parameter for LTR insertion time calculation while the EDTA not. The user have to recalculate by themselves. For my own, I'm afraid I may make mistakes in the calculation steps. So could you please do a favor to add the -u parameter to EDTA in the next update?
Thanks a lot !

**Comment by oushujun** [comment]
Hello @tinyfallen,

This is a good suggestion. I will add -u in the next release.

Shujun

**Comment by Chriswinefield** [comment]
Hi Shujun,
Just related to this I was wondering if the EDA output could be used to feed back into LTR_retriever with the -u flag to generate the insertion time calculation, or whether there is a suitable intermediate output file that we could use.

Like @tinyfallen having this flag in EDTA would be fantastic - cant wait for the next release :)

Many thanks Chris

**Comment by oushujun** [comment]
HI Chris,

Thank you for reminding me. Yes, this is on my to-do list and I will try to get it done soon.

Best,
Shujun

**Comment by Chriswinefield** [comment]
Thanks Shujun,

Looking forward to the update in due course. In the meantime Is there a possibility of using one of the EDTA intermediate files to pop into LTR-retriever or would I be best just running the LTR-retriever pipeline independantly?

Kind Regards
Chris

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by oushujun** [comment]
Hi Chris,

You can run EDTA_raw.pl with the `--type ltr` parameter. Then essentially you will be just running LTR_retriever. You may also use the *scn files located in the `*raw/LTR/` directory to run LTR_retriever with `-inharvest`.

Shujun

**Comment by oushujun** [comment]
This parameter (`--u`) is added to the latest repo and release. Please allow a couple of days to reflect on the conda recepie. Please let me know if you have more questions.

**Comment by tinyfallen** [comment]
> This parameter (`--u`) is added to the latest repo and release. Please allow a couple of days to reflect on the conda recepie. Please let me know if you have more questions.

Dear teacher,

That's so fantastic!

Actually, I do have met some problems about the classification of TEs recently.

I found almost half of the final library labelled Unknown which seemed to come from the RepeatModeler steps. So I separately fed the lib to TEsorter and deepTE to perform classification, in which some sequence's classification may be contradictory with each other or the original result of EDTA.

Following comes my questions:

1. Is it necessary to further classify the unknowns?

2. The RepeatMasker's out file contains many overlaps between repeats in different repeat types. I found the EDTA's **-anno** result have a consensus number between the total and the sum of all types' percentages. Could you please tell me how does EDTA deal with the overlaps, or criteria to  determine the overlapped genome sequence's classification destiny?

Maybe I should open a new issue to consult the questions, or you could just give me some brief suggestions, thanks!

Best~

**Comment by oushujun** [comment]
Hi @tinyfallen,

Thank you for your suggestions. I have added the following Q&As to the wiki: https://github.com/oushujun/EDTA/wiki/Making-sense-of-EDTA-usage-and-outputs---Q&A
What's the difference between different GFF files?
How to summarize TE annotation in my genome?

For unknown TEs, it's always recommended to classify them as much and accurately as possible, but this is challenging. You may use TEsorter, deepTE, or others to do so, and use `--curatedlib` to provide the updated library. Always keep in mind, that there will be misclassification. 

Best,
Shujun

**Comment by tinyfallen** [comment]
Many thanks dear teacher!

Best~
