### ISSUE TITLE
Thank you Prof, Hello @HejunLu,

### ISSUE THREAD

**Issue by HejunLu** [oushujun/EDTA#274]
Hello @HejunLu,

Did you have the same error on other genomes or if you rerun EDTA on this genome, did you receive the same error?

On a side note, you may want to update EDTA to 2.0. 

Best,
Shujun

_Originally posted by @oushujun in https://github.com/oushujun/EDTA/issues/250#issuecomment-1167784865_

That err does not happen again, it should due to my reset on the environment when the shell cycle is running .

Thanks a lot, best regards.

**Comment by oushujun** [comment]
Thanks for your update.

Best,
Shujun
