### ISSUE TITLE
Can EDTA produce the non-redundant and matched gfffile of genome.mod.EDTA.TElib.fa?

### ISSUE THREAD

**Issue by 2eYu** [oushujun/EDTA#275]
Hi, Mr. Ou

I used following command: 
perl EDTA.pl --genome HFTH1.all.chr.fa  --sensitive 1  --evaluate 1 -t 10
Then I got HFTH1.all.chr.fa.mod.EDTA.TElib.fa, HFTH1.all.chr.fa.mod.EDTA.intact.gff3 and other files. In order to get the location information of each TEs in HFTH1.all.chr.fa.mod.EDTA.TElib.fa, I looked up HFTH1.all.chr.fa.mod.EDTA.intact.gff3 and other files, however, I find it's hard for me to match every HFTH1.all.chr.fa.mod.EDTA.TElib.fa TEs with TEs in  HFTH1.all.chr.fa.mod.EDTA.intact.gff3, consequently, I can't get the location information of each TE in HFTH1.all.chr.fa.mod.EDTA.TElib.fa. So, could you give me some suggestion to get the location information(like gff3 format file) of each TE in TElib？

Sincerely,
Ze

**Comment by oushujun** [comment]
Hi Ze,

The `HFTH1.all.chr.fa.mod.EDTA.TElib.fa` is a collection of non-redundant sequences derived from TEs in your genome. Some of these sequences are processed and not the original sequence any more, and thus difficult to find their exact location. Do you have a particular reason of doing so?

Best,
Shujun

**Comment by 2eYu** [comment]
Hi, Mr. Ou

Thanks for your quick reply!!!
The reason why I want to get the exact location of TEs in TElib is that I want to use MCScanX to seek synteny of TEs and some genes. MCScanX requires TE's bed file and their fasta file. So, do you think this idea will work?

Best,
Ze

**Comment by oushujun** [comment]
Hi Ze,

Based on your description you should use the whole-genome annotation, which is the TEanno.gff3 file.

Best,
Shujun
