### ISSUE TITLE
ERROR: blastn is not exist in the BLAST+ path 

### ISSUE THREAD

**Issue by ericadinatale** [oushujun/EDTA#277]
Hello!

I am running the cleanup_nested.pl as following:
perl cleanup_nested.pl -in file.fa -blastplus /path to blast conda environment

But I have this error:
ERROR: blastn is not exist in the BLAST+ path 

Do you have any advice? I am sure blastn is there :)

Cheers!
Erica

**Comment by oushujun** [comment]
Hello Erica,

The code is expecting blastn accessible from $ENV:
```
$blastplus=`which blastn 2>/dev/null` if $blastplus eq '';
$blastplus=~s/blastn\n//;
die "ERROR: blastn is not exist in the BLAST+ path $blastplus!\n" unless -X "${blastplus}blastn";
```
Please double check.

Best,
Shujun
