### ISSUE TITLE
A question about difference of repeat rate in EDTA results !

### ISSUE THREAD

**Issue by YuChrming** [oushujun/EDTA#282]
Dear Author!
     It is really a nice pipline that save much time.
     I successfully ran EDTA pipline and got results . Though I know the second one(`*mod.MAKER.masked`) is used for Maker to annotate, but I have a question that which rate should I show in publication and how to explain the difference ?
Thans and expect a reply!

![1658391949051](https://user-images.githubusercontent.com/92568144/180167253-7acd89e1-c947-4f83-9e7b-9ad15c37c1b6.jpg)

**Comment by oushujun** [comment]
Hello,

Thank you for using EDTA. The readme has the information you are looking for: https://github.com/oushujun/EDTA#outputs. Let me know if you have more questions.

Best,
Shujun
