### ISSUE TITLE
Header reformatting fails

### ISSUE THREAD

**Issue by mptrsen** [oushujun/EDTA#283]
Header reformatting fails on a genome where the sequences are named sequentially, with sub-scaffolds such as:

```
scaffold_1
scaffold_2
scaffold_3
scaffold_4_3
scaffold_4_2
scaffold_4_1
scaffold_5
scaffold_6
scaffold_7_2
scaffold_7_1
[...]
scaffold_150_2
scaffold_150_1
scaffold_151
scaffold_152_3
scaffold_152_2
scaffold_152_1
[...]
```

The second round of reformatting only considers numbers in `\$_=">\$1" if /([0-9]+)/` ([line 329 of EDTA.pl](https://github.com/oushujun/EDTA/blob/020b8cc45ab74b9f27ebf0d9752c7a8e03b311d8/EDTA.pl#L329)) and produces duplicates for these subscaffolds.

I suggest to rename sequences with ascending numbers and create a dictionary (hash in Perl) that maps these numbers to the original names.

Out of interest: Why is it necessary to reformat the headers in the first place? Which program can not deal with headers longer than 13 characters? Would it be an option to increase this maximum?

**Comment by mptrsen** [comment]
Ok, thank you. Since it was not phrased as a requirement in the Readme and EDTA does try to shorten the headers, I paid the header length no further consideration until I ran into this issue. With pre-shortened headers, my dataset runs through fine. It's unfortunate that RepeatMasker can not deal with long headers, but that's the way it is.

**Comment by arslan9732** [comment]
Use [seqtk](https://github.com/lh3/seqtk) to replace headers:

```
seqtk rename genome_raw.fa seq | sed -r 's/^(>\S+)\s.*/\1/' >genome.fa
```
