### ISSUE TITLE
About repeat elements in the results of EDTA!

### ISSUE THREAD

**Issue by sunnycqcn** [oushujun/EDTA#29]
Hello,
I tried a small dataset and got the results as following:
Confusion matrix of BL06.R11.pilon.fasta.EDTA.TE.fa.stat for the all category
DNA/DTC DNA/DTH DNA/DTM LTR/Copia       LTR/unknown     MITE/DTM        Misclas_rate
DNA/DTC 7       0       0       0       0       0       0.0000
DNA/DTH 0       1163    1       0       0       0       0.0009
DNA/DTM 0       0       7936    0       3       1       0.0005
LTR/Copia       0       0       0       259     0       0       0.0000
LTR/unknown     1       1       4       0       25193   1       0.0003
MITE/DTM        0       0       2       0       0       168     0.0118
So my question is that EDTA can analyze the repeat elments, such as  AT-rich, GC-rich, short repeat elments, like (AT)n.
Thanks,
Fuyou

**Comment by oushujun** [comment]
Dear Fuyou,

You must be using a very standardized dataset. Your results are super good! It's even higher than the curated library (0.1%-2%).
To answer your question, no EDTA does not have the functionality to identify low complexity sequences or tandem repeats. You may use RepeatMasker to do so.

Best,
Shujun

**Comment by sunnycqcn** [comment]
Thanks.
Fuyou
