### ISSUE TITLE
The evaluation step takes a long time

### ISSUE THREAD

**Issue by LandiMi2** [oushujun/EDTA#290]
Hey, @oushujun I started running EDTA 13days ago. 

Now running "Evaluate the level of inconsistency for whole-genome TE annotation (slow step):"  this step. My genome is around 700Mb, is this normal? should I be patient enough?

**Comment by oushujun** [comment]
Hi @LandiMi2,

Yes, the evaluation step is VERY slow, but the annotation is done - so you can ignore this step and just let it finish. This step won't change any annotation of your genome, but just give you an idea of how good/bad it is.

Shujun

**Comment by LandiMi2** [comment]
oh, thanks @oushujun !
