### ISSUE TITLE
About the files *.divsum and *.sum

### ISSUE THREAD

**Issue by luisafmc** [oushujun/EDTA#295]
Hi, thank you so much for the development of the EDTA pipeline. It became a very useful tool for me and my collages.
I just want to ask if the differences between the files *.divsum and *.sum. I have executed the EDTA pipeline and just the file *.sum came out. 
My commands:
EDTA.pl --genome genome.fasta --species others --step all --anno 1 --threads 8 --overwrite 1
RepeatMasker -pa 2 -s -a -inv -norna -xsmall -div 40 -lib *EDTA.TElib.fa -cutoff 225 genome.fasta

I could not find the *.divsum. I'm doing something wrong?

Thank you!

**Comment by oushujun** [comment]
Hello @luisafmc,

There is no *.divsum file generated by EDTA. Please check out readme or wiki for more info.

Best,
Shujun

**Comment by luisafmc** [comment]
Hi @oushujun 

Now I understand the problem! Thanks to the wiki

I try to follow the pipeline described here https://github.com/oushujun/EDTA/issues/92 

First I would need to run calcDivergenceFromAlign.pl and them createRepeatLandscape.pl. The output of this last one is the file *.divsum

Thanks for the support 🍡
