### ISSUE TITLE
Error in test

### ISSUE THREAD

**Issue by wangxuleiii** [oushujun/EDTA#296]
Hello Dr. Ou,
Thank you for the tool and tutorials! However, I have the following problems when using and testing:

Because I don't have root, I use CONDA to install.
Using `git clone https://github.com/oushujun/EDTA.git``conda env create -f EDTA.yml`  , following problems:
[nohup.out.txt](https://github.com/oushujun/EDTA/files/9459360/nohup.out.txt)

so I changed a new method to install,  I try to use `mamba install -c conda-forge -c bioconda edta python=3.6 tensorflow=1.14 'h5py<3'` to intall, but following error when I test:
[nohup.out2.txt](https://github.com/oushujun/EDTA/files/9459376/nohup.out2.txt)

Run command：
1、`perl ../EDTA.pl --genome genome.fa --cds genome.cds.fa --curatedlib ../database/rice6.9.5.liban --exclude genome.exclude.bed --overwrite 1 --sensitive 1 --anno 1 --evaluate 1 --threads 10
` （Tutorials on GitHub）

Next，I used another command：
2、`nohup /usr/bin/time -v perl ../EDTA.pl --genome genome.fa --cds genome.cds.fa --curatedlib ../database/rice6.9.5.liban --exclude genome.exclude.bed --overwrite 1 --sensitive 1 --anno 1 --evaluate 1 --threads 10 > EDTA.test &` （in /test/README.txt）

`conda env create -f EDTA.yml`‘s error is：
[EDTA.test.txt](https://github.com/oushujun/EDTA/files/9459514/EDTA.test.txt)

`mamba install -c conda-forge -c bioconda edta python=3.6 tensorflow=1.14 'h5py<3'` 's erros is :
[EDTA.test1.txt](https://github.com/oushujun/EDTA/files/9459540/EDTA.test1.txt)

What is the problem？
Thanks.

Cheers!
wang

**Comment by oushujun** [comment]
Hi Wang,

I am not sure what caused your issues. You may want to create an clean
conda env to reinstall EDTA. Let me know if this doesn't work.

Best,
Shujun

**Comment by wangxuleiii** [comment]
These two installation methods are newly created environments, and then encounter such problems.

**Comment by oushujun** [comment]
The first and last error is `(core dumped) perl`, and the second and third error is `Error while loading sequence`. You should check your conda installation or your system. The installation is not proper.
