### ISSUE TITLE
About whole-genome TE annotation %

### ISSUE THREAD

**Issue by luisafmc** [oushujun/EDTA#297]
Hi

I just want to ask if inside the EDTA output you could find the information of the Whole-genome TE annotation. 

I know that information is available in the Log file that appears at the end of the running but is there another place?

I have checked everywhere but seems that it would be necessary to re-run the process to obtain. 

Thank you so much!

**Comment by oushujun** [comment]
Hello @luisafmc,

It's available in the .sum file. Please find more details in the wiki: https://github.com/oushujun/EDTA/wiki/Making-sense-of-EDTA-usage-and-outputs---Q&A

Best,
Shujun

**Comment by luisafmc** [comment]
Thank you! 

I really like EDTA
