### ISSUE TITLE
Can EDTA be used to calculate the insertion time of LTR?

### ISSUE THREAD

**Issue by Xinxin0314** [oushujun/EDTA#298]
Hello Dr. Ou,

I have already finished the work to identify the transposon using EDTA. The results of  LTR_retriever can be used to calculate the LTR insertion time. So, I wonder if I can calculate the LTR insertion time using the result file of EDTA. 

Thank you. Looking forward to your reply.

Xinxin

**Comment by oushujun** [comment]
Yes, see more: #233 #271

**Comment by Xinxin0314** [comment]
Thanks for your response very much.

**Comment by nousiaso** [comment]
Hello ! 
Thank you for the very nice software ! 

I wanted to ask you, can you please elaborate on how LTR_retriever estimates the insertion time (-u option)? The manual does not specify the procedure. Is it done through a pairwise alignment of the LTR full sequences followed by the T= K/2m where m is the input substitution rate ?  Therefore each insertion time is the average pairwise distance  of each full sequence vs the rest / 2 * the substitution rate the user specifies? 

Looking forward to your reply,
Best regards
