### ISSUE TITLE
Error in test and installation issue

### ISSUE THREAD

**Issue by eliasprim** [oushujun/EDTA#299]
Hello Dr Ou,

I am raising this issue, because I got an error while I was trying to run the test example.

The error I got is the following: Error: LTR_retriever is not found in the LTR_retriever path ./!

Most probably it is an installation issue and I tried to install EDTA with both conda ways, "Quick installation using conda (Linux64)" and "Other ways to install with conda".

With the first way I did not face any issues, while in the second one I got this:

Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with nexy repodata source.
Collecting package metadata (current_repodata.json): done

And after that there is an infinite loading.

Do you have any ideas what is going wrong?

Thank you in advance.

Kind regards,

Elias Primetis

**Comment by eliasprim** [comment]
Hi Dr Ou,

After a lot of my own research I managed to install EDTA, but when I try to run the test in order to understand how EDTA works I get the following errors:


########################################################
##### Extensive de-novo TE Annotator (EDTA) v2.0.1  ####
##### Shujun Ou (shujun.ou.1@gmail.com)             ####
########################################################



Wed 14 Sep 12:07:43 BST 2022	Dependency checking:
				All passed!

	A custom library ../database/rice6.9.5.liban is provided via --curatedlib. Please make sure this is a manually curated library but not machine generated.

	A CDS file genome.cds.fa is provided via --cds. Please make sure this is the DNA sequence of coding regions only.

	A BED file is provided via --exclude. Regions specified by this file will be excluded from TE annotation and masking.

Wed 14 Sep 12:07:45 BST 2022	Obtain raw TE libraries using various structure-based programs: 
Wed 14 Sep 12:07:45 BST 2022	EDTA_raw: Check dependencies, prepare working directories.

Wed 14 Sep 12:07:46 BST 2022	Start to find LTR candidates.

Wed 14 Sep 12:07:46 BST 2022	Identify LTR retrotransposon candidates from scratch.

Warning: LOC list genome.fa.mod.ltrTE.veryfalse is empty.
Wed 14 Sep 12:08:11 BST 2022	Finish finding LTR candidates.

Wed 14 Sep 12:08:11 BST 2022	Start to find TIR candidates.

Wed 14 Sep 12:08:11 BST 2022	Identify TIR candidates from scratch.

Species: others
dirname: missing operand
Try 'dirname --help' for more information.
Can't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.fa: No such file or directory at /mnt/RAID/method/EDTA/util/rename_tirlearner.pl line 19.
Warning: LOC list genome.fa.mod.TIR.ext30.list is empty.

Error: Error while loading sequenceCan't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.gff3: No such file or directory.
Warning: The TIR result file has 0 bp!

Wed 14 Sep 12:08:12 BST 2022	Start to find Helitron candidates.

Wed 14 Sep 12:08:12 BST 2022	Identify Helitron candidates from scratch.

Wed 14 Sep 12:08:36 BST 2022	Finish finding Helitron candidates.

Wed 14 Sep 12:08:36 BST 2022	Execution of EDTA_raw.pl is finished!

ERROR: Raw TIR results not found in genome.fa.mod.EDTA.raw/genome.fa.mod.TIR.raw.fa
	If you believe the program is working properly, this may be caused by the lack of intact TIRs in your genome. Consider to use the --force 1 parameter to overwrite this check


I have checked a lot of similar issues, but nothing worked.

Could you please help me with that?

Kind regards,

Elias

**Comment by oushujun** [comment]
Hi Elias,

The error suggests the installation is still not good. Did you install EDTA on a standalone conda env or shared with other packages? You may try to reinstall in a brandnew env. Also, you may try `mamba`(https://anaconda.org/conda-forge/mamba) which can resolve environment much quicker than conda.

Best,
Shujun

**Comment by 12oaks1** [comment]
Hello Dr. Ou,

My issue is "ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found"  in the TIR learner step. 
The quick installation using conda (Linux64) was OK. The test run could finish finding LTR candidates but failed in the step of "Identify TIR candidates from scratch" and proceeded to "Identify Helitron candidates" . 

I checked the default gblic on CentOS 6.8, it's glibc2.12. However other glibc versions  2.14, 2.15, 2.17 were also installed. I tried to link glibc2.14 using export LD_LIBRARY_PATH or LD_PRELOAD but was not successful.
I am not a root user of the system and changing the default gblic will cause more issues such as “core dumped”. 
Your suggestions will be greatly appreciated!

Best wishes,

Lingtong

Thu Feb  9 11:09:54 CST 2023	Dependency checking: All passed!

A custom library ../database/rice6.9.5.liban is provided via --curatedlib. Please make sure this is a manually curated library but not machine generated.

A CDS file genome.cds.fa is provided via --cds. Please make sure this is the DNA sequence of coding regions only.

A BED file is provided via --exclude. Regions specified by this file will be excluded from TE annotation and masking.

Thu Feb  9 11:10:02 CST 2023	Obtain raw TE libraries using various structure-based programs: 
Thu Feb  9 11:10:02 CST 2023	EDTA_raw: Check dependencies, prepare working directories.
Thu Feb  9 11:10:05 CST 2023	Start to find LTR candidates.
Thu Feb  9 11:10:05 CST 2023	Identify LTR retrotransposon candidates from scratch.
Warning: LOC list genome.fa.mod.ltrTE.veryfalse is empty.
Thu Feb  9 11:10:47 CST 2023	Finish finding LTR candidates.

Thu Feb  9 11:10:47 CST 2023	Start to find TIR candidates.

Thu Feb  9 11:10:47 CST 2023	Identify TIR candidates from scratch.

Species: others
Traceback (most recent call last):
File "/datapool/wangtai/liulingtong/anaconda3/envs/EDTA/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
from tensorflow.python.pywrap_tensorflow_internal import *
File "/datapool/wangtai/liulingtong/anaconda3/envs/EDTA/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
File "/datapool/wangtai/liulingtong/anaconda3/envs/EDTA/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
File "/datapool/wangtai/liulingtong/anaconda3/envs/EDTA/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
File "/datapool/wangtai/liulingtong/anaconda3/envs/EDTA/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /datapool/wangtai/liulingtong/anaconda3/envs/EDTA/lib/python3.6/lib-dynload/../../libssl.so.1.1)

**Comment by oushujun** [comment]
The install of TIR-Learner is incomplete. Try different ways to install in
conda. Remove this one and install brand new.

Shujun

**Comment by sumoii** [comment]
Hello Dr. Ou,
when I try to run the test  I get the following errors:

     Tue Mar 21 10:05:56 CST 2023    EDTA_raw: Check dependencies, prepare working directories.
     Tue Mar 21 10:06:01 CST 2023    Start to find LTR candidates.
     Tue Mar 21 10:06:01 CST 2023    Identify LTR retrotransposon candidates from scratch.
     Warning: LOC list genome.fa.mod.ltrTE.veryfalse is empty.
     Tue Mar 21 10:07:33 CST 2023    Finish finding LTR candidates.
     Tue Mar 21 10:07:34 CST 2023    Start to find TIR candidates.
     Tue Mar 21 10:07:34 CST 2023    Identify TIR candidates from scratch.
     Species: others
     Tue Mar 21 10:08:23 CST 2023    Finish finding TIR candidates.
     Tue Mar 21 10:08:23 CST 2023    Start to find Helitron candidates.
     Tue Mar 21 10:08:23 CST 2023    Identify Helitron candidates from scratch.
     Tue Mar 21 10:09:27 CST 2023    Finish finding Helitron candidates.
     Tue Mar 21 10:09:27 CST 2023    Execution of EDTA_raw.pl is finished!
     Died at /biodata/users/xiaogh/software/anaconda3/envs/EDTA/bin/BuildDatabase line 332.
     cat: 'RM_*/consensi.fa': No such file or directory

Could you please help me with that?

**Comment by oushujun** [comment]
Could you please paste the whole report and your command? Thanks!

Shujun

**Comment by frabanal** [comment]
Hi @oushujun , 

I'm an avid user of EDTA. I've recently installed version 2.1.3 with conda, and I've gotten the two issues reported by @sumoii  

**1.**
`Warning: LOC list genome.fa.mod.ltrTE.veryfalse is empty.
`
This may be considered solved after downgrading ltr_retriever from 2.9.4 (I believe) to 2.9.0. Is that correct?

**2.**
This other issue I haven't been able to solve.

```
cat: 'RM_*/consensi.fa': No such file or directory
                                RepeatModeler is finished, but no consensi.fa files found.
```
Here is the command I ran:
`perl $EDTA/EDTA.pl --genome $REF --step all --overwrite 0 --sensitive 1 --anno 1 --threads $CORES |& tee $REF.log_edta.txt
`
I ran it in an _A. thaliana_ genome and this is the top of the output summary:
```
Repeat Classes
==============
Total Sequences: 126
Total Length: 143725422 bp
Class                  Count        bpMasked    %masked
=====                  =====        ========     =======
LTR                    --           --           --   
    Copia              1155         1386483      0.96% 
    Gypsy              87428        18654076     12.98% 
    unknown            2142         2868476      2.00% 
TIR                    --           --           --   
    CACTA              1315         838089       0.58% 
    Mutator            3401         934735       0.65% 
    PIF_Harbinger      441          213671       0.15% 
    Tc1_Mariner        203          113080       0.08% 
    hAT                763          334602       0.23% 
nonTIR                 --           --           --   
    helitron           12166        6716155      4.67% 
                      ---------------------------------
    total interspersed 109014       32059367     22.31%

---------------------------------------------------------
Total                  109014       32059367     22.31%

```

Thing is, I have ran EDTA v1.9.7 on this genome in the past, and this was the top of the result summary:

```
 Repeat Classes
==============
Total Sequences: 126
Total Length: 143725422 bp
Class                  Count        bpMasked    %masked
=====                  =====        ========     =======
LTR                    --           --           --   
    Copia              1183         1387803      0.97% 
    Gypsy              87261        18679441     13.00% 
    unknown            2606         2916845      2.03% 
TIR                    --           --           --   
    CACTA              1225         774288       0.54% 
    Mutator            3580         1095407      0.76% 
    PIF_Harbinger      463          246049       0.17% 
    Tc1_Mariner        205          114077       0.08% 
    hAT                791          369313       0.26% 
nonLTR                 --           --           --   
    LINE_element       248          255290       0.18% 
nonTIR                 --           --           --   
    helitron           11629        6503269      4.52% 
repeat_region          12757        6810757      4.74% 
                      ---------------------------------
    total interspersed 121948       39152539     27.24%

---------------------------------------------------------
Total                  121948       39152539     27.24%

```

Thus, it seems I'm missing "nonLTR (LINE element)" and "repeat_region". I would very much appreciate your guidance with solving these issues, so I can run the latest EDTA version and move to the panEDTA step.

Kind regards, 

Fernando

**Comment by oushujun** [comment]
1. Yes that's fine.
2. You may want to check the EDTA.final/RM_* folder and see if
RepeatModeler finished properly. If You run up to round-6 and still have 0
consensus, it worked on but just couldn't find repeats

**Comment by frabanal** [comment]
Thank for the prompt response. EDTA.final/RM_* folder does not exist. 
here the content of the directory `ls -lt ANGE-B-10.fa.mod.EDTA.final/`

```
-rw-r--r-- 1 frabanal ebio   613900 Jun 28 18:35 ANGE-B-10.fa.mod.EDTA.intact.gff3
-rw-r--r-- 1 frabanal ebio  5976124 Jun 28 18:35 ANGE-B-10.fa.mod.EDTA.intact.fa
-rw-r--r-- 1 frabanal ebio    56521 Jun 28 18:35 ANGE-B-10.fa.mod.EDTA.intact.fa.rename.list
-rw-r--r-- 1 frabanal ebio     2467 Jun 28 18:35 ANGE-B-10.fa.mod.EDTA.intact.fa.tbl
-rw-r--r-- 1 frabanal ebio  6087713 Jun 28 18:35 ANGE-B-10.fa.mod.EDTA.intact.fa.masked
-rw-r--r-- 1 frabanal ebio   680912 Jun 28 18:35 ANGE-B-10.fa.mod.EDTA.intact.fa.out
-rw-r--r-- 1 frabanal ebio 30563935 Jun 28 18:35 ANGE-B-10.fa.mod.EDTA.intact.fa.cat
-rw-r--r-- 1 frabanal ebio  2966550 Jun 28 18:35 ANGE-B-10.fa.mod.EDTA.TElib.fa
-rw-r--r-- 1 frabanal ebio  3227602 Jun 28 18:34 ANGE-B-10.fa.mod.EDTA.raw.fa
-rw-r--r-- 1 frabanal ebio  3227602 Jun 28 18:34 ANGE-B-10.fa.mod.LTR.TIR.Helitron.others.fa.stg2.clean
-rw-r--r-- 1 frabanal ebio        0 Jun 28 18:34 ANGE-B-10.fa.mod.RM.consensi.fa
-rw-r--r-- 1 frabanal ebio      555 Jun 28 18:34 ANGE-B-10.fa.mod.masked.njs
-rw-r--r-- 1 frabanal ebio     1752 Jun 28 18:34 ANGE-B-10.fa.mod.masked.translation
-rw-r--r-- 1 frabanal ebio     2474 Jun 28 18:34 ANGE-B-10.fa.mod.tbl
-rw-r--r-- 1 frabanal ebio  5096780 Jun 28 18:34 ANGE-B-10.fa.mod.out
lrwxrwxrwx 1 frabanal ebio       19 Jun 28 18:21 ANGE-B-10.fa.mod -> ../ANGE-B-10.fa.mod
-rw-r--r-- 1 frabanal ebio  5969968 Jun 28 18:21 ANGE-B-10.fa.mod.EDTA.intact.fa.raw
-rw-r--r-- 1 frabanal ebio  3227602 Jun 28 18:21 ANGE-B-10.fa.mod.LTR.TIR.Helitron.fa.stg1

```

**Comment by oushujun** [comment]
I meant the Arabidopsis genome. If you don't have the RM_ folder, it
suggests that you didn't run the annotation with the --sensitive 1
parameter.

Shujun

**Comment by frabanal** [comment]
Indeed, that might be the problem: EDTA not detecting that I gave it the "--sensitive 1" parameter. 

Below the command I used, same issue for another Arabidopsis genome, and an insect one: *EDTA.final/RM_* folder does not exist. 

`perl $EDTA/EDTA.pl --genome $REF --step all --overwrite 0 --sensitive 1 --anno 1 --threads $CORES |& tee $REF.log_edta.txt`

Is there something we can do about it? 

Kind regards, 

Fernando

**Comment by oushujun** [comment]
Can you test whether RepeatModeler in the EDTA env can run normally abd
generate results?

Shujun

**Comment by frabanal** [comment]
Hi again, 
Just tested it: 

```
BuildDatabase -name ANGE-B-10 ANGE-B-10.fa 
RepeatModeler -database ANGE-B-10 -threads 96 -LTRStruct >& run.out &
```

It worked well (RM_* was created, there are up to 5 round-* subdirs, and consensi.fa is there). So, I'm guessing "--sensitive 1" is not detected in the EDTA command. 

Cheers

**Comment by oushujun** [comment]
Hello @frabanal,

What version of EDTA are you using? Can you update EDTA and try again?
Alternatively, you may extract the SINE/LINE sequences from the RepeatModeler result and give them to EDTA via --curatedlib.

Shujun

**Comment by frabanal** [comment]
Hi @oushujun,

Just to update on my issue, which is not anymore. I re-install EDTA, this time with `conda env create -f EDTA.yml` (version 2.1.3), and everything worked out well: `RepeatModeler` works as expected. 

Before I was installing version 2.1.0 through `conda install -c bioconda edta`. And that was giving me troubles. 

Thanks and sorry for the confusion.
Fernando
