### ISSUE TITLE
Can't find label error

### ISSUE THREAD

**Issue by QiushiLi** [oushujun/EDTA#3]
Dear Shujun,

Please see this error,

Dependency checking: All passed!
Can't find label ALL at /data/home/qiushi_volumn1/programs/EDTA/EDTA.pl line 118.

perl version info:
This is perl 5, version 26, subversion 2 (v5.26.2) built for x86_64-linux-thread-multi

Many thanks~
Your loyal fans

**Comment by ofedrigo** [comment]
I have the same issue than above.

This is perl 5, version 26, subversion 2 (v5.26.2) built for x86_64-linux-thread-multi

**Comment by oushujun** [comment]
Dear @QiushiLi @ofedrigo,

Thank you for using EDTA. I just finished a major upgrade for the program, please reinstall it and help to test with your genomes. Please ignore the FASTA-Reader error (e.g. `FASTA-Reader: Ignoring invalid residues at position(s): On line 252: 520-746`) and `cp` `rm` errors for now. They are harmless to the result.

Please kindly let me know if you encounter any other errors. Thank you!

Best,
Shujun

**Comment by QiushiLi** [comment]
Dear Shujun,

My pleasure to run the test. Please see the this full screen output with some fatal errors. Seems like caused by some Glibc absence?

Thanks,
Qiushi

CMD:
perl /data/home/qiushi_volumn1/programs/EDTA/EDTA.pl -genome path/to/genome.fa -threads 36

########################################################
##### Extensive de-novo TE Annotator (EDTA) v1.2    ####
##### Shujun Ou (shujun.ou.1@gmail.com)             ####
########################################################



Tue Jun 18 03:19:53 MDT 2019	Dependency checking:
		All passed!
Tue Jun 18 03:19:57 MDT 2019	Obtain raw TE libraries using various structure-based programs: 
FASTA-Reader: Ignoring invalid residues at position(s): On line 250: 1224-1597, 1622-1750
FASTA-Reader: Ignoring invalid residues at position(s): On line 252: 520-746
FASTA-Reader: Ignoring invalid residues at position(s): On line 254: 1936-2299
FASTA-Reader: Ignoring invalid residues at position(s): On line 534: 225-229
FASTA-Reader: Ignoring invalid residues at position(s): On line 566: 11-15
FASTA-Reader: Ignoring invalid residues at position(s): On line 380: 5993-6353
FASTA-Reader: Ignoring invalid residues at position(s): On line 386: 238-242, 1481-1485, 2106-2110, 3127-3131
FASTA-Reader: Ignoring invalid residues at position(s): On line 472: 268-272
Traceback (most recent call last):
  File "/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/Module1/Fullcov.py", line 52, in <module>
    ProcessHomology(genome_Name)
  File "/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/Module1/Fullcov.py", line 41, in ProcessHomology
    f = pd.read_csv(blast, header=None, sep="\t") 
  File "/data/qiushi/anaconda3/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/data/qiushi/anaconda3/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/data/qiushi/anaconda3/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/data/qiushi/anaconda3/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/data/qiushi/anaconda3/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 545, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
cat: *DTA-+-select.fa: No such file or directory
cat: *DTC-+-select.fa: No such file or directory
cat: *DTH-+-select.fa: No such file or directory
cat: *DTM-+-select.fa: No such file or directory
cat: *DTT-+-select.fa: No such file or directory
cat: *-+-*-+-*.gff3: No such file or directory
Traceback (most recent call last):
  File "/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/Module1/Lowcomp_M1.py", line 84, in <module>
    records = list(SeqIO.parse(genome_Name+spliter+"F200.fa", "fasta"))
  File "/data/qiushi/anaconda3/envs/EDTA/lib/python3.6/site-packages/Bio/SeqIO/__init__.py", line 636, in parse
    with as_handle(handle, mode) as fp:
  File "/data/qiushi/anaconda3/envs/EDTA/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/data/qiushi/anaconda3/envs/EDTA/lib/python3.6/site-packages/Bio/File.py", line 113, in as_handle
    with open(handleish, mode, **kwargs) as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner-+-F200.fa'
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/../GenericRepeatFinder/bin//grf-main)
cp: cannot stat ‘chrI/candidate.fasta’: No such file or directory
cp: cannot stat ‘chrII/candidate.fasta’: No such file or directory
cp: cannot stat ‘chrIII/candidate.fasta’: No such file or directory
cp: cannot stat ‘chrIV/candidate.fasta’: No such file or directory
cp: cannot stat ‘chrIX/candidate.fasta’: No such file or directory
cp: cannot stat ‘chrM/candidate.fasta’: No such file or directory
cp: cannot stat ‘chrUn/candidate.fasta’: No such file or directory
cp: cannot stat ‘chrV/candidate.fasta’: No such file or directory
cp: cannot stat ‘chrVI/candidate.fasta’: No such file or directory
cp: cannot stat ‘chrVII/candidate.fasta’: No such file or directory
cp: cannot stat ‘chrVIII/candidate.fasta’: No such file or directory
cp: cannot stat ‘chrX/candidate.fasta’: No such file or directory
cp: cannot stat ‘chrXI/candidate.fasta’: No such file or directory
cp: cannot stat ‘chrXII/candidate.fasta’: No such file or directory
cp: cannot stat ‘chrXIII/candidate.fasta’: No such file or directory
cp: cannot stat ‘chrXIV/candidate.fasta’: No such file or directory
cp: cannot stat ‘chrXIX/candidate.fasta’: No such file or directory
cp: cannot stat ‘chrXV/candidate.fasta’: No such file or directory
cp: cannot stat ‘chrXVI/candidate.fasta’: No such file or directory
cp: cannot stat ‘chrXVII/candidate.fasta’: No such file or directory
cp: cannot stat ‘chrXVIII/candidate.fasta’: No such file or directory
cp: cannot stat ‘chrXX/candidate.fasta’: No such file or directory
cp: cannot stat ‘chrXXI/candidate.fasta’: No such file or directory
cp: cannot stat ‘TIR-Learner/*-p’: No such file or directory
cp: cannot stat ‘/*_RefLib’: No such file or directory
cat: *chrI*80.fa: No such file or directory
cat: *chrII*80.fa: No such file or directory
cat: *chrIII*80.fa: No such file or directory
cat: *chrIV*80.fa: No such file or directory
cat: *chrIX*80.fa: No such file or directory
cat: *chrM*80.fa: No such file or directory
cat: *chrUn*80.fa: No such file or directory
cat: *chrV*80.fa: No such file or directory
cat: *chrVI*80.fa: No such file or directory
cat: *chrVII*80.fa: No such file or directory
cat: *chrVIII*80.fa: No such file or directory
cat: *chrX*80.fa: No such file or directory
cat: *chrXI*80.fa: No such file or directory
cat: *chrXII*80.fa: No such file or directory
cat: *chrXIII*80.fa: No such file or directory
cat: *chrXIV*80.fa: No such file or directory
cat: *chrXIX*80.fa: No such file or directory
cat: *chrXV*80.fa: No such file or directory
cat: *chrXVI*80.fa: No such file or directory
cat: *chrXVII*80.fa: No such file or directory
cat: *chrXVIII*80.fa: No such file or directory
cat: *chrXX*80.fa: No such file or directory
cat: *chrXXI*80.fa: No such file or directory
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/data/qiushi/anaconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/data/qiushi/anaconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/Module2/GetSeq_M2.py", line 74, in getNonHomo
    records_all=list(SeqIO.parse(allSeq,"fasta"))
  File "/data/qiushi/anaconda3/envs/EDTA/lib/python3.6/site-packages/Bio/SeqIO/__init__.py", line 636, in parse
    with as_handle(handle, mode) as fp:
  File "/data/qiushi/anaconda3/envs/EDTA/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/data/qiushi/anaconda3/envs/EDTA/lib/python3.6/site-packages/Bio/File.py", line 113, in as_handle
    with open(handleish, mode, **kwargs) as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner-+-chrIX-+-GRFmite.fa-+-p'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/Module2/GetSeq_M2.py", line 101, in <module>
    pool.map(getNonHomo,l_list)
  File "/data/qiushi/anaconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/data/qiushi/anaconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner-+-chrIX-+-GRFmite.fa-+-p'
cat: *DTA_RefLib-+-80.fa: No such file or directory
rm: cannot remove ‘*DTA_RefLib-+-80’: No such file or directory
rm: cannot remove ‘*DTA_RefLib-+-80.fa’: No such file or directory
cat: *DTC_RefLib-+-80.fa: No such file or directory
rm: cannot remove ‘*DTC_RefLib-+-80’: No such file or directory
rm: cannot remove ‘*DTC_RefLib-+-80.fa’: No such file or directory
cat: *DTH_RefLib-+-80.fa: No such file or directory
rm: cannot remove ‘*DTH_RefLib-+-80’: No such file or directory
rm: cannot remove ‘*DTH_RefLib-+-80.fa’: No such file or directory
cat: *DTM_RefLib-+-80.fa: No such file or directory
rm: cannot remove ‘*DTM_RefLib-+-80’: No such file or directory
rm: cannot remove ‘*DTM_RefLib-+-80.fa’: No such file or directory
cat: *DTT_RefLib-+-80.fa: No such file or directory
rm: cannot remove ‘*DTT_RefLib-+-80’: No such file or directory
rm: cannot remove ‘*DTT_RefLib-+-80.fa’: No such file or directory
rm: cannot remove ‘./*-+-p’: No such file or directory
rm: cannot remove ‘./*-+-p’: No such file or directory
rm: cannot remove ‘./*-+-homo.fa’: No such file or directory
rm: cannot remove ‘./*-+-p’: No such file or directory
rm: cannot remove ‘./*-+-homo.fa’: No such file or directory
rm: cannot remove ‘./*-+-p’: No such file or directory
rm: cannot remove ‘./*-+-homo.fa’: No such file or directory
rm: cannot remove ‘./*-+-p’: No such file or directory
rm: cannot remove ‘./*-+-homo.fa’: No such file or directory
cat: *-+-*-+-*.gff3: No such file or directory
rm: cannot remove ‘*-+-*-+-*.gff3’: No such file or directory
rm: cannot remove ‘*homo-+-80.fa’: No such file or directory
Traceback (most recent call last):
  File "/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/Module2/Lowcomp_M2.py", line 85, in <module>
    records = list(SeqIO.parse(genome_Name+spliter+"M2F200.fa", "fasta"))
  File "/data/qiushi/anaconda3/envs/EDTA/lib/python3.6/site-packages/Bio/SeqIO/__init__.py", line 636, in parse
    with as_handle(handle, mode) as fp:
  File "/data/qiushi/anaconda3/envs/EDTA/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/data/qiushi/anaconda3/envs/EDTA/lib/python3.6/site-packages/Bio/File.py", line 113, in as_handle
    with open(handleish, mode, **kwargs) as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner-+-M2F200.fa'
mv: cannot stat ‘../Module2/TIR-Learner/*_nonHomo.fa’: No such file or directory
cp: cannot stat ‘TIR-Learner/*.csv’: No such file or directory
cp: cannot stat ‘TIR-Learner/*nonHomo.fa’: No such file or directory
cat: *DTA.fa: No such file or directory
rm: cannot remove ‘*_DTA.fa’: No such file or directory
cat: *DTC.fa: No such file or directory
rm: cannot remove ‘*_DTC.fa’: No such file or directory
cat: *DTH.fa: No such file or directory
rm: cannot remove ‘*_DTH.fa’: No such file or directory
cat: *DTM.fa: No such file or directory
rm: cannot remove ‘*_DTM.fa’: No such file or directory
cat: *DTT.fa: No such file or directory
rm: cannot remove ‘*_DTT.fa’: No such file or directory
rm: cannot remove ‘*.csv’: No such file or directory
rm: cannot remove ‘*_nonHomo.fa’: No such file or directory
cat: *-+-*-+-*.gff3: No such file or directory
rm: cannot remove ‘*-+-*-+-*.gff3’: No such file or directory
Traceback (most recent call last):
  File "/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/Module3/Lowcomp_M3.py", line 86, in <module>
    records = list(SeqIO.parse(genome_Name+spliter+"M3F200.fa", "fasta"))
  File "/data/qiushi/anaconda3/envs/EDTA/lib/python3.6/site-packages/Bio/SeqIO/__init__.py", line 636, in parse
    with as_handle(handle, mode) as fp:
  File "/data/qiushi/anaconda3/envs/EDTA/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/data/qiushi/anaconda3/envs/EDTA/lib/python3.6/site-packages/Bio/File.py", line 113, in as_handle
    with open(handleish, mode, **kwargs) as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner-+-M3F200.fa'
cp: cannot stat ‘Module1/TIR-Learner/TIR-Learner-+-Module1-+-Low’: No such file or directory
cp: cannot stat ‘Module2/TIR-Learner/TIR-Learner-+-Module2-+-Low’: No such file or directory
cp: cannot stat ‘Module3/TIR-Learner/TIR-Learner-+-Module3-+-Low’: No such file or directory
Traceback (most recent call last):
  File "/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/CombineAll.py", line 91, in <module>
    remove = FlankingBlast("%sLow"%(genome_Name+spliter+dataset+spliter))
  File "/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/CombineAll.py", line 37, in FlankingBlast
    f=open(file,"r+")
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner-+-Module1-+-Low'
rm: cannot remove ‘*Low’: No such file or directory
Traceback (most recent call last):
  File "/data/home/qiushi_volumn1/programs/EDTA/bin/TIR-Learner1.12/GetAllSeq.py", line 60, in <module>
    file=open(f,"r+")
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner_FinalAnn.gff3'
mv: cannot stat ‘TIR-Learner/*FinalAnn.gff3’: No such file or directory
mv: cannot stat ‘TIR-Learner/*FinalAnn.fa’: No such file or directory
cp: cannot stat ‘TIR-Learner-Result/TIR-Learner_FinalAnn.fa’: No such file or directory
Error: TIR results not found!

ERROR: Raw TIR results not found in Gac-HiC_revised_genome_assembly.fa.EDTA.raw/Gac-HiC_revised_genome_assembly.fa.TIR.raw.fa at /data/home/qiushi_volumn1/programs/EDTA/EDTA.pl line 137.

**Comment by oushujun** [comment]
Hi @QiushiLi @ofedrigo ,

Sorry for the bug. Please refer to #4 for a test version of EDTA. Please let me know if there is any error in this version.

Best,
Shujun
