### ISSUE TITLE
MITE information lacking from final summary file (.sum)

### ISSUE THREAD

**Issue by bijendrabio** [oushujun/EDTA#301]
Hello,
I was curious to know why MITE information is lacking from the final summary report file (.sum), despite the MITE elements information being available in the de novo repeat library file (.EDTA.TElib.fa file). Kindly advise!

Regards,
B

**Comment by xizhesun** [comment]
I focus on MITE search. It seems it has combined in the TIR. Because TIR-learner also include the identificaiton of MITE. I am not sure.  I really need this information to show clearlly in EDTA

**Comment by oushujun** [comment]
Hi,

Historically MITE information is presented in the final result but
obviously it created more confusions than help. Most people don't know MITE
is just a special form of TIR that lacks the transposase. So I collapse
MITEs back to TIRs.

For people like you studying MITEs specifically, they can extract MITE from
structurally annotated TIRs with the length of <600bp (or with the length
of your confidence). You may do so too.

Best,
Shujun

**Comment by xizhesun** [comment]
Dear Shujun,

Thank you for the MITE extract method. 

I have another question. I find the TE number in  **mod.EDTA.TE.fa.stat.all.sum** file was different with the **mod.EDTA.TEanno.sum** summary file. 
In the summary file, it contains the information as follow.

> Class                  Count        bpMasked    %masked
> =====                  =====        ========     =======
> LTR                    --           --           --   
>     Copia              304          594214       1.06% 
>     Gypsy              332          583011       1.04% 
>     unknown            399          336181       0.60% 
> TIR                    --           --           --   
>     CACTA              124          111896       0.20% 
>     Mutator            388          283664       0.51% 
>     PIF_Harbinger      7            20541        0.04% 
>     Tc1_Mariner        17           11283        0.02% 
>     hAT                572          341007       0.61% 
> nonLTR                 --           --           --   
>     LINE_element       120          46016        0.08% 
> nonTIR                 --           --           --   
>     helitron           59           261003       0.47% 
> repeat_region          1588         402130       0.72% 
>                       ---------------------------------
>     total interspersed 3910         2990946      5.34%
> 
> ---------------------------------------------------------
> Total                  3910         2990946      5.34%

I want to present the information of different TE class on the Circos Plot.  But in the gff file, I find 4490 (not 3910) TE with different "name=". Is there a list to show which "name=" ID each class of TE contains? I don't know what the problem is. Do you have any suggestion?

All Best,
Xizhe

**Comment by xizhesun** [comment]
Dear  @bijendrabio 

Do you have the similar situation which TE number in mod.EDTA.TE.fa.stat.all.sum file was different with the mod.EDTA.TEanno.sum summary file?

**Comment by bijendrabio** [comment]
Hello,
Thank you for the clarification.  Any suggestion on how to extract them (MITEs) from the structurally annotated TIRs and represent them in the final summary annotation file.?

Thank you for your time in advance. 

Regards,
B

> Hi, Historically MITE information is presented in the final result but obviously it created more confusions than help. Most people don't know MITE is just a special form of TIR that lacks the transposase. So I collapse MITEs back to TIRs. For people like you studying MITEs specifically, they can extract MITE from structurally annotated TIRs with the length of <600bp (or with the length of your confidence). You may do so too. Best, Shujun
> […](#)

**Comment by bijendrabio** [comment]
> Dear @bijendrabio
> 

Dear @xizhesun, 
In my case, I only received the *EDTA.TEanno.sum as a summary output of whole-genome TE annotation. (See output section at https://github.com/oushujun/EDTA)

Regards,
B


> Do you have the similar situation which TE number in mod.EDTA.TE.fa.stat.all.sum file was different with the mod.EDTA.TEanno.sum summary file?

**Comment by oushujun** [comment]
You can use awk or other similar utilities to obtain MITEs based on element
length and the annotation labels 'structural' & 'TIR'.

Shujun
