### ISSUE TITLE
Please can you share details concerning the  -u option (from LTR_retriever) (repeat time inference) 

### ISSUE THREAD

**Issue by nousiaso** [oushujun/EDTA#302]
Hello !
Thank you for the very nice software !

I wanted to ask you, can you please elaborate on how LTR_retriever estimates the insertion time (-u option)? The manual does not specify the procedure. Is it done through a pairwise alignment of the LTR full sequences followed by the T= K/2m where m is the input substitution rate ? Therefore each insertion time is the average pairwise distance of each full sequence vs the rest / 2 * the substitution rate the user specifies?

Looking forward to your reply,
Best regards

**Comment by oushujun** [comment]
You are correct! The distance K is estimated from the Jukes Cantor 1969
model. I may have put the estimation method in the original paper.

Shujun
