### ISSUE TITLE
LTR classfication in pangenome pipeline

### ISSUE THREAD

**Issue by jia-wu-feng** [oushujun/EDTA#303]
Dear shujun,

Thanks for your great software!

When I used the pangenome pipeline of EDTA, the ratio of LTR Copia and LTR unknown changed.

Is it possible to add related species to the pan-genome pipeline?

We have a genome not of the same species, but of closely related species. However, it is also closely related species that undergo large changes in LTR annotation.

<img width="643" alt="image" src="https://user-images.githubusercontent.com/24247803/194834206-bb331496-6b6e-4873-acc8-edf3b287293c.png">

I would like to know your views on the use of the EDTA pangenome pipeline between different species.

Thanks,
Jiawu Feng

**Comment by oushujun** [comment]
Hi Jiawu,

Can you please describe your inputs, commands, and parameters?

Shujun

**Comment by oushujun** [comment]
I don't follow what you mean. How many genomes do you have?

**Comment by jia-wu-feng** [comment]
I have 19 genomes, one is specie 1, and 18 are specie 2. I want to analyze the 2 species' TE differences.

When I used EDTA normal pipeline and pangenome pipeline, the specie 1 in LTR has a lot of change.

**Comment by oushujun** [comment]
Thank you for the extra information. It could be that some families are
border-line classified and the rerun (panEDTA) have it classified as
unknown. You may rerun panEDTA to regenerate the panTE library or use
TEsorter with REXDB-plant to reclassify the panTE library and see if
there's any improvement.

Shujun

**Comment by oushujun** [comment]
Any updates?

**Comment by oushujun** [comment]
Close due to no update. Please reopen if you still have questions. Thanks!

Shujun
