### ISSUE TITLE
Determination of feature type for gff to gtf conversion

### ISSUE THREAD

**Issue by synanth** [oushujun/EDTA#304]
Hi, 
I'm exploring this wonderful software as a way to get a comprehensive CHM13 TE annotation file for downstream analysis of RNASeq data. The other bits of software I am using requires gtf, rather than gff, so I am wondering how to determine a reduction mapping between gff's more comprehensive features and gtf's more limited ones. Is it a mechanism of the TE family, or of some other portion of the gff produced by EDTA?

Thank you so much,
Synanth

**Comment by synanth** [comment]
Managed to get it working with AGAT through editing it's associated json files to automatically do the conversion.

**Comment by oushujun** [comment]
Thanks for opening the issue and providing a solution to the problem!

Best,
Shujun

**Comment by Cjianghao** [comment]
> Hi, I'm exploring this wonderful software as a way to get a comprehensive CHM13 TE annotation file for downstream analysis of RNASeq data. The other bits of software I am using requires gtf, rather than gff, so I am wondering how to determine a reduction mapping between gff's more comprehensive features and gtf's more limited ones. Is it a mechanism of the TE family, or of some other portion of the gff produced by EDTA?
> 
> Thank you so much, Synanth



> Managed to get it working with AGAT through editing it's associated json files to automatically do the conversion.
Hi,synanth，I also encountered this problem, how did you ultimately solve it? I haven't solved it yet.

**Comment by synanth** [comment]
iirc I used AGAT, but I no longer have the script I originally used. It involved changing the mapping parameters in the conversion, but it looks like it may use a yaml format now. Anyways, look into AGAT and see if that works for your use case.
