### ISSUE TITLE
the discrepancy of blast records between EDTA TE lib and RepeatMasker TE lib

### ISSUE THREAD

**Issue by leon945945** [oushujun/EDTA#305]
Hi shujun,
My purpose is to detect TE insertion in my resequencing data, then I extracted the 'unmapped mate' sequences of 299582 singletons (one mate mapped, the other unmapped) to conduct blast with TE library, however the 144 blast records of EDTA TE library was less than the 293 blast records of RepeatMasker TE library.
Actually, I prefer to use EDTA due to its useful intact TE annotation, but the lower blast records made me worry about the sensibility of TE insertion detection. To my knowledge, application of EDTA and RepeatMasker to the same genome should generate highly similar TE libraries, I am confused of the discrepancy of blast results.
I want to know why the discrepancy exists and would the less blast records of EDTA TE library decrease the sensibility of TE insertion detection.
Thank you, here are the results of blast.
[EDTA.txt](https://github.com/oushujun/EDTA/files/9750693/EDTA.txt)
[RepeatMasker.txt](https://github.com/oushujun/EDTA/files/9750695/RepeatMasker.txt)

**Comment by oushujun** [comment]
I have not done this before, but either way seems pretty low to me given
300k reads. Maybe you need to check the blast parameter.

Shujun

**Comment by leon945945** [comment]
Thanks for your reply. I'll try other blast parameters.
