### ISSUE TITLE
Quickly obtain the position of TE

### ISSUE THREAD

**Issue by Midreancgle** [oushujun/EDTA#307]
Hello!

The EDTA is a good job.

I want to know how to quickly obtain the specific starting and ending position of all transposons in the genome from EDTA output files? Can you give me some methods or advice?

Thanks

**Comment by oushujun** [comment]
Hello, you may want to check out the gff3 file. See more here: https://github.com/oushujun/EDTA/wiki/Making-sense-of-EDTA-usage-and-outputs---Q&A
