### ISSUE TITLE
TIR-Learner is slow with many contigs

### ISSUE THREAD

**Issue by mergi-2674** [oushujun/EDTA#308]
I would like to appreciate for the best pipeline you developed so far! However, I was running EDTA on the plant genome which has a size of 3GB and EDTA was running for a week on a pc with 380GB of RAM and 32 threads. It didn't  gave me the final result ans stacked on TIR step. How long does it takes to finish the analysis?

Best
Mergi

![Screenshot from 2022-10-19 11-41-36](https://user-images.githubusercontent.com/66041822/196656895-36b196e8-9866-4bf3-8c2c-2c9f574a54d9.png)

**Comment by oushujun** [comment]
Yeah the TIR step will be slow if you have a very fragmented genome. TIR-Learner will get slow down for thousands of contigs. You may want to remove the small contigs and rerun or keep waiting... Alternatively, you can concatenate the small contigs into Chr0 which will much speed up the run.

Shujun

**Comment by mergi-2674** [comment]
Hi Shujun
Thank you for replay. I have a genome with thousands of contigs and that is why the TIR step takes more longer. I wanted to concatenate the small contigs into chr0 but i don't know how. Could you help me with this please?

Best,
Mergi

**Comment by oushujun** [comment]
Hi Mergi,

You may search around and make your own. For example, you can start from here: https://www.biostars.org/p/379245/

Best,
Shujun

**Comment by oushujun** [comment]
This issue should be fixed in v2.2.2 with the new TIR-Learner 3.
