### ISSUE TITLE
gt is not found in the genometools path

### ISSUE THREAD

**Issue by mergi-2674** [oushujun/EDTA#309]
I was trying to run EDTA on a cluster. I created the EDTA environment and installed all. but when i tried to run my analysis it always gives me an error which says gt is not found in the genometools path ./!.
How can i fix and run my analysis?

Best Regards!

**Comment by oushujun** [comment]
Hello,

You may want to install EDTA through conda. If you did so and still get the error, you may want to check your $ENV path or your $PATH in the ~/.bashrc file and see if anything supersedes the default conda $ENV. EDTA looks for dependencies from $ENV.

Shujun
