### ISSUE TITLE
TEanno.bed and TEanno.out

### ISSUE THREAD

**Issue by cfz1998** [oushujun/EDTA#314]
Hi! @oushujun.
What's the difference between TEanno.out and TEanno.bed? I can not see detail in the wiki. Could I only use TEanno.out for the true result for the TE anno?

Thank you for your reply!
Best wishes!

--zcf

**Comment by oushujun** [comment]
Hello,

These are intermediate results of EDTA. The final annotation is the gff3
file.

Shujun

**Comment by cfz1998** [comment]
> 

Thank you! Shujun

--zcf
