### ISSUE TITLE
Question about TIR-Learner_rmLTR

### ISSUE THREAD

**Issue by CSU-KangHu** [oushujun/EDTA#318]
I noticed a significant improvement from TIR-Learner to TIR-Learner_rmLTR, which is mainly due to the removal of LTR contaminants in TIR results.

![image](https://user-images.githubusercontent.com/22925278/205882861-c88aa76c-2b19-4c29-8c32-8fd0f5fc1cc1.png)

I use the command "perl EDTA_raw.pl --type tir/ltr" to obtain TIR and LTR results, respectively. Whether the TIR result corresponds to TIR-learner? What should I do to obtain a result for TIR-Learner_rmLTR?

**Comment by oushujun** [comment]
Hello,

Thank you for reading the paper closely. TIR-Learner_rmLTR was generated using the curated LTR library to mask LTR-related sequences in the TIR-Learner reported candidates. This result showed that, compared to TIRvish and other programs, TIR-Learner was more promising when LTR contaminants were properly removed. That transformed the problem of high-quality TIR annotation into removing LTR sequences from TIR-Learner results. For a new genome, we don't have a curated LTR library, but LTR_retriever results can approximate a curated LTR library. With several other purging steps, it becomes today's EDTA.

Hope this helps!
Shujun
