### ISSUE TITLE
update citation of TEsorter

### ISSUE THREAD

**Issue by zhangrengang** [oushujun/EDTA#322]
Hi @oushujun, can you update the citation of TEsorter in https://github.com/oushujun/EDTA/tree/master/bin/[README.md](https://github.com/oushujun/EDTA/tree/master/bin#readme) to:
```
Zhang RG, Li GL, Wang XL et. al. TEsorter: an accurate and fast method to classify LTR retrotransposons in plant genomes. Hortic Res, 2022; 9: uhac017
```

**Comment by oushujun** [comment]
Thanks for catching this, done!
