### ISSUE TITLE
Curated library option possible bug

### ISSUE THREAD

**Issue by swomics** [oushujun/EDTA#324]
Hi, thanks for this program. I had interesting results from an earlier version and I'm looking forward to using the new pangenome script with some recent data.

I tried running without a curated library, as the documentation suggests this is optional, however when run without this option panEDTA.sh throws the error:

ERROR: The curated library  file is not found or is empty

I got around this by commenting out line 76. Is this ok, or have i made a mistake?

The command I used is this, and the installation was from conda

panEDTA.sh -g genome.list -c merged.transcripts.fa -t 60

**Comment by oushujun** [comment]
@swomics THank you for reporting. Commenting Line 76 out should be fine. I have improved the parameter reading and should allow you to use no curated library now.
