### ISSUE TITLE
Question: pan EDTA usage of CDS FASTA

### ISSUE THREAD

**Issue by sjteresi** [oushujun/EDTA#326]
Hello Shujun,

Hope you are doing well.

I have a question pertaining to the the usage of the CDS FASTA files in the panEDTA.sh script. Is there a way to use a CDS FASTA file for some genomes and none whatsoever for other genomes?

To provide more context, I am creating a pan-genome for about 8 genomes, I only have a good CDS FASTA for about 5 of the 8 genomes, and I **do** want to use those for each corresponding genome. However, I do not want to provide the `-c` argument and use a different genome's CDS FASTA for the genomes that I do not have the CDS file.

What do you suggest I do?

Thank you for your time :)

Sincerely,
Scott

**Comment by oushujun** [comment]
Hi Scott,

Yes you can. This scheme is available in panEDTA. You will need to put the respective CDS file in the genome list file. For those without their own CDS, just leave it blank and then use the `-c` parameter to provide a generic CDS file for those missing. eg:
>genome.a.fa cds.a.fa
genome.b.fa cds.b.fa
genome.c.fa
genome.d.fa cds.d.fa


Thanks,
Shujun

**Comment by oushujun** [comment]
It means a good quality CDS file to be used on all those without a specific
CDS file. You may use a dummy file but that won't help with the quality.

Shujun

**Comment by sjteresi** [comment]
Perhaps I should just use a dummy file for the handful of genomes in which I do not have any CDS information... Previously, before updating to EDTA 2.1.0, I was using 1.9.5 and I was just running regular EDTA.pl **without** the CDS option for the genomes where I didn't have that information (and then following your old guidelines for merging the individual libraries). I am hoping that there is an analogous solution here. 

I'm puzzled regarding the decision process using another genome's CDS or a generic CDS to "fill-in" for those in which I don't have that data. I'm not sure which one would be best chosen as the candidate to fill in for others, or how I would choose/create the generic file. I am hesitant to use another genome's CDS for the missing CDS files because I have a wide range of genomes with different ploidies, levels of "wildness", and quality. So making the judgement call on which one is best is difficult.

I apologize if I am being dense. I appreciate your advice.

- Scott

**Comment by oushujun** [comment]
Kevin asked about this a while ago. Here is the answer: https://github.com/oushujun/EDTA/wiki/Making-sense-of-EDTA-usage-and-outputs---Q&A

You may use the CDS file from the closest species. Even using the Arabidopsis CDS will contribute to the annotation quality. I would use the CDS of the most recognized species in your genomes, for example, Brassica rapa seems good. There may be different heterogeneity of different CDS files being used, but overall it's similar and will be better than not using any CDS sequences.

For previous runs, you may provide a CDS and rerun from the final step.

Best,
Shujun

**Comment by sjteresi** [comment]
Ahh OK, thank you for your help and speedy responses. That is excellent advice. I apologize for missing the information inside the wiki. Thanks again!
