### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by AMartinsJr** [oushujun/EDTA#327]
Dear Ou Shujun,

I've runned EDTA in a genome and I get an error in TIR step about no space left on device to create some directory (see below). In this case, the TIR result was 0 bp.
So, I removed more than 100 GB of space in the server, to re-run the analysis.
The same problem was observed. Then, tried to run it in another genome and the same problem occurred.
Before these analysis, I've runned EDTA in 3 other genomes and it works well.
Is it a problem of space or could be someting else?
Best regards,

genome = genomalate2.fas
cds = CDS.fna

########################################################
########################################################

Wed Jan 11 16:20:00 -03 2023	Dependency checking:
				All passed!

	A custom library /home/antonio/antonio/clib_Dfam-3.6.fa is provided via --curatedlib. Please make sure this is a manually curated library but not machine generated.

	A CDS file CDS.fna is provided via --cds. Please make sure this is the DNA sequence of coding regions only.

Wed Jan 11 16:20:35 -03 2023	Obtain raw TE libraries using various structure-based programs: 
Wed Jan 11 16:20:35 -03 2023	EDTA_raw: Check dependencies, prepare working directories.

Wed Jan 11 16:20:40 -03 2023	Start to find LTR candidates.

Wed Jan 11 16:20:40 -03 2023	Identify LTR retrotransposon candidates from scratch.

Wed Jan 11 19:39:15 -03 2023	Finish finding LTR candidates.

Wed Jan 11 19:39:15 -03 2023	Start to find TIR candidates.

Wed Jan 11 19:39:15 -03 2023	Identify TIR candidates from scratch.

Species: others
Segmentation fault (core dumped)
failed to execute command /home/antonio/.conda/envs/EDTA/bin/grf-filter 10 2147483647 10 5000 10000174.1/candidate.fasta 10000174.1/candidate.fasta.filterd
mkdir: cannot create directory ‘10000231.1’: No space left on device
can't open file: 10000231.1/candidate.fasta
mkdir: cannot create directory ‘10002823.1’: No space left on device
can't open file: 10002823.1/candidate.fasta
mkdir: cannot create directory ‘10003393.1’: No space left on device
can't open file: 10003393.1/candidate.fasta
mkdir: cannot create directory ‘10001064.1’: No space left on device
can't open file: 10001064.1/candidate.fasta
mkdir: cannot create directory ‘10001928.1’: No space left on device
can't open file: 10001928.1/candidate.fasta
mkdir: cannot create directory ‘10000931.1’: No space left on device
can't open file: 10000931.1/candidate.fasta
mkdir: cannot create directory ‘10003651.1’: No space left on device
can't open file: 10003651.1/candidate.fasta
mkdir: cannot create directory ‘10003257.1’: No space left on device
can't open file: 10003257.1/candidate.fasta
mkdir: cannot create directory ‘10000016.1’: No space left on device
can't open file: 10000016.1/candidate.fasta
mkdir: cannot create directory ‘10000902.1’: No space left on device
can't open file: 10000902.1/candidate.fasta
mkdir: cannot create directory ‘10003661.1’: No space left on device
can't open file: 10003661.1/candidate.fasta
mkdir: cannot create directory ‘10003253.1’: No space left on device
can't open file: 10003253.1/candidate.fasta
mkdir: cannot create directory ‘10003154.1’: No space left on device
can't open file: 10003154.1/candidate.fasta
mkdir: cannot create directory ‘10001048.1’: No space left on device
can't open file: 10001048.1/candidate.fasta
mkdir: cannot create directory ‘10001246.1’: No space left on device
can't open file: 10001246.1/candidate.fasta
mkdir: cannot create directory ‘10000325.1’: No space left on device
can't open file: 10000325.1/candidate.fasta
mkdir: cannot create directory ‘10001177.1’: No space left on device
can't open file: 10001177.1/candidate.fasta
mkdir: cannot create directory ‘10001738.1’: No space left on device
can't open file: 10001738.1/candidate.fasta
mkdir: cannot create directory ‘10002124.1’: No space left on device
can't open file: 10002124.1/candidate.fasta
mkdir: cannot create directory ‘10001965.1’: No space left on device
can't open file: 10001965.1/candidate.fasta
mkdir: cannot create directory ‘10004199.1’: No space left on device
can't open file: 10004199.1/candidate.fasta
mkdir: cannot create directory ‘10002685.1’: No space left on device
can't open file: 10002685.1/candidate.fasta
mkdir: cannot create directory ‘10000917.1’: No space left on device
can't open file: 10000917.1/candidate.fasta
mkdir: cannot create directory Can't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.fa: No such file or directory at /usr/local/EDTA/util/rename_tirlearner.pl line 19.
Warning: LOC list genomalate2.fas.mod.TIR.ext30.list is empty.

Error: Error while loading sequenceCan't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.gff3: No such file or directory.
Warning: The TIR result file has 0 bp!

Fri Jan 13 11:49:31 -03 2023	Start to find Helitron candidates.

Fri Jan 13 11:49:31 -03 2023	Identify Helitron candidates from scratch.

Sat Jan 14 11:37:31 -03 2023	Finish finding Helitron candidates.

Sat Jan 14 11:37:31 -03 2023	Execution of EDTA_raw.pl is finished!

Sat Jan 14 11:37:31 -03 2023	Obtain raw TE libraries finished.
				All intact TEs found by EDTA: 
					genomalate2.fas.mod.EDTA.intact.fa
					genomalate2.fas.mod.EDTA.intact.gff3

**Comment by oushujun** [comment]
When you had this error, did you try duplicating a random file and see if you have space? Sometimes you may need to remove the entire *raw/TIR folder to make it run correctly. TIR-Learner does take quite some space for intermediate files.

Shujun

**Comment by Yutang-ETH** [comment]
Hi,

Sorry to jump in here, but I got the same issues while running EDTA (v2.2.0) on our machine. We have more than 5 Tb space, but still we got the no space left error. 

I happened to find that maybe this error was caused by outputting intermediate files in our /tmp folder, which only has 50 Gb space. Is it possible to have a user-defined tmp folder for EDTA?

What do you think, @oushujun?

Best wishes,
Yutang

**Comment by Yutang-ETH** [comment]
Hi @oushujun,

Just to follow my last comment. I was curious why the /tmp was used to store the intermediate file, so I checked the python scripts of TIR-learner. I found that TIR-learner has a -w option which allows your to specify the working directory. If -w is used, then the intermediate files will be stored in the working directory. I added -w $genome_file_real_path.EDTA.raw/TIR to line 576 of EDTA_raw.pl and it worked. See log below

Species: others
Tue Feb 13 06:27:00 CET 2024    Finish finding TIR candidates.

Best wishes,
Yutang

**Comment by GallVp** [comment]
Hi @Yutang-ETH 

One solution which has worked for me (with 10 GB /tmp), is to export `TMPDIR` variable before executing EDTA.pl:

```bash
export TMPDIR='/workspace/user_xyz/tmp'

EDTA.pl ...
```

If you use a EDTA with a container such as docker or singularity, don't forget to mount `TMPDIR` into the container. Otherwise, EDTA will either fail or will be stuck forever on some step without producing any error.

**Comment by Yutang-ETH** [comment]
Hi @GallVp,

Thank you very much for sharing your solution, and I think it makes sense to change the global variable TMPDIR because probably the TIR-learner python script generates the temporary folder [DO_NOT_ALTER]_TIR-Learner_sandbox_directory in the path of TMPDIR. Sorry that I haven't used python for a long time, otherwise I could explain it better. Anyway, if my current run dies, I will probably take your suggestion.

I am using EDTA installed via conda on our local Linux machine. 

Best wishes,
Yutang
