### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by clauderispe** [oushujun/EDTA#328]
Dear Shujun, 
I have just run EDTA v2.1.0, and first, I had no issue with the test data set.
However, I am having two issues in the run I made on my whole genome.

i) in the output file below an error is issued at line 34 (the words in French say that the list of arguments is too long)

Can't exec "sort": Liste d'arguments trop longue at /usr/local/bioinfo/src/Miniconda/Miniconda3/envs/EDTA-v2.1.0_env/share/EDTA/bin/TIR-Learner2.5/call_seq_by_list2.pl line 98.

ii) the last line of the output also reports an error

slurmstepd: error: Detected 2261 oom-kill event(s) in StepId=44106051.batch. Some of your processes may have been killed by the cgroup out-of-memory handler.

However, as far I can tell, the program ran to the end as all steps of search have ben made, and the files EDTA.TE anno.gff3 and EDTA.TEanno.gff3 have been produced. So perhaps these errors were non-blocking?

Thanks for your feedback!

Claude

[run_edta_2.1.0_20230124.txt](https://github.com/oushujun/EDTA/files/10516415/run_edta_2.1.0_20230124.txt)

**Comment by oushujun** [comment]
Hi Claude,

The TIR-Learner step is problematic. You'd better reformat your genome
sequence IDs and redo annotation. Always SIMPLIFY and tidy up your sequence
IDs before downstream works. You may also want to give more memory Since
There's an out of memory kill.

Best,
Shujun
