### ISSUE TITLE
Difference in metrics between sum and gff3 files

### ISSUE THREAD

**Issue by clauderispe** [oushujun/EDTA#331]
Dear Shujun
I notice a difference between the summarized metrics reported in the file genome.mod.EDTA.TEanno.sum and the genome.EDTA.TEanno.gff3 files. The sum files indicates a total count of 3184990 elements while there are 3939911 lines in the gff3.
And for example, the sum file reports 3239 Copia elements, whereas there are 3785 lines with "Copia" in the gff3.
Is there an explanation for this pattern? 
Could it be related with the error messages I reported in a previous issue (#328 , program runs to the end but reports errors for call_seq_by_list2.pl, and oom-kill event(s)) ?
Thanks for your feedback!
Claude

**Comment by oushujun** [comment]
Hi Claude,

Structural intact elements will have multiple lines for different features.
Please find more information in the wiki page.

Best,
Shujun
