### ISSUE TITLE
LINE and SINE

### ISSUE THREAD

**Issue by bijendrabio** [oushujun/EDTA#332]
Hello,
Curious if there's a way to integrate additional SINE and LINE information to EDTA final TE library (*TE.lib.fa) file and run the final annotation step to generate the summary (.sum) file showing the information about added SINE/LINE composition. 

I tried by adding the following opitions: --curatedlib *TE.lib_SINEadded.fa --step anno -anno 1
but got the blank results in .sum file. Kindly suggest!

Regards,
B

**Comment by oushujun** [comment]
Hi,

Yes You can do it  this way, but you will need to format the library in the
RepeatMasker format. Please refer to the wiki page for more information.

Shujun

**Comment by bijendrabio** [comment]
Thank you @oushujun. Is there a way to update the final result of EDTA with newly identified SINE and LINE without the need to restart the EDTA from the beginning?.

**Comment by oushujun** [comment]
Yes, you can start from --anno 1 --step final --overwrite 1 to include SINE
LINE results.

Shujun
