### ISSUE TITLE
Question related to TE library generated by EDTA+curlib+cds vs RpeatModeler2

### ISSUE THREAD

**Issue by BenAawf** [oushujun/EDTA#333]
Hi @oushujun, first of all, thank you for writing EDTA; I really find it very useful to annotate TEs of recently assembled genomes.

This is just a question related to TEs annotations using only EDTA and EDTA+ msRepDB (free DB of TEs alternative to Repbase.). since I'm new to this domain. I would really appreciate your advice on which approach is best for annotating TEs of a bird genome (Taxid: 9071).

I generated three custom TEs library
1- EDTA only: 
`perl $EDTA --genome $genome \
--species others --step all --anno 1 -t 40 --overwrite 1 --debug 1`
RepeatMasker tablefile-out1: [https://drive.google.com/file/d/1bc_kwd_2ZX2ilSs4-NXm4cB3QkEoLx3y/view?usp=sharing](url)
2- EDTA + Cuartedlib+ CDs of close-related:
`perl $EDTA --genome $genome --curatedlib $curatedlib --cds $cds_closerelative \
--species others --step all --anno 1 -t 40 --overwrite 1 --debug 1`
tbl file RM
RM-tablefile-out2: [https://drive.google.com/file/d/1MrHjn60eWV_WxqEc7ZAiFqcYyPEtnA6F/view?usp=share_link](url)

3-  Custom lib generated by RepeatModeler2:
`RepeatModeler -database $DBname -pa 15 -LTRStruct > out.log`
RM-tablefile-out3: [https://drive.google.com/file/d/17zeI3X2DlKlqKrqpMRnXRVGrcnwUYd_W/view?usp=share_link](url)

After soft masking with RepeatMasker 4.1.4, using each lib, there is like comparable results bvetween EDTA-curlib+cds and RepeatModeler.
my question which one of those repeatlib that i can trust more for  downstream analysis such (soft-masking , DNA substitution analysis (kimura-distance ..))

Kind regads
ben

**Comment by oushujun** [comment]
Hi Ben,

A very easy approach is to evaluate the annotation consistency. util/
evaluation.pl can help with this or invoke --evaluation 1 for EDTA. You may
also want to check the percentage of different TE categories. You want to
have as less of unknown categories  while having consistent annotation.

Best,
Shujun

**Comment by oushujun** [comment]
@BenAawf Did you find out which annotation is more consistent? Could you please share the results here? Thanks!

Shujun

**Comment by BenAawf** [comment]
Hi @oushujun, sorry for the delayed reply. as much I can say that after combing both TE libraries from EDTA and RepeatModeler, I found that the percentage of the repetitive elements is higher for an Aves genome 13% than using only RepeatModeler, so I decided I remove all classified unknown elements from the RM lib since I put much confidence on the EDTA lib and combined all for soft-masking.

Thank you
