### ISSUE TITLE
RepeatModeler BuildDatabase line 333

### ISSUE THREAD

**Issue by bijendrabio** [oushujun/EDTA#335]
Hello,
I noticed following message in the log file of completed EDTA run. Is this something to be concerned about?

"Died at /home/miniconda3/envs/EDTA/share/RepeatModeler/BuildDatabase line 333." Kindly suggest!

Regards,
B

**Comment by oushujun** [comment]
Hello,

Sorry for the delay. You may rerun the final step (--step final).

Best,
Shujun
