### ISSUE TITLE
error with LTRs

### ISSUE THREAD

**Issue by JoseLopezArcondo** [oushujun/EDTA#336]
Hello,

I want to detect TE in a bunch of yeast genomes, I found this error:

Wed 22 Feb 2023 06:15:35 PM CET Identify LTR retrotransposon candidates from scratch.

awk: fatal: cannot open file `GCA_001600435.1.fna.mod.pass.list' for reading: No such file or directory
Warning: LOC list - is empty.

Error: Error while loading sequence
        perl filter_gff3.pl file.gff3 file.list > new.gff3

I am using this command to run:

perl pathto/EDTA.pl --genome GCA_001600435.1.fna --overwrite 1 --sensitive 1 --anno 1 --evaluate 1 --threads 10

Thanks

**Comment by oushujun** [comment]
Maybe there is no intact LTR elements that could be found in this genome.

Shujun

**Comment by JoseLopezArcondo** [comment]
Thanks, yes I think that was it. Then I run with the —force 1 option and it worked fine
Best
José
