### ISSUE TITLE
ERROR: RepeatMasker results not found in genome.FINAL.fasta.mod.out!

### ISSUE THREAD

**Issue by panpandzf** [oushujun/EDTA#337]
Hey,
![image](https://user-images.githubusercontent.com/126332368/221414021-094bacb2-e18f-46f4-9a5f-7e15704de1af.png)

Can someone help me with this question? I'm not sure what has gone wrong, or what steps can be taken to resolve it. Any help would be greatly appreciated.

The code I ran was:
EDTA.pl --genome genome.fasta --sensitive 1 --anno 1 --evaluate 1 --threads 40 --force 1 --overwrite 0 
EDTA version is 2.1.0

**Comment by oushujun** [comment]
Hello,

Can you post a full screen output of this run? Thanks!

Shujun

**Comment by panpandzf** [comment]
Thank you for your reply! 
When I rerun it successfully, I don't know why? In addition, the running results of 20 threads and 40 threads of the same genome are somewhat different. Compared with 40 threads, 20 threads annotated more types and quantities of repeated sequences, and the final annotated repeat ratio was 2 percentage points higher. Is this a problem? Attached are the log files of my two runs. Hope for your answer.
[20threads.log](https://github.com/oushujun/EDTA/files/10845535/20threads.log)
[40threads.log](https://github.com/oushujun/EDTA/files/10845536/40threads.log)

**Comment by oushujun** [comment]
Each time you run EDTA will generate slightly differnet annotations. Please refer to the wiki for more details.

Thanks,
Shujun

**Comment by oushujun** [comment]
Probably the previous run was interrupted by your HPC. The run differences
are expected, please read wiki.

Shujun
