### ISSUE TITLE
softmasking

### ISSUE THREAD

**Issue by bijendrabio** [oushujun/EDTA#339]
Hello,
Curious if there a way to generate softmasked genome as output, or convert the hardmasked output to softmask format using EDTA? 
Does EDTA generates corresponding gff3 file for *.mod.MAKER.masked file?

Kindly suggest!

Regards,
B

**Comment by oushujun** [comment]
#166

**Comment by oushujun** [comment]
No, EDTA does not generate gff3 file for *.mod.MAKER.masked file, but you may generate it yourself, which is a simple length filter for entries >1000bp from the TEanno.gff3 file.

Shujun
