### ISSUE TITLE
RepeatMasker

### ISSUE THREAD

**Issue by jia-wu-feng** [oushujun/EDTA#340]
Dear shujun,

   I got error like this. I try to run RepeatMasker command, and it successfully finished.

Thanks,
Jiawu
ERROR: RepeatMasker is not running properly!
        Please check the file hbogdanii_pseudomolecules_v2+unanchored_contigs.fasta.contig.2.fa.mod.ltrTE.mask.lib and hbogdanii_pseudomolecules_v2+unanchored_contigs.fasta.contig.2.fa.mod.ltrTE.trunc and test run:
                RepeatMasker -e ncbi -q -pa 50 -no_is -norna -nolow -div 40 -lib hbogdanii_pseudomolecules_v2+unanchored_contigs.fasta.contig.2.fa.mod.ltrTE.mask.lib -cutoff 225 hbogdanii_pseudomolecules_v2+unanchored_contigs.fasta.contig.2.fa.mod.ltrTE.trunc
Please report errors to https://github.com/oushujun/LTR_retriever/issues
Program halt!
awk: fatal: cannot open file `hbogdanii_pseudomolecules_v2+unanchored_contigs.fasta.contig.2.fa.mod.pass.list' for reading (No such file or directory)
Warning: LOC list - is empty.

Error: Error while loading sequence
        perl filter_gff3.pl file.gff3 file.list > new.gff3

**Comment by oushujun** [comment]
May be you can simplify the file name and test again. The "+" sign is usually not used in file names which is a red flag for me.

Shujun

**Comment by jia-wu-feng** [comment]
Thanks, it worked.
