### ISSUE TITLE
Whether curatedlib will be processed (remove redundancy and filter) before generating Final TE library used for annotation?

### ISSUE THREAD

**Issue by Taoo777** [oushujun/EDTA#345]
Hi @oushujun! firstly, thank you for establishing EDTA pipeline, it's very useful for TEs annotation of non-model organism genome and has helped me a lot.

I have a small question about curatedlib processing. I wonder whether the curated library that I added will be processed together with RepeatModeler results to remove redundancy and filter and then generate the Final TE library used for annotation? Or does EDTA do nothing to input curated library and directly merge it with RepeatModeler results to generate Final TE library?

Looking forward to your reply!

**Comment by oushujun** [comment]
Hello,
 
Thank you for using EDTA. For the curated library, it will be directly merged into the final library, so be cautious about what you put in it. You will need to format the curated library as in the RepeatMasker library format to be recognized by EDTA/Repeatmasker. For the EDTA library or the RepeatModeler library, their redundancy will be removed by comparing to the curated library if provided.
 
Thanks,
Shujun
