### ISSUE TITLE
Why the highly similar sequence didn't be annotated as a Mutator transposon?

### ISSUE THREAD

**Issue by leon945945** [oushujun/EDTA#348]
Initially, I find a 1.2kb sequence insertion on promoter of one certain gene at chr1:14838138-14841138, then I blast it to the whole genome TE sequences annotated by EDTA, it was highly similar with an intact Mutator transposon which located at chr1:14881719-14882938 with only 11 gaps as shown below (query was the 1.2kb insertion sequence, subject was the intact Mutator):
![图片1](https://user-images.githubusercontent.com/61004157/229813770-0370f907-ae03-44f1-b2cc-a3444c4317d3.png)
![图片2](https://user-images.githubusercontent.com/61004157/229813801-aa3a9387-39da-4e30-8906-c7a449e0eff0.png)
They have the identical TIR and only 11 gaps, why the 1.2kb sequence didn't be annotated as a Mutator transposon?
Thank you.

**Comment by oushujun** [comment]
Hello, was this sequence annotated as something else or not at all?
