### ISSUE TITLE
TE differences between different rice varieties

### ISSUE THREAD

**Issue by yingnansun** [oushujun/EDTA#349]
Hello.
I'm a layman, I've heard of EDTA before, but have not tried it, I've recently paid more attention to MITE, I noticed that Databases inside the rice6.9.5.liban, it is the output of EDTA and manually correct the results? I only found about 10w MITEs in the file annotated by RepeatMasker in rice6.9.5.liban, but there are reports of 18w in Nip. My main concern is whether these transposons will be very different in different rice varieties (e.g. between japonica and indica)? Can I use rice6.9.5.liban as lib to annotate between different rice genomes?

                                                                                                                                                                          I would appreciate it, thanks!

**Comment by oushujun** [comment]
Hi,

Yes you may. If you want to annotate novel MITEs you may use EDTA in
combination with the rice library.

Best,
Shujun
