### ISSUE TITLE
ERROR: Final TE library not found in genome.fa.mod.EDTA.TElib.fa at /biodata/biosoft/conda/envs/EDTA/share/EDTA/EDTA.pl line 578.

### ISSUE THREAD

**Issue by Keliang-Lyu** [oushujun/EDTA#351]
Hi shujun!
I use EDTA (EDTA.pl --genome genome.fa --species others --sensitive 0 --anno 1 --threads 20 --curatedlib RepBase_rosids.fa --step final --overwrite 1） but get the error below. I do not know what's wrong with it, can you help me ?

########################################################
########################################################

Thu Apr 13 23:03:10 CST 2023    Dependency checking:
                                All passed!

Thu Apr 13 23:03:13 CST 2023    The longest sequence ID in the genome contains 52 characters, which is longer than the limit (13)
                                Trying to reformat seq IDs...
                                Attempt 1...
Thu Apr 13 23:03:14 CST 2023    Seq ID conversion successful!

        A custom library RepBase_rosids.fa is provided via --curatedlib. Please make sure this is a manually curated library but not machine generated.

Thu Apr 13 23:03:15 CST 2023    Perform EDTA final steps to generate a non-redundant comprehensive TE library:

cp: cannot stat '../genome.fa.mod.EDTA.combine/genome.fa.mod.LTR.TIR.Helitron.fa.stg1': No such file or directory
cp: cannot stat '../genome.fa.mod.EDTA.raw/genome.fa.mod.EDTA.intact.fa': No such file or directory
cp: cannot stat '../genome.fa.mod.EDTA.raw/genome.fa.mod.EDTA.intact.gff3': No such file or directory
                                Skipping the RepeatModeler step (--sensitive 0).
                                Run EDTA.pl --step final --sensitive 1 if you want to use RepeatModeler.

cp: cannot stat 'genome.fa.mod.LTR.TIR.Helitron.fa.stg1': No such file or directory
cp: cannot stat 'genome.fa.mod.LTR.TIR.Helitron.others.fa.stg2.clean': No such file or directory
                                Skipping the CDS cleaning step (--cds [File]) since no CDS file is provided or it's empty.

cp: cannot stat 'genome.fa.mod.EDTA.raw.fa': No such file or directory
cp: cannot stat 'genome.fa.mod.EDTA.intact.fa.raw': No such file or directory

Input not found!
ERROR: Final TE library not found in genome.fa.mod.EDTA.TElib.fa at /biodata/biosoft/conda/envs/EDTA/share/EDTA/EDTA.pl line 578.

**Comment by oushujun** [comment]
You can't skip the previous steps and jump directly to the `anno` step if previous steps have never run or have not finished.

Shujun

**Comment by Keliang-Lyu** [comment]
> 

Thank you very much for your reply.
Yes, I skip the previous steps.
The program works perfectly after dropping the `step` parameter.
Keliang
