### ISSUE TITLE
Get trouble when use EDTA to annotate Repbase sequences

### ISSUE THREAD

**Issue by unavailable-2374** [oushujun/EDTA#356]
Hi

I tried running EDTA directly on the Repbase sequences, but the results were poor, with only 5% of the sequences being identified as TEs. I then inserted it into a random section of non-TE sequence, and no TEs were detected either.

Did I make any mistakes? 

best 
Cao

**Comment by oushujun** [comment]
EDTA was not designed to rediscover repeats from individual repeats. You will need some flanking sequences surrounding the target to allow EDTA to check for structural features. Please read the paper for more info.

Best,
Shujun

**Comment by unavailable-2374** [comment]
thanks for you reply.
