### ISSUE TITLE
How to treat high helitron results ？

### ISSUE THREAD

**Issue by zhangwenda0518** [oushujun/EDTA#357]
The respect teacher  ：
     I used EDTA to analyze my genome and got a high proportion of helitron prediction results. I got different but high results on the two versions of the genome.Then I tried to use repeatMasker, repeatModeler and https://github.com/dontkme/EAHelitron for analysis, and their results were all very low.
I read the issue [#](https://github.com/oushujun/EDTA/issues/90)   and https://github.com/oushujun/EDTA/issues/206 ，Cyperaceae species are my close relatives, and for a high proportion of helitron, 

Can you give me some advice to analyze why it is so high? Or do you think it is a false alarm? How can I adjust the parameters of EDTA?

![微信图片_20230427164115](https://user-images.githubusercontent.com/77140740/234808529-633538c9-4afb-43cd-a33a-b439f4a06154.png)
![微信图片_202304271641151](https://user-images.githubusercontent.com/77140740/234808539-5f99d044-436b-492b-bf00-ea9b13a5611f.png)
![微信图片_202304271641152](https://user-images.githubusercontent.com/77140740/234808544-dcf6b9e3-ab0d-4bac-9839-e1e8e352f6d8.png)
![微信图片_202304271641153](https://user-images.githubusercontent.com/77140740/234808547-49c39de5-1905-48aa-9c81-c8a7b757a4ea.png)

**Comment by oushujun** [comment]
The suggestions from #206 and #90 are still valid. You may keep the structural helitrons and discard the fragment annotations to be conservative, but then you will have a lower sensitivity. RepeatModeler2 for identitying helitorns is not sensitive at all, so you see low percentage.
