### ISSUE TITLE
Chromosome names from $genome.EDTA.intact.gff3 are different with my genome file chromosome names 

### ISSUE THREAD

**Issue by qjiangzhao** [oushujun/EDTA#358]
Dear Shujun,

I found EDTA will short chromosome name when it is too long and the final $genome.EDTA.intact.gff3 and $genome.EDTA.TEanno.gff3 is based on the modified chromosome name. This will lead to a problem if I want to get fasta sequences based on those gff3 files. I guess there must be a reason you have to modify the name. But that will be good if you can supply a file containing the original and modified chromosome names. 

For example, this is my original chromosome name:
<img width="107" alt="image" src="https://user-images.githubusercontent.com/75024559/235365175-ad425505-8549-477b-8c3e-6e85eaf35b99.png">
But from my $genome.EDTA.intact.gff3 file, they are:
<img width="281" alt="image" src="https://user-images.githubusercontent.com/75024559/235365231-5a5472b8-ecae-4c90-86fa-c1be7fca5f40.png">

Yours sincerely
Jiangzhao

**Comment by oushujun** [comment]
Please read README or the wiki.

TThanks,
Shujun
