### ISSUE TITLE
about the step of re-annotate all genomes with the panEDTA library

### ISSUE THREAD

**Issue by Scy-bio** [oushujun/EDTA#359]
Dear shujun,
I refer to pipeline of the pan-genome annotation [example](https://github.com/HuffordLab/NAM-genomes/tree/master/te-annotation) and the sequential version of [panEDTA.sh](https://github.com/oushujun/EDTA/blob/master/panEDTA.sh). I hope to use the panEDTA to compare repeat sequences from a group of closely related species, like this [article](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9075770/).

The command given in the step of re-annotate all genomes with the panEDTA library is as follows：
1. Re-mask all genomes with the pan-genome TE lib：
`RepeatMasker -pa 36 -q -div 40 -lib $panEDTA.TElib.fa -cutoff 225 -gff $genome.mod`
2. Re-run EDTA final on each genome：
`perl $path/EDTA.pl --genome $genome -t $threads --step final --anno 1 --curatedlib $panEDTA.TElib.fa --cds $cds --rmout $genome.mod.out`

The question is，
The result of Re-mask all genomes with the pan-genome TE lib by RepeatMasker seems good, as I got a higher percentage for repeats annotation. However, the result of Re-run EDTA, the percentage for repeats annotation is lower than the first EDTA annotation (the result of executing EDTA annotation of each genome separately).

And the another question is，
Is there any difference between the result obtained by this step and directly running the following command?
`EDTA.pl --genome genome --cds $cds --curatedlib $panEDTA.TElib.fa --step anno --anno 1 -t $threads --overwrite 1`

The result of this coomand is good，I got a higher percentage for repeats annotation.

**Comment by oushujun** [comment]
Hello,

You may want to experiment with the -f parameter which helps to filter out
false positives accumulated while adding more genomes. If you see decreased
TE proportion you may want to lower the -f to 2 or even 1.

Preannotated RM.out files are needed for the purpose of copy number
counting for the -f parameter.

Let me know how it goes.

Thanks,
Shujun

**Comment by Scy-bio** [comment]
Thanks for your quick reply. 

In fact, I kept all full-length TEs from each genome, as you advised using parameters -f=1. And I found a similar question #293. I think decreased TE proportion may be related to the "Re-run EDTA final" step. 

Best,
Chenyu
