### ISSUE TITLE
Which lib should I use  for Analysis about the animal genome?

### ISSUE THREAD

**Issue by zyworship** [oushujun/EDTA#36]
Hi, dear professor Shujun,
I want to use EDTA to analysis some animal genome for de nove predict the TE.  However, It looks like  the EDTA's lib has Rice, I don't find a parameter for specify an animal lib.
Could the EDTA specify an animal lib? And, How about the effect of EDTA work on animal?

ZhangYi.

**Comment by oushujun** [comment]
Dear ZhangYi,

EDTA was developed using the rice genome for benchmarking and have comparable results in both maize and drosophila. For benchmarking results, please read our [paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1905-y) for more details. It does not require a library to run EDTA, but if you have a curated library for your species, it will help to preserve the historical curation efforts in the EDTA result. Please let me know if you have more questions.

Best,
Shujun
