### ISSUE TITLE
A new error for LTR

### ISSUE THREAD

**Issue by SC-Duan** [oushujun/EDTA#364]
Hi, when I test EDTA in conda EDTA environment with "EDTA.pl --genome genome.fa --cds genome.cds.fa --curatedlib ../database/rice6.9.5.liban --exclude genome.exclude.bed --overwrite 1 --sensitive 1 --anno 1 --evaluate 1 --threads 10", I got an error:

Sat May 27 15:36:22 CST 2023    Dependency checking:
                                All passed!

        A custom library ../database/rice6.9.5.liban is provided via --curatedlib. Please make sure this is a manually curated library but not machine generated.

        A CDS file genome.cds.fa is provided via --cds. Please make sure this is the DNA sequence of coding regions only.

        A BED file is provided via --exclude. Regions specified by this file will be excluded from TE annotation and masking.

Sat May 27 15:36:30 CST 2023    Obtain raw TE libraries using various structure-based programs:
Sat May 27 15:36:30 CST 2023    EDTA_raw: Check dependencies, prepare working directories.

Sat May 27 15:36:33 CST 2023    Start to find LTR candidates.

Sat May 27 15:36:33 CST 2023    Identify LTR retrotransposon candidates from scratch.

Invalid value for shared scalar at ~/soft/anaconda3/envs/edta/share/LTR_retriever/bin/LTR.identifier.pl line 114, <ANNO> line
 11.
cp: cannot stat 'genome.fa.mod.retriever.scn.adj': No such file or directory
awk: fatal: cannot open file `genome.fa.mod.pass.list' for reading (No such file or directory)
Warning: LOC list - is empty.

Error: Error while loading sequence
        perl filter_gff3.pl file.gff3 file.list > new.gff3

Sat May 27 15:37:02 CST 2023    Warning: The LTR result file has 0 bp!

Sat May 27 15:37:02 CST 2023    Start to find TIR candidates.

Sat May 27 15:37:02 CST 2023    Identify TIR candidates from scratch.

Species: others
Sat May 27 15:38:39 CST 2023    Finish finding TIR candidates.

Sat May 27 15:38:39 CST 2023    Start to find Helitron candidates.

Sat May 27 15:38:39 CST 2023    Identify Helitron candidates from scratch.

Sat May 27 15:40:09 CST 2023    Finish finding Helitron candidates.

Sat May 27 15:40:09 CST 2023    Execution of EDTA_raw.pl is finished!

ERROR: Raw LTR results not found in genome.fa.mod.EDTA.raw/genome.fa.mod.LTR.raw.fa
        If you believe the program is working properly, this may be caused by the lack of intact LTRs in your genome. Consider to use the --
force 1 parameter to overwrite this check

I install the EDTA by Conda.
How should I check the problem?
Thank you!

**Comment by SC-Duan** [comment]
Same as https://github.com/oushujun/LTR_retriever/issues/153

**Comment by SC-Duan** [comment]
Well, the version of LTR_retriever is 2.9.x under automatic conda installation. Downgrading to 2.8.x and it woks.

**Comment by oushujun** [comment]
Thank you for catching the bug. I will look into the recent LTR_retriever
update and see what's going on.

Shujun
