### ISSUE TITLE
Please!

### ISSUE THREAD

**Issue by ZhouTaoWang** [oushujun/EDTA#366]
![78fe891613d1b2dce82a658a3a6863f](https://github.com/oushujun/EDTA/assets/41276492/0351035c-69d4-4ccb-8141-bf0a7a52ed9a)

**Comment by ZhouTaoWang** [comment]
The Genome size is 12Gb

**Comment by oushujun** [comment]
From the error message you don't have enough memory. Consider to split the
genome into smaller chunks like 2gb, and run them in pan-genome mode.

Shujun
