### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Chipcui** [oushujun/EDTA#37]
Dear Shujun,

When I run the EDTA with `EDTA/EDTA.pl -genome non-redundant.shortname.fa -species others -step all -t 28`, but it got some error when identify TIR candidates as following:
```
EDTA/bin/TIR-Learner2.4/Module2/RunGRF.py", line 79, in <module>
    if (len(str(records[0].seq))>int(length)+500):
IndexError: list index out of range
```
So how I can fix this error, Thank you!

**Comment by oushujun** [comment]
Dear @Chipcui,

This is a strange error because when you run EDTA with `-species others`, TIR-Learner will not run Module2. Please update EDTA to v1.7 if you have not done so and try again.

Best,
Shujun

**Comment by Chipcui** [comment]
Yes, I have updated to EDTA v1.7, but it also have this error.

**Comment by oushujun** [comment]
Please test it on the Arabidopsis or Drosophila genome with the same parameter. If possible you may try to make a reproducible dataset for me to test on.

**Comment by oushujun** [comment]
Close due to inactivity. Please reopen it if the issue is not resolved.
