### ISSUE TITLE
Assigning manual $protlib

### ISSUE THREAD

**Issue by sahoo-rk** [oushujun/EDTA#370]
Hello @oushujun 
I am aware that $protlib in EDTA is used for limited filtering of TE library. -cds file is therefore more critical in TE filtering. However, if I wish to provide a manual library as $protlib, how do I proceed? There's no direct option to use $protlib option during EDTA.pl execution. As I checked the EDTA scripts, three files utilize $protlib option: EDTA.pl, EDTA_processI.pl and cleanup_proteins.pl. My concern is as follows:
1. Do I need to manually edit the above-mentioned script files at the option $protlib? Are there any other scripts that takes $protlib option?
2. If editing the scripts is not a right way, how shall I proceed?

Please excuse my brevity, if any. Thanks for developing this brilliant tool.

best,

**Comment by oushujun** [comment]
Hello,

LTR_retriever also uses the same scheme to Remove protein contaminations.
If you want to use a new protein file, you need to benchmark the new file
in several model species to make sure the new file won't harm the
sensitivity too much, Then replace the original file. There is no such
option straightforwardly at the moment.

Thanks,
Shujun

**Comment by sahoo-rk** [comment]
Thanks Shujun. Its clear now.
