### ISSUE TITLE
No TE_struc_xxx file generated

### ISSUE THREAD

**Issue by shiyi-pan** [oushujun/EDTA#371]
Hi, shujun
I try to use EDTA to annotate my genome sequence. Here is my script:

perl ./EDTA.pl --genome ptg000001l.fa --species others --step all --overwrite 1 --threads  8 --sensitive 1 --anno 1 --evaluate 1

The program did not report any errors but don't generate the "TE_struc_xxx" file which means to be annotated by structural methods.

Here is my ptg000001l.fa.mod.EDTA.anno directory:

ptg000001l.fa.mod                                                     ptg000001l.fa.mod.EDTA.TEanno.bed.iter7   ptg000001l.fa.mod.EDTA.TE.fa.iter7
ptg000001l.fa.mod.cat.gz                                              ptg000001l.fa.mod.EDTA.TEanno.bed.iter8   ptg000001l.fa.mod.EDTA.TE.fa.iter8
ptg000001l.fa.mod.EDTA.homo.bed                                       ptg000001l.fa.mod.EDTA.TEanno.bed.iter9   ptg000001l.fa.mod.EDTA.TE.fa.iter9
ptg000001l.fa.mod.EDTA.homo.gff3                                      ptg000001l.fa.mod.EDTA.TEanno.gff3        ptg000001l.fa.mod.EDTA.TE.fa.stat
ptg000001l.fa.mod.EDTA.intact.bed                                     ptg000001l.fa.mod.EDTA.TEanno.out         ptg000001l.fa.mod.EDTA.TE.fa.stat.all.sum
ptg000001l.fa.mod.EDTA.intact.bed.cmb                                 ptg000001l.fa.mod.EDTA.TEanno.split.bed   ptg000001l.fa.mod.EDTA.TE.fa.stat.nested.sum
ptg000001l.fa.mod.EDTA.intact.bed-ptg000001l.fa.mod.EDTA.RM.bed       ptg000001l.fa.mod.EDTA.TEanno.split.gff3  ptg000001l.fa.mod.EDTA.TE.fa.stat.redun.sum
ptg000001l.fa.mod.EDTA.intact.bed-ptg000001l.fa.mod.EDTA.RM.bed.homo  ptg000001l.fa.mod.EDTA.TEanno.sum         ptg000001l.fa.mod.EDTA.TElib.fa
ptg000001l.fa.mod.EDTA.intact.gff3                                    ptg000001l.fa.mod.EDTA.TE.fa              ptg000001l.fa.mod.EDTA.TElib.fa.ndb
ptg000001l.fa.mod.EDTA.RM.bed                                         ptg000001l.fa.mod.EDTA.TE.fa.cln          ptg000001l.fa.mod.EDTA.TElib.fa.nhr
ptg000001l.fa.mod.EDTA.RM.bed-ptg000001l.fa.mod.EDTA.intact.bed.cmb   ptg000001l.fa.mod.EDTA.TE.fa.iter0        ptg000001l.fa.mod.EDTA.TElib.fa.nin
ptg000001l.fa.mod.EDTA.RM.gff3                                        ptg000001l.fa.mod.EDTA.TE.fa.iter1        ptg000001l.fa.mod.EDTA.TElib.fa.not
ptg000001l.fa.mod.EDTA.RM.out                                         ptg000001l.fa.mod.EDTA.TE.fa.iter10       ptg000001l.fa.mod.EDTA.TElib.fa.nsq
ptg000001l.fa.mod.EDTA.TEanno.bed                                     ptg000001l.fa.mod.EDTA.TE.fa.iter11       ptg000001l.fa.mod.EDTA.TElib.fa.ntf
ptg000001l.fa.mod.EDTA.TEanno.bed.iter1                               ptg000001l.fa.mod.EDTA.TE.fa.iter12       ptg000001l.fa.mod.EDTA.TElib.fa.nto
ptg000001l.fa.mod.EDTA.TEanno.bed.iter10                              ptg000001l.fa.mod.EDTA.TE.fa.iter13       ptg000001l.fa.mod.MAKER.masked
ptg000001l.fa.mod.EDTA.TEanno.bed.iter11                              ptg000001l.fa.mod.EDTA.TE.fa.iter14       ptg000001l.fa.mod.masked
ptg000001l.fa.mod.EDTA.TEanno.bed.iter12                              ptg000001l.fa.mod.EDTA.TE.fa.iter15       ptg000001l.fa.mod.out
ptg000001l.fa.mod.EDTA.TEanno.bed.iter2                               ptg000001l.fa.mod.EDTA.TE.fa.iter2        ptg000001l.fa.mod.out.new
ptg000001l.fa.mod.EDTA.TEanno.bed.iter3                               ptg000001l.fa.mod.EDTA.TE.fa.iter3        ptg000001l.fa.mod.out.new.bed
ptg000001l.fa.mod.EDTA.TEanno.bed.iter4                               ptg000001l.fa.mod.EDTA.TE.fa.iter4        ptg000001l.fa.mod.out.new.bed.cbi
ptg000001l.fa.mod.EDTA.TEanno.bed.iter5                               ptg000001l.fa.mod.EDTA.TE.fa.iter5        ptg000001l.fa.mod.out.target.bed
ptg000001l.fa.mod.EDTA.TEanno.bed.iter6                               ptg000001l.fa.mod.EDTA.TE.fa.iter6        ptg000001l.fa.mod.tbl

Could you give me some advice? Thank you again.

**Comment by oushujun** [comment]
You can find them here ptg000001l.fa.mod.EDTA.intact.gff3 or here
ptg000001l.fa.mod.EDTA.TEanno.gff3

Shujun

**Comment by shiyi-pan** [comment]
Thank you very much for your reply. 
I checked ptg000001l.fa.mod.EDTA.intact.gff3 and ptg000001l.fa.mod.EDTA.TEanno.gff3 file and find some TEs which ID is "TE_struc_XXX". Is the current version of EDTA not generating the 'TE_struc_xxx' file to save annotated by structural methods?

Best wishes.

**Comment by oushujun** [comment]
Hello,

The two files you Checked contain structural TE annotations. I not sure
what you are looking for.

Shujun

**Comment by shiyi-pan** [comment]
sorry for to bother you.
I think I misunderstood the content of question 4 in Q&A (https://github.com/oushujun/EDTA/wiki/Making-sense-of-EDTA-usage-and-outputs---Q&A). 
Question 4 mentions "TE_homo_xxx" and "TE_struc_xxx". In my results file, there is a "xxx_homo_xxx" file, so I subconsciously think that there should also be a "xxx_struc_xxx" file to store TEs detected based on structural methods.
Now I know that there is no 'xxx_struc_xxx' file to store TEs detected based on the structural method, but rather TEs labled with 'TE_struc_xxx' in the file such as ptg000001l.fa.mod.EDTA.TEanno.gff3, indicating that the TE was detected based on the structural method.

Thank you for your reply again.
best wishes
 shujun

**Comment by oushujun** [comment]
This file `ptg000001l.fa.mod.EDTA.intact.gff3` contains all elements detected by the structural method.

shujun
