### ISSUE TITLE
Annotation issue still there in v2.1.3

### ISSUE THREAD

**Issue by sahoo-rk** [oushujun/EDTA#372]
Hi Shujun,
With the **EDTA v2.1.3, TE** identification and annotation completed. But with an **empty .sum** file, along with the following messages. I guess, I can safely ignore the first two warnings. However, the last one seems the problem for an empty .sum file (previously discussed here #171 ,#219 , #229 ).  

1. polinton/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
2. Warning: TIR/Sola1 not found in the TE_SO database, will use the general term 'repeat_region	SO:0000657' to replace it.
3. Use of uninitialized value $type in concatenation (.) or string at /home/sahoork/EDTA/util/gff2bed.pl line 110, <GFF> line 2069.

How to fix this? The temporary solution discussed at #219 doesn't meet the exact line number in current gff2bed.pl file. Please suggest.

Best,
-sahoo

**Comment by oushujun** [comment]
Hi Sahoo,

Sorry, somehow I missed this thread. Please replace the following two files in /EDTA/util/ and try again.
[gff2bed.txt](https://github.com/oushujun/EDTA/files/12389138/gff2bed.txt) (rename `txt` to `pl`)
[TE_Sequence_Ontology.txt](https://github.com/oushujun/EDTA/files/12389146/TE_Sequence_Ontology.txt)

Let me know how it goes, thanks!

Shujun

**Comment by sahoo-rk** [comment]
It works fine now. Thanks.
