### ISSUE TITLE
Fasta file issue

### ISSUE THREAD

**Issue by Ramkyeri** [oushujun/EDTA#374]
Dear @oushujun 

Many thanks for developing this very useful tool. 

it is not accepting cds fasta file. 

this is my file format

<img width="1682" alt="image" src="https://github.com/oushujun/EDTA/assets/70749594/cb52e043-9453-4bef-90c7-9f00973a6ee3">

with regards

Ramky

**Comment by oushujun** [comment]
Hi Ramky,

Can you provide the error message here? Thanks

Shujun

**Comment by oushujun** [comment]
@Ramkyeri any luck?

**Comment by Ramkyeri** [comment]
Dear Shujun,
Thank you for your message. I will update you soon.  sorry for the delay.

with regards

Ramky

**Comment by Ramkyeri** [comment]
Dear Shujun, 
Greetings!
Many thanks for your kindness. I am so sorry for the dealyed response. 

This is the error:  

########################################################
##### Extensive de-novo TE Annotator (EDTA) v2.0.0  ####
##### Shujun Ou (shujun.ou.1@gmail.com)             ####
########################################################



Sat Aug 26 02:59:05 UTC 2023	Dependency checking:
				All passed!

	ERROR: The CDS file Phyllostachys_edulis_V1.cds you specified is not found!


with regards 

Ramky

**Comment by Ramkyeri** [comment]
Dear Shujun, 
It is not accepting cds file,  I donot know the reason, 
Now I am running without cds file  using nohup command, 
I am using our server,   after closing the terminal,  EDTA is not running. 

with regards 
Ramky

**Comment by oushujun** [comment]
Can you provide the command you used that has the error?

**Comment by Ramkyeri** [comment]
Dear Shujun, 

This is the command  

nohup singularity exec EDTA.sif EDTA.pl --genome genome.fa --overwrite 1 --sensitive 1 --anno 1 --evaluate 1 --threads 25

with regards
Ramky

**Comment by oushujun** [comment]
I see. There may be some issues of passing files to the container. You may want to use the conda version instead of docker/singularity.

Shujun

**Comment by Ramkyeri** [comment]
Dear Shujun,  

Thank you,   Conda version needs many dependencies.  

with regards 

Ramky

**Comment by oushujun** [comment]
Yup. They can be installed through: `conda env create -f EDTA.yml`

Shujun

**Comment by Ramkyeri** [comment]
Dear Shujun, 
Thank you for your kind response. I will update you further results. 
with regards
Ramky

**Comment by Ramkyeri** [comment]
Dear Shujun,

As per your suggestion,  I used conda env create -f EDTA.yml,  

I got the following while running the code, 

perl ../EDTA.pl --genome genome.fa --cds genome.cds.fa --curatedlib ../database/rice6.9.5.liban --exclude genome.exclude.bed --overwrite 1 --sensitive 1 --anno 1 --evaluate 1 --threads 10


gt is not found in the genometools path ./!


with regards 

ramky

**Comment by oushujun** [comment]
Hi Ramky,

That means EDTA is not correctly installed. Please reinstall and try again.

Shujun

**Comment by Ramkyeri** [comment]
Dear Shujun, 
Thanks for your kind reply. I will update you. 
with regards

ramky

**Comment by Ramkyeri** [comment]
Dear Shujun,  

I have re-installed EDTA.yml,  interestingly conda environment accepted cds file,   but singularity did not accept the cds file.

thank you I will update you the results. 


########################################################
##### Extensive de-novo TE Annotator (EDTA) v2.0.1  ####
##### Shujun Ou (shujun.ou.1@gmail.com)             ####
########################################################



Thu Sep 14 02:45:50 AM UTC 2023	Dependency checking:
				All passed!

	A CDS file sequence.cds.fasta is provided via --cds. Please make sure this is the DNA sequence of coding regions only.

Thu Sep 14 02:46:05 AM UTC 2023	Obtain raw TE libraries using various structure-based programs: 
Thu Sep 14 02:46:05 AM UTC 2023	EDTA_raw: Check dependencies, prepare working directories.

Thu Sep 14 02:46:08 AM UTC 2023	Start to find LTR candidates.

Thu Sep 14 02:46:08 AM UTC 2023	Identify LTR retrotransposon candidates from scratch.


with regards 
ramky

**Comment by Ramkyeri** [comment]
Dear @oushujun 

Thed EDTA is runing more than 45 days, now it is in slow step,  I do not know how long it will take to complete this slow stop,  but this is the last step. 

with regards 
Ramky

**Comment by oushujun** [comment]
Which step exactly? The evaluation step is not necessary for annotation.
Thanks!

Shujun

**Comment by Ramkyeri** [comment]
Dear @oushujun 
this step
Wed Oct  4 01:23:37 PM UTC 2023	Evaluate the level of inconsistency for whole-genome TE annotation (slow step):

with regards
Ramky

**Comment by oushujun** [comment]
Yes this is the evaluation step I mentioned

Shujun

**Comment by Ramkyeri** [comment]
Dear @oushujun 
Thank you for your reply.  So,  I can just stop the program using Kill command.  
with regards
Ramky

**Comment by Ramkyeri** [comment]
Dear @oushujun 

Finally it is completed,  

Wed Oct  4 01:23:37 PM UTC 2023	Evaluate the level of inconsistency for whole-genome TE annotation (slow step):

Wed Nov 29 12:14:57 PM UTC 2023	Evaluation of TE annotation finished! Check out these files:

				Overall: sequence.fasta.mod.EDTA.TE.fa.stat.all.sum
				Nested: sequence.fasta.mod.EDTA.TE.fa.stat.nested.sum
				Non-nested: sequence.fasta.mod.EDTA.TE.fa.stat.redun.sum
