### ISSUE TITLE
TE comparsions in different species

### ISSUE THREAD

**Issue by YuboWang1994** [oushujun/EDTA#376]
Hi,

I truly appreciate your development of the EDTA pipeline, which has been immensely helpful to me. However, I have a small issue that I would like to trouble you with.

I am currently researching four plant genomes from the same Family. I have annotated repetitive sequences using the EDTA pipeline for each genome and obtained the corresponding non-redundant TE library. My next research step is comparing compositional differences in repetitive sequences within the sex-determining regions of these four genomes, such as copy numbers and sequence compositions. However, since each genome was annotated separately with EDTA, the four non-redundant TE libraries might contain the same TE IDs like TE_00000000, making direct comparisons challenging. 

Considering that these four species share a common Family and exhibit high sequence and gene collinearity, I've designed the following approach:

1. Classify each non-redundant TE library based on sequence types, such as TIR, helitron, LTR-gypsy, LTR-copia, LTR-unknown, etc.
2. Merge TE sequences of the same type from the four genomes, remove redundancy using CD-HIT, and rename sequence IDs.
3. Perform subsequent analyses using the new IDs, such as comparing copy number and compositional differences of the same TE across different species.

Does this sequence similarity-based approach for merging non-redundant TE libraries seem scientifically make sense?

I'm appreciate your help.

**Comment by oushujun** [comment]
Hello,

Please check out panEDTA for this purpose.

Thanks!
Shujun

**Comment by YuboWang1994** [comment]
Hi,

Thanks for your help. It seems work.

Best
Yubo Wang
