### ISSUE TITLE
stats file is null

### ISSUE THREAD

**Issue by HaoWenhy** [oushujun/EDTA#377]
Hello, after my EDTA annotation, there is no sum stats file, I follow the question [#169](https://github.com/oushujun/EDTA/issues/169) to process and distribute to get the bed, out and stats file, and then use buildSummary.pl to build the sum stats file, I don't know why, my stats file is still null, and there is no other error, I hope you can answer, thank you very much!

**Comment by oushujun** [comment]
Do you have a non-empty TEanno.gff3 file? Any errors during the run?

Shujun

**Comment by HaoWenhy** [comment]
Yes, the TEanno.gff3 files all have data, I have run a total of three genomes and all of them came up with no sum file and after going to fix it according to problem [#169](https://github.com/oushujun/EDTA/issues/169), none of them worked. There are two errors reported throughout the EDTA run:
ERROR: Can not recognize this MSU position in the list!
ERROR: TE annotation stats results not found in finall.fasta.mod.EDTA.TE.fa.stat!
I'm looking forward to your advice.

**Comment by HaoWenhy** [comment]
For the EDTA annotations for all three genes, the error reported is the same, no stats file for any of them. However I went through gff2bed.pl, Convert bed to RepeatMasker .out, count_base.pl, buildSummary.pl, to generate TEanno.bed, TEanno.out, $genome.stats, and TEanno.sum respectively . Finally TEanno.sum is an empty file. I'm not sure what's wrong with it, please advise!

**Comment by oushujun** [comment]
I don't know how to debug without error messages. Can you give a small example to reproduce your issue?

**Comment by xujialupaoli** [comment]
Hi shujun!
I have the similar error, and my TEanno.gff3 files all have data.
I am using EDTA  (perl /home/jialu/jialusoftware/EDTA-master/EDTA.pl --genome /home/work/jialu/Mt/Drive/new_res/MtrunR108.changed.fasta --cds /home/work/jialu/Mt/Drive/new_res/MtrunR108.changed.cdsNEW.fa --exclude /home/work/jialu/Mt/Drive/new_res/MtrunR108
), but this time the script ended with
 ERROR: Can not recognize this MSU position in the list!
ERROR: TE annotation stats results not found in MtrunR108.changed.fasta.mod.EDTA.TE.fa.stat!


I'm not sure what's wrong with it, please advise!

My EDTA version is v2.1.3

Thank you! : )

![image](https://github.com/oushujun/EDTA/assets/96410022/b3aed6e4-a16a-43a5-b711-685b3e47d45c)
![image](https://github.com/oushujun/EDTA/assets/96410022/6384767f-a090-4365-bee3-c8eeb390a2bb)
![image](https://github.com/oushujun/EDTA/assets/96410022/16d04204-7477-4128-b774-c273dab84f67)

**Comment by oushujun** [comment]
Hello @xujialupaoli,

Sorry for the delayed response. Have you solved this issue? Looks like the program had issues before it finished the annotation.

Shujun

**Comment by oushujun** [comment]
@xujialupaoli any luck?

**Comment by oushujun** [comment]
Closing due to no response. Please reopen if the issue remains. You may also want to try the v2.2.0 update.
