### ISSUE TITLE
error: LTR_retriever is not found in the LTR_retriever path ./!

### ISSUE THREAD

**Issue by karthickbrlab** [oushujun/EDTA#379]
Dear shujun
I installed EDTA using EDTA.yml
conda env create -f EDTA.yml

Retrieving notices: ...working... done
Collecting package metadata (repodata.json): done
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining conflict for entrez-direct blast rmblast perl-net-http perl-lwp-protocol-https perl-libwww-perl: : 229it [0Examining conflict for entrez-direct perl-html-parser blast perl-html-tree rmblast perl-lwp-protocol-https perl-libwwExamining conflict for entrez-direct perl-html-parser blast perl-html-tree rmblast perl-lwp-protocol-https perl-libwwExamining conflict for rmblast entrez-direct blast: : 231it [07:29, 10.33it/s]                                       Examining conflict for perl-mozilla-ca entrez-direct rmblast perl-lwp-protocol-https blast: : 234it [07:29, 10.51it/sExamining conflict for rmblast entrez-direct perl-lwp-protocol-https blast: : 235it [07:30, 10.51it/s]               Examining conflict for entrez-direct blast rmblast perl-http-negotiate perl-lwp-protocol-https perl-libwww-perl: : 23Examining conflict for entrez-direct blast rmblast perl-http-negotiate perl-lwp-protocol-https perl-libwww-perl: : 23Examining conflict for xorg-libxi xorg-libxtst openjdk xorg-inputproto: : 238it [07:30, 11.99it/s]                   Examining conflict for perl-socket perl-test-requiresinternet perl-lwp-protocol-https perl-libwww-perl: : 241it [07:3Examining conflict for perl-socket perl-test-requiresinternet perl-lwp-protocol-https perl-libwww-perl: : 242it [07:3Examining conflict for xorg-libx11 cairo libxcb xorg-libxau: : 242it [07:30,  7.59it/s]                              failed                                                                                                         - 
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.

*********
While running im getting this error.
error: LTR_retriever is not found in the LTR_retriever path ./!

kinldy help me out to resolve this issue.
bin folder in EDTA  has no LTR retriever. so i downloaded it separately and added to bin folder.

**Comment by oushujun** [comment]
LTR_retriever is installed via conda. You may install it again

Shujun

**Comment by oushujun** [comment]
How did it go? - Shujun

**Comment by karthickbrlab** [comment]
Dear shujun.

Thanks for your kind suggestions. 
The problem were with conda channel priorities.. EDTA got installed properly after setting channel priority flexible.
