### ISSUE TITLE
How to speed up for big genome?

### ISSUE THREAD

**Issue by zyworship** [oushujun/EDTA#38]
Hi dear Shujun,
      I have configured the environment  for computing about the EDTA. 
      But I work on genome for amphibians, the genome size is bigger than other animals. I have run EDTA_raw for TIR, LTR, helitron.`EDTA_raw.pl -genome frog1_genome.chromosome.fa -type tir -thrads 16`. It's been running for 48 hours and it's not finished yet. 
Is there any methods for speed up for big genomes?

Thank you for your attention and reply.

Zhangyi

**Comment by oushujun** [comment]
Dear @zyworship, 

48 hours on a big genome is a VERY short time. You may want to give it a week or more. Think about the time for gene predictions your genome may take, EDTA is no less simple or faster at the moment. Your way of splitting the EDTA_raw.pl is the recommended way to speed up EDTA. While waiting for TIR to finish, you may also run `-type ltr` and `-type helitron` at the same time in the same folder in different jobs.

Best,
Shujun
