### ISSUE TITLE
Question about MITEs

### ISSUE THREAD

**Issue by tongyin121** [oushujun/EDTA#381]
Hello, during the use of EDTA, I found that many MITE transposons are enriched in certain regions of the genome and belong to the same TE family (TE_00001032#MITE/DTM). The sequence is TTGCCTTTGAATTTCGGGTGATCTCTCTTGAGCATGTATGCTTCTGCTACTTGTTCTACATCAGACTTCTTCCGCAAACGGCGAAACGCTTTGACTCGGTGAGTTTCGCGGCATTCCGACTTCGATGCCCCAAATTACC.
 I would like to ask how to verify the validity and accuracy of the annotation results?

**Comment by oushujun** [comment]
Hello, you need to manually curate it. For example, extract the sequence with extension to its flanking for a certain distance, ie. 1000bp, then blast your genome and see if the alignment is only on your candidate TE or extends further out.
