### ISSUE TITLE
Many overlapping regions of TE

### ISSUE THREAD

**Issue by hanxiaoxu1110** [oushujun/EDTA#384]
Dear Dr.Ou

hi

I used EDTA v2.01 to identify TE. but in the genome.fasta.mod.EDTA.TEanno.gff3 check found that there are very many TE overlap regions. As shown below. Do I need to process and filter these overlapping TE? Because I want to do a detailed analysis of TE in this genome. Thanks very much!
<img width="1152" alt="551694140446_ pic" src="https://github.com/oushujun/EDTA/assets/84905582/8bcc7800-812e-4820-8ebb-125b9d0e748c">
Best regards

**Comment by oushujun** [comment]
Hello,

Sorry for the delay. Please check out the wiki to better understand the output gff file. Also, naturally nested structures are prevalent. Misannotations are also likely for cases like tandem repeats.

Shujun
