### ISSUE TITLE
CACTA

### ISSUE THREAD

**Issue by bijendrabio** [oushujun/EDTA#385]
Hello,
EDTA appears to underestimate CACTA content. Could you please kindly confirm it its true @oushujun 

Regards,
B

**Comment by oushujun** [comment]
Dear B,

I don't have such an impression. Can you show some observations?

Shujun

**Comment by oushujun** [comment]
Close due to no response. Please reopen if you have more questions or need any help.

**Comment by oushujun** [comment]
It's hard to know which one is "correct" and neither can be wrong given the state of genome annotation. It can be frustrating if you consider the published number as "correct". To find out, you can evaluate the annotation consistency using `EDTA/util/evaluation.pl` to find out which version of annotation is more consistent, but this still won't tell you which one is more "correct" without manual curation.

Shujun
