### ISSUE TITLE
LAI values from LTRRetrivar

### ISSUE THREAD

**Issue by ankush290307** [oushujun/EDTA#386]
I couldnt find LAI values using the pipeline. Can you please advise me where or how I can get it while running the pipeline.

**Comment by oushujun** [comment]
Asked before: #134
Short answer, EDTA won't compute LAI for you.
Longer answer: you can do it yourself with the output of EDTA: https://github.com/oushujun/EDTA/wiki/Calculate-LAI-from-EDTA-GFF3-files

Hope this helps!
Shujun
