### ISSUE TITLE
LAI 

### ISSUE THREAD

**Issue by Xinxin0314** [oushujun/EDTA#387]
Hi，

I found I met a question that I can't analysis the LAI result.

First, I used the EDTA to identify the TE. Then I used the command "LAI -t 10 -genome /md1200/genome.v1.fa -intact ~/genome.v1.fa.mod.EDTA.raw/LTR/genome.v1.fa.mod.list -all ~/genome.v1.fa.mod.EDTA.final/genome.v1.fa.mod.out &> lai.out &" to calculate the LAI. I got two result files: genome.v1.fa.mod.out, genome.v1.fa.mod.out.LAI.LTR.ava.age and  genome.v1.fa.mod.out.LAI.LTR.ava.out, and, lai.out was empty. While genome.v1.fa.mod.out.LAI.LTR.ava.age only have one line, the content is "Input:zdd0006.genome.v1.fa.mod.out      Seq_num:207806  Mean_identity:94.7854070084853". And another file had large contents.

I would like to know from which file I could obtain LAI values for assessing genome quality.

Thank you~
 Looking forward to your reply.

Best wishes,
Xin

**Comment by oushujun** [comment]
H Xin,

you used the wrong files for -intact and -all. please check out the
relevant issues.

shujun

**Comment by Xinxin0314** [comment]
Hi shujun，

Thank you for reminding me. I solved the problem.

Best wishes,
Xin
