### ISSUE TITLE
Multiple EDTAs in parallel

### ISSUE THREAD

**Issue by chao77777777** [oushujun/EDTA#388]
Hi，
If many EDTAs are run in parallel, such as six or seven, will it have any impact on the speed of a single detection without saturating the server? Because the identification of some species with larger genomes is very slow after I parallelize it.
W,
regards

**Comment by oushujun** [comment]
The IO demand of multiple runs simultaneously will throttle the speed of
each run due to the possibility that your hard drives can not catch up with
the demand. So yes, negative impacts.
