### ISSUE TITLE
LTR_retriever": No such file or directory at /home/ubuntu/deru/EDTA/EDTA_raw.pl line 307.

### ISSUE THREAD

**Issue by karthickbrlab** [oushujun/EDTA#389]
KINDLY LOOK INTO THIS ISSUE.

Thursday 21 September 2023 11:23:36 AM IST	Dependency checking:
				All passed!

Thursday 21 September 2023 11:23:58 AM IST	Obtain raw TE libraries using various structure-based programs: 
Thursday 21 September 2023 11:23:58 AM IST	EDTA_raw: Check dependencies, prepare working directories.

Thursday 21 September 2023 11:24:01 AM IST	Start to find LTR candidates.

Thursday 21 September 2023 11:24:01 AM IST	Identify LTR retrotransposon candidates from scratch.

Can't exec "./LTR_retriever": No such file or directory at /home/ubuntu/EDTA/EDTA_raw.pl line 307.
awk: fatal: cannot open file `out3_JBAT.FINAL.fa.mod.pass.list' for reading: No such file or directory
Warning: LOC list - is empty.

	perl rename_LTR_skim.pl target_sequence.fa LTR_retriever.defalse

sh: 1: ./mdust: not found

Error: Error while loading sequence
	perl filter_gff3.pl file.gff3 file.list > new.gff3

Thursday 21 September 2023 02:53:48 PM IST	Warning: The LTR result file has 0 bp!

Thursday 21 September 2023 02:53:48 PM IST	Start to find TIR candidates.

Thursday 21 September 2023 02:53:48 PM IST	Identify TIR candidates from scratch.

Species: others
dirname: missing operand
Try 'dirname --help' for more information.
Can't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.fa: No such file or directory at /home/ubuntu/EDTA/util/rename_tirlearner.pl line 19.
Warning: LOC list out3_JBAT.FINAL.fa.mod.TIR.ext30.list is empty.
sh: 1: ./mdust: not found

Error: Error while loading sequenceCan't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.gff3: No such file or directory.
Warning: The TIR result file has 0 bp!

Thursday 21 September 2023 02:54:08 PM IST	Start to find Helitron candidates.

Thursday 21 September 2023 02:54:08 PM IST	Identify Helitron candidates from scratch.

sh: 1: ./mdust: not found

Error: Error while loading sequence
	perl make_bed_with_intact.pl EDTA.intact.fa > EDTA.intact.bed 

Thursday 21 September 2023 10:14:40 PM IST	Warning: The Helitron result file has 0 bp!

Thursday 21 September 2023 10:14:40 PM IST	Execution of EDTA_raw.pl is finished!

ERROR: Raw LTR results not found in out3_JBAT.FINAL.fa.mod.EDTA.raw/out3_JBAT.FINAL.fa.mod.LTR.raw.fa
	If you believe the program is working properly, this may be caused by the lack of intact LTRs in your genome. Consider to use the --force 1 parameter to overwrite this check

**Comment by oushujun** [comment]
Your installation is not proper. Please reinstall and test with the test file.

Shujun

**Comment by karthickbrlab** [comment]
i tried to install EDTA using conda EDTA.yml

conda env create -f EDTA.yml 
Collecting package metadata (repodata.json): done
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining conflict for cairo xorg-libx11 pthread-stubs libxcb: : 229it [23Examining conflict for libev libcurl libnghttp2: : 230it [23:47,  1.24it/sExamining conflict for edta scikit-learn: : 231it [23:47,  1.24it/s]      Examining conflict for threadpoolctl edta scikit-learn: : 232it [23:47,  1Examining conflict for edta joblib scikit-learn: : 233it [23:48,  1.24it/sExamining conflict for edta joblib scikit-learn: : 234it [23:48,  2.28it/sExamining conflict for edta biopython tesorter: : 234it [23:49,  2.28it/s]Examining conflict for perl-xml-parser perl-xml-simple perl-xml-sax-expat:Examining conflict for perl-compress-raw-bzip2 perl-io-compress perl-archiExamining conflict for edta genometools-genometools repeatmodeler: : 237itExamining conflict for edta repeatmodeler tesorter: : 238it [23:50,  1.86iExamining conflict for edta repeatmodeler tesorter: : 239it [23:50,  2.41iExamining conflict for rmblast tesorter edta repeatmasker gnutls repeatmodExamining conflict for edta repeatmasker tesorter: : 240it [23:51,  2.41itExamining conflict for edta repeatmasker tesorter: : 241it [23:51,  2.00itExamining conflict for edta drmaa tesorter: : 241it [23:53,  2.00it/s]    Examining conflict for rmblast tesorter edta nettle repeatmasker gnutls reExamining conflict for rmblast tesorter edta nettle repeatmasker gnutls reExamining conflict for edta regex: : 245it [24:00,  1.41s/it]             Examining conflict for perl-business-isbn-data perl-business-isbn perl-uriExamining conflict for perl-business-isbn-data perl-business-isbn perl-uriExamining conflict for edta genericrepeatfinder: : 248it [24:01,  1.06s/itExamining conflict for edta repeatmodeler ltr_retriever genericrepeatfindeExamining conflict for cd-hit edta ltr_retriever repeatmodeler genericrepeExamining conflict for cd-hit edta ltr_retriever repeatmodeler genericrepeExamining conflict for edta mafft repeatmodeler: : 251it [24:03,  1.35it/sExamining conflict for edta mafft repeatmodeler: : 252it [24:03,  1.23it/sExamining conflict for wheel python pip: : 252it [24:05,  1.23it/s]       Examining conflict for edta ltr_retriever repeatmodeler: : 253it [24:05,  Examining conflict for edta repeatmasker ltr_retriever repeatmodeler: : 25Examining conflict for edta repeatmasker ltr_retriever repeatmodeler: : 25Examining conflict for ltr_retriever perl-text-soundex edta repeatmasker rExamining conflict for ltr_retriever perl-text-soundex edta repeatmasker rExamining conflict for ltr_retriever rmblast edta repeatmasker repeatmodelExamining conflict for scipy numpy: : 257it [24:08,  1.20it/s]            Examining conflict for edta perl-gd libgd openjdk: : 260it [24:10,  1.13itExamining conflict for edta perl-gd libgd openjdk: : 261it [24:10,  1.32itExamining conflict for muscle edta: : 261it [24:12,  1.32it/s]            Examining conflict for edta repeatmodeler recon: : 262it [24:12,  1.17it/sExamining conflict for edta glob2: : 263it [24:13,  1.17it/s]             failed

**Comment by oushujun** [comment]
Hi, 

Sorry for the delayed response. You need to add two channels `-c bioconda -c conda-forge`. Previously it was not required but somehow you need to specify these now.

Best,
Shujun

**Comment by karthickbrlab** [comment]
Hi Shujun

Can you please explain how to add those channels. I have tried using 
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda config --set channel_priority strict

Im getting
Warning: 'bioconda' already in 'channels' list, moving to the top
Warning: 'conda-forge' already in 'channels' list, moving to the top

**Comment by oushujun** [comment]
Adding these channels should allow you to install EDTA. If not, you can
manually specify these channels using -c while installing EDTA.

Shujun

**Comment by karthickbrlab** [comment]
Dear shujun.

Issue was with conda channel priority. I changed it to flexible and now it is working well.
Im closing this thread.


Thank you for your support.
