### ISSUE TITLE
Are "Unknowns" Unknown TEs or generally unknown repeats? 

### ISSUE THREAD

**Issue by isabelladistefano** [oushujun/EDTA#390]
Dear Shujun,

I am summarising TEs in three species and wonder whethter to include the Unknown results as Unknown TEs or any type of repeat region?

They are SO:0000657
http://sequenceontology.org/browser/current_svn/term/SO:0000657  which say the "children" could be:

nested_repeat (SO:0001649)
direct_repeat (SO:0000314)
inverted_repeat (SO:0000294)
long_terminal_repeat (SO:0000286)
non_LTR_retrotransposon_polymeric_tract (SO:0000433)
flanking_repeat (SO:0002192)
X_element_combinatorial_repeat (SO:0001484)
tandem_repeat (SO:0000705)
knob (SO:0002257)
Y_prime_element (SO:0001485)
telomeric_repeat (SO:0001496)
centromeric_repeat (SO:0001797)
terminal_repeat (SO:0002201)
dispersed_repeat (SO:0000658)
engineered_foreign_repetitive_element (SO:0000293)

I have read the QandA, but I am wondering if EDTA only picks up certain types of these "children"

Best wishes,

Isabella

**Comment by oushujun** [comment]
HI Isabella,

It's unknown repeat, which could be TEs or non-TE repeats but EDTA could
not find information to further classify them.

Shujun

**Comment by isabelladistefano** [comment]
Thank you.

As this list from SO only mentions RNA transposons, does this mean that these particular Unknowns are definitely not of a DNA transposon nature?

Best wishes,

Isabella

**Comment by oushujun** [comment]
No, it can also be DNA transposons but there isn’t any evidence to tell.
All TEs can belong under the dispersed repeat child SO.

Thanks,
Shujun
