### ISSUE TITLE
genome.fa problem

### ISSUE THREAD

**Issue by xiaomifeng12** [oushujun/EDTA#393]
Dear @oushujun
Many thanks for developing this very useful tool.
Some errors occurred while using EDTA software

I installed the EDTA software using Conda and ran the data in test using the EDTA command, and everything went smoothly.
conda activate EDTA
Usage: EDTA.pl  --genome test.genome.fa  --step all  --species others --sensitive 1 --anno 1 --threads 32  --u 1.6e-8  --curatedlib ~/db/sine_line.fa --overwrite 1

But when using the same EDTA command to run my data, some errors will be reported.
conda activate EDTA
Usage: EDTA.pl  --genome genome.fa  --step all  --species others --sensitive 1 --anno 1 --threads 32  --u 1.6e-8  --curatedlib ~/db/sine_line.fa --overwrite 1

error1:
Species: others
Traceback (most recent call last):
File "/public/home/dd/miniconda3/envs/EDTA/share/EDTA/bin/TIR-Learner2.5/Module2/RunGRF.py", line 79, in <module>
if (len(str(records[0].seq))>int(length)+500):
IndexError: list index out of range
cp: cannot stat 'TIR-Learner/-p': No such file or directorycat: '-+-DTA.fa': No such file or directory
cat: '-+-DTC.fa': No such file or directorycat: '-+-DTH.fa': No such file or directory
cat: '-+-DTM.fa': No such file or directorycat: '-+-DTT.fa': No such file or directory
cat: '-+-NonTIR.fa': No such file or directorycat: '-+--+-.gff3': No such file or directory
rm: cannot remove '-+--+-*.gff3': No such file or directory
Traceback (most recent call last):

error2:
Species: others
Warning: LOC list Cjam.genome.fasta.mod.TIR.ext30.list is empty.
Error: Error while loading sequenceWarning: The TIR result file has 0 bp!
Sun Oct  8 00:01:27 CST 2023    Start to find Helitron candidates.
Sun Oct  8 00:01:27 CST 2023    Identify Helitron candidates from scratch.
Warning: LOC list Cjam.genome.fasta.mod.HelitronScanner.raw.ext.list is empty.
Warning: LOC list Cjam.genome.fasta.mod.HelitronScanner.raw.ext.list is empty.
Error: Error while loading sequence
        perl make_bed_with_intact.pl EDTA.intact.fa > EDTA.intact.bed

This is my file1 format
>010000002.1
aatcctcttactaatgtatttatcttcaaaataagctatcacatgtagctatagtcatag
atttgagggaggagaagattttcttagacgcgtaccccaaaaaccgcgtaagttcacaaa
aaatcagttttttcgaaatagcaacaaatctattgttccggcagaaaaaaggccgtcaac
cttttcgatggggaatgtttttgcgcacattttggtgaaaatgttgtgaaaatatcttga

This is my file2 format
>Chr5
TAAAATACCTAACATGCTTTAAGTTTTCAATATTTCGTTGAAATTAATCAAGTTTCTTAT
TTTTATTTTTGCAACTTAATTTGATACATGTTTTGATAAGTTTTGAAAACGAAGTTTAAA
TAATTAATATGGAATTTTTCCTTTCTGCCAAATAATGTGGGTATGTCAACGAAACCCTAT
GACAGAACTCATAACCGTCAGTTTGACAGGCGGTATAAGTCTCTCCACTGACATCCACTT
AAATGTTTGATATGGTTTTTGTAGTAGTCCATTGTGGAAAAAATATTTATTTCCTCTTTG
ACCATTTTTTTCTACAGGTATAACTCATGTAAACTTTAACAAAACAAATACTTGCTTCGT
GTTTGGTATCGTTTTAGTATTCCTCCAGTCAGCTCAGCCATGTCTGATTCTGTTAGCGTT
CTGATTCTGTTAGTATTGTCATTTTGCGAATGCAGTGAGATTTGGAGACGGTTAAACTCA
GTATCGATAAGAATATTATATTTCCCGGAAAGAACATATTTGAGAAAGACGGAAATTTCA
GACTGCTTTTCTGTGCCAAAAGGTGTCTCCAGCACAAGGACTGTTCGTTCATCACACGAA
ACCGGGAATGTCGAGGATTCGGTAACTCGGAAGGAATTGAAATATATATGCTATATCTTT

I have tried various parameters, but still cannot run EDTA normally. I hope you can help solve it. Thank you very much!

**Comment by oushujun** [comment]
Try not to use number only sequence names. Your two files do not follow the
FASTA format conventions, which require each sequence ID starts with “>”

Shujun

**Comment by oushujun** [comment]
Try the test file. Looks like not installed correctly. Try to install with
the yml file.

Shujun

**Comment by xiaomifeng12** [comment]
Thank you very much for your reply.

I reinstalled the EDTA using conda and ran the data in test file using the EDTA command, and everything went smoothly.

Steps for installing EDTA:
```
git clone https://github.com/oushujun/EDTA.git
conda env create -f EDTA.yml
```

Run data in test file using EDTA, and the results are normal without any errors.
```
EDTA.pl --genome test.genome.fasta --step all --species others --sensitive 1 --anno 1 --threads 32 --u 1.2e-9 --curatedlib sine_line_base.fa --overwrite 1
```

Running my data using EDTA, some errors occurred. These errors are what I mentioned above
```
EDTA.pl --genome genome.fasta --step all --species others --sensitive 1 --anno 1 --threads 32 --u 1.2e-9 --curatedlib sine_line_base.fa --overwrite 1
```

This file1 only contains one sequence (~20M) for testing. This is my file1 format.
```
>Chr5
TAAAATACCTAACATGCTTTAAGTTTTCAATATTTCGTTGAAATTAATCAAGTTTCTTAT
TTTTATTTTTGCAACTTAATTTGATACATGTTTTGATAAGTTTTGAAAACGAAGTTTAAA
TAATTAATATGGAATTTTTCCTTTCTGCCAAATAATGTGGGTATGTCAACGAAACCCTAT
GACAGAACTCATAACCGTCAGTTTGACAGGCGGTATAAGTCTCTCCACTGACATCCACTT
AAATGTTTGATATGGTTTTTGTAGTAGTCCATTGTGGAAAAAATATTTATTTCCTCTTTG
ACCATTTTTTTCTACAGGTATAACTCATGTAAACTTTAACAAAACAAATACTTGCTTCGT
```

This file2 only contains one sequence for testing. This is my file2 format.
```
>ct002.1
aatcctcttactaatgtatttatcttcaaaataagctatcacatgtagctatagtcatag
atttgagggaggagaagattttcttagacgcgtaccccaaaaaccgcgtaagttcacaaa
aaatcagttttttcgaaatagcaacaaatctattgttccggcagaaaaaaggccgtcaac
cttttcgatggggaatgtttttgcgcacattttggtgaaaatgttgtgaaaatatcttga
atagtttccgagttattaaggtttgaagttttgacttcaaggggagataactcaagaaag
aagtcgaaaatcaaaaaaagtggctcgttattatcttagttcagccacaggctagcatcc
ctgcaaatgtcatgcaaatcggcccagtggttacttcagaaacctctggtcaaaaaagta

```

Looking forward to your reply. Thank you very much!

**Comment by oushujun** [comment]
Can you please share with me the small files that can reproduce your errors?

Thanks!
Shujun

**Comment by oushujun** [comment]
@xiaomifeng12 any luck?

**Comment by oushujun** [comment]
Inactive, closing for now. Please reopen if the issue persists.
