### ISSUE TITLE
Error when running panEDTA

### ISSUE THREAD

**Issue by smallfishcui** [oushujun/EDTA#394]
Hi,  
I have been trying many times to use the pan EDTA and always get an error message like this:

	LANG = "C.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
Traceback (most recent call last):
  File "/home/cuiwang/.conda/envs/EDTA/share/RepeatMasker/famdb.py", line 51, in <module>
    import h5py
  File "/home/cuiwang/.conda/envs/EDTA/lib/python3.6/site-packages/h5py/__init__.py", line 46, in <module>
    from ._conv import register_converters as _register_converters
  File "h5py/_conv.pyx", line 1, in init h5py._conv
  File "h5py/h5t.pyx", line 1, in init h5py.h5t
SystemError: execution of module h5py.utils raised unreported exception

The run continues after this, but I don't know if this affects the results. It appears that the error occurs when running repeatmasker.
I installed the EDTA using the most updated yml file on github. I run the panEDTA as instructed, first run EDTA for each assembly and then use panEDTA to integrate the results together.
Could you please help?

Thanks,
Cui

**Comment by oushujun** [comment]
Hi Cui,

Looks like you need to reinstall numpy and h5py. If your HPC also has `module` managed programs, please unload all the modules before installing and using the conda version of EDTA. You need to make sure EDTA is working properly before using panEDTA. 

Thanks,
Shujun

**Comment by smallfishcui** [comment]
<img width="1228" alt="Screenshot 2023-10-19 at 14 47 48" src="https://github.com/oushujun/EDTA/assets/41078885/71da9cf2-cbcb-46d1-8c2c-3706506288c2">
Hi Shujun,

Thank you very much for your prompt reply! I tried to sed other directories from $PATH, and only keep the bioconda and basic paths,and then I run EDTA again, and get this message. I saw other posts that this indicates some sort of error, is it? IS it still the installation problem? My first run was also like this, and I used --force=1, but I guess I shouldn't do it that way.


best,
Cui

**Comment by oushujun** [comment]
Hi Cui,

Yes looks like the installation is not correct, which could be due to setting paths and also using conda env. It's still possible to install this way, but you need to pass the test using the small test files to make sure your installation is good.

Shujun

**Comment by oushujun** [comment]
Hello,

Please update EDTA to v2.2.1 and try again. Please reopen the issue if it still doesn't work.

Thanks!
Shujun
