### ISSUE TITLE
lib-test.pl -std and -tst must have different input file name

### ISSUE THREAD

**Issue by qjiangzhao** [oushujun/EDTA#396]
Dear Shujun,

Many thanks for the wonderful benchmarking tool lib-test.pl. I found a problem when I used it, which might be common for others. 

For example:

perl ./lib-test.pl -std <path_to_std_file/std_file_name.out> -tst <path_to_tst_file/tst_file_name.out> 

in the example, <std_file_name.out> has to be different with <tst_file_name.out>. 

But when you use RepeatMasker for genome TE annotation, the default out file name is "your_genome_name.out", this will lead to a result that <std_file_name.out> is identical with <tst_file_name.out>. 

If other users encounter the same problem, you can modify <your tst_file_name.out> and run the script again. 

Yours sincerely
Jiangzhao Qian

**Comment by oushujun** [comment]
Hi Jiangzhao,

Thank you for the comment! As standard annotation is usually curated and won't have many versions, the file is usually named differently. One should rename the standard annotation to make it different from the test annotation. If you have different versions of test annotations, they should be named differently, too, to distinguish them from each other.

best,
Shujun
