### ISSUE TITLE
Pipeline failed at LTR_FINDER_parallel step

### ISSUE THREAD

**Issue by stefaniehoho** [oushujun/EDTA#40]
Dear Shujun,

I ran the EDTA pipeline v1.7.1 for a genome with the following command. It failed at the step of identify LTR retrotransposon candidates from scratch. 
> perl /LabShares/Tools/EDTA/EDTA/EDTA.pl -genome DR_OL_ens90.fa -step all -cds DR_OL_cds_ens90.fa -sensitive 1 -anno 1 
The STDERR showed an error:  
> Unsuccessful stat on filename containing newline at /LabShares/Tools/EDTA/EDTA/bin/LTR_FINDER_parallel/LTR_FINDER_parallel line 156, <List> line 10314.

In the folder of LTR, a list of intermediate files have been generated:
> alluniRefprexp082813.197723
> alluniRefprexp082813.197723.phr
> alluniRefprexp082813.197723.pin
> alluniRefprexp082813.197723.psq
> DR_OL_ens90.fa.finder.combine.scn
> DR_OL_ens90.fa.harvest.scn
> DR_OL_ens90.fa.list
> DR_OL_ens90.fa.LTR.intact.fa
> DR_OL_ens90.fa.LTR.intact.fa.ori
> DR_OL_ens90.fa.LTR.intact.fa.ori.dusted
> DR_OL_ens90.fa.LTR.intact.fa.ori.dusted.cleanup
> DR_OL_ens90.fa.rawLTR.scn
> Tpases020812DNA.197723
> Tpases020812DNA.197723.phr
> Tpases020812DNA.197723.pin
> Tpases020812DNA.197723.psq
> Tpases020812LINE.197723
> Tpases020812LINE.197723.phr
> Tpases020812LINE.197723.pin
> Tpases020812LINE.197723.psq

All DR_OL_ens90.fa.LTR.intact* files are empty. Could you give me some suggestions to fix this?

Here I have the full STDERR attached for your reference. 

Thank you so much.

Best,
Yixuan
[AN_EDTA_DR_OL_ens90.txt](https://github.com/oushujun/EDTA/files/4036867/AN_EDTA_DR_OL_ens90.txt)

**Comment by oushujun** [comment]
Dear Yixuan,

Please double check your genome file especially the sequence names. Use
short and simple names only.

Best,
Shujun
