### ISSUE TITLE
Updated docker container

### ISSUE THREAD

**Issue by mrmrwinter** [oushujun/EDTA#400]
Hi,

Is it possible to update the docker/ singularity container to 2.1.0 please? The current 2.0.0 version on dockerhub seems to contain the TIR Learner bug - https://github.com/oushujun/EDTA/issues/365 - , and installing via clone and conda doesnt wortk because fof conflicting dependencies.

Thanks

**Comment by oushujun** [comment]
Hi, if you rename your sequence IDs to contain not only numbers (ie, change >00001 to >a00001), you should not encounter the issue #365. That being said, updating docker/apptainer to the latest version of EDTA is still on my to-do list.

Thanks,
Shujun
