### ISSUE TITLE
Overlapping TEs

### ISSUE THREAD

**Issue by bijendrabio** [oushujun/EDTA#401]
@oushujun 
Curious if EDTA double counts bp sizes for different overlapped TEs while generating the summary of whole-genome TE annotation (genome.mod.EDTA.TEanno.sum)

For example, overlapped TEs (structurally intact and fragmented TEs) in genome.mod.EDTA.TEanno.gff3 file: 
![EDTA](https://github.com/oushujun/EDTA/assets/98179638/dbfbdb26-103b-4562-9a58-b646adb96d40)

Regards,
B

**Comment by oushujun** [comment]
Hi,

The summary is generated by /EDTA/util/buildSummary.pl adapted from
RepeatMasker. It handles over counting in some level but cases like yours I
haven’t checked myself. Maybe you can extract just these fragments and
resummrize with the script to check it out.

Thanks,
Shujun
