### ISSUE TITLE
An empty EDTA.TElib.novel.fa was generated after perform EDTA.

### ISSUE THREAD

**Issue by Github-Yilei** [oushujun/EDTA#403]
Hi Shujun,

we annotates a plant genome by runing EDTA  with a  --curatedlib:(https://sines.eimb.ru/). it's successfully annotated the TEs, however, the  EDTA.TElib.novel.fa  was empty and the EDTA.TElib.fa only contained  sequence of SINEBase.

This seems that no novel TEs was identified？

**Comment by oushujun** [comment]
Please paste your command here and version used. If you see any errors and
warnings, please also paste them here.

Thanks!
Shujun

**Comment by Github-Yilei** [comment]
Hi Shujun,
      Thank you for response!
      I re-runed the pipeline and the problem was resolved.
