### ISSUE TITLE
no sine?

### ISSUE THREAD

**Issue by Xinxin0314** [oushujun/EDTA#404]
Hi Ou,

I used this command to identify TEs,
 
-species others -step all --sensitive 1 -t 20 -anno 1 -evaluate 1 .

But in my "result.sum", only LINE in the result file while no SINE. 

However, SINE has been identified in other genomes of this species.

Looking forward to your reply.

Best wishes,
Xin

**Comment by oushujun** [comment]
It's not very sensitive at the moment. Please read more here: https://github.com/oushujun/EDTA/wiki/How-to-prepare-a-curated-library-to-maximize-the-efficacy-of-EDTA

https://github.com/oushujun/EDTA/wiki/Making-sense-of-EDTA-usage-and-outputs---Q&A

**Comment by oushujun** [comment]
Please try the v2.2.0 version and see if this improved. Thanks!
