### ISSUE TITLE
Can this tool be used in the genomes of bacteria, archaea and fungi?

### ISSUE THREAD

**Issue by RuolinHe** [oushujun/EDTA#405]
Hi Ou,

I knew this tool is designed for high eukaryotic genomes such as plants and animals.

And I am curious whether I can use this tool in the genomes of bacteria, archaea and fungi.

Looking forward to your reply.

Best wishes,
Ruolin He

**Comment by oushujun** [comment]
Someone tried in fungi and need to use the —force 1 parameter. I am not
sure in archaea and maybe not in bacteria. You probably need to use
copy-number based approaches to achieve higher confidence for these smaller
genomes

Shujun

**Comment by RuolinHe** [comment]
Thank you for your response. I will try it!
