### ISSUE TITLE
Should I rewrite the previous results ？

### ISSUE THREAD

**Issue by tongyin121** [oushujun/EDTA#406]
Hi, 
I have annotated my genomes by using the panEDTA pipeline, and now I have to add some new genomes. I am curious about that should I overwrite the previous EDTA results and rerun the panEDTA pipeline or just rerun the panEDTA pipeline?

Best regards

**Comment by oushujun** [comment]
Hello,

If you have backed up the previous EDTA results, you can just reuse those and add your extra genome. If you have panEDTA overwritten your EDTA results, you may want to rerun EDTA on each genome plus your new genome. You don't need to rerun the raw step and the filter step, so you can start with `--step final` for those existing genomes.

Best,
Shujun

**Comment by tongyin121** [comment]
Hi,
Thanks for your help. 
Best,
tonyin

**Comment by tongyin121** [comment]
Hi,
After rerunning EDTA with my all genome, I find the results id quite different. Some important TE families in the PanEDTA library which can be found before have not been found yet.  Can I merge the results of these two libraries.

**Comment by tongyin121** [comment]
Hi,
you may misunderstand what I mean because of my ambiguous expression. The TE IDs will change but the sequence will not change.  Therefore, I use the TE family that interests me which comes from the old library as the query to blast with the new TE library, and the output file is empty.

**Comment by tongyin121** [comment]
Hi,
I checked the results before and after, I found that the first panEDTA annotated the repeats as MITE/DTM, but the second time, the panEDTA annotated the repeats as Gypsy_LTR_retrotransposon. The result is pretty paradoxical,  the previous result which annotated the repeats as MITE/DTM has annotated the TIR and TSD. But the newer result did not find a corresponding Gypsy_LTR retrotransposon structure. 
Could you please help? This is very important to me.

**Comment by oushujun** [comment]
If you have TEs that are curated or particular families interested in your study, you should provide it to EDTA via `--curatedlib`. panEDTA filters out low-copy families to control false positives, so families shown in the EDTA annotation may not be found in the panEDTA annotation simply because they are low-copy. 

There are moderate levels of misannotation in the current version of EDTA. The new update (v2.2.0) has a better filter for intact TEs, you may try it out.
