### ISSUE TITLE
Unsafe argparse in the `cut.pl`

### ISSUE THREAD

**Issue by baozg** [oushujun/EDTA#407]
Hi, Shujun

I recently found that several genomes cannot run with LTR_step in the `EDTA_raw` step.  My genome name is `IP-San-6.Chr_scaffolds.fa` and it can resolved if I change the name to `San6.Chr_scaffolds.fa`. I found that the problem arose from the `/EDTA/bin/LTR_*_parallel/bin/cut.pl`. 

```perl
my $length=5000000; #length of a sequence
my $separate=1; #1 for 1 sequence per file, 0 for all sequence in 1 files.
my $size=0; #no size control; if set to 10000; program will output sequence files every $length base (roundup to single sequence)
my $i=0;
foreach (@ARGV){
        $separate=1 if $_=~/-s|Separate/;
        $length=$ARGV[$i+1] if $_=~/-l|Length/i;
        $size=1 if /-S|size/;
        $i++;
        }
open Seq, "<$ARGV[0]" or die $!;
open List, ">$ARGV[0].list" if $separate==1;
```

All the genome fails with "-S" in the name, I would suggest changing this part with `Getopt::long` or replacing this script with `bedtools`. Which option do you think is more reliable? I could work on this.

**Comment by oushujun** [comment]
Thanks for reporting! I prefer the `Getopt::long` option. Thanks!

Shujun

**Comment by oushujun** [comment]
Fixed in EDTA2.2
