### ISSUE TITLE
The LTR result file has 0 bp!

### ISSUE THREAD

**Issue by bvs** [oushujun/EDTA#408]
Dear @oushujun,

I am using EDTA v2.0.1 to annotate TEs/repeats in highly fragmented de novo genome assemblies (50K - 100K scaffolds/assembly). I am annotating several assemblies using the divide-and-conquer strategy, but I am only getting the error below for a few assemblies. This error generates empty files for LTRs.

I am using the below-presented command:
$EDTA_raw.pl --genome $genome --type ltr --repeatmasker $repeatmasker -t 5 --convert_seq_name 0

Error:
----------------------------------------------------------------------------------
Thu 30 Nov 18:15:46 CET 2023    EDTA_raw: Check dependencies, prepare working directories.
Thu 30 Nov 18:16:00 CET 2023    Start to find LTR candidates.
Thu 30 Nov 18:16:00 CET 2023    Identify LTR retrotransposon candidates from scratch.
awk: fatal: cannot open file `GCA_029582405.1_S15_genomic.fna2.pass.list' for reading (No such file or directory)
Warning: LOC list - is empty.
        perl rename_LTR_skim.pl target_sequence.fa LTR_retriever.defalse
Error: Error while loading sequence
        perl filter_gff3.pl file.gff3 file.list > new.gff3
Fri  1 Dec 06:57:53 CET 2023    Warning: The LTR result file has 0 bp!
Fri  1 Dec 06:57:53 CET 2023    Execution of EDTA_raw.pl is finished!
----------------------------------------------------------------------------------

Please look into this error and let me know a possible solution.

Best,
Suresh

**Comment by linshengnan09** [comment]
hi, I encountered a similar error. Is your problem solved?
The command:
EDTA.pl --genome $ref --anno 1  --force 1 --debug 1 -sensitive 1 -t $thread --rmout ${ref}.out --repeatmasker ~/02biosoft/RepeatMasker/RepeatMasker

The log information：
Wed Dec  6 12:03:24 CST 2023    EDTA_raw: Check dependencies, prepare working directories.

Wed Dec  6 12:04:25 CST 2023    Start to find LTR candidates.

Wed Dec  6 12:04:25 CST 2023    Identify LTR retrotransposon candidates from scratch.

Invalid value for shared scalar at $home/micromamba/envs/EDTA/share/LTR_retriever/bin/LTR.identifier.pl line 114, <ANNO> line 79176.
cp: cannot stat 'Aa_225.fa.mod.retriever.scn.adj': No such file or directory
awk: fatal: cannot open file `Aa_225.fa.mod.pass.list' for reading (No such file or directory)
Warning: LOC list - is empty.

Error: Error while loading sequence
        perl filter_gff3.pl file.gff3 file.list > new.gff3

Wed Dec  6 14:09:30 CST 2023    Warning: The LTR result file has 0 bp!

Wed Dec  6 14:09:30 CST 2023    Start to find TIR candidates.

Wed Dec  6 14:09:30 CST 2023    Identify TIR candidates from scratch.

Thank you!

**Comment by jacquelinemattos** [comment]
Hi,
I'm also finding the same error. Any solutions from anyone?

Thanks!

**Comment by oushujun** [comment]
Please update your LTR_retriever. https://github.com/oushujun/LTR_retriever/issues/153
