### ISSUE TITLE
Is it acceptable to use rice or Arabidopsis thaliana to calculate the LTR insertion time of basal angiosperms?

### ISSUE THREAD

**Issue by XXH123a** [oushujun/EDTA#410]
Hello, Professor Ou,
Excuse me, I would like to ask if there is a simpler way to solve the problem shown in the title.
1. as the title shows, it is the simplest method. I wonder if it is reasonable for me to do so?
2. `nucleotide mutation frequency = number of SNPs and indels in the range of TE sequence / (total length of TE sequence x2),` is this method reasonable?
I tried to extract the complete LTR-RTs and compare them using mafft, but then I didn't know what to do

**Comment by oushujun** [comment]
Hello,

You may use a generic molecular clock but you should aware that it’s not
accurate and could be off for 1000 times or more. A better approach would
be just use divergence instead of absolute age to avoid the inaccurate
mutation rate.

Shujun

**Comment by XXH123a** [comment]
Thank you for your guidance.
