### ISSUE TITLE
Is EDTA suitable for Animal genomes

### ISSUE THREAD

**Issue by JINPENG-WANG** [oushujun/EDTA#411]
Hi Shujun,

I would like to use EDTA for animal genomes.  What should I prepare to make EDTA suitable for Animal genomes?  

Thanks very much.

Wang Jinpeng

**Comment by oushujun** [comment]
Depending on how you use it. Animal genomes (assuming vertebrate) have more non-LTR retrotransposons, which is not sensitively annotated by the current EDTA. You will need to provide a library for these elements to EDTA for their annotation.

Shujun

**Comment by JINPENG-WANG** [comment]
Thanks!  I will try.

**Comment by oushujun** [comment]
Hello @JINPENG-WANG,

The latest EDTA (2.2.0) has better SINE/LINE support and is thus more suitable for animal genomes. Please give it a try.

Best,
Shujun

**Comment by JINPENG-WANG** [comment]
Thanks, I will try.
