### ISSUE TITLE
 conda activate EDTA？

### ISSUE THREAD

**Issue by 8Purplegrapes** [oushujun/EDTA#413]
Hi everyone，

Do I need to call EDTA's conda environment when running panEDTA? conda activate EDTA

Thanks very much

**Comment by oushujun** [comment]
Yes you do.

Thanks,
Shujun

**Comment by 8Purplegrapes** [comment]
hi oushujun，
This is a previous pan EDTA analysis using the EDTA environment. The first genome analysis reported an error when it reached RepeatMasker. Is there any good solution?

2023-12-25 01:52:31,383 -INFO- writing classified protein domains in `zs11.genome.cds.fasta.code.rexdb.cls.pep`
2023-12-25 01:52:31,453 -INFO- Summary of classifications:
Order           Superfamily      # of Sequences# of Clade Sequences    # of Clades# of full Domains
LTR             Bel-Pao                      26              0              0              0
LTR             Copia                       474            139             16              0
LTR             Gypsy                       821            535             17              0
LTR             Retrovirus                   14              0              0              0
LTR             mixture                       8              0              0              0
pararetrovirus  unknown                      25              0              0              0
DIRS            unknown                      40              0              0              0
Penelope        unknown                      14              0              0              0
LINE            unknown                     498              0              0              0
TIR             EnSpm_CACTA                   3              0              0              0
TIR             MuDR_Mutator                  7              0              0              0
TIR             PIF_Harbinger                76              0              0              0
TIR             hAT                          22              0              0              0
Maverick        unknown                     327              0              0              0
mixture         mixture                       4              0              0              0
2023-12-25 01:52:31,455 -INFO- Pipeline done.
2023-12-25 01:52:31,456 -INFO- cleaning the temporary directory ./tmp
Mon Dec 25 09:45:42 CST 2023    Homology-based annotation of TEs using ganganF73.genome.fa.mod.EDTA.TElib.fa from scratch.

**ERROR: RepeatMasker results not found in ganganF73.genome.fa.mod.out!

ERROR: Initial EDTA failed for ganganF73.genome.fa**

**Comment by oushujun** [comment]
Did you test EDTA on the small test file?

**Comment by oushujun** [comment]
any luck? @8Purplegrapes

**Comment by 8Purplegrapes** [comment]
Thank you, I used "conda activate EDTA" and then ran panEDTA.sh, and then it ran successfully
