### ISSUE TITLE
Can I install it using source code on an ARM machine?

### ISSUE THREAD

**Issue by z4668640** [oushujun/EDTA#414]
Can EDTA be installed from source? 
The ARM-based servers I use, conda and docker are all difficult to install EDTA. 
Thank you.

**Comment by oushujun** [comment]
No. EDTA itself is just Perl but relies on a bunch of dependencies. You will need to compile all the dependencies in the ARM server. I've heard Huwwei engineers have done that in support of their ARM products. I don't have access to those versions unfortunately.

Shujun

**Comment by z4668640** [comment]
Thank you very much for your reply. I think I need to try to find this Huawei version. I'll let you know when I find it.
I still want to know what dependencies EDTA relies on? I am confident that I can install all the dependencies manually, but there are too many dependencies in the EDTA.yml file, I would like to know what are the direct dependencies of your script?

Thanks again for your reply.

> No. EDTA itself is just Perl but relies on a bunch of dependencies. You will need to compile all the dependencies in the ARM server. I've heard Huwwei engineers have done that in support of their ARM products. I don't have access to those versions unfortunately.
> 
> Shujun

**Comment by oushujun** [comment]
Those are the dependencies required. If you want to know what packages require all these dependencies, you can check out the conda recipe: https://github.com/bioconda/bioconda-recipes/blob/c9aaf8ca728676ea0d06de59069ad021159dc6c2/recipes/edta/meta.yaml

Happy New Year!
Shujun

**Comment by z4668640** [comment]
Thank you very much for your help. 
I know what I have to do next.
Happy New Year! 😀


> Those are the dependencies required. If you want to know what packages require all these dependencies, you can check out the conda recipe: https://github.com/bioconda/bioconda-recipes/blob/c9aaf8ca728676ea0d06de59069ad021159dc6c2/recipes/edta/meta.yaml
> 
> Happy New Year! Shujun

**Comment by z4668640** [comment]
After my experiment, EDTA can run on ARM architecture. The difficulty lies in the adaptation of dependencies. The adaptation of LTR_Finder took me the most time, but this software has been submitted in the source code branch and accepted by the author, now download the source code directly compiled to use.
Another change is that the./EDTA/bin/TIR-Learner2.5/ python code upgrades its code to accommodate the newer versions of tensorflow2 and pandas. (Take advantage of the tensorflow2 upgrade script and python error messages.) Other dependencies can also be found directly on the source page to run the ARM method. The process is too complicated for me to write clearly, but in the end EDTA can run smoothly on ARM.


> Those are the dependencies required. If you want to know what packages require all these dependencies, you can check out the conda recipe: https://github.com/bioconda/bioconda-recipes/blob/c9aaf8ca728676ea0d06de59069ad021159dc6c2/recipes/edta/meta.yaml
> 
> Happy New Year! Shujun

**Comment by oushujun** [comment]
Did you mean the EDTA2 can be installed in ARM as well? If the LTR_finder
is updated, does that mean the conda recipe can be used in ARM servers?
Can you please write a more detailed step-by-step for other ARM users?

Thanks!
Shujun

**Comment by z4668640** [comment]
Maybe it will take me a long time to sort this out, because EDTA is so dependent on it. I'm not sure how to make dependencies for conda. LTR_finder I am currently on github submitted the source code changes, ARM running also need to compile.
