### ISSUE TITLE
The use of EDTA_raw.pl and EDTA.pl

### ISSUE THREAD

**Issue by qdu-beep** [oushujun/EDTA#415]
I would like to ask if I want to obtain the genome sequence with only LTR regions masked and using soft-masking, should I follow the steps below? The main question is whether I should use EDTA.pl  after using raw_EDTA.pl. I would greatly appreciate your response!

Should I use EDTA_raw.pl with the -type ltr  to obtain the raw library of LTR? 
And then, should I use EDTA.pl with the --overwrite 0 to further annotate and filter based on the results of raw_EDTA.pl? 
Finally, I should use make_masked.pl for soft masking. 

I came across the following description on the website, but I'm not sure if my understanding is correct. Thank you for your assistance!
"Users may run EDTA_raw.pl for each TE type with --threads 1, then run EDTA.pl with multi threads and --overwrite 0"(https://github.com/oushujun/EDTA/releases)
_Originally posted by @qdu-beep in https://github.com/oushujun/EDTA/issues/61#issuecomment-1870767074_

**Comment by oushujun** [comment]
Hello,

If you are only interested in the LTRs, you should just run `LTR_retriever`. The `EDTA_raw.pl --type ltr` will get you there, but without whole-genome annotation. You can do your own by running `RepeatMasker -lib $genome.mod.LTRlib.fa` within `EDTA.raw/LTR/`. After RepeatMasking, you can run `make_masked.pl` for soft masking.

Shujun

**Comment by qdu-beep** [comment]
> Hello,
> 
> If you are only interested in the LTRs, you should just run `LTR_retriever`. The `EDTA_raw.pl --type ltr` will get you there, but without whole-genome annotation. You can do your own by running `RepeatMasker -lib $genome.mod.LTRlib.fa` within `EDTA.raw/LTR/`. After RepeatMasking, you can run `make_masked.pl` for soft masking.
> 
> Shujun

Dear oushujun,

Many thanks for your useful reply! My question has been resolved!

Sincerely,
qdu-beep
