### ISSUE TITLE
Evaluating the results of an already finished EDTA pipeline run

### ISSUE THREAD

**Issue by adeoliveira86** [oushujun/EDTA#416]
Dear authors,

I am working with a highly repetitive invertebrate genome and, as expected, the last step of the EDTA pipeline (evaluate 1) is still running after almost 20 days of execution in a 24 threads machine. I would like to know, if it is possible to divide the EDTA run into two instances: one running the whole pipeline without `evaluate`, and later evaluating the results of the whole pipeline with the `evaluate 1`. I checked the "divide and conquer" suggested pipeline, but it revolves around the structural prediction of TE elements, and do not this specific step I mentioned.

Best regards and thanks a lot for the wonderful tool.
André

**Comment by oushujun** [comment]
Hi André,

Please use the `/util/evaluation.pl` script for this purpose. 

Thanks,
Shujun
