### ISSUE TITLE
LTR retriever fails

### ISSUE THREAD

**Issue by foriin** [oushujun/EDTA#420]
Hello, I get this error from EDTA when running on [this assembly](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/013/340/165/GCF_013340165.1_LBDM_Dsuz_2.1.pri/GCF_013340165.1_LBDM_Dsuz_2.1.pri_genomic.fna.gz):
```
2024-01-17T15:01:18 CET	Identify LTR retrotransposon candidates from scratch.
Invalid value for shared scalar at /home/foriin/anaconda3/envs/te/share/LTR_retriever/bin/LTR.identifier.pl line 114, <ANNO> line 3939.
```

The last file generated is .rawLTR.scn

**Comment by oushujun** [comment]
Can you please indicate what versions of LTR_retriever and edta you are
using?

Shujun

**Comment by foriin** [comment]
EDTA v 2.2.0, LTR_retriever v 2.9.4

**Comment by foriin** [comment]
I've update retriever to 2.9.9, now trying to run EDTA again. Is there a way to set up the maximum length of LTR when running it?

**Comment by oushujun** [comment]
Yes this is a known bug for LTR_retriever v2.9.4 https://github.com/oushujun/LTR_retriever/issues/153. Setting max length for the LTR region is not enabled in LTR_retriever, you may manually filter them using the pass.list file.

**Comment by foriin** [comment]
Yes, thanks, Shujun, EDTA got to the end after the update.
