### ISSUE TITLE
Rerun EDTA 2.2.0 with results from older version

### ISSUE THREAD

**Issue by CongLiu37** [oushujun/EDTA#423]
Hello, 

I have run EDTA v2.0.0 on my animal genomes with such commands:
`singularity exec ~/EDTA.sif EDTA.pl --genome ${cat_genome.fa} --species others --step all --overwrite 0 --sensitive 0 --anno 0 --threads 64`
I did not do the annotation because those small fragments were merged to fake scaffolds in order to reduce running time of TIR-learner. 

Now I want to use EDTA v2.2.0 to take the improvement in LINE/SINE search and do the annotation. Is it possible to run the new EDTA v2.2.0 with the results I already have and the original genome assembly? Something like this:
`EDTA.pl --genome ${genome.fa} --species others --step all --overwrite 0 --sensitive 1 --anno 1 --threads 64 --cds ${cds.fna}`

Also, just one minor idea, it would be great if EDTA can do some file cleaning after running. It is difficult to copy/move the large file tree from TIR-learner. 

Sincerely,

Cong

**Comment by oushujun** [comment]
It’s better to rerun the whole program, and you don’t need to merge the
small contigs since TIR-Learner has upgraded.

Shujun

**Comment by CongLiu37** [comment]
Thanks for your quick reply. I am wondering if there is a singularity container for EDTA v2.2.0? I tried 2.2.0--hdfd78af_1 and 2.2.0--hdfd78af_0 from `https://quay.io/repository/biocontainers/edta?tab=tags`, but seems they are crashed. Here is the error:

`FATAL:   could not open image /apps/unit/BourguignonU/EDTA.sif: SIF image /hpcshare/appsunit/BourguignonU/EDTA.sif is corrupted: wrong partition size`

Sincerely,

Cong

**Comment by GallVp** [comment]
Hi @CongLiu37 

How did you build the singularity image? Can you kindly share your bash commands?

**Comment by CongLiu37** [comment]
Hello @GallVp 

Here is the commands:
`singularity pull EDTA.sif docker://quay.io/biocontainers/edta:2.2.0--hdfd78af_1`
The sif file was about 1.8G. Then I tried 
`singularity exec EDTA.sif EDTA.pl --help`
and got the error:
`FATAL:   could not open image /apps/unit/BourguignonU/EDTA.sif: SIF image /hpcshare/appsunit/BourguignonU/EDTA.sif is corrupted: wrong partition size`

Sincerely,

Cong

**Comment by GallVp** [comment]
I am using docker and the file is about 8 GB. Anyways, can you try:

```
singularity pull EDTA.sif quay.io/biocontainers/edta:2.2.0--hdfd78af_1
```

If that does not work, simply download the build container from galaxy.

```
curl -LJO https://depot.galaxyproject.org/singularity/edta:2.2.0--hdfd78af_1
```

After download you can rename the file to `EDTA.sif`

**Comment by oushujun** [comment]
The current conda recipe is not correctly configured, so the
docker/singularity derived from it won’t work. We are working on the conda
recipe now.

Shujun

**Comment by CongLiu37** [comment]
Hello @oushujun @GallVp 

Thanks for your messages. The curl command worked as 
`singularity exec EDTA.sif EDTA.pl -h`
printed the help manual. But for the test:
`singularity exec /apps/unit/BourguignonU/EDTA.sif EDTA.pl --genome genome.fa --cds genome.cds.fa --curatedlib ../database/rice6.9.5.liban --exclude genome.exclude.bed --overwrite 1 --sensitive 1 --anno 1 --evaluate 1 --threads 10`
there was something wrong with the dependencies:

```
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "en_GB.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").

#########################################################
##### Extensive de-novo TE Annotator (EDTA) v2.2.0  #####
##### Shujun Ou (shujun.ou.1@gmail.com)             #####
#########################################################


Parameters: --genome genome.fa --cds genome.cds.fa --curatedlib ../database/rice6.9.5.liban --exclude genome.exclude.bed --overwrite 1 --sensitive 1 --anno 1 --evaluate 1 --threads 10


Wed Jan 31 10:39:07 JST 2024	Dependency checking:
Error: gt is not found in the genometools path ./!
```


I am not sure about singularity, but I have gt installed:

```
which gt
~/miniconda3/bin/gt
```

Sincerely,

Cong

**Comment by CongLiu37** [comment]
Anyway I successfully installed all dependencies with mamba. Although I am still having issues, but it is in another question. I am closing this one. Thanks for your help.

Sincerely,

Cong
