### ISSUE TITLE
2024-01-30 02:12:48,620 -WARNING- Grid computing is not available because DRMAA not configured properly: 

### ISSUE THREAD

**Issue by mirror110** [oushujun/EDTA#425]
Hi,
I used EDTA to screen the whole genome sequences, while I received some warning information as following:

2024-01-30 02:12:48,620 -WARNING- Grid computing is not available because DRMAA not configured properly: Could not find drmaa library.  Please specify its full path using the environment variable DRMAA_LIBRARY_PATH

/public2/home/mambaforge/envs/EDTA/lib/python3.6/site-packages/Bio/Seq.py:2338: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.

How should I deal with these issues ?

Thanks.

**Comment by oushujun** [comment]
That’s a warning message from TEsorter, you may just ignore it. It’s fine.

Shujun
