### ISSUE TITLE
TIR filtration

### ISSUE THREAD

**Issue by bijendrabio** [oushujun/EDTA#426]
Hello Shujun,
Curious if the TIR elements identified using "EDTA_raw.pl --type tir" requires filtering. Its generate two files *.intact.fa and *.raw.fa, both of which are same. Does this indicate that additional processing is needed?

Regards,
B

**Comment by oushujun** [comment]
It's already filtered by EDTA_raw and produced the two files. And yes, they are identical just for programmatic convenience. They will be further filtered by EDTA_processK.pl in the .combine folder.

Shujun

**Comment by oushujun** [comment]
Process_K will get more false positive filtered, but the intact file in raw
is already heavily filtered. It’s your call.

Shujun
