### ISSUE TITLE
Benefit of using panEDTA

### ISSUE THREAD

**Issue by Isoris** [oushujun/EDTA#428]
Hello, I would like to compare the TE landscapes of different species of the same taxonomic order. I have obtained the TE libraries using EDTA for each species. 
Now if I use panEDTA and reannotate each species using the panTE library, will the TE landscape be of higher quality? What are the advantages of using panEDTA over EDTA multiple times?

Can I be able to find which TE are present in a subset of species or common to a subset of species but not in others? Which are present and absent ? 

Can I compare two repeat landscapes of two species by using EDTA two times? Or should I only compare them if I have used panEDTA?

Thank you for your answer because I don't really understand what type of analysis that panEDTA allow over EDTA for between species and not within species analyses?

**Comment by oushujun** [comment]
PanEDTA gives you higher quality annotations and consistent names so that
you can compare across genomes.

Shujun
