### ISSUE TITLE
EDTA_2.2.x.yml seems not working

### ISSUE THREAD

**Issue by Yutang-ETH** [oushujun/EDTA#430]
Hi Shujun,

Thank you very much for providing EDTA to the world. 

I am trying to install EDTA with conda following your instruction. However, I found that conda failed to solve the env with EDTA_2.2.x.yml. Please see below what I got from conda:

        Could not solve for environment specs
        Encountered problems while solving:
          - nothing provides __cuda needed by tensorflow-2.11.0-cuda112py39h01bd6f0_0
          - nothing provides __cuda needed by tensorflow-base-2.11.0-cuda112py39h1c230a5_0
          - nothing provides __cuda needed by tensorflow-base-2.11.0-cuda112py39h1c230a5_0
        
        The environment can't be solved, aborting the operation 

While, on the other hand, I can confirm that EDTA.yml worked perfectly fine for me on my Linux machine. 
The command I used for conda installation is the following:

    mamba env create -p path_to_my_env/EDTA -f path_to_edta_gitrepo/EDTA.yml (or EDTA_2.2.x.yml)

Maybe just a quick question: what is the difference between EDTA.yml and EDTA_2.2.x.yml? Are the two versions? Which one is better?

Best wishes,
Yutang

**Comment by Yutang-ETH** [comment]
Just a quick update. While I was running EDTA installed with EDTA.yml, I found that AnnoSINE is missing:

`perl ./EDTA/EDTA.pl --check_dependencies`

Error: AnnoSINE is not found in the AnnoSINE path ./!

So I have to install AnnoSINE again with mamba
`mamba install -p /scratch/yutang/EDTA/ annosine2`

Now check the dependencies again
`perl ./EDTA/EDTA.pl --check_dependencies`

Sat Feb 10 13:15:06 CET 2024    Dependency checking:
                                                    All passed!

If you want, I could share the spec-file.txt of my conda env so that people can create an identical env as mine. https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#building-identical-conda-environments
`conda create --name myenv --file spec-file.txt`

Best wishes,
Yutang

**Comment by G-Thomson** [comment]
Hi Yutang

I also am having trouble with the EDTA_2.2.x.yml file. Are you able to share your spec-file.txt with me?
Either here or my email is in my bio.

Many thanks,
Geoffrey

**Comment by Yutang-ETH** [comment]
Hi Geoffrey, @G-Thomson 

No problem, let me just paste it here so that maybe others can also try. 
[edta_yutang_spec-file.txt](https://github.com/oushujun/EDTA/files/14307920/edta_yutang_spec-file.txt)

Good luck.

@oushujun, I hope you don't mind I share the file here. Otherwise, I will delete it. Thank you.

Best wishes,
Yutang

**Comment by G-Thomson** [comment]
Thank-you Yutang!

**Comment by oushujun** [comment]
Hello,

Please try the updated yml file. Thanks!

Shujun

**Comment by Yutang-ETH** [comment]
Thank you @oushujun , I will try the new yml file.

Best wishes,
Yutang

**Comment by Yutang-ETH** [comment]
Hi, @oushujun,

Sorry for the late reply, but now I can confirm that the installation with the latest EDTA_2.2.x.yml works.

Best wishes,
Yutang
