### ISSUE TITLE
Exploring the Discrepancies between TEanno.gff3 and TElib.fa

### ISSUE THREAD

**Issue by khjia** [oushujun/EDTA#433]
Hi, 
I am using EDTA version 1.9.9, and the command I executed is: `perl ~/bin/EDTA/EDTA.pl --genome *.fa --overwrite 0 --sensitive 1 --anno 1 --threads 24`. The program runs normally and I got the correct output results. However, I noticed a discrepancy in the annotation between the genome.fasta.mod.EDTA.TEanno.gff3 and genome.fasta.mod.EDTA.TElib.fa files. For instance, in the gff3 file, I annotated MITE type TE, but these are not present in the TElib.fa file. I am wondering why this is happening. Can you help me with this issue?

Best wishes,
Kai-Hua

**Comment by EdgarLW** [comment]
I am having a similar issue when comparing the genome.fasta.mod.EDTA.TElib.fa with the genome.fasta.mod.EDTA.TEanno.sum. In the summary report, only 29 sequences of TIR-CACTA are reported, but doing a simple `grep '>' $file | grep` -c 'CACTA' in the fasta library results in 99 instances. Furthermore, the sum file reports only a total of 3168 basepairs masked, while a single CACTA sequence of the 99 is over 3000 bps in length.
It is as if they are depicting different files/genomes.

I'm working with the singularity container of EDTA 2.0.0 from bioconda.

**Comment by EdgarLW** [comment]
After a couple of BLASTn runs, in my case, it appears that the .gff and the .sum files are the correct ones. For some reason many CACTA and other Type II TEs were added to many of the libraries even though they are not present, resulting in over 1400 TEs with 100% identity across 18 genomes. BLASTn helped checking actual TEs present from the .fa file. Not sure if it is implemented and I missed it, but it would be nice to be able to retrieve the TEs using the genome and gff anotation file in this case, not just relying on the annotated .fa file.

**Comment by oushujun** [comment]
Hello, sorry for the delayed response. The library contains elements with a decent number of copies in the genome, while the gff3 also contains low-copy elements. Including the low-copy element in the library will significantly increase the library size and the false positive rate, thus they were not used in the homology annotation step. This is likely the discrepancy you observed. I'll close this thread for now. feel free to reopen it if you have questions.

Thanks!
Shujun
