### ISSUE TITLE
the pipeline about panEDTA

### ISSUE THREAD

**Issue by QianghuiZhu** [oushujun/EDTA#436]
Hi, Oushujun!
I have some animal genomes and want to annotate them by panEDTA. But now, I am confused about the some pipeline of panEDTA. 
I read some others' issues about panEDTA, and they seem that: 
1) Using EDTA for each genome;
2) Using panEDTA to get the pan TE lib;
3) Using panTElib to reannotate each genome again by EDTA.

But I read the example you provided (https://github.com/HuffordLab/NAM-genomes/tree/master/te-annotation)
![image](https://github.com/oushujun/EDTA/assets/77773766/bf5e0623-82b9-463a-b7cb-dbc9b2469a52)
It seems that:
1) Using EDTA for each genome; 
2) Using TElib of each genome to reannotate each genome again by EDTA;
3) Using panEDTA to get the pan TE lib;
4) Using panTElib to reannotate each genome again by EDTA.

So, my question is about,should I reannotate the genome again with their TEblib in step2?

Thanks!
Best Wishes!

**Comment by QianghuiZhu** [comment]
I used two ways of above with EDTA: pipeline1) using EDTA for genomeA; pipeline2) using the output TElib of pipeline1 as a curated library (--curatedlib), and rerun EDTA for genomeA again.
And here is the result statistics
![image](https://github.com/oushujun/EDTA/assets/77773766/80e110d2-b8ec-408e-8f17-f0c67101b0af)
Some types of TE with different num in these two output results. I checked some TE position and they are same.

Is it possible that reannotating genome by EDTA again is optional, or not need to reannotate again?

Best!

**Comment by oushujun** [comment]
Hello,

Your pipeline 2 step 2 can be merged into step 1 if you specify —anno 1 in
your step 1. This annotation is necessary to identify copy numbers of each
family.

Your results are pretty consistent. The variations can be considered
uncertainty of TE annotation. Please check the wiki.

Best,
Shujun

**Comment by QianghuiZhu** [comment]
Thank you, Shujun.
I run pipeline1 and pipeline2 both with _--anno 1_ previously. I'll just use pipeline1 (with --anno 1) to save time.
Best!

> Hello, Your pipeline 2 step 2 can be merged into step 1 if you specify —anno 1 in your step 1. This annotation is necessary to identify copy numbers of each family. 
> Your results are pretty consistent. The variations can be considered uncertainty of TE annotation. Please check the wiki. 
> Best, Shujun

**Comment by CSU-KangHu** [comment]
Hi @oushujun,
I have some confusion about the panEDTA pipeline. It seems that panEDTA runs EDTA on each genome individually and then merges the EDTA TE libraries from each genome. Considering that genomes constituting the panGenome have a significant proportion of shared conserved sequences (core genome), why not first construct the panGenome from different genomes and then use EDTA to identify and annotate TEs on the panGenome?

**Comment by oushujun** [comment]
Yes, you may do that. Be aware that the graph pangenome may present
variable sequences to you without the adjacent sequences, the latter are
needed for EDTA to determine the authenticity of a structurally intact TE.

Best,
Shujun

**Comment by QianghuiZhu** [comment]
Hi, Shujun.
I am sorry to bother you again.

I downloaded some genome and cds data from NCBI, and want to annotate them using EDTA. 
Some homologous chr sequence in different genomes are inverted. And I plan to use the reverse complement sequence of these chr to ensure the consistency of strand.  May I also need to use the reverse complement sequence of cds data in these chr? Or primary cds data is ok and strand INFO have no impacts on TE annotation?

Thanks!
Best!
