### ISSUE TITLE
Two genomes LTR result file has 0 bp, while the others are not.

### ISSUE THREAD

**Issue by ZhuYongli1212** [oushujun/EDTA#437]
Hi Shujun, 

I'm annotating the over 50 maize genomes using EDTA. I ran into a weird situation where the LTR annotation results for two genomes showing as 0, while the others are normal. I've checked the input files for these two genomes, and they seem no different from the others. Not sure where things went wrong, so I'm reaching out for your help. Any insights would be greatly appreciated. 

I am using the below-presented command:
EDTA.pl --genome Zm-S37.chr10.fa  --anno 1 --threads 3 --curatedlib NAM..MTEC02052020.clean.fa

Error:
Mon Feb 26 14:41:26 CST 2024    Obtain raw TE libraries using various structure-based programs: 
Mon Feb 26 14:41:26 CST 2024    EDTA_raw: Check dependencies, prepare working directories.
Mon Feb 26 14:41:29 CST 2024    Start to find LTR candidates.
Mon Feb 26 14:41:29 CST 2024    Identify LTR retrotransposon candidates from scratch.
ERROR: No candidate is found in the file(s) you specified.
awk: cannot open Zm-S37_chr10.fa.mod.pass.list (No such file or directory)
Warning: LOC list - is empty.
        perl rename_LTR_skim.pl target_sequence.fa LTR_retriever.defalse
Error: Error while loading sequence
        perl filter_gff3.pl file.gff3 file.list > new.gff3
Mon Feb 26 14:41:42 CST 2024    Warning: The LTR result file has 0 bp!

*scn file contains no additional information.
<img width="380" alt="dc783e5ce4d65f29ec872ae3ce63190" src="https://github.com/oushujun/EDTA/assets/143006646/520903c3-5fb3-4384-98dd-031a63ee67e8">
<img width="847" alt="865472b0d517e16fe70c18d840dafd3" src="https://github.com/oushujun/EDTA/assets/143006646/510e7a5c-977c-4bde-8adc-b598fc142216">

Looking forward to your response. Thanks a bunch!

Best,
Yongli

**Comment by oushujun** [comment]
Hi Yongli,

Sorry for the delay. Please check the sequence header of your genomes. Also try to run LTR_FINDER_parallel separately and see if there's any error message.

Best,
Shujun

**Comment by oushujun** [comment]
Any luck?

**Comment by ZhuYongli1212** [comment]
Apologies for the delay. I've been occupied with other matters recently, and this issue was temporarily set aside. I'll continue addressing this problem and provide timely updates as soon as there are any results. Thank you for your ongoing patience and interest in this matter.
