### ISSUE TITLE
TIRlearner crashes Out of Memory

### ISSUE THREAD

**Issue by maudf** [oushujun/EDTA#44]
Hi ! 
I run into a memory issue trying to run TIR-Learner. Did you already run into it? And what can I do to solve this issue?

Here are the commands/outputs that I get:
$ nohup perl ../EDTA/EDTA_raw.pl -genome F2.genome.fasta -species Maize -type tir -threads 20 > essai_tir.out 2> essai_tir.err &
$ cat essai_tir.err
nohup: ignoring input
Wed Jan 15 19:24:43 CET 2020	EDTA_raw: Check files and dependencies, prepare working directories.

Wed Jan 15 19:24:43 CET 2020	Start to find TIR candidates.

ln: failed to create symbolic link 'F2.genome.fasta': Input/output error
Wed Jan 15 19:24:43 CET 2020	Identify TIR candidates from scratch.

Species: Maize
Out of memory!
Out of memory!
Out of memory!
Out of memory!
Out of memory!
Out of memory!
Out of memory!
Out of memory!
Out of memory!
Out of memory!
Out of memory!
Out of memory!
Out of memory!
Out of memory!
Out of memory!
Out of memory!

	ERROR: no LOC list!

	Usage: perl call_seq_by_list.pl MSU_format_list -C genome.fasta -out file.fa [options]
		itself	Output sequence specified in the list (default).
		up_[int]	Output sequences [int] bp upstream of the region.
		down_[int]	Output sequences [int] bp downstream of the region.
		-C [fasta]	A fasta file you want to extract sequence from.
		-out	Output file name. Default: MSU_format_list.fa
		-header	[0|1]	Output sequence with (1, default) or without (0) sequence header.
		-rmvoid	[0|1]	Remove empty sequence (1, default) or retain empty sequence (0) in output.
		-ex		Exclude sequence specified by the list. Default: Output sequence specified by the list.
		-cov	[0-1]	Work with -ex. If excluding too much of the target (default 1), discard the entire sequence.
		-purge	[0|1]	Work with -ex. Switch on=1/off=0(default) to clean up aligned region and joint unaligned sequences.
	Example: 
		Call sequence of upper 2000 bp region in the list and output to result.fa
			perl call_seq_by_list.pl array_list -C rice.fasta up_2000 -out result.fa
Out of memory!
Out of memory!
Out of memory!
Out of memory!

**Comment by oushujun** [comment]
Hello, you may need to allocate more memory to run it. I tried on a wheat
genome and it took at least 100 G of memory.

Best,
Shujun
