### ISSUE TITLE
make_masked.pl     Permission denied

### ISSUE THREAD

**Issue by chun-he-316** [oushujun/EDTA#440]
Hi Shujun,
I want to get softmasked genome. I used this command "perl ../util/make_masked.pl -genome genome.fa -minlen 80 -hardmask 0 -t 2 -rmout genome.fa.mod.EDTA.anno/genome.fa.mod.EDTA.TEanno.out",but this error occurred "Permission denied ../util/make_masked.pl line 54."
Please tell me how to solve this issue. Thanks.
The best,
Chun

**Comment by oushujun** [comment]
Hi Chun,

Please make sure you have write access to the folder that contains your
output.

Thanks,
Shujun
