### ISSUE TITLE
The inconsistency between the classification labels of the EDTA library and RepeatMasker

### ISSUE THREAD

**Issue by CSU-KangHu** [oushujun/EDTA#442]
Hi @oushujun,
Thank you for developing such a useful tool like EDTA. 

While running EDTA, I encountered an issue that I had previously overlooked. The classification labels of the TE library outputted by EDTA do not match those of RepeatMasker. This discrepancy results in certain types of TEs being ignored when the TE library generated by EDTA is used as the input parameter (`-lib`) in RepeatMasker to generate the `.tbl` file. 

For instance, EDTA's Helitron label is classified as `DNA/Helitron`, whereas RepeatMasker classifies it as `RC/Helitron`. As a result, the `Rolling-circles` line in the .tbl file shows `0` bp, and the proportion of `DNA transposons` is overestimated. Similarly, there are issues with other labels such as `MITE`, which seem to be classified as `DNA` labels for RepeatMasker to properly categorize them as `DNA transposons`. Could you please let me know if EDTA provides a script to convert the classification labels of the TE library to match those of RepeatMasker?

**Comment by oushujun** [comment]
I haven’t figured out what names RepeatMasker takes or not takes. You
should use the less picky buildSummary.pl script to generate the rm out
summary.

Shujun
