### ISSUE TITLE
fa file

### ISSUE THREAD

**Issue by DangPengsanqi** [oushujun/EDTA#444]
In the process of using the software, there were many inconsistencies in the results, I extracted a short sequence from the genome to form a fa file, and there was a difference between the prediction results and the full genome fa file, and some TEs were not annotated in the small fa file

**Comment by oushujun** [comment]
EDTA is designed for TE annotation on whole-genome data, not for small genomic sequences. Please read the wiki for more information. Thanks for using EDTA!

Shujun

**Comment by DangPengsanqi** [comment]
OK,Thank you very much for your reply

**Comment by DangPengsanqi** [comment]
> EDTA is designed for TE annotation on whole-genome data, not for small genomic sequences. Please read the wiki for more information. Thanks for using EDTA!
> 
> Shujun

OK,Thank you very much for your reply
