### ISSUE TITLE
ERROR: TE annotation stats results not found in mod.EDTA.TE.fa.stat!

### ISSUE THREAD

**Issue by CrayonLinchan** [oushujun/EDTA#445]
Hi,
thanks for the nice tools.  I have installed the latest EDTA v2.2.1 using conda and run the test file successfully. However, when I ran my own data, I encountered the following error message and  obtain TEanno.sum file with 0k (but I have gff3 file for TE annotation). I am so confuded :(

Here is my code:
`nohup EDTA/EDTA.pl --genome selected.fa --species others --sensitive 1 --step all  --anno 1  -t 8 --u 7e-9 2> edta.log &`

And here is my EDTA.log file:
nohup: ignoring input and appending output to 'nohup.out'
Sat 09 Mar 2024 08:53:38 PM CST	EDTA_raw: Check dependencies, prepare working directories.

Sat 09 Mar 2024 08:53:39 PM CST	Start to find LTR candidates.

Sat 09 Mar 2024 08:53:39 PM CST	Identify LTR retrotransposon candidates from scratch.

Sat 09 Mar 2024 09:24:37 PM CST	Finish finding LTR candidates.

Sat 09 Mar 2024 09:24:37 PM CST	Start to find SINE candidates.

Sat 09 Mar 2024 09:52:06 PM CST	Finish finding SINE candidates.

Sat 09 Mar 2024 09:52:06 PM CST	Start to find LINE candidates.

Sat 09 Mar 2024 09:52:06 PM CST	Identify LINE retrotransposon candidates from scratch.

Sun 10 Mar 2024 01:54:53 AM CST	Finish finding LINE candidates.

Sun 10 Mar 2024 01:54:53 AM CST	Start to find TIR candidates.

Sun 10 Mar 2024 01:54:53 AM CST	Identify TIR candidates from scratch.

Species: others
Sun 10 Mar 2024 03:43:28 AM CST	Finish finding TIR candidates.

Sun 10 Mar 2024 03:43:28 AM CST	Start to find Helitron candidates.

Sun 10 Mar 2024 03:43:28 AM CST	Identify Helitron candidates from scratch.

Sun 10 Mar 2024 04:24:48 AM CST	Finish finding Helitron candidates.

Sun 10 Mar 2024 04:24:48 AM CST	Execution of EDTA_raw.pl is finished!

Warning: No sequences were masked
Sun 10 Mar 2024 04:30:12 AM CST	Homology-based annotation of TEs using selected.fa.mod.EDTA.TElib.fa from scratch.

Use of uninitialized value $type in concatenation (.) or string at /EDTA/util/gff2bed.pl line 112, <GFF> line 13922.
Use of uninitialized value $type in concatenation (.) or string at /EDTA/util/gff2bed.pl line 112, <GFF> line 16127.
Use of uninitialized value $type in concatenation (.) or string at /EDTA/util/gff2bed.pl line 112, <GFF> line 16612.
Use of uninitialized value $type in concatenation (.) or string at /EDTA/util/gff2bed.pl line 112, <GFF> line 23942.
Use of uninitialized value $type in concatenation (.) or string at /EDTA/util/gff2bed.pl line 112, <GFF> line 28139.
Use of uninitialized value $type in concatenation (.) or string at /EDTA/util/gff2bed.pl line 112, <GFF> line 36110.
Use of uninitialized value $type in concatenation (.) or string at /EDTA/util/gff2bed.pl line 112, <GFF> line 36974.
Use of uninitialized value $type in concatenation (.) or string at /EDTA/util/gff2bed.pl line 112, <GFF> line 13999.
Use of uninitialized value $type in concatenation (.) or string at /EDTA/util/gff2bed.pl line 112, <GFF> line 16192.
Use of uninitialized value $type in concatenation (.) or string at /EDTA/util/gff2bed.pl line 112, <GFF> line 16681.
Use of uninitialized value $type in concatenation (.) or string at /EDTA/util/gff2bed.pl line 112, <GFF> line 24052.
Use of uninitialized value $type in concatenation (.) or string at /EDTA/util/gff2bed.pl line 112, <GFF> line 28349.
Use of uninitialized value $type in concatenation (.) or string at /EDTA/util/gff2bed.pl line 112, <GFF> line 36329.
Use of uninitialized value $type in concatenation (.) or string at /EDTA/util/gff2bed.pl line 112, <GFF> line 37176.
Use of uninitialized value $class in hash element at /EDTA/util/div_table2.pl line 80, <$fh> line 13502.
Use of uninitialized value $class in hash element at /EDTA/util/div_table2.pl line 81, <$fh> line 13502.
Use of uninitialized value $class in hash element at /EDTA/util/div_table2.pl line 80, <$fh> line 15655.
Use of uninitialized value $class in hash element at /EDTA/util/div_table2.pl line 81, <$fh> line 15655.
Use of uninitialized value $class in hash element at /EDTA/util/div_table2.pl line 80, <$fh> line 16134.
Use of uninitialized value $class in hash element at /EDTA/util/div_table2.pl line 81, <$fh> line 16134.
Use of uninitialized value $class in hash element at /EDTA/util/div_table2.pl line 80, <$fh> line 23140.
Use of uninitialized value $class in hash element at /EDTA/util/div_table2.pl line 81, <$fh> line 23140.
Use of uninitialized value $class in hash element at /EDTA/util/div_table2.pl line 80, <$fh> line 27207.
Use of uninitialized value $class in hash element at /EDTA/util/div_table2.pl line 81, <$fh> line 27207.
Use of uninitialized value $class in hash element at /EDTA/util/div_table2.pl line 80, <$fh> line 34902.
Use of uninitialized value $class in hash element at /EDTA/util/div_table2.pl line 81, <$fh> line 34902.
Use of uninitialized value $class in hash element at /EDTA/util/div_table2.pl line 80, <$fh> line 35739.
Use of uninitialized value $class in hash element at /EDTA/util/div_table2.pl line 81, <$fh> line 35739.
Use of uninitialized value in pattern match (m//) at /EDTA/util/call_seq_by_list.pl line 90.
Use of uninitialized value $chr_pre in hash element at /EDTA/util/call_seq_by_list.pl line 92.
Use of uninitialized value $pos in pattern match (m//) at /EDTA/util/call_seq_by_list.pl line 103.
Use of uninitialized value $pos in concatenation (.) or string at /EDTA/util/call_seq_by_list.pl line 106.
ERROR: Can not recognize this MSU position in the list!
ERROR: TE annotation stats results not found in selected.fa.mod.EDTA.TE.fa.stat!

And here is my nohup.out file:

#########################################################
#########################################################

Parameters: --genome selected.fa --species others --sensitive 1 --step all --anno 1 -t 8 --u 7e-9

Sat 09 Mar 2024 08:53:34 PM CST	Dependency checking:
				All passed!

Sat 09 Mar 2024 08:53:38 PM CST	Obtain raw TE libraries using various structure-based programs: 
Sun 10 Mar 2024 04:24:48 AM CST	Obtain raw TE libraries finished.
				All intact TEs found by EDTA: 
					selected.fa.mod.EDTA.intact.raw.fa 
					selected.fa.mod.EDTA.intact.raw.gff3

Sun 10 Mar 2024 04:24:48 AM CST	Perform EDTA advance filtering for raw TE candidates and generate the stage 1 library: 

Sun 10 Mar 2024 04:26:53 AM CST	EDTA advance filtering finished.

Sun 10 Mar 2024 04:26:53 AM CST	Perform EDTA final steps to generate a non-redundant comprehensive TE library.

				Filter RepeatModeler results that are ignored in the raw step.

				Skipping the CDS cleaning step (--cds [File]) since no CDS file is provided or it's empty.

Sun 10 Mar 2024 04:30:12 AM CST	EDTA final stage finished! You may check out:
				The final EDTA TE library: selected.fa.mod.EDTA.TElib.fa
Sun 10 Mar 2024 04:30:12 AM CST	Perform post-EDTA analysis for whole-genome annotation:

Sun 10 Mar 2024 04:36:00 AM CST	TE annotation using the EDTA library has finished! Check out:
				Whole-genome TE annotation (total TE: ): selected.fa.mod.EDTA.TEanno.gff3
				Whole-genome TE annotation summary: selected.fa.mod.EDTA.TEanno.sum
				Whole-genome TE divergence plot: selected.fa.mod_divergence_plot.pdf
				Whole-genome TE density plot: selected.fa.mod.EDTA.TEanno.density_plots.pdf
				Low-threshold TE masking for MAKER gene annotation (masked: 14.49%): selected.fa.mod.MAKER.masked

Sun 10 Mar 2024 04:36:00 AM CST	Evaluate the level of inconsistency for whole-genome TE annotation:

Looking forward to your kindly reply!!
Have a nice day! :)

**Comment by CrayonLinchan** [comment]
I found some issues with my genome files!! I will fix it and try again!

**Comment by yanyew** [comment]
> I found some issues with my genome files!! I will fix it and try again!

What's the exact issue that cause this error?

**Comment by QuintoHe** [comment]
same for me , no clue
