### ISSUE TITLE
Would you consider adding -w $genome_file_real_path.EDTA.raw/TIR to line 576 of EDTA_raw.pl

### ISSUE THREAD

**Issue by Yutang-ETH** [oushujun/EDTA#447]
Hi @oushujun ,

I found the -w could specify the working directory for TIR-learner so that the intermediate files won't go to the default TMP folder which might not have the enough space to hold the intermediate files #327 

Best wishes,
Yutang

**Comment by oushujun** [comment]
Good call! I have added this to the EDTA_raw, which will be seen in the next update. - Shujun
