### ISSUE TITLE
Can't locate SearchResult.pm in @INC (you may need to install the SearchResult module)

### ISSUE THREAD

**Issue by chenHuiRu8** [oushujun/EDTA#448]
calcDivergenceFromAlign.pl -a
Can't locate SearchResult.pm in @INC (you may need to install the SearchResult module) (@INC contains: /share/home/stu_chenhuiru/miniconda3/bin/.. /share/home/stu_chenhuiru/miniconda3/share/RepeatMasker/util /home/rhubley/projects/RepeatMasker /share/home/stu_chenhuiru/miniconda3/lib/site_perl/5.26.2/x86_64-linux-thread-multi /share/home/stu_chenhuiru/miniconda3/lib/site_perl/5.26.2 /share/home/stu_chenhuiru/miniconda3/lib/5.26.2/x86_64-linux-thread-multi /share/home/stu_chenhuiru/miniconda3/lib/5.26.2 .) at /share/home/stu_chenhuiru/miniconda3/bin/calcDivergenceFromAlign.pl line 92.
BEGIN failed--compilation aborted at /share/home/stu_chenhuiru/miniconda3/bin/calcDivergenceFromAlign.pl line 92.
i had already cpan install SearchResult
but it didint work out .

**Comment by chenHuiRu8** [comment]
calcDivergenceFromAlign.pl
Can't locate SearchResult.pm in @INC (you may need to install the SearchResult module) (@INC contains: /share/home/stu_chenhuiru/miniconda3/bin/.. /share/home/stu_chenhuiru/miniconda3/share/RepeatMasker/util /home/rhubley/projects/RepeatMasker /share/home/stu_chenhuiru/miniconda3/lib/site_perl/5.26.2/x86_64-linux-thread-multi /share/home/stu_chenhuiru/miniconda3/lib/site_perl/5.26.2 /share/home/stu_chenhuiru/miniconda3/lib/5.26.2/x86_64-linux-thread-multi /share/home/stu_chenhuiru/miniconda3/lib/5.26.2 .) at /share/home/stu_chenhuiru/miniconda3/bin/calcDivergenceFromAlign.pl line 92.
BEGIN failed--compilation aborted at /share/home/stu_chenhuiru/miniconda3/bin/calcDivergenceFromAlign.pl line 92.

**Comment by oushujun** [comment]
This seems to be the issue of Repeatmasker or the conda version of RepeatMasker. Please seek help on their sites because I have no idea. Thank you!

Shujun

**Comment by wuyh0328** [comment]
Hey!Have you solved your problem? I had the same problem.
