### ISSUE TITLE
Hey!Have you solved your problem? I had the same problem.

### ISSUE THREAD

**Issue by chenHuiRu8** [oushujun/EDTA#449]
Hey!Have you solved your problem? I had the same problem.

_Originally posted by @wuyh0328 in https://github.com/oushujun/EDTA/issues/448#issuecomment-2011172734_
            haven't solved yet

**Comment by oushujun** [comment]
@chenHuiRu8 Please don't open new issues by replying to an existing issue. Thanks! - Shujun
