### ISSUE TITLE
I just found that this script in the (../../share/RepeatMasker/) folder will not have this error, maybe can copy the input file, I think it can try?If you tried, can you tell me the result?

### ISSUE THREAD

**Issue by chenHuiRu8** [oushujun/EDTA#450]
I just found that this script in the (../../share/RepeatMasker/) folder will not have this error, maybe can copy the input file, I think it can try?If you tried, can you tell me the result?

_Originally posted by @wuyh0328 in https://github.com/oushujun/EDTA/issues/449#issuecomment-2011317472_
            I just solved the problem.
export PERL5LIB=$PERL5LIB:/share/home/stu_chenhuiru/miniconda3/envs/EDTA/share/RepeatMasker

**Comment by chenHuiRu8** [comment]
yes






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月21日(星期四) 下午3:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [oushujun/EDTA] I just found that this script in the (../../share/RepeatMasker/) folder will not have this error, maybe can copy the input file, I think it can try?If you tried, can you tell me the result? (Issue #450)





 
Wow, did you add the perl environment with RepeatMasker to the whole conda environment? You are so good! So you can successfully generate the file，right?

**Comment by wuyh0328** [comment]
> yes
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年3月21日(星期四) 下午3:39 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [oushujun/EDTA] I just found that this script in the (../../share/RepeatMasker/) folder will not have this error, maybe can copy the input file, I think it can try?If you tried, can you tell me the result? (Issue #450) Wow, did you add the perl environment with RepeatMasker to the whole conda environment? You are so good! So you can successfully generate the file，right? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

NICE!

**Comment by oushujun** [comment]
@chenHuiRu8 Please don't open new issues by replying to an existing issue. Thanks!  - Shujun
