### ISSUE TITLE
文件缺失

### ISSUE THREAD

**Issue by Blosers** [oushujun/EDTA#452]
您好，我在git clone 安装完edta 之后 去运行 test 文件就会出现这样的报错，请问怎么解决？
Fri Mar 22 14:24:23 CST 2024	Dependency checking:
Error: AnnoSINE is not found in the AnnoSINE path ./!

**Comment by oushujun** [comment]
Hello,

Please reinstall or use a different way to install. The ReadMe file has multiple approaches.

Thanks!
Shujun
