### ISSUE TITLE
several issues in the ruuning of EDTA2

### ISSUE THREAD

**Issue by yanyew** [oushujun/EDTA#466]
Hello, thanks for your development of this useful tools!
I met several issues when use EDTA2:
1) the file `$genome.EDTA.TEanno.split.density` didin't show the running result but the following content
![image](https://github.com/oushujun/EDTA/assets/90335707/4420e2ef-2aee-4f14-86d2-307fddead3a4)

but the command line`python $density_table -genome $genome -gff $genome.EDTA.TEanno.split.gff3 > $genome.EDTA.TEanno.split.density` worked standalone rather than in the pipeline in EDTA.pl.

2) the file `$genome.EDTA.TEanno.sum` is empty while no any error message came out
![image](https://github.com/oushujun/EDTA/assets/90335707/0eb3101e-ff6d-4e86-a372-600dc7f4022d)

**Comment by oushujun** [comment]
@yanyew Sorry for the long delay. It's been a while since you opened this issue, and EDTA has updated substantially. Please reinstall EDTA and try again. Thanks!

Shujun
