### ISSUE TITLE
Test file failed

### ISSUE THREAD

**Issue by xiaoxiao349** [oushujun/EDTA#469]
I spent two whole days running the test files but never succeeded. Tried every method to install the edta, including the ones on the github and conda local install, mamba or conda, lower versions of edta, through yml or conda, whatever... 

Got really exhausted and any advice would be deeply appreciated.

This is the error massage

Warning: LOC list genome.fa.mod.ltrTE.veryfalse is empty.

Filter sequence based on TEsorter classifications. Unclassified sequences will also be output to the clean file.
        Usage: perl cleanup_misclas.pl sequence.fa.rexdb.cls.tsv
        Author: Shujun Ou (shujun.ou.1@gmail.com) 10/11/2019

mv: cannot stat 'genome.fa.mod.LTR.intact.fa.ori.dusted.cln.cln': No such file or directory
mv: cannot stat 'genome.fa.mod.LTR.intact.fa.ori.dusted.cln.cln.list': No such file or directory
cp: cannot stat 'genome.fa.mod.LTR.intact.raw.fa.anno.list': No such file or directory
ERROR: No such file or directory at /data/home/liucm_lab/user/xx/edta_trial/EDTA/util/output_by_list.pl line 39.
Thu Jun  6 15:58:29 CST 2024    Finish finding LTR candidates.

Thu Jun  6 15:58:29 CST 2024    Start to find SINE candidates.

Thu Jun  6 15:59:11 CST 2024    Warning: The SINE result file has 0 bp!

Thu Jun  6 15:59:11 CST 2024    Start to find LINE candidates.

Thu Jun  6 15:59:11 CST 2024    Identify LINE retrotransposon candidates from scratch.

Filter sequence based on TEsorter classifications. Unclassified sequences will also be output to the clean file.
        Usage: perl cleanup_misclas.pl sequence.fa.rexdb.cls.tsv
        Author: Shujun Ou (shujun.ou.1@gmail.com) 10/11/2019

Can't open genome.fa.mod.RM2.raw.fa.cln.rexdb.cls.lib: No such file or directory.

Error: Error while loading sequenceThu Jun  6 16:00:29 CST 2024 Warning: The LINE result file has 0 bp!

Thu Jun  6 16:00:29 CST 2024    Start to find TIR candidates.

Thu Jun  6 16:00:29 CST 2024    Identify TIR candidates from scratch.

Species: others

Filter sequence based on TEsorter classifications. Unclassified sequences will also be output to the clean file.
        Usage: perl cleanup_misclas.pl sequence.fa.rexdb.cls.tsv
        Author: Shujun Ou (shujun.ou.1@gmail.com) 10/11/2019

mv: cannot stat 'genome.fa.mod.TIR.ext30.fa.pass.fa.dusted.cln.cln': No such file or directory
cp: cannot stat 'genome.fa.mod.TIR.ext30.fa.pass.fa.dusted.cln.cln.list': No such file or directory
cp: cannot stat 'genome.fa.mod.TIR.intact.raw.fa.anno.list': No such file or directory
ERROR: No such file or directory at /data/home/liucm_lab/user/xx/edta_trial/EDTA/util/output_by_list.pl line 39.
Warning: The TIR result file has 0 bp!

Thu Jun  6 16:00:56 CST 2024    Start to find Helitron candidates.

Thu Jun  6 16:00:56 CST 2024    Identify Helitron candidates from scratch.

Error: dl failure on line 542
Error: failed /data/home/liucm_lab/user/yzz/miniconda3/envs/EDTA2.2/lib/jvm/lib/server/libjvm.so, because /data/home/liucm_lab/software/sos/libm.so.6: symbol __strtof128_nan, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
Error: dl failure on line 542
Error: failed /data/home/liucm_lab/user/yzz/miniconda3/envs/EDTA2.2/lib/jvm/lib/server/libjvm.so, because /data/home/liucm_lab/software/sos/libm.so.6: symbol __strtof128_nan, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
Error: dl failure on line 542
Error: failed /data/home/liucm_lab/user/yzz/miniconda3/envs/EDTA2.2/lib/jvm/lib/server/libjvm.so, because /data/home/liucm_lab/software/sos/libm.so.6: symbol __strtof128_nan, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
Error: dl failure on line 542
Error: failed /data/home/liucm_lab/user/yzz/miniconda3/envs/EDTA2.2/lib/jvm/lib/server/libjvm.so, because /data/home/liucm_lab/software/sos/libm.so.6: symbol __strtof128_nan, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
Error: dl failure on line 542
Error: failed /data/home/liucm_lab/user/yzz/miniconda3/envs/EDTA2.2/lib/jvm/lib/server/libjvm.so, because /data/home/liucm_lab/software/sos/libm.so.6: symbol __strtof128_nan, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
Error: dl failure on line 542
Error: failed /data/home/liucm_lab/user/yzz/miniconda3/envs/EDTA2.2/lib/jvm/lib/server/libjvm.so, because /data/home/liucm_lab/software/sos/libm.so.6: symbol __strtof128_nan, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
Error: dl failure on line 542
Error: failed /data/home/liucm_lab/user/yzz/miniconda3/envs/EDTA2.2/lib/jvm/lib/server/libjvm.so, because /data/home/liucm_lab/software/sos/libm.so.6: symbol __strtof128_nan, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
Error: dl failure on line 542
Error: failed /data/home/liucm_lab/user/yzz/miniconda3/envs/EDTA2.2/lib/jvm/lib/server/libjvm.so, because /data/home/liucm_lab/software/sos/libm.so.6: symbol __strtof128_nan, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
HelitronScanner result files for the genome.fa.mod is not found!

Filter HelitronScanner fasta candidates
        perl format_helitronscanner_out.pl -genome genome.fa [options]
                -sitefilter     [0|1]   1 will filter out candidate without AT or TT target site (default); 0 will not.
                -minscore       [int]   Candidates with head and tail quality scores add up less than this will be discarded. Default: 12
                -keepshorter    [0|1]   1 will keep the shorter possible when multi 5' end presents (default); 0 will not; 2 will keep all possible 5' ends.
                -extlen [int]   Length of flanking sequence for blast and output. Default: 30 (bp)
                -extout [0|1]   Output original sequence (0, default) or extended (1) sequence.
                -h|-help        Display this help messege and exit.

HelitronScanner result files for the genome.fa.mod is not found!

Filter HelitronScanner fasta candidates
        perl format_helitronscanner_out.pl -genome genome.fa [options]
                -sitefilter     [0|1]   1 will filter out candidate without AT or TT target site (default); 0 will not.
                -minscore       [int]   Candidates with head and tail quality scores add up less than this will be discarded. Default: 12
                -keepshorter    [0|1]   1 will keep the shorter possible when multi 5' end presents (default); 0 will not; 2 will keep all possible 5' ends.
                -extlen [int]   Length of flanking sequence for blast and output. Default: 30 (bp)
                -extout [0|1]   Output original sequence (0, default) or extended (1) sequence.
                -h|-help        Display this help messege and exit.

The query file genome.fa.mod.HelitronScanner.filtered.ext.fa is not found!

Filter HelitronScanner fasta candidates
        perl flanking_filter.pl -genome genome.fa -query candidate.fa [options]
                -genome [file]  The multifasta file that used to generate the -query
                -query  [file]  The candidate TE sequence to be filtered by this script
                -extlen [int]   The length of extended flanking sequence in -query. Default: 30 (bp)
                -tgt_out        [int]   Output taget site with [int] length on each terminal. Default: 15 (bp)
                -miniden        [int]   Minimum identity for flanking sequence alignment. Default: 80 (%)
                -mincov [float] Minimum coverage for flanking sequence alignment that counts as full match. Default: 0.8
                -maxct  [int]   Maximum allowed copy number for flanking sequence for a true element. Default: 1.
                -blastplus      [path]  Path to the blastn program. Defalut: read from $ENV
                -t|-threads     [int]   Number of threads to run this program. Default: 4
                -h|-help        Display this help messege and exit.

ERROR: No such file or directory at /data/home/liucm_lab/user/xx/edta_trial/EDTA/util/output_by_list.pl line 37.

Error: Error while loading sequence
Filter sequence based on TEsorter classifications. Unclassified sequences will also be output to the clean file.
        Usage: perl cleanup_misclas.pl sequence.fa.rexdb.cls.tsv
        Author: Shujun Ou (shujun.ou.1@gmail.com) 10/11/2019

mv: cannot stat 'genome.fa.mod.HelitronScanner.filtered.fa.pass.fa.dusted.cln.cln': No such file or directory
cp: cannot stat 'genome.fa.mod.HelitronScanner.filtered.fa.pass.fa.dusted.cln.cln.list': No such file or directory
cp: cannot stat 'genome.fa.mod.Helitron.intact.raw.fa.anno.list': No such file or directory

        perl make_bed_with_intact.pl EDTA.intact.fa > EDTA.intact.bed

Thu Jun  6 16:00:57 CST 2024    Warning: The Helitron result file has 0 bp!

Thu Jun  6 16:00:57 CST 2024    Execution of EDTA_raw.pl is finished!

ERROR: Raw LTR results not found in genome.fa.mod.EDTA.raw/genome.fa.mod.LTR.raw.fa and genome.fa.mod.EDTA.raw/genome.fa.mod.LTR.intact.raw.fa
        If you believe the program is working properly, this may be caused by the lack of intact LTRs in your genome. Consider to use the --force 1 parameter to overwrite this check

**Comment by oushujun** [comment]
Hey @xiaoxiao349, I am sorry for the frustrating experience. Please refer to this issue for installations: #497. Please reopen the issue if you still have problems installing it.

Shujun
