### ISSUE TITLE
Locate source of annotation

### ISSUE THREAD

**Issue by fungal-spore** [oushujun/EDTA#470]
Hello,
I am interested in looking at the source that this element was annotated from (details in image).

![image](https://github.com/oushujun/EDTA/assets/52299431/41e9a43d-8514-438f-8104-af63c7d108ed)

I'm not sure how to locate. The database file 'Tpases020812LINE' doesn't seem to have anything that matches the description.
The sequence ontology site doesn't seem to have information for downloading seq data. 
http://sequenceontology.org/browser/current_release/term/SO:0000194

Please if you can help me learn how to find I would appreciate.

**Comment by oushujun** [comment]
Hello,

the sequence of this LINE element should located in the TElib.fa file. Please search the name "TE_00000249" for this sequence.

Thanks!
Shujun
