### ISSUE TITLE
.mod.EDTA.TEanno.sum was empty

### ISSUE THREAD

**Issue by Jimpann97** [oushujun/EDTA#471]
Hello, Professor Ou.

Recently, I have been using EDTA to annotate transposable elements (TEs) in multiple animal genomes. However, while some genomes can generate the .mod.EDTA.TEanno.sum file, others are blank.

My command is: perl EDTA.pl --step all --genome genome.fa --species others --threads 128 --sensitive 1 --anno 1 --overwrite 1 --curatedlib /DATA6/EDTA/11.software/SINELINE.fa 

The log that the .sum was empty shown that : 

Use of uninitialized value in pattern match (m//) at /DATA6/jimpan2/EDTA/util/call_seq_by_list.pl line 90.
Use of uninitialized value $chr_pre in hash element at /DATA6/jimpan2/EDTA/util/call_seq_by_list.pl line 92.
Use of uninitialized value $pos in pattern match (m//) at /DATA6/jimpan2/EDTA/util/call_seq_by_list.pl line 103.
Use of uninitialized value $pos in concatenation (.) or string at /DATA6/jimpan2/EDTA/util/call_seq_by_list.pl line 106.
ERROR: Can not recognize this MSU position in the list!
ERROR: TE annotation stats results not found in genome.fa.mod.EDTA.TE.fa.stat!

Best,
Pan

**Comment by FayeFang17** [comment]
Hi Pan, I think this is due to the lack of some sequence types, and I just updated EDTA. You may also try the EDTA2 branch version if you like!
