### ISSUE TITLE
Can I concatenate EDTA library and Repbase library manually?

### ISSUE THREAD

**Issue by Marh32** [oushujun/EDTA#472]
Hi Professor Ou:

I would like to ask whether I can concatenate EDTA library and Repbase library, then run RepeatMasker manually? I was glad to find EDTA can significantly reduce the percentage of unclassified in results. However, compare to the results from repeatmodeler customed library  + Repbase library, the percentage of repeat mask in EDTA's results is lower. Here are my results:
When I run EDTA with following command`perl ../EDTA.pl --genome genome.fa  --overwrite 1 --sensitive 1 --anno 1 --threads 30
`, I got the result(~31%):
<img width="514" alt="Screenshot 2024-06-19 at 22 33 23" src="https://github.com/oushujun/EDTA/assets/136884024/61222547-aaa3-4758-8da5-64b45d56550e">
But concatenate the Repbase and RepeatModeler customed library then run Repeatmasker `cat my_genome-families.fa RepeatMaskerLib.fasta > combine.fasta`, `RepeatMasker -pa 28 -s -lib combine.fasta -dir RMasker -e rmblast  my_genomic.fna`  I got the result(~40%):
<img width="550" alt="Screenshot 2024-06-19 at 22 58 10" src="https://github.com/oushujun/EDTA/assets/136884024/8fc54c6b-6456-473a-a4b9-27686b38bf19">
And I run Repeatmasker based on RepeatModeler customed library( Repbase library is not included) `RepeatMasker -pa 28 -s -lib my_genome-families.fa  -dir RMasker -e rmblast  my_genomic.fna`, I got the result(~35%): 
<img width="538" alt="Screenshot 2024-06-20 at 12 46 34" src="https://github.com/oushujun/EDTA/assets/136884024/6291f1e7-4f93-4c67-9e94-601f2e8d8b5b">

Is it possible that the lack of repbase library is causing the output to be low? Can I concatenate EDTA library and Repbase library to improve it? Or are there other reasons for the difference?  Thanks for your help in advance.

Best regards,
Hao

**Comment by oushujun** [comment]
Hello Hao,

It's possible, but also increase your chance to introduce false annotations. please check the extra sequence annotation with your other genome features like genes. Using EDTA with --sensitive 1 automatically activates RepeatModeler for further annotations. If you have a curated library, like Repbase, you can provide it to EDTA through --curatedlib.

Thanks,
Shujun
