### ISSUE TITLE
How to identify the structure feature of a TE sequence

### ISSUE THREAD

**Issue by leon945945** [oushujun/EDTA#486]
Hi, I have a TE sequence and I want to know its sequence structure feature, like TIR, EN, ORF1, ORF2, LTR, PBS, PPT, gag, pol or other structures.
Can EDTA be used to identify these sequence structure?

**Comment by oushujun** [comment]
Hello,

You can extract this information through different programs. EDTA provides TIR, LTR, and gag, pol information. For EN, ORF1, ORF2, you may use TEsorter. For PBS, PPT, you can use LTR_digest.

Thanks,
Shujun
