### ISSUE TITLE
NestTE out

### ISSUE THREAD

**Issue by porkfan** [oushujun/EDTA#488]
Hello Dr. Ou! I have a transposable element (TE) that was annotated using RepeatModeler, resulting in a complete 3.5kb CACTA_TIR_transposon. However, using the EDTA2 and the latest panEDTA pipeline, the annotation resulted in a 3kb Mutator-type transposon plus a 900bp Mutator_TIR_transposon. According to previous reports, there is mention of a 3.6kb CACTA-type transposon, but there has been no mention of the existence of a Mutator. Should I consider this as an annotation error or a new discovery (a Mutator inserted into the CACTA transposon)?

**Comment by oushujun** [comment]
Nested insertions are prevalent. You may use TEtrimmer to curate them.

Shujun

**Comment by porkfan** [comment]
Thank you for your prompt reply. I've heard quite a few recommendations about this software recently. I'll go back and learn more about it!
