### ISSUE TITLE
awk: fatal: cannot open file `genome.fa.mod.pass.list' for reading: No such file or directory

### ISSUE THREAD

**Issue by Dorrie1041** [oushujun/EDTA#490]
I install by conda, and when I run the test, I got this error, Could you please help me deal with that issue? Thank you! Here is the error I got.

Invalid value for shared scalar at /$MY_PATH/miniconda3/envs/EDTA/share
/LTR_retriever/bin/LTR.identifier.pl line 114, <ANNO> line 11.
cp: cannot stat 'genome.fa.mod.retriever.scn.adj': No such file or directory
awk: fatal: cannot open file `genome.fa.mod.pass.list' for reading: No such file or directory
Warning: LOC list - is empty.

Error: Error while loading sequence
Filter sequence based on TEsorter classifications. Unclassified sequences will also be output to the clean file.
        Usage: perl cleanup_misclas.pl sequence.fa.rexdb.cls.tsv
        Author: Shujun Ou (shujun.ou.1@gmail.com) 10/11/2019
        
mv: cannot stat 'genome.fa.mod.LTR.intact.fa.ori.dusted.cln.cln': No such file or directory
mv: cannot stat 'genome.fa.mod.LTR.intact.fa.ori.dusted.cln.cln.list': No such file or directory
cp: cannot stat 'genome.fa.mod.LTR.intact.raw.fa.anno.list': No such file or directory
ERROR: No such file or directory at /clusterfs/jgi/groups/science/homes/dshen/miniconda3/envs/EDTA/share/EDTA/util/output_by_list.pl line 39.

**Comment by Okompath** [comment]
encountering the same issue, how was this resolved?

**Comment by oushujun** [comment]
Please look up the error in other issues.

Shujun
