### ISSUE TITLE
LINE/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.

### ISSUE THREAD

**Issue by liangchengbo** [oushujun/EDTA#491]
There are no errors or warnings in my log, but at the end there is a lot of "LINE/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
"Does this affect the subsequent analysis? How can I solve this problem?

**log**：
2024年 08月 05日 星期一 07:36:44 CST	EDTA_raw: Check dependencies, prepare working directories.
2024年 08月 05日 星期一 07:36:47 CST	Start to find LTR candidates.
2024年 08月 05日 星期一 07:36:47 CST	Identify LTR retrotransposon candidates from scratch.
2024年 08月 05日 星期一 10:49:58 CST	Finish finding LTR candidates.
2024年 08月 05日 星期一 10:49:58 CST	Start to find SINE candidates.
2024年 08月 05日 星期一 14:56:48 CST	Finish finding SINE candidates.
2024年 08月 05日 星期一 14:56:48 CST	Start to find LINE candidates.
2024年 08月 05日 星期一 14:56:48 CST	Identify LINE retrotransposon candidates from scratch.
2024年 08月 06日 星期二 03:32:51 CST	Finish finding LINE candidates.
2024年 08月 06日 星期二 03:32:51 CST	Start to find TIR candidates.
2024年 08月 06日 星期二 03:32:51 CST	Identify TIR candidates from scratch.
Species: others
2024年 08月 06日 星期二 22:14:36 CST	Finish finding TIR candidates.
2024年 08月 06日 星期二 22:14:36 CST	Start to find Helitron candidates.
2024年 08月 06日 星期二 22:14:36 CST	Identify Helitron candidates from scratch.
2024年 08月 07日 星期三 13:04:37 CST	Finish finding Helitron candidates.
2024年 08月 07日 星期三 13:04:37 CST	Execution of EDTA_raw.pl is finished!
LINE/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
LINE/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
LINE/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
LINE/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
LINE/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
LINE/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
LINE/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
LINE/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
LINE/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
LINE/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
LINE/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
LINE/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
LINE/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
LINE/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
LINE/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
LINE/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
LINE/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
LINE/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
LINE/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
LINE/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
LINE/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
LINE/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
LINE/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
LINE/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
LINE/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
LINE/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
LINE/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
LINE/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
LINE/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
LINE/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
LINE/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
LINE/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.

**Comment by jwli-code** [comment]
Have you solved it? I had the same problem

**Comment by liangchengbo** [comment]
I changed the TE_Sequence_Ontology.txt file. I added “not found” to it. The error didn't happen again, but I'm not sure if it's correct.

**Comment by liangchengbo** [comment]
I changed the TE_Sequence_Ontology.txt. I added “LINE/NA” to it. The error didn't happen again, but I'm not sure if it's correct.

**Comment by FayeFang17** [comment]
You are right about the lack of LINE/NA previously. I just updated EDTA. You may also try if you like!

Best,
Faye
