### ISSUE TITLE
EDTA.pl 1.9版本，转换成EDTA.pl 2.2版本哪些过程可以跳过；

### ISSUE THREAD

**Issue by LengFeng00** [oushujun/EDTA#499]
老师，您好，请问我用EDTA.pl 1.9版本已经分析的结果，想转换成EDTA.pl 2.2版本哪些过程可以跳过；

**Comment by FayeFang17** [comment]
Hi LengFeng, 

you may keep the raw files, but other than that you would have to rerun. 

Best,
Faye

**Comment by LengFeng00** [comment]
Hi Faye,

Thank you for your reply! I will keep the raw files and rerun as needed.

Best,
LengFeng

**Comment by LengFeng00** [comment]
> Hi LengFeng,
> 
> you may keep the raw files, but other than that you would have to rerun.
> 
> Best, Faye

Hi Faye,

Thank you for your reply! I will keep the raw files and rerun as needed.

Best,
LengFeng
