### ISSUE TITLE
ERROR: Stage 1 library not found in chr1.fa.mod.EDTA.combine/chr1.fa.mod.LTR.TIR.Helitron.fa.stg1 at EDTA.pl line 384.

### ISSUE THREAD

**Issue by Tkastylevsky** [oushujun/EDTA#50]
Hello, 

I am trying to use EDTA in order to annotate an avian genome(as a test I do it on a single chromosome), but i keep running into an error.
I have installed it with conda, following the script you have on github.
here is the copy of what I execute in order to run your script : 

```
PATH=$PATH:/home/tkastylevsky/EDTA
cd
cd /home/tkastylevsky/FASTA_files/EDTA/gallus_gallus/chr1/
EDTA.pl -genome chr1.fa -anno 1  -force 1
```

(I tried to add the force 1 based on a solved issue on this github but it didn't help)

and this is what I get (some of it is in french, sorry, feel free to ask me if you need any translation, at first glance it seemed to me that everything was roughly understandable) :

> ########################################################
> ##### Extensive de-novo TE Annotator (EDTA) v1.7.6  ####
> ##### Shujun Ou (shujun.ou.1@gmail.com)             ####
> ########################################################
> 
> 
> 
> mercredi 29 janvier 2020, 18:08:10 (UTC+0100)	Dependency checking:
> 				All passed!
> mercredi 29 janvier 2020, 18:08:20 (UTC+0100)	Obtain raw TE libraries using various structure-based programs: 
> At least 1 parameter mandatory:
> 1) Input fasta file: --genome
> 
> 
> Obtain raw TE libraries using various structure-based programs
> 	perl EDTA_raw.pl [options]
> 		--genome	[File]	The genome FASTA
> 		--species [rice|maize|others]	Specify the species for identification of TIR candidates. Default: others
> 		--type	[ltr|tir|helitron|all]	Specify which type of raw TE candidates you want to get. Default: all
> 		--overwrite	[0|1]	If previous results are found, decide to overwrite (1, rerun) or not (0, default).
> 		--threads|-t	[int]	Number of theads to run this script. Default: 4
> 		--help|-h	Display this help info
> 
> 
> 
> 
> cat: chr1.fa.mod.LTR.intact.fa: Aucun fichier ou dossier de ce type
> cat: chr1.fa.mod.TIR.intact.fa: Aucun fichier ou dossier de ce type
> cat: chr1.fa.mod.Helitron.intact.fa: Aucun fichier ou dossier de ce type
> cat: chr1.fa.mod.LTR.intact.fa.gff3: Aucun fichier ou dossier de ce type
> cat: chr1.fa.mod.TIR.intact.fa.gff: Aucun fichier ou dossier de ce type
> cat: chr1.fa.mod.Helitron.intact.fa.gff: Aucun fichier ou dossier de ce type
> 
> 	perl bed2gff.pl EDTA.TE.combo.bed
> 
> mv: impossible d'évaluer 'chr1.fa.mod.EDTA.intact.bed.gff': Aucun fichier ou dossier de ce type
> cp: impossible d'évaluer 'chr1.fa.mod.EDTA.intact.gff': Aucun fichier ou dossier de ce type
> mercredi 29 janvier 2020, 18:08:20 (UTC+0100)	Obtain raw TE libraries finished.
> 				All intact TEs found by EDTA: 
> 					chr1.fa.mod.EDTA.intact.fa
> 					chr1.fa.mod.EDTA.intact.gff
> 
> mercredi 29 janvier 2020, 18:08:20 (UTC+0100)	Perform EDTA advcance filtering for raw TE candidates and generate the stage 1 library: 
> 
> Genome file chr1.fa.mod not exists!
> 
> Perform EDTA basic and advcanced filterings for raw TE candidates and generate the stage 1 library
> 	perl EDTA_processF.pl [options]
> 		-genome	[File]	The genome FASTA
> 		-ltr	[File]	The raw LTR library FASTA
> 		-tir	[File]	The raw TIR library FASTA
> 		-helitron	[File]	The raw Helitron library FASTA
> 		-mindiff_ltr	[float]	The minimum fold difference in richness between LTRs and contaminants (default: 1)
> 		-mindiff_tir	[float]	The minimum fold difference in richness between TIRs and contaminants (default: 1)
> 		-mindiff_hel	[float]	The minimum fold difference in richness between Helitrons and contaminants (default: 4)
> 		-repeatmasker [path]	The directory containing RepeatMasker (default: read from ENV)
> 		-blast [path]	The directory containing Blastn (default: read from ENV)
> 		-protlib [File] Protein-coding aa sequences to be removed from TE candidates. (default lib: alluniRefprexp082813 (plant))
> 					You may use uniprot_sprot database available from here:
> 					ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/taxonomic_divisions/
> 		-threads|-t	[int]	Number of theads to run this script
> 		-help|-h	Display this help info
> 
> ERROR: Stage 1 library not found in chr1.fa.mod.EDTA.combine/chr1.fa.mod.LTR.TIR.Helitron.fa.stg1 at /home/tkastylevsky/EDTA/EDTA.pl line 384.

 
I know, through other annotation methods (repeatmodeler) that there are LTR, TIR and helitrons on this chromosome. 

Thank you in advance,

**Comment by oushujun** [comment]
The usage changed a little bit. You need to use two dashes for each long
parameter. Please also update to v1.7.7. Let me know if you have the issue.

**Comment by Tkastylevsky** [comment]
Done both and it is currently running ! Looks good ! Thanks !
