### ISSUE TITLE
cannot create temporary file in '/scratch/363641.1.all.q

### ISSUE THREAD

**Issue by bijendrabio** [oushujun/EDTA#501]
Hello @oushujun @FayeFang17 , 
I am receiving following error while running EDTAv2.20 using singularity. Kindly suggest!

Identify LTR retrotransposon candidates from scratch.

sort: cannot create temporary file in '/scratch/363641.1.all.q': No such file or directory
Warning: LOC list input_genome.fasta.mod.retriever.scn.full is empty.

        Usage: perl cleanup.pl -f sample.fa [options] > sample.cln.fa 
	Options:
		-misschar	n	Define the letter representing unknown sequences; case insensitive; default: n
		-Nscreen	[0|1]	Enable (1) or disable (0) the -nc parameter; default: 1
		-nc		[int]	Ambuguous sequence len cutoff; discard the entire sequence if > this number; default: 0
		-nr		[0-1]	Ambuguous sequence percentage cutoff; discard the entire sequence if > this number; default: 1
		-minlen		[int]	Minimum sequence length filter after clean up; default: 100 (bp)
		-cleanN		[0|1]	Retain (0) or remove (1) the -misschar taget in output sequence; default: 0
		-trf		[0|1]	Enable (1) or disable (0) tandem repeat finder (trf); default: 1
		-trf_path	path	Path to the trf program
        
cp: cannot stat 'input_genome.fasta.mod.retriever.scn.adj': No such file or directory
awk: fatal: cannot open file `input_genome.fasta.mod.pass.list' for reading: No such file or directory
Warning: LOC list - is empty.

	perl rename_LTR_skim.pl target_sequence.fa LTR_retriever.defalse

Error: Error while loading sequence
Filter sequence based on TEsorter classifications. Unclassified sequences will also be output to the clean file.
	Usage: perl cleanup_misclas.pl sequence.fa.rexdb.cls.tsv
	Author: Shujun Ou (shujun.ou.1@gmail.com) 10/11/2019

**Comment by oushujun** [comment]
Hello,

The singularity version is outdated and still pending an update. Please use the github version instead and use conda to install the dependencies.

Best,
Shujun

**Comment by bijendrabio** [comment]
Thanks @oushujun
