### ISSUE TITLE
LTR not found in plant genome

### ISSUE THREAD

**Issue by LeoVincenzi** [oushujun/EDTA#502]
Dear developers, 
 I'm facing an issue (or more) annotating a plant genome. 
Launching the command 
`EDTA.pl --genome genome.fa -t 40`
At the LTR identification, I obtain the following output:

> Mon 09 Sep 2024 02:55:32 PM UTC Start to find LTR candidates.
> 
> Mon 09 Sep 2024 02:55:32 PM UTC Identify LTR retrotransposon candidates from scratch.
> 
> Invalid value for shared scalar at /home/leonardo/miniconda3/envs/EDTA/share/LTR_retriever/bin/LTR.identifier.pl line 114, <ANNO> line 6792.
> cp: cannot stat 'temp.fa.mod.retriever.scn.adj': No such file or directory
> awk: fatal: cannot open file `temp.fa.mod.pass.list' for reading: No such file or directory
> Warning: LOC list - is empty.
> 
> Error: Error while loading sequence
> Filter sequence based on TEsorter classifications. Unclassified sequences will also be output to the clean file.
>         Usage: perl cleanup_misclas.pl sequence.fa.rexdb.cls.tsv
>         Author: Shujun Ou (shujun.ou.1@gmail.com) 10/11/2019
> 
> mv: cannot stat 'temp.fa.mod.LTR.intact.fa.ori.dusted.cln.cln': No such file or directory
> mv: cannot stat 'temp.fa.mod.LTR.intact.fa.ori.dusted.cln.cln.list': No such file or directory
> cp: cannot stat 'temp.fa.mod.LTR.intact.raw.fa.anno.list': No such file or directory
> ERROR: No such file or directory at /home/leonardo/miniconda3/envs/EDTA/share/EDTA/util/output_by_list.pl line 39.
> 
>         perl filter_gff3.pl file.gff3 file.list > new.gff3
> 
> Mon 09 Sep 2024 04:01:54 PM UTC Warning: The LTR result file has 0 bp!
> 

I don't think my genome doesn't contain LTRs, since RepeatMasker also managed to identify a good portion of them, so I wonder what could be the cause. 
The output for the moment is only the folder **temp.fa.mod.EDTA.raw** and **temp.fa.mod.RM2.raw.fa**
If you can give me some hints about it, it would be great! 

Leo

**Comment by oushujun** [comment]
Known and solved issue. Please search other issues. Reinstall LTR_retriever
should work

Shujun
