### ISSUE TITLE
How to continue running make_panTElib.pl

### ISSUE THREAD

**Issue by Xuuuurj** [oushujun/EDTA#503]
Hello,
One month ago, I submitted a job to create a panTElib using the following command:perl /user/software/EDTA-1.1.0/util/make_panTElib.pl -liblist liblist.txt -threads 50.
Last week, my task was forcibly terminated because of my server shutdown.
Could I resume the process by replacing the data in liblist.txt with the .iter file generated last?

**Comment by oushujun** [comment]
This script has been retired. Please use the latest version.

Shujun

**Comment by Xuuuurj** [comment]
Hello Shujun,
Thank you so much for taking the time to answer my question. 
I will try to use the latest version. 
Wishing you all the best!
Once again, thank you!

Warm regards,
Rongjing
