### ISSUE TITLE
Invalid value for shared scalar at /public/home/kanaconda3/envs/edta/share/LTR_retriever/bin/LT

### ISSUE THREAD

**Issue by Hanjiangna** [oushujun/EDTA#507]
hello
I encountered an error when useing edta 2.30.
Invalid value for shared scalar at /public/home/anaconda3/envs/edta/share/LTR_retriever/bin/LTR.identifier.pl line 114, <ANNO> line 843.
cp: 对 'R0301.new.fa.mod.retriever.scn.adj' 调用 stat 失败: 没有那个文件或目录
awk: 致命错误：无法打开文件“R0301.new.fa.mod.pass.list”进行读取：没有那个文件或目录
Warning: LOC list - is empty.

Error: Error while loading sequence
Thanks

**Comment by oushujun** [comment]
Please check out other similar issues.

Shujun
