### ISSUE TITLE
NO  SINE,EDTA v2.2.0

### ISSUE THREAD

**Issue by Apl-cc** [oushujun/EDTA#509]
Hi Dr. Shujun,

EDTA is a very good software！
Recently, I also encountered a problem when annotating TE sequences in the IWGSCv1p1A.fa genome with EDTA. The error message is as follows: No SINE results were found! v2.2.0

Start to find SINE candidates.

cp: cannot stat 'IWGSCv1p1A.fa.mod.SINE.raw.fa': No such file or directory
Error: SINE results not found!

ERROR: Raw SINE results not found in IWGSCv1p1A.fa.mod.EDTA.raw/IWGSCv1p1A.fa.mod.SINE.raw.fa
        If you believe the program is working properly, this may be caused by the lack of SINEs in your genome.

The IWGSC genome has three subgenomes (A, B, and D). When I annotated the B genome, it worked properly, but the A and D genomes encountered the above problems, In addition, I also successfully annotated a genome using EDTA. And these files were generated in the raw/SINE folder

1359834c85e311efadb2b4055db3aef5
55a8c0b0857e11ef9caab4055db3aef5
b8f5b0b6857811efa898b4055db3a915
d0ad680c801911efb3ddb4055db3a915
HMM_out
IWGSCv1p1A.fa_0150c31885e311efadb2b4055db3aef5.mod
IWGSCv1p1A.fa_190dd9887fcf11efb3ddb4055db3a915-matches.fasta
IWGSCv1p1A.fa_190dd9887fcf11efb3ddb4055db3a915.mod
IWGSCv1p1A.fa_456360a2857e11ef9caab4055db3aef5.mod
IWGSCv1p1A.fa_a8b2e714857811efa898b4055db3a915.mod
IWGSCv1p1A.fa.mod -> ../../IWGSCv1p1A.fa.mod
Step1_extend_tsd_input_1.fa
Step1_extend_tsd_input_2.fa
Step1_extend_tsd_input.fa
Step2_extend_blast_input.fa
Step2_extend_blast_input_rename.fa
Step2_tsd_output.fa
Step2_tsd.txt
Step3_blast_output.paf

Any good suggestions to solve this problem?

pengliang

**Comment by oushujun** [comment]
Please check the SINE folder in the A D subgenome. It may be too large for
AnnoSINE to handle.

Shujun

**Comment by Apl-cc** [comment]
<img width="785" alt="Snipaste_2024-10-17_14-31-50" src="https://github.com/user-attachments/assets/bed419f0-6a44-4626-a10e-44e11cbefdae">
Maybe the file is too large to be processed, as you said. How to solve this problem?

pengliang

**Comment by ifoo1213** [comment]
> <img alt="Snipaste_2024-10-17_14-31-50" width="785" src="https://private-user-images.githubusercontent.com/181370863/377339705-bed419f0-6a44-4626-a10e-44e11cbefdae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMzA5MzcsIm5iZiI6MTczMDEzMDYzNywicGF0aCI6Ii8xODEzNzA4NjMvMzc3MzM5NzA1LWJlZDQxOWYwLTZhNDQtNDYyNi1hMTBlLTQ0ZTExY2JlZmRhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOFQxNTUwMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mY2YyZTBjODYxNTA4YjY1Y2VlMGNlMTYxYTA2NDY1MjliNjRlNmE5MDY3ODlkNDA5ZDUyNzkwMDYzYzlkMDYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cNaozdzt2Mx5CriRX8OMZDMUc9zg7NahftcF2CEuDYs"> Maybe the file is too large to be processed, as you said. How to solve this problem?
> pengliang

Hi, Pengliang, have you resolved this issue, I have the same issue as yours. not sure how to increase the memory here? set the memory in the command?

**Comment by oushujun** [comment]
@ifoo1213 you need to use a server with larger memory. You don't need to set anything in EDTA, it will consume necessary memory it requires, but if your server does not have sufficient memory, it will exit with OOM (out-of-memory) error.

**Comment by Apl-cc** [comment]
@oushujun When encountering such a situation, add --force 1 after the command and the task can be completed. Does adding this parameter have any effect on the result?

**Comment by oushujun** [comment]
Lacking SINE/LINE won’t interrupt the run. Please update your code to the
latest.

Shujun

**Comment by jwli-code** [comment]
Why is the proportion of SINE annotations much lower in the new version of EDTA compared to the previous version

**Comment by jwli-code** [comment]
`tRNA/NA not found in the TE_SO database, it will not be used to rename sequences in the final annotation.`

**Comment by oushujun** [comment]
Please test again with 2.2.2.
