### ISSUE TITLE
"long_terminal_repeat" vs "LTR_retrotransposon"

### ISSUE THREAD

**Issue by G-Thomson** [oushujun/EDTA#511]
In EDTA annotations of plant genomes I see two families of elements "long_terminal_repeat" vs "LTR_retrotransposon", amongst the others.

Are these the same? Just labelled differently by different components of the pipeline?

**Comment by oushujun** [comment]
Hi, "long_terminal_repeat" is a component of "LTR_retrotransposon". Please check out the wiki. Thanks!

Shujun
