### ISSUE TITLE
Request for Software Recommendations for Protein Annotation

### ISSUE THREAD

**Issue by Flooooooooooooower** [oushujun/EDTA#513]
Hello, I apologize for the disturbance. Thank you for creating such excellent software. After obtaining annotated DNA transposons using EDTA, I would like to translate them into proteins for functional analysis. However, their promoters can be P, M, F, or O. Could you please recommend any software that can annotate these transposons as proteins?

**Comment by oushujun** [comment]
Try TEsorter. - Shujun
