### ISSUE TITLE
EDTA 2.2 stalling early in LTR discovery

### ISSUE THREAD

**Issue by Chriswinefield** [oushujun/EDTA#519]
Hi Shujun,

I am having some considerable trouble getting EDTA2.2 to run, with it stalling about 2 hrs into the LTR discovery phase of the pipeline. There appears to be a I/O issue with the programme waiting for a file or response that is not happening. I am currently running the pipeline on the NeSI HPC using SLURM. Both the team at NeSi and I cant find what EDTA is waiting for. Initially I was trying a module prepared by the team at NeSI but have moved to installing a CONDA instance on my account. The genome I am working with is an improved version of an earlier genome that worked fine so there shouldn't be any spectific issues with the pipeline finishing in ~ 4days. 

Sometime ago I had a similar problem with a much earlier version of EDTA and this was resolved by launching EDTA from my account space. but it appears this is not a fix I can use. Could you suggest what might be causing a stall? As the LTR-finder has stalled at the finder stage there are no errors to help.

Thanks for the assistance with this.

Kind Regards
Chris

**Comment by oushujun** [comment]
Hi Chris,

Did you test it with a small data? How long is the longest sequence in your
genome?

Thanks,
Shujun

**Comment by Chriswinefield** [comment]
Hi Shujun,

I have launched the test dataset and am waiting for resources for this to run on the cluster.

There are 19 chromosomes (T-to T) in the reference fasta. Longest sequence/contig is 185,284,850 bp. I have previously managed to get EDTA to work on an earlier 19 chromosome assembly of this plant successfully.

Regards
Chris


Chris Winefield
Associate Professor in Plant Genomics and Molecular Biology
Associate Investigator, ARC Centre of Excellence in Plant Success in Nature & Agriculture, Brisbane, Australia
 Director, Lincoln Genomics  - an MGI enabled Next Generation Sequencing Facility
––––––––––––––––––––––––––––––––––
Wine, Food and Molecular Biosciences Department
RFH, room 062
Engineering Drive
P O Box 85084, Lincoln University
Lincoln 7647, Christchurch, New Zealand
p +64 3 4230630 | m +64 021 0238 4476
e ***@***.******@***.***> | w www.lincoln.ac.nz<http://www.lincoln.ac.nz/>
––––––––––––––––––––––––––––––––––
Lincoln University
Te Whare Wānaka o Aoraki
––––––––––––––––––––––––––––––––––
[cid:be4203a1-c4f8-4d38-9407-2e7f35726f1f]      [A logo with a person and leaves]
The NZ Plant <http://www.mobilekiwi.org/>       Lincoln Genomics<https://app.smartsheet.com/b/form/97efbf730e0f4974b67875a7b47f9e63>
Transposon <http://www.mobilekiwi.org/>
Team<http://www.mobilekiwi.org/>
________________________________

**Comment by oushujun** [comment]
That's strange. There were only small changes in LTR_retriever. Did you try annotating the genome on a different server? When I encounter such issues, it was usually the server being too busy.

Shujun

**Comment by Chriswinefield** [comment]
Hi Shujun,

Yes we think that there is a server issue, so at the moment the node secured by the SLUM system will use a separate disk allocation where EDTA is initiated from (my Scratch space). WE think that this may be generating the bottleneck WRT file I/O issues. What we would like to try is to initiate the run on a node and have EDTA work with a dedicated attached SSD. To do this we need to be able to direct the outputs and intermediate fles to this drive rather than where the EDTA.pl file resides. In the past this has been part of the problem.  So Dini asked if we can direct the output  from EDTA to this attached drive - there doesn't appear to be a specific command to direct the output. I guess the issue is that we need to launch the pipeline via SLRUM so we/I dont have complete authority over how the run is set up in terms of attached SSDs and specific nodes. So I dont think I can pop the raw data and and the EDTA instance in the drive attached to the node that SLURM would choose.

An ability to direct the output od EDTA would be a good starting point for us.

One other thing - I used the --debug command and only the LTR temp files were kept - there was no obvious tmp file deposition for the other TE folders (SINE, LINE, Helitron, TIR) is the debug only for the LTR pipeline or is there another location that the tmp file collection for the other TE classes that I have missed.

Thanks
Chris

Chris Winefield
Associate Professor in Plant Genomics and Molecular Biology
Associate Investigator, ARC Centre of Excellence in Plant Success in Nature & Agriculture, Brisbane, Australia
 Director, Lincoln Genomics  - an MGI enabled Next Generation Sequencing Facility
––––––––––––––––––––––––––––––––––
Wine, Food and Molecular Biosciences Department
RFH, room 062
Engineering Drive
P O Box 85084, Lincoln University
Lincoln 7647, Christchurch, New Zealand
p +64 3 4230630 | m +64 021 0238 4476
e ***@***.******@***.***> | w www.lincoln.ac.nz<http://www.lincoln.ac.nz/>
––––––––––––––––––––––––––––––––––
Lincoln University
Te Whare Wānaka o Aoraki
––––––––––––––––––––––––––––––––––
[cid:9b38e659-b64c-4031-a6d6-86202ecf0341]      [A logo with a person and leaves]
The NZ Plant <http://www.mobilekiwi.org/>       Lincoln Genomics<https://app.smartsheet.com/b/form/97efbf730e0f4974b67875a7b47f9e63>
Transposon <http://www.mobilekiwi.org/>
Team<http://www.mobilekiwi.org/>
________________________________

**Comment by oushujun** [comment]
Hi Chris,

You are correct, EDTA does not have the functionality to redirect outputs other than the genome folder. You can first copy the genome into your local SLURM machine and run EDTA on that local storage. `$SLURM_TMPDIR` is the path in SLURM representing the local storage. After finishing the job, rsync/cp everything from `$SLURM_TMPDIR` back to your Scratch storage. Is it possible on your cluster?

Shujun

**Comment by oushujun** [comment]
The --debug is only for LTR_retriever

**Comment by Chriswinefield** [comment]
Thanks Shujun,

I think that may be possible within the SLURM script I set up to launch the Job. There is clearly a glitch with the system we have at the moment that is causing I/O slow downs. The single chromosome seemed to work well so there isn't anything specific with the pipeline causing issues.

Thanks again for your support - it is a great pipeline and invaluable to my work 🙂

Regards
Chris


Chris Winefield
Associate Professor in Plant Genomics and Molecular Biology
Associate Investigator, ARC Centre of Excellence in Plant Success in Nature & Agriculture, Brisbane, Australia
 Director, Lincoln Genomics  - an MGI enabled Next Generation Sequencing Facility
––––––––––––––––––––––––––––––––––
Wine, Food and Molecular Biosciences Department
RFH, room 062
Engineering Drive
P O Box 85084, Lincoln University
Lincoln 7647, Christchurch, New Zealand
p +64 3 4230630 | m +64 021 0238 4476
e ***@***.******@***.***> | w www.lincoln.ac.nz<http://www.lincoln.ac.nz/>
––––––––––––––––––––––––––––––––––
Lincoln University
Te Whare Wānaka o Aoraki
––––––––––––––––––––––––––––––––––
[cid:f987be16-7e99-4323-b6a8-09d54bc60578]      [A logo with a person and leaves]
The NZ Plant <http://www.mobilekiwi.org/>       Lincoln Genomics<https://app.smartsheet.com/b/form/97efbf730e0f4974b67875a7b47f9e63>
Transposon <http://www.mobilekiwi.org/>
Team<http://www.mobilekiwi.org/>
________________________________
