### ISSUE TITLE
EDTA222-docker-image-do not find LTR_FINDER_parallel

### ISSUE THREAD

**Issue by Wan9299** [oushujun/EDTA#521]
$ /usr/bin/time -v singularity exec ./EDTA222.sif EDTA.pl \
> --genome NbT2T \
> --threads 12 \
> --overwrite 0 \
> --anno 1 \
> --sensitive 1 \
> --evaluate 1 \
> --cds Nb-cds-NCBI.fa

#########################################################
#########################################################

Parameters: --genome NbT2T --threads 12 --overwrite 0  --anno 1 --sensitive 1 --evaluate 1 --cds Nb-cds-NCBI.fa

Wed Dec  4 00:57:58 CST 2024	Dependency checking:
	All passed!

	A CDS file Nb-cds-NCBI.fa is provided via --cds. Please make sure this is the DNA sequence of coding regions only.

Wed Dec  4 00:58:12 CST 2024	Obtain raw TE libraries using various structure-based programs: 
Wed Dec  4 00:58:12 CST 2024	EDTA_raw: Check dependencies, prepare working directories.

Wed Dec  4 00:58:26 CST 2024	Start to find LTR candidates.

Wed Dec  4 00:58:26 CST 2024	Identify LTR retrotransposon candidates from scratch.

Can't open perl script "/usr/local/share/EDTA/bin/LTR_FINDER_parallel/LTR_FINDER_parallel": No such file or directory
cat: NbT2T.mod.finder.combine.scn: No such file or directory
Error: cd-hit-est is not found in the CDHIT path !
awk: fatal: cannot open file `NbT2T.mod.pass.list' for reading: No such file or directory
Warning: LOC list - is empty.

	perl rename_LTR_skim.pl target_sequence.fa LTR_retriever.defalse

Error: Error while loading sequence
Filter sequence based on TEsorter classifications. Unclassified sequences will also be output to the clean file.
	Usage: perl cleanup_misclas.pl sequence.fa.rexdb.cls.tsv
	Author: Shujun Ou (shujun.ou.1@gmail.com) 10/11/2019
	
mv: cannot stat 'NbT2T.mod.LTR.intact.fa.ori.dusted.cln.cln': No such file or directory
mv: cannot stat 'NbT2T.mod.LTR.intact.fa.ori.dusted.cln.cln.list': No such file or directory
cp: cannot stat 'NbT2T.mod.LTR.intact.raw.fa.anno.list': No such file or directory
ERROR: No such file or directory at /usr/local/share/EDTA/bin/output_by_list.pl line 39.

	perl filter_gff3.pl file.gff3 file.list > new.gff3

Wed Dec  4 01:10:24 CST 2024	Warning: The LTR result file has 0 bp!

Wed Dec  4 01:10:24 CST 2024	Start to find SINE candidates.

Wed Dec  4 04:06:21 CST 2024	Finish finding SINE candidates.

Wed Dec  4 04:06:21 CST 2024	Start to find LINE candidates.

Wed Dec  4 04:06:21 CST 2024	Identify LINE retrotransposon candidates from scratch.

^CCommand terminated by signal 2

	User time (seconds): 6.94
	System time (seconds): 6.27
	Percent of CPU this job got: 0%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 11:05:24
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 554204
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 409
	Minor (reclaiming a frame) page faults: 286175
	Voluntary context switches: 5742
	Involuntary context switches: 22434
	Swaps: 0
	File system inputs: 5860558
	File system outputs: 5565448
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0

**Comment by ron-alonday** [comment]
I also have the same issue in conda environment. 

![Screenshot 2024-12-12 at 3 17 16 PM](https://github.com/user-attachments/assets/140a0286-f56b-4456-9ce2-ba15ae3cbd3d)

**Comment by oushujun** [comment]
Fixed in #526.
