### ISSUE TITLE
edta-2.2.2 is incompatible with LTR_FINDER_parallel in conda/mamba install

### ISSUE THREAD

**Issue by drk0311** [oushujun/EDTA#526]
I installed EDTA-2.2.2 via mamba and encountered an error message saying LTR_FINDER_parallel cannot be installed because of incompatibility with edta-2.2.2.

The error message was as below.
```
ClobberError: This transaction has incompatible packages due to a shared path.
   packages: bioconda/noarch::ltr_finder_parallel-1.1-hdfd78af_1, bioconda/noarch::edta-2.2.2-hdfd78af_0
   path: 'bin/LTR_FINDER_parallel
```
 
After installation is finished, there is a binary file of LTR_FINDER_parallel but nothing in ~/miniforge3/envs/EDTA/share/EDTA/bin/. 
So when I try to execute LTR_FINDER_parallel, it says

`Can't open perl script "/home/naitok785/miniforge3/envs/test/share/EDTA/bin/LTR_FINDER_parallel/LTR_FINDER_parallel": No such file or directory`

I managed to have EDTA work by removing the LTR_FINDER_parallel binary form the ~/miniforge3/envs/EDTA/bin,  git cloned LTR_FINDER_parallel myself and soft-linked the cloned binary and bin directory to the  ~/miniforge3/envs/EDTA/bin, as like
```
cd ~/miniforge3/envs/EDTA/bin
ln -s ~/LTR_FINDER_parallel/LTR_FINDER_parallel .
ln -s ~/LTR_FINDER_paralle/bin .
```

Thank you anyway, I have been a long-time user of this fantastic pipeline!

**Comment by oushujun** [comment]
There were two bugs in here, we have just updated the recipe to fix them both. Please try again. Thanks!

Shujun
