### ISSUE TITLE
TE not found in the TE_SO database 

### ISSUE THREAD

**Issue by C-YONG** [oushujun/EDTA#529]
There are no errors  in my log, but towards the end, numerous entries like SINE/tRNA-Mermaid and DNA/MULE-MuDR? are reported as not found in the TE_SO database and will therefore be excluded from renaming sequences in the final annotation. I updated the TE_Sequence_Ontology.txt to include "SINE/tRNA-Mermaid" and "DNA/MULE-MuDR?". I want to ask if this approach is correct. Will it cause any subsequent issues?

Sun Dec 22 01:51:17 PM CST 2024	Combine the high-quality TE library fugu.fasta with the EDTA library:

SINE/tRNA-Mermaid not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
SINE/tRNA-Mermaid not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
SINE/tRNA-Mermaid not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
SINE/tRNA-Mermaid not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
SINE/tRNA-Mermaid not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
SINE/tRNA-Mermaid not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
SINE/tRNA-Mermaid not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
SINE/tRNA-Mermaid not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
DNA/MULE-MuDR? not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
DNA/MULE-MuDR? not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
SINE/tRNA-Mermaid not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
DNA/MULE-MuDR? not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
SINE/tRNA-Mermaid not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
SINE/tRNA-Mermaid not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
SINE/tRNA-Mermaid not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
SINE/tRNA-Mermaid not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
SINE/tRNA-Mermaid not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
SINE/tRNA-Mermaid not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
SINE/tRNA-Mermaid not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
SINE/tRNA-Mermaid not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
SINE/tRNA-Mermaid not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
SINE/tRNA-Mermaid not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
SINE/tRNA-Mermaid not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
SINE/tRNA-Mermaid not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
SINE/tRNA-Mermaid not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
SINE/tRNA-Mermaid not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
SINE/tRNA-Mermaid not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
SINE/tRNA-Mermaid not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
SINE/tRNA-Mermaid not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
SINE/tRNA-Mermaid not found in the TE_SO database, it will not be used to rename sequences in the final annotation.
Sun Dec 22 01:51:42 PM CST 2024	EDTA final stage finished! You may check out:

**Comment by C-YONG** [comment]
Thank you for your contribution to software development. Why does the generated GFF file contain "###"?

Thank you for your contribution to software development.
##gff-version 3
##date Sun Dec 22 01:51:42 PM CST 2024
##This file contains all repeats annotated by EDTA v2.2.2 in the split format (non-overlapping). Repeats can be broken into pieces by nested insertions.
##This file follows the ENSEMBL standard: https://useast.ensembl.org/info/website/upload/gff3.html
##Column 3: Sequence Ontology of repeat features. Please refer to the SO database for more details: http://www.sequenceontology.org/. In cases where the SO database does not have the repeat feature, tentative SO names are used, with a full list included in EDTA/bin/TE_Sequence_Ontology.txt (Enhancement notes), and the sequence_ontology in Column 9 uses the closest parent SO.
##Column 7: The Smith-Waterman score generated by RepeatMasker, only available for homology entries.
##Column 9: 
##	ID: unique ID for this feature in the genome.
##	classification: Same as Column 3 but formatted following the RepeatMasker naming convention.
##	sequence_ontology: Sequence Ontology ID of the feature.
##	identity: Sequence identity (0-1) between the library sequence and the target region.
##	ltr_identity: Sequence identity (0-1) between the left and right LTR regions for structurally annotated LTR elements.
##	Name: Repeat family name. Some may be shown as coordinates, which are single-copy and structrually identified elements that are not included in the repeat library.
##	method: Indicate if this entry is produced by structural annotation or homology annotation.
##	motif/TSD/TIR: structural features of structurally annotated LTR and TIR elements.
##For more details about this file, please refer to the EDTA wiki: https://github.com/oushujun/EDTA/wiki/Making-sense-of-EDTA-usage-and-outputs---Q&A
##seqid source sequence_ontology start end score strand phase attributes
chr1	EDTA	Penelope_retrotransposon	991	5250	648	+	.	ID=TE_annot_0;Name=TE_00001326;classification=LINE/Penelope;sequence_ontology=SO:0002290;identity=0.865;method=homology
###
chr1	EDTA	hAT_TIR_transposon	6141	6713	736	-	.	ID=TE_annot_1;Name=TE_00000265;classification=DNA/DTA;sequence_ontology=SO:0002279;identity=0.796;method=homology
###
chr1	EDTA	Tc1_Mariner_TIR_transposon	15074	15520	3986	-	.	ID=TE_annot_2;Name=TE_00000672;classification=DNA/DTT;sequence_ontology=SO:0002278;identity=0.995;method=homology
###
chr1	EDTA	Tc1_Mariner_TIR_transposon	15566	16115	4895	-	.	ID=TE_annot_3;Name=TE_00000672;classification=DNA/DTT;sequence_ontology=SO:0002278;identity=1;method=homology
###
chr1	EDTA	Tc1_Mariner_TIR_transposon	16169	16275	959	-	.	ID=TE_annot_4;Name=TE_00000672;classification=DNA/DTT;sequence_ontology=SO:0002278;identity=1;method=homology
###
chr1	EDTA	Tc1_Mariner_TIR_transposon	16322	16823	2715	-	.	ID=TE_annot_5;Name=TE_00000672;classification=DNA/DTT;sequence_ontology=SO:0002278;identity=0.992;method=homology
###
chr1	EDTA	Tc1_Mariner_TIR_transposon	16869	16991	1063	-	.	ID=TE_annot_6;Name=TE_00000672;classification=DNA/DTT;sequence_ontology=SO:0002278;identity=1;method=homology

**Comment by C-YONG** [comment]
It can be seen that there is a difference between these two tables. The final table generated by EDTA shows 0% for DNA_transposon, while RepeatMasker shows 4.1%. Could you help identify what I might have done wrong?
![image](https://github.com/user-attachments/assets/547e52b4-62a4-4636-8e85-5e01b102c593)
![image](https://github.com/user-attachments/assets/28e35ca1-625e-428f-96b8-5b95646eb882)

**Comment by oushujun** [comment]
Yes, you need to update TE_Sequence_Ontology.txt to include these elements that are new to the document. The `###` lines separate each structurally intact TEs to better follow the GFF3 standard. You may use supply the RepeatMasker library to EDTA to enhance it's performance in detecting known TEs.

Thanks!
Shujun

**Comment by C-YONG** [comment]
In the EDTA pipeline, we added the parameter anno -1, which caused it to run RepeatMasker and generate the results mentioned above. However, during subsequent steps, the software likely performed some integration or filtering, which resulted in the EDTA sum file. This file appears to differ significantly from the sum file generated by RepeatMasker within EDTA. What could be the reason for this? While running EDTA, we already used the --curatedlib option to include LINEs, SINEs, and TEs from the model species library.

**Comment by oushujun** [comment]
After homology search, EDTA will combine it with structurally intact elements, which may mask some of the homology-searched TE fragments. There is an increase of helitrons likely due to this. You may remove intact Helitrons in this file `$genome.EDTA.final/$genome.EDTA.intact.gff3` to reduce the false positive introduced by the less reliable helitrons.

Shujun

**Comment by oushujun** [comment]
I have added these new aliases to the TE_SO database, which will be reflected in the next update. Thank you for your contribution!

Shujun
