### ISSUE TITLE
Cannot install mdust

### ISSUE THREAD

**Issue by mhrobert** [oushujun/EDTA#59]
Hi, 

Thanks for this pipeline! I don't know if you can help with this issue, but I'm difficulty installing mdust using conda.

The error I receive is below:

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - mdust

Current channels:

  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/biocore/osx-64
  - https://conda.anaconda.org/biocore/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/r/osx-64
  - https://conda.anaconda.org/r/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/plotly/osx-64
  - https://conda.anaconda.org/plotly/noarch
  - https://conda.anaconda.org/numpy/osx-64
  - https://conda.anaconda.org/numpy/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

But, I think mdust should available through bioconda? Just wondering if you have a work around for this issue. Thanks!

**Comment by oushujun** [comment]
It appears that `mdust` is not available for OSX. See: https://anaconda.org/bioconda/mdust

You may want to switch to a Linux platform or use a linux virtual machine.

**Comment by Juke34** [comment]
If you downgrade repeatmodeler to the previous version it should be fine. Can you give a try?

**Comment by oushujun** [comment]
EDTA also uses mdust to identify simple repeats.

**Comment by mhrobert** [comment]
Thanks for your feedback! Actually, I switched to the docker container and it seems to be running.

**Comment by oushujun** [comment]
That's good to know :)
