### ISSUE TITLE
GRF error: Input genome sequence size is short. Can't perform detection. Segmentation fault

### ISSUE THREAD

**Issue by aderzelle** [oushujun/EDTA#6]
Hello,
I have this error, however the pipeline is still running. Is it a benign warning? 
I indeed have some very short sequences in my fasta, however I also have scaffolds of several Mb.  But I don't know on which scaffolds it failed. I think that would be helpful to know that? 

And what is the minimal length of a sequence? 

thank you

**Comment by oushujun** [comment]
Hi,

This is the error of GRF. I forgot what is the minimum length required by GRF, you may try different lengths of sequences with:

`./EDTA/bin/GenericRepeatFinder/bin/grf-main -i sequence.fa -o test -c 1 -t 10 -p 20`

You may kill the current process and resume when you filter out short sequences in your genome. Please let me know the minimum length so that others can benefit from your experience. Thanks!

Best,
Shujun

**Comment by aderzelle** [comment]
Strangely when I run your command, with my original genome file without any filtering out of short sequences, GRF runs without any error and returns a candidates.fasta that containes candidates MITE.

**Comment by aderzelle** [comment]
I kindly bump up the issue, since it's not resolved. It doesn't make sense to me why GRF complains in the pipeline but not when launched as standalone. Any idea?

**Comment by oushujun** [comment]
Sorry for the late reply. I experimented about this issue and found the
solution. The minimum sequence length is 5,500 bp, so please filter out
short sequence and run it again. The automated filter version will be
updated in the next version.

**Comment by aderzelle** [comment]
thank you, another error, I don't know if you prefer I make another thread
`TR_annotation/EDTA/bin/TIR-Learner1.19/TIR-Learner.sh: 97: [: others: unexpected operator`
It doesn't seem to prevent EDTA to run though, it might be benign.

**Comment by oushujun** [comment]
Someone reported this error to me too. Can you reinstall EDTA and try
again? Otherwise, specifying -species others should solve the problem.

Best,
Shujun

**Comment by aderzelle** [comment]
I am using -species others
```
./EDTA/EDTA.pl -genome Avaga.Masurca.Graal.min5500.fa -species others -step all -t 40 

########################################################
##### Extensive de-novo TE Annotator (EDTA) v1.3    ####
##### Shujun Ou (shujun.ou.1@gmail.com)             ####
########################################################



Fr Aug  9 15:55:38 CEST 2019    Dependency checking:
                All passed!
Fr Aug  9 15:55:49 CEST 2019    Obtain raw TE libraries using various structure-based programs: 
/media/urbe/MyBDrive/Alessandro/TR_annotation/EDTA/bin/TIR-Learner1.19/TIR-Learner.sh: 97: [: others: unexpected operator
/media/urbe/MyBDrive/Alessandro/TR_annotation/EDTA/bin/TIR-Learner1.19/TIR-Learner.sh: 97: [: others: unexpected operator
```
What kind of output should I expect from the pipeline? Previous runs outputted several fasta files, is there any kind of "log" or "summary.txt" or gff3 that should be in the output?

**Comment by oushujun** [comment]
Hello,

Sorry for the delay response. The only result you should expect is a file ends with `.EDTA.TElib.fa` in your work folder. This is a `RepeatMasker` recognizable TE library for whole-genome TE annotation. Please also check the program status output for any errors.

Best,
Shujun
