### ISSUE TITLE
unknown LTRs are too much in wheat - better classification  superfamily and family level

### ISSUE THREAD

**Issue by bioteksampath** [oushujun/EDTA#65]
Hi oushujun,

It was good to meet you at the PAG2020.
I have a couple of things to ask,

1. Do you suggest any way to improve the superfamily classification? when I run EDTA on wheat v1.0 chromosome 5A,5B and 5D, I found that unknow LTRs are >18% (expected to be < 4% based https://genomebiology.biomedcentral.com/articles/10.1186/s13059-018-1479-0/tables/1).
so, do you have any suggestions to improve the super family-level classification and to reduce the unknowns? do you thing merging TE library from different plant species should be helpful?

2. Do you also have any tools/suggestions on classify superfamily into family level?

Thanks a lot for this interesting tool, it makes life a lot easier.

Thanks
sam

**Comment by zhangleigloria** [comment]
Hello, has your problem been solved? My result unknown LTRs accounts for 7%. Thank you very much!

**Comment by oushujun** [comment]
Hi Sam,

Sorry for the delay response. It was great to meet you over PAG2020.

I checked my maize annotation and the unknown LTR rate is 11%. It could be higher or lower in other species but if you are using EDTA > v1.7.0 you should have the same latest classification scheme. For further classifications (i.e., family-level) you may use [TEsorter](https://github.com/zhangrengang/TEsorter) which is very fast and accurate.

Merging TE libraries from different species is a yes-and-no thing. Yes it's helpful if species are close (divergence < 1MY) and you want a unified naming scheme for the pan-genome annotation. No if they are too divergent and you want to use this scheme to identify more TEs - more likely the extra annotations are false positives and need to proceed with more stringent filterings.

Let me know if you have further questions.

Best,
Shujun
