### ISSUE TITLE
Does the *EDTA.TEanno.gff file contain both intact and fragmented TEs?

### ISSUE THREAD

**Issue by aderzelle** [oushujun/EDTA#67]
Hello, does the file
shasta_final.fa.mod.EDTA.TEanno.gff

contains annotation of only the full canonical copies or are the fragments also included? 

thank you!

**Comment by oushujun** [comment]
So this file contains both structurally intact and fragmented annotation.
The entries labeled structural means it’s structural annotation, the one
that named homology means it’s fragmented.

Shujun
