### ISSUE TITLE
EDTA fatal error

### ISSUE THREAD

**Issue by sajjadasaf** [oushujun/EDTA#68]
Hello oushujun,
I have run EDTA on one fungi genome with the following command
perl EDTA.pl --genome reference.fna --sensitive 1 --anno 1 --evaluate 1 --species others --step all
However, unable to get results and it shows the following error 

awk: fatal: cannot open file `reference.fna.mod.pass.list' for reading (No such file or directory)
Warning: LOC list - is empty.

Error: Error while loading sequencecp: cannot stat 'reference.fna.mod.LTRlib.fa': No such file or directory
cp: cannot stat 'reference.fna.mod.LTRlib.fa': No such file or directory
Error: LTR results not found!

ERROR: Raw LTR results not found in reference.fna.mod.EDTA.raw/reference.fna.mod.LTR.raw.fa at EDTA.pl line 367.

please help me

**Comment by oushujun** [comment]
It seems like no LTR was found in your genome, does this make sense? If so,
you may need to use the —force 1 parameter to bypass the missing of LTRs.

**Comment by sajjadasaf** [comment]
Thank you for your help
