### ISSUE TITLE
TEsorter is not exist in the TEsorter path !

### ISSUE THREAD

**Issue by majie5976** [oushujun/EDTA#69]
Dear, 
      i am facing this problem while running EDTA, Could you help me to solve this issue. Thank you so much.
![TEsorter](https://user-images.githubusercontent.com/54849045/76289913-2d951800-62e5-11ea-9555-ed8aec917c37.png)

**Comment by oushujun** [comment]
Hi, please update and reinstall EDTA, thanks!

**Comment by majie5976** [comment]
Thanks Dear,
                  its working now
