### ISSUE TITLE
Cannot install repeatmodeler or repeatmasker

### ISSUE THREAD

**Issue by hw449** [oushujun/EDTA#7]
Sorry this question may be irrelevant to EDTA. I am having problems installing repeatmodeler or repeatmasker. Could you please help me with this? Thanks. When I run "conda install -y -c bioconda repeatmodeler", the error messages look like this:

Collecting package metadata (current_repodata.json): done
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Initial quick solve with frozen env failed.  Unfreezing env and trying again.
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed
Initial quick solve with frozen env failed.  Unfreezing env and trying again.
Solving environment: failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Package tk conflicts for:
python=3.6 -> tk[version='8.6.*|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0']
Package libstdcxx-ng conflicts for:
python=3.6 -> libstdcxx-ng[version='>=7.2.0|>=7.3.0']
Package repeatscout conflicts for:
repeatmodeler -> repeatscout
Package perl-threaded conflicts for:
repeatmodeler -> perl-threaded
Package readline conflicts for:
python=3.6 -> readline[version='7.*|>=7.0,<8.0a0']
Package perl conflicts for:
repeatmodeler -> perl[version='5.22.0.*|>=5.26.2,<5.27.0a0']
Package pip conflicts for:
python=3.6 -> pip
Package recon conflicts for:
repeatmodeler -> recon
Package libffi conflicts for:
python=3.6 -> libffi[version='3.2.*|>=3.2.1,<4.0a0']
Package ncurses conflicts for:
python=3.6 -> ncurses[version='6.0.*|>=6.0,<7.0a0|>=6.1,<7.0a0']
Package zlib conflicts for:
python=3.6 -> zlib[version='>=1.2.11,<1.3.0a0']
Package xz conflicts for:
python=3.6 -> xz[version='>=5.2.3,<6.0a0|>=5.2.4,<6.0a0']
Package libgcc-ng conflicts for:
python=3.6 -> libgcc-ng[version='>=7.2.0|>=7.3.0']
Package trf conflicts for:
repeatmodeler -> trf
Package openssl conflicts for:
python=3.6 -> openssl[version='1.0.*|1.0.*,>=1.0.2l,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2n,<1.0.3a|>=1.0.2o,<1.0.3a|
>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1c,<1.1.2a']
Package repeatmasker conflicts for:
repeatmodeler -> repeatmasker
Package perl-text-soundex conflicts for:
repeatmodeler -> perl-text-soundex
Package rmblast conflicts for:
repeatmodeler -> rmblast
Package sqlite conflicts for:
python=3.6 -> sqlite[version='>=3.20.1,<4.0a0|>=3.22.0,<4.0a0|>=3.23.1,<4.0a0|>=3.24.0,<4.0a0|>=3.25.2,<4.0a0|>
=3.26.0,<4.0a0|>=3.29.0,<4.0a0']

**Comment by oushujun** [comment]
Hello,

I didn't see this kind of errors on RepeatMasker and RepeatModeler installations. You may update or reinstall conda and create a brand new env to install EDTA.

Please let me know if you solve this.

Best,
Shujun

**Comment by Neato-Nick** [comment]
I got this error as well. Solved by:

1. removing the env and creating a new one
2. installing python while creating the environment
3. adding conda-forge, biocore, and bioconda[ to my channels](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-channels.html) and installing these packages in the same line. Conda is great at chunking through dependencies, and handing over all the packages at once worked for me. Adding these sources to the list of channels will allow conda to search those databases for any package dependencies and install them.

``` 
conda create -n EDTA python=3.6
conda activate EDTA
conda install -y -c anaconda biopython pandas glob2 scikit-learn=0.19.0
conda config --add channels conda-forge
conda config --add channels biocore
conda config --add channels bioconda
conda install -y -c cyclus java-jdk
conda install -y blast-legacy perl perl-text-soundex multiprocess regex tensorflow=1.14.0 keras=2.2.4 cd-hit repeatmodeler muscle mdust repeatmasker
git clone https://github.com/oushujun/EDTA
./EDTA/EDTA.pl
