### ISSUE TITLE
cds option

### ISSUE THREAD

**Issue by ptranvan** [oushujun/EDTA#70]
Hi,

For:

> Coding sequence of the species or closely related species [FASTA]. This file helps to purge gene sequences in the TE library.

Do you need the sequences in DNA or amino acid ?

**Comment by oushujun** [comment]
DNA sequences, remember to remove introns and UTRs, thanks!

Shujun

**Comment by oliviamr** [comment]
Hi both, 

I have a quick question about this: do you mean all the CDS from genes that are not gag, tat, rh etc related to TE autonomy?

Thank you, 
O
