### ISSUE TITLE
Strange bug with TIR-Learner, conda, and perhaps my environment

### ISSUE THREAD

**Issue by philippbayer** [oushujun/EDTA#74]
I found a weird problem in the TIR learner part of EDTA. It used to work, but it stopped working with recent installs?

I made a clean conda environment and installed the EDTA conda package as described in the README.

Running the TIR step like this:

<pre>
conda activate EDTA
EDTA_raw.pl --threads 28 --type tir --genome ../P_australis_genome_bigger1kbp.fasta > TIR_out 2> TIR_err
</pre>

results in a weird error that pre.py and all the other Python scripts from TIR-Learner2.4 cannot find biopython and crash:

<pre>
Species: others
Traceback (most recent call last):
  File "/group/pawsey0149/pbayer/anaconda3/envs/EDTA/share/EDTA/bin/TIR-Learner2.4/pre.py", line 1, in <module>
    from Bio import SeqIO
ModuleNotFoundError: No module named 'Bio'
Traceback (most recent call last):
  File "/group/pawsey0149/pbayer/anaconda3/envs/EDTA/share/EDTA/bin/TIR-Learner2.4/Module2/RunGRF.py", line 1, in <module>
    from Bio import SeqIO
ModuleNotFoundError: No module named 'Bio'
...
</pre>

If I run these scripts manually within the conda environment everything's fine, so for some reason it doesn't pick up the conda-installed Python libraries. (only TIR-Learner though! all other tools finish fine)

I don't know whether this is an error specific to our cluster or not. I don't know whether this is a bug or not. 

My workaround for this is to manually set PYTHONPATH to the conda-python path before the script:

     export PYTHONPATH=/group/pawsey0149/pbayer/anaconda3/envs/EDTA/lib/python3.6/site-packages/

then it seems to work fine? This is however not really the 'conda way'.

Again, not sure whether this is an EDTA issue or whether this is a conda issue. At least my workaround is documented here in case others have this issue.

**Comment by oushujun** [comment]
Sorry for the delay. I am not sure, but seems like incompatibility for me. Did you specify versions for python packages? e.g.,
`conda install -n EDTA -y tensorflow=1.14.0 keras=2.2.4 scikit-learn=0.19.0 python=3.6 biopython numpy=1.16.4`

**Comment by philippbayer** [comment]
Thanks, that seems to have fixed it :)
