### ISSUE TITLE
The "?" in "strand" Column of *.EDTA.intact.gff (output file)

### ISSUE THREAD

**Issue by cliu528** [oushujun/EDTA#80]
Hello, Shujun!
Thanks for developing such a convenient tool!
Last week, I have used this pipline on a plant genome, and it works well. But I found that there were a series of lines (all belong to LTR class) in *.EDTA.intact.gff that reported "?" in the 7th Column ("strand"), so I wonder if there are something wrong in these repeat? (I check the repeat annotation "irgsp1_repeat_unit.gff" downloaded from RAP-DB, and only "-/+" are found in the strand Column.)
##A statistics of these kind of lines by types:
LTR/unknown     1028
LTR/Gypsy       163
LTR/Copia       13

Thank you very much!.
Liu

**Comment by oushujun** [comment]
Glad to know it’s working.
? means the direction of the element could not be determined using pfam
matching. They may not have any pfam matching or have confounding
directions from different pfams. Please refer to the LTR_retriever paper
for more details.

Shujun

**Comment by cliu528** [comment]
Thanks for your feedback. It helps a lot!

**Comment by cliu528** [comment]
Thanks for your feedback! It helps a lot!
