### ISSUE TITLE
RepeatModeler died

### ISSUE THREAD

**Issue by yuanhelianyi** [oushujun/EDTA#81]
@oushujun 
Thanks for developing this useful tool. I found an error when I use the command (perl /data2/EDTA/EDTA.pl --genome W_v1.fasta --sensitive 1 --anno 1 --evaluate 1 --threads 32) to annotate genome. The error shows as follows, please teach me what can I do to solve this problem. Thanks!
<img width="797" alt="屏幕快照 2020-05-06 上午8 35 57" src="https://user-images.githubusercontent.com/28393277/81129124-ec805380-8f75-11ea-8e68-d16494543ec4.png">

**Comment by oushujun** [comment]
Hi,

You may want to test RepeatModeler to make sure it’s working properly.

Shujun

**Comment by yuanhelianyi** [comment]
@oushujun 
Thanks!
I tried to rerun the RepeatModeler to build the database using command ''BuildDatabase -name WEW_v1.fasta.mod.masked WEW_v1.fasta.mod.masked''. The message indicated my input file has potential formating errors. But it built a New DB. I confused if it really died because it do the repeatmasker subsequently. I didn't know what is the formating error. I also found the new DB have a new sequence ID and nsq file. How to resolve it ? 
<img width="768" alt="屏幕快照 2020-05-08 下午4 43 43" src="https://user-images.githubusercontent.com/28393277/81388780-60c02000-914b-11ea-9a61-92959a186a67.png">
![图片 1](https://user-images.githubusercontent.com/28393277/81393662-54d85c00-9153-11ea-8746-5b212c1ae442.png)

**Comment by oushujun** [comment]
@yuanhelianyi That means there is something wrong in the genome file. Please check if it follows the FASTA format.

**Comment by shri1984** [comment]
Hi, 
I have same issue. Died at /home/omg/miniconda3/envs/EDTA/share/RepeatModeler/BuildDatabase line 333. But program is still running with trf module. I am not sure whether i need to terminate the program or let it continue. I had same issue in the previous run and then I killed it and restarted with overwrite option. But it seems like again getting into same trouble. 

Thanks 
Shri

**Comment by oushujun** [comment]
Hi Shri,

It seems RepeatModeler is not functioning in your installation. You may
need to reinstall it.

Shujun
