### ISSUE TITLE
Warning: Use of uninitialized value

### ISSUE THREAD

**Issue by yuanhelianyi** [oushujun/EDTA#82]
@oushujun 
There is a warning when I use EDTA to annotate. Does this problem need to be solved? 

Sincerely,
Jing
<img width="781" alt="屏幕快照 2020-05-09 上午10 26 37" src="https://user-images.githubusercontent.com/28393277/81461730-60259900-91e0-11ea-996d-122deee06f7e.png">

**Comment by oushujun** [comment]
@yuanhelianyi Yes, you may ignore this random error if it's not recurrent.
