### ISSUE TITLE
getDataset.py & --cds/--exclude

### ISSUE THREAD

**Issue by niederhuth** [oushujun/EDTA#85]
1. Installed EDTA with Conda, which installs newer versions of tensorflow & keras than you have listed in the step by step installation.

When I run the pipeline, TIR-Learner fails, as it cannot import 'to_categorical' while running getDataset.py

ImportError: cannot import name 'to_categorical' from 'tensorflow.python.keras.utils'

Had to modify this import step in Module3/getDataset.py & Module3_New/getDataset.py from

from tensorflow.python.keras.utils import to_categorical

to 

from tensorflow.keras.utils import to_categorical

in order for it to work

2. Maybe a feature, not a bug, but I could not get the --cds or --exclude options to read their respective files using something like "--cds ../Athaliana-cds.fa". Instead, had to run edta in same directory as the Athaliana-cds.fa for it to open the file.

**Comment by oushujun** [comment]
Glad it's working after changing the python import line. Does this downward adaptable to older `keras` versions?

For 2, I believe it's fixed in the GitHub version but not yet pushed to `conda` yet. Will do so in the next update.

Shujun
