### ISSUE TITLE
Expected Memory Usage

### ISSUE THREAD

**Issue by nhartwic** [oushujun/EDTA#87]
I'm currently trying to run edta using AWS via tibanna. I've used this workflow for a couple genomes before now without issue, but the current genome I'm working on is very large. As a result, I seem to be hitting memory limits with one of the tools edta is running.

Basically, I'm looking for intuition regarding how much memory would be needed to run edta on a roughly 6 gig genome. For reference, here is a link that profiles the resource usage of edta when running on this genome...

https://salk-tm-logs.s3.amazonaws.com/oZMUk6hqQPmo.metrics/metrics.html

... You can see that Memory usage starts climbing at around 2100 minutes and hits the ceiling at around 2350 minutes. At this point, I believe processes start dying in a way that isn't detected properly by one of the tools in EDTA, resulting in a parent process waiting forever for these dead processes that will never finish. After the remaining processes finish, tibanna waits an hour before killing the instance due to cpu usage being too low.

What edta tool is so memory intensive? How does that tool scale with genome size? Is it reasonably possible to run EDTA on such a large genome? If so, how much memory should I expect to need?

Thanks in advance for any assistance you can provide.

**Comment by oushujun** [comment]
Hi, @nhartwic,

You may search "memory" in the previous issues and see some related discussions. One of the relevant ones: #61 

The memory-intensive steps are TIR-Learner and post-processing. If your genome is fragmented (ie, has >100k contigs), then TIR-Learner will take significantly more memory to process them all. On AWS you may specify the 768G node for the job if the resource is available.

Best,
Shujun

**Comment by nhartwic** [comment]
Thanks for the help.
