### ISSUE TITLE
Identification of non-LTR retrotransposons

### ISSUE THREAD

**Issue by hkchi** [oushujun/EDTA#88]
Hi Shujun, 

It seems that EDTA does not specifically identify LINE/SINE since EDTA_raw.pl only finds ltr|tir|helitron. Has it been benchmarked in animal genomes (e.g. human) where these elements are more prevalent? 

Thanks, 
Kaichi

**Comment by hkchi** [comment]
Sorry I realized this might be duplicated with #8 and #58. I suppose that the LINE/SINE will need to be picked up by RepeatModeler/RepeatMasker in the FINAL step for animal genomes.

**Comment by oushujun** [comment]
We benchmarked SINE/LINE search programs in the [paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1905-y) using the rice genome. The performance was not satisfactory, so none of these tools were used in the EDTA pipeline. However, I didn't benchmark these tools using any animal genomes (ie. human), so I don't know whether these tools are just poor in rice or also in other genomes.
