### ISSUE TITLE
Job is always killed

### ISSUE THREAD

**Issue by moontree1985** [oushujun/EDTA#9]
Hi, Shujun,

I am testing edta on our school's computer. However, the job is always killed. Here is my script:
module load edta/20190108
module load ltrretriever/1.6

EDTA.pl -genome Zm-I-REFERENCE-FL-1.0.fa -species Maize -threads 2

Here is the error message:
########################################################
########################################################

Tue Aug  6 13:57:01 EDT 2019    Dependency checking:
                All passed!
Tue Aug  6 13:57:13 EDT 2019    Obtain raw TE libraries using various structure-based programs: 
sh: line 1: 32154 Killed                  /apps/edta/20190108/edta/bin/genometools-1.5.10/bin/gt suffixerator -db Zm-I-REFERENCE-FL-1.0.fa -indexname Zm-I-REFERENCE-FL-1.0.fa -
Can't locate object method "end" via package "Thread::Queue" at /apps/edta/20190108/edta/bin/LTR_FINDER_parallel/LTR_FINDER_parallel line 115, <List> line 10732.
cat: Zm-I-REFERENCE-FL-1.0.fa.finder.combine.scn: No such file or directory
Error: (1431.1) FASTA-Reader: Warning: FASTA-Reader: Ignoring FASTA modifier(s) found because the input was not expected to have any.
Error: (1431.1) FASTA-Reader: Warning: FASTA-Reader: Ignoring FASTA modifier(s) found because the input was not expected to have any.
Error: (1431.1) FASTA-Reader: Warning: FASTA-Reader: Ignoring FASTA modifier(s) found because the input was not expected to have any.
grep: Zm-I-REFERENCE-FL-1.0.fa.retriever.scn: No such file or directory
Argument "" isn't numeric in numeric gt (>) at /apps/edta/20190108/edta/bin/LTR_retriever/LTR_retriever line 355.

ERROR: No candidate is found in the file(s) you specified.

cp: cannot stat ‘Zm-I-REFERENCE-FL-1.0.fa.LTRlib.fa’: No such file or directory
cp: cannot stat ‘Zm-I-REFERENCE-FL-1.0.fa.LTRlib.fa’: No such file or directory
Error: LTR results not found!

ERROR: Raw LTR results not found in Zm-I-REFERENCE-FL-1.0.fa.EDTA.raw/Zm-I-REFERENCE-FL-1.0.fa.LTR.raw.fa at /apps/edta/20190108/edta/EDTA.pl line 170.
slurmstepd: error: Detected 1 oom-kill event(s) in step 40042225.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.

I found in LTR folder Zm-I-REFERENCE-FL-1.0.fa.harvest.scn and Zm-I-REFERENCE-FL-1.0.fa.rawLTR.scn are empty. 

Looking forward to your reply!

Best,

Ying

**Comment by oushujun** [comment]
Hi Ying,

It looks like EDTA requires more memory than what you have requested. You may want to increase the memory allocation to this job. Please inquire with the HPC crew in your institute for more guidance.

Best,
Shujun

**Comment by moontree1985** [comment]
Hi, Shujun,

Thanks for your help! EDTA does need 36 Gb memory to run. However, I still have the following error:
Can't locate object method "end" via package "Thread::Queue" at /apps/edta/20190108/edta/bin/LTR_FINDER_parallel/LTR_FINDER_parallel line 115, line 10732.
cat: Zm-I-REFERENCE-FL-1.0.fa.finder.combine.scn: No such file or directory

Something wrong with LTR_FINDER_parallel. I don't have the output 'Zm-I-REFERENCE-FL-1.0.fa.finder.combine.scn' from LTR_FINDER_parallel.  I think LTR-retriever skips this output and only uses LTR harvest output to run. Can you help me fix it?

Thanks,
Ying

**Comment by oushujun** [comment]
Hi Ying,

Something is wrong with your PERL. Please reinstall EDTA in a brand-new
conda environment and try again.

Best,
Shujun
