### ISSUE TITLE
conda installation: GLIBCXX_3.4.21 error

### ISSUE THREAD

**Issue by sanyalab** [oushujun/EDTA#94]
Hello,

I have installed EDTA using conda. I then tried the divide and conquer technique to create the raw TE libs. I find that the TIR and LTR runs are very unstable. The pipeline starts ok from the EDTA environment, but soon is throwing "GLIBCXX_3.4.21" errors as the calls keep dropping off from the anaconda environment and makes system calls. Here is the command I ran for predicting TIR candidates.

`nohup perl EDTA_raw.pl --genome /Grass/Test_grass.fasta --species others --type tir --overwrite 0 --threads 16 &`

Below attached is the error file.
[Error.txt](https://github.com/oushujun/EDTA/files/4945482/Error.txt)

Please advice how to overcome this.

Thanks
Abhijit

**Comment by oushujun** [comment]
Helli Abhijit,

Apparently your installation of EDTA was unsuccessful. Please update conda and create a fresh environment for the installation. If this does not work out, you may use the docker/singularity version.

Best,
Shujun

**Comment by sanyalab** [comment]
Hi Shujun,

I have edta version 1.8.3 installed in conda. The version 1.8.5 is not committed yet in conda environment I think. Maybe the problem will go away then. Can you confirm if the 1.8.5 version is available in conda?

Thanks
Abhijit

**Comment by oushujun** [comment]
Hi Abhijit,

This has nothing to do with 1. 8. 3.  You don't have it installed correctly
yet. Please reinstall.

Shujun
