### ISSUE TITLE
Annotate existing repeat.gff

### ISSUE THREAD

**Issue by mycecilia** [oushujun/EDTA#95]
Hi Shujun,

I got a whole genome repeat.gff from running Maker2, and I want to annotate the repeats using EDTA. Is there a way to do just annotation using my repeat.gff or repeat.fasta file? 

Thanks!
Shiyu

**Comment by oushujun** [comment]
Hi Shiyu,

I am not sure what's in your repeat.gff file. If you want to block out
regions during the EDTA annotation you can do that. If you have a repeat
library already,  you can do a repeatmasker to annotate TEs with in
homology.

Best,
Shujun
