### ISSUE TITLE
TIR_Learner with Fragmented Assembly

### ISSUE THREAD

**Issue by rajewski** [oushujun/EDTA#97]
I've had some success with the divide and conquer strategy, and the Helitron and LTR searches finished fine. Unfortunately, the TIR search keeps failing. I've attached the log below, and the issue seems to have something to do with the number of contigs fed in. It works fine when I use my 337 largest contigs, but fails when I include more. 

My genome is _highly_ fragmented with ~200,000 contigs. I'd like to run this search on all of them, but limiting it to a subset could be fine. Do you have any advice on getting this to run including more contigs? Is there a limit in terms of minimum contig size/absolute contig number, or do you think the failure has more to do with computing resources?

[EDTA_TIR-1871769.txt](https://github.com/oushujun/EDTA/files/4978227/EDTA_TIR-1871769.txt)

**Comment by oushujun** [comment]
Small scaffolds should be fine for the latest version but just slower and
more memory intensive. You may run into Python errors when the hpc node is
too CPU busy or not enough memory. Please check with other similar issues
for more information.

Best,
Shujun
