### ISSUE TITLE
DNA - DTA vs. TIR hAT

### ISSUE THREAD

**Issue by fungal-spore** [oushujun/EDTA#99]
Hello,
I followed link to where TE codes are (Wicker et al. 2007), and see that the DTA code is for TIR - hAT. 
However, in the output there is line for DNA - DTA and then another line for TIR - hAT (bold/italics in output below). 
Can you please clarify what the difference between these two grouping is (i.e. why are they not grouped as one?)
Thanks!

Repeat Classes
==============
Total Sequences: 6828
Total Length: 34443611 bp
Class                  Count        bpMasked    %masked
=====                  =====        ========     =======
DNA                    --           --           --
    _**DTA                3            5903         0.02%**_
    DTC                649          145097       0.42%
    DTH                3            8844         0.03%
    DTM                129          94526        0.27%
    Helitron           793          189370       0.55%
LINE                   --           --           --
    unknown            130          21647        0.06%
LTR                    --           --           --
    Copia              1405         299610       0.87%
    unknown            477          141257       0.41%
MITE                   --           --           --
    DTA                12           1937         0.01%
    DTC                2            388          0.00%
    DTH                1            359          0.00%
    DTM                270          25870        0.08%
TIR                    --           --           --
    Tc1_Mariner        797          228874       0.66%
    **_hAT                81           13266        0.04%_**
Unknown                8213         1183747      3.44%
                      ---------------------------------
    total interspersed 12965        2360695      6.85%

**Comment by oushujun** [comment]
Hi,
This is likely due to the `--sensitive 1` parameter in which it recruits `RepeatModeler` to identify leftover TEs, and the sequence name produced by `RepeatModeler` is not consistent with `EDTA`. I am working to solve this inconsistency but have not encountered cases like yours. If possible can you share with your data for testing purposes? My email is shujun.ou.1@gmail.com. Thank you.

Best,
Shujun

**Comment by YTLogos** [comment]
Hi @oushujun 
I encountered the same case with version v1.8.5 (but v1.8.2 not). Maybe it's the version update caused this inconsistency. On tht other hand, can I mix the MITE and DNA (for example MITE/DTA and DNA/DTA) together for statistics or I need to separate them？

**Comment by oushujun** [comment]
Hi @YTLogos,

Did you use the `--sensitive 1` parameter? There were some updates in v1.8.3 or v1.8.5 to fix the classification issue of `RepeatModeler2` when I include this new version of RM2 in the package.

You can mix MITE and TIRs together for stats. They are similar elements with different lengths.

Best,
Shujun

**Comment by YTLogos** [comment]
> Hi @YTLogos,
> 
> Did you use the `--sensitive 1` parameter? There were some updates in v1.8.3 or v1.8.5 to fix the classification issue of `RepeatModeler2` when I include this new version of RM2 in the package.
> 
> You can mix MITE and TIRs together for stats. They are similar elements with different lengths.
> 
> Best,
> Shujun

Yes, I used the `--sensitive 1` parameter. Thanks for nice reply, I get it now!
